/*
 * Banco de preguntas de "Carrera de Medallas".
 *
 * Para agregar una pregunta basta con sumar un objeto a la lista de su
 * categoría con este formato:
 *
 *   {
 *     q: 'Enunciado de la pregunta',
 *     correct: 'Respuesta correcta',
 *     wrong: ['Incorrecta 1', 'Incorrecta 2', 'Incorrecta 3'],
 *     explain: 'Explicación breve que se muestra al responder',
 *   }
 *
 * Categorías: tipos, pokedex, habilidades, cambalache y liga.
 *
 * El juego mezcla las opciones en cada aparición, así que el orden en el
 * que se escriben aquí no importa. Cada pregunta debe tener exactamente
 * tres respuestas incorrectas (cuatro opciones en total).
 */
window.QUESTION_BANK = {
  // ── TIPOS: efectividades, debilidades, inmunidades y combinaciones ──
  tipos: [
    {
      q: 'Un ataque de tipo Fuego contra Scizor (Bicho/Acero), ¿cuánto daño hace?',
      correct: 'x4',
      wrong: ['x2', 'x1', 'x0,5'],
      explain: 'Fuego es súper eficaz contra Bicho y contra Acero: x2 · x2 = x4.',
    },
    {
      q: 'Un ataque de tipo Lucha contra Sableye (Siniestro/Fantasma), ¿cuánto daño hace?',
      correct: 'x0',
      wrong: ['x1', 'x2', 'x0,5'],
      explain: 'Lucha haría x2 al tipo Siniestro, pero el tipo Fantasma es inmune: x0.',
    },
    {
      q: '¿Cuál de estos tipos de ataque no afecta a Gengar (Fantasma/Veneno)?',
      correct: 'Normal',
      wrong: ['Tierra', 'Psíquico', 'Bicho'],
      explain: 'El tipo Fantasma es inmune a Normal (y a Lucha). Tierra y Psíquico son súper eficaces; Bicho hace x0,25.',
    },
    {
      q: '¿Cuántas debilidades tiene un Pokémon de tipo Planta puro?',
      correct: '5',
      wrong: ['4', '6', '3'],
      explain: 'Planta es débil a Fuego, Hielo, Veneno, Volador y Bicho.',
    },
    {
      q: '¿Cuántas debilidades tiene un Pokémon de tipo Normal puro?',
      correct: '1',
      wrong: ['2', '0', '3'],
      explain: 'El tipo Normal solo es débil a Lucha.',
    },
    {
      q: '¿A qué tipo de ataque es débil x4 Tyranitar (Roca/Siniestro)?',
      correct: 'Lucha',
      wrong: ['Agua', 'Tierra', 'Bicho'],
      explain: 'Lucha es súper eficaz contra Roca y contra Siniestro: x4. Agua, Tierra y Bicho hacen x2.',
    },
    {
      q: '¿A qué tipo de ataque es débil x4 Gyarados (Agua/Volador)?',
      correct: 'Eléctrico',
      wrong: ['Roca', 'Hielo', 'Planta'],
      explain: 'Eléctrico es súper eficaz contra Agua y contra Volador: x4.',
    },
    {
      q: '¿Qué tipo resiste los ataques de tipo Hada?',
      correct: 'Veneno',
      wrong: ['Dragón', 'Lucha', 'Siniestro'],
      explain: 'Hada es poco eficaz contra Fuego, Veneno y Acero. Contra Dragón, Lucha y Siniestro es súper eficaz.',
    },
    {
      q: '¿A qué tipo de ataques es inmune el tipo Acero?',
      correct: 'Veneno',
      wrong: ['Hada', 'Psíquico', 'Fuego'],
      explain: 'Acero es inmune a Veneno. Resiste Hada y Psíquico, y es débil a Fuego.',
    },
    {
      q: '¿Qué tipo de ataque es poco eficaz contra el tipo Bicho?',
      correct: 'Tierra',
      wrong: ['Volador', 'Roca', 'Fuego'],
      explain: 'Bicho resiste Lucha, Tierra y Planta. Volador, Roca y Fuego son súper eficaces.',
    },
    {
      q: 'Un ataque de tipo Agua contra Ludicolo (Agua/Planta), ¿cuánto daño hace?',
      correct: 'x0,25',
      wrong: ['x0,5', 'x1', 'x2'],
      explain: 'Agua es poco eficaz contra Agua y contra Planta: x0,5 · x0,5 = x0,25.',
    },
    {
      q: 'Un ataque de tipo Eléctrico contra Quagsire (Agua/Tierra), ¿cuánto daño hace?',
      correct: 'x0',
      wrong: ['x2', 'x1', 'x4'],
      explain: 'El tipo Tierra es inmune a Eléctrico, aunque Quagsire también sea de tipo Agua.',
    },
    {
      q: 'Un ataque de tipo Hielo contra Garchomp (Dragón/Tierra), ¿cuánto daño hace?',
      correct: 'x4',
      wrong: ['x2', 'x1', 'x0,5'],
      explain: 'Hielo es súper eficaz contra Dragón y contra Tierra: x4.',
    },
    {
      q: 'Un ataque de tipo Siniestro contra Gardevoir (Psíquico/Hada), ¿cuánto daño hace?',
      correct: 'x1',
      wrong: ['x2', 'x0,5', 'x4'],
      explain: 'Siniestro hace x2 a Psíquico y x0,5 a Hada: x1.',
    },
    {
      q: '¿Contra cuál de estos tipos es poco eficaz el tipo Eléctrico?',
      correct: 'Dragón',
      wrong: ['Volador', 'Agua', 'Acero'],
      explain: 'Eléctrico es poco eficaz contra Eléctrico, Planta y Dragón (Tierra es inmune). Contra Acero hace x1.',
    },
    {
      q: '¿Qué tipo de ataque es súper eficaz contra el tipo Acero?',
      correct: 'Lucha',
      wrong: ['Hielo', 'Roca', 'Hada'],
      explain: 'Fuego, Lucha y Tierra son súper eficaces contra Acero. Acero resiste Hielo, Roca y Hada.',
    },
    {
      q: '¿Qué tipo de ataque es súper eficaz contra el tipo Roca?',
      correct: 'Acero',
      wrong: ['Fuego', 'Volador', 'Bicho'],
      explain: 'Agua, Planta, Lucha, Tierra y Acero son súper eficaces contra Roca. Roca resiste Fuego y Volador.',
    },
    {
      q: '¿De qué tipo es Skarmory?',
      correct: 'Acero/Volador',
      wrong: ['Acero/Roca', 'Volador/Siniestro', 'Acero'],
      explain: 'Skarmory es de tipo Acero/Volador.',
    },
    {
      q: '¿De qué tipo es Azumarill?',
      correct: 'Agua/Hada',
      wrong: ['Agua', 'Agua/Normal', 'Hada'],
      explain: 'Desde la sexta generación, Azumarill es de tipo Agua/Hada.',
    },
    {
      q: '¿De qué tipo es Mawile?',
      correct: 'Acero/Hada',
      wrong: ['Acero', 'Hada', 'Siniestro/Hada'],
      explain: 'Desde la sexta generación, Mawile es de tipo Acero/Hada.',
    },
    {
      q: '¿De qué tipo es Dragonite?',
      correct: 'Dragón/Volador',
      wrong: ['Dragón', 'Dragón/Agua', 'Normal/Volador'],
      explain: 'Dragonite es de tipo Dragón/Volador.',
    },
    {
      q: '¿Qué tipo de ataque no le hace nada al tipo Hada?',
      correct: 'Dragón',
      wrong: ['Siniestro', 'Lucha', 'Bicho'],
      explain: 'El tipo Hada es inmune a Dragón. Siniestro, Lucha y Bicho solo hacen x0,5.',
    },
    {
      q: '¿Cuál de estos Pokémon es de tipo Bicho/Roca?',
      correct: 'Shuckle',
      wrong: ['Kabuto', 'Skorupi', 'Nosepass'],
      explain: 'Shuckle es Bicho/Roca. Kabuto es Roca/Agua, Skorupi Veneno/Bicho y Nosepass Roca.',
    },
    {
      q: 'Un ataque de tipo Tierra contra Skarmory (Acero/Volador), ¿cuánto daño hace?',
      correct: 'x0',
      wrong: ['x2', 'x1', 'x0,5'],
      explain: 'Tierra haría x2 al tipo Acero, pero el tipo Volador es inmune: x0.',
    },
  ],

  // ── POKÉDEX: números, alturas y pesos ──
  pokedex: [
    {
      q: '¿Qué número tiene Lucario en la Pokédex Nacional?',
      correct: '#448',
      wrong: ['#447', '#449', '#445'],
      explain: 'Lucario es el #448; Riolu, su preevolución, es el #447.',
    },
    {
      q: '¿Qué número tiene Snorlax en la Pokédex Nacional?',
      correct: '#143',
      wrong: ['#142', '#144', '#139'],
      explain: 'Snorlax es el #143, entre Aerodactyl (#142) y Articuno (#144).',
    },
    {
      q: '¿Qué número tiene Eevee en la Pokédex Nacional?',
      correct: '#133',
      wrong: ['#132', '#134', '#137'],
      explain: 'Eevee es el #133; Ditto es el #132 y Vaporeon el #134.',
    },
    {
      q: '¿Qué número tiene Gengar en la Pokédex Nacional?',
      correct: '#094',
      wrong: ['#092', '#093', '#095'],
      explain: 'Gastly es el #092, Haunter el #093 y Gengar el #094.',
    },
    {
      q: '¿Qué número tiene Gyarados en la Pokédex Nacional?',
      correct: '#130',
      wrong: ['#129', '#131', '#128'],
      explain: 'Magikarp es el #129 y Gyarados el #130.',
    },
    {
      q: '¿Qué número tiene Dragonite en la Pokédex Nacional?',
      correct: '#149',
      wrong: ['#147', '#148', '#150'],
      explain: 'Dratini es el #147, Dragonair el #148 y Dragonite el #149.',
    },
    {
      q: '¿Qué número tiene Lugia en la Pokédex Nacional?',
      correct: '#249',
      wrong: ['#250', '#248', '#251'],
      explain: 'Lugia es el #249 y Ho-Oh el #250.',
    },
    {
      q: '¿Qué número tiene Gardevoir en la Pokédex Nacional?',
      correct: '#282',
      wrong: ['#280', '#281', '#283'],
      explain: 'Ralts es el #280, Kirlia el #281 y Gardevoir el #282.',
    },
    {
      q: '¿Qué número tiene Garchomp en la Pokédex Nacional?',
      correct: '#445',
      wrong: ['#443', '#444', '#446'],
      explain: 'Gible es el #443, Gabite el #444 y Garchomp el #445.',
    },
    {
      q: '¿Qué Pokémon ocupa el número #054 de la Pokédex Nacional?',
      correct: 'Psyduck',
      wrong: ['Golduck', 'Slowpoke', 'Poliwag'],
      explain: 'Psyduck es el #054; Golduck el #055, Poliwag el #060 y Slowpoke el #079.',
    },
    {
      q: '¿Qué Pokémon ocupa el número #196 de la Pokédex Nacional?',
      correct: 'Espeon',
      wrong: ['Umbreon', 'Jolteon', 'Leafeon'],
      explain: 'Espeon es el #196 y Umbreon el #197.',
    },
    {
      q: '¿Qué Pokémon ocupa el número #212 de la Pokédex Nacional?',
      correct: 'Scizor',
      wrong: ['Scyther', 'Heracross', 'Shuckle'],
      explain: 'Scizor es el #212, Shuckle el #213 y Heracross el #214. Scyther es el #123.',
    },
    {
      q: '¿Cuánto mide Pikachu según la Pokédex?',
      correct: '0,4 m',
      wrong: ['0,5 m', '0,3 m', '0,6 m'],
      explain: 'Pikachu mide 0,4 m y pesa 6,0 kg.',
    },
    {
      q: '¿Cuánto pesa Pikachu según la Pokédex?',
      correct: '6,0 kg',
      wrong: ['7,5 kg', '4,5 kg', '8,0 kg'],
      explain: 'Pikachu pesa 6,0 kg.',
    },
    {
      q: '¿Cuánto mide Onix según la Pokédex?',
      correct: '8,8 m',
      wrong: ['9,2 m', '7,9 m', '10,5 m'],
      explain: 'Onix mide 8,8 m; Steelix, su evolución, mide 9,2 m.',
    },
    {
      q: '¿Cuánto pesa Snorlax según la Pokédex?',
      correct: '460,0 kg',
      wrong: ['410,0 kg', '500,0 kg', '380,0 kg'],
      explain: 'Snorlax pesa 460 kg.',
    },
    {
      q: '¿Cuánto mide Wailord según la Pokédex?',
      correct: '14,5 m',
      wrong: ['12,0 m', '16,0 m', '13,2 m'],
      explain: 'Wailord mide 14,5 m.',
    },
    {
      q: '¿Cuánto pesa Gengar según la Pokédex?',
      correct: '40,5 kg',
      wrong: ['30,5 kg', '45,0 kg', '52,5 kg'],
      explain: 'Gengar pesa 40,5 kg.',
    },
    {
      q: '¿Cuánto mide Charizard según la Pokédex?',
      correct: '1,7 m',
      wrong: ['1,8 m', '1,5 m', '2,0 m'],
      explain: 'Charizard mide 1,7 m y pesa 90,5 kg.',
    },
    {
      q: '¿Cuánto pesa Mewtwo según la Pokédex?',
      correct: '122,0 kg',
      wrong: ['106,0 kg', '130,0 kg', '98,0 kg'],
      explain: 'Mewtwo pesa 122 kg y mide 2,0 m.',
    },
    {
      q: '¿Cuál de estos Pokémon es el más pesado?',
      correct: 'Groudon',
      wrong: ['Snorlax', 'Wailord', 'Steelix'],
      explain: 'Groudon pesa 950 kg; Snorlax 460 kg, Steelix 400 kg y Wailord 398 kg.',
    },
    {
      q: '¿Cuál de estos Pokémon es el más alto?',
      correct: 'Wailord',
      wrong: ['Steelix', 'Onix', 'Rayquaza'],
      explain: 'Wailord mide 14,5 m; Steelix 9,2 m, Onix 8,8 m y Rayquaza 7,0 m.',
    },
    {
      q: '¿Cuál de estos Pokémon aparece primero en la Pokédex Nacional?',
      correct: 'Psyduck',
      wrong: ['Machop', 'Geodude', 'Ponyta'],
      explain: 'Psyduck es el #054, Machop el #066, Geodude el #074 y Ponyta el #077.',
    },
    {
      q: '¿Qué número tiene Chikorita en la Pokédex Nacional?',
      correct: '#152',
      wrong: ['#151', '#153', '#155'],
      explain: 'Chikorita es el #152, el primero de la segunda generación; Mew es el #151 y Cyndaquil el #155.',
    },
  ],

  // ── HABILIDADES Y MOVIMIENTOS: potencia, precisión, prioridad y efectos ──
  habilidades: [
    {
      q: '¿Qué potencia tiene Hiperrayo?',
      correct: '150',
      wrong: ['140', '160', '120'],
      explain: 'Hiperrayo tiene 150 de potencia, pero el usuario debe descansar el turno siguiente.',
    },
    {
      q: '¿Qué potencia tiene Terremoto?',
      correct: '100',
      wrong: ['90', '110', '120'],
      explain: 'Terremoto tiene 100 de potencia y 100 % de precisión.',
    },
    {
      q: '¿Qué potencia tiene Rayo?',
      correct: '90',
      wrong: ['95', '80', '100'],
      explain: 'Desde la sexta generación, Rayo tiene 90 de potencia (antes, 95).',
    },
    {
      q: '¿Qué potencia tiene Llamarada?',
      correct: '110',
      wrong: ['120', '100', '90'],
      explain: 'Desde la sexta generación, Llamarada tiene 110 de potencia (antes, 120).',
    },
    {
      q: '¿Qué precisión tiene Hidrobomba?',
      correct: '80 %',
      wrong: ['85 %', '75 %', '90 %'],
      explain: 'Hidrobomba tiene 80 % de precisión.',
    },
    {
      q: '¿Qué precisión tiene Trueno?',
      correct: '70 %',
      wrong: ['75 %', '65 %', '80 %'],
      explain: 'Trueno tiene 70 % de precisión (y no falla con lluvia).',
    },
    {
      q: '¿Qué precisión tiene Ventisca?',
      correct: '70 %',
      wrong: ['80 %', '75 %', '65 %'],
      explain: 'Ventisca tiene 70 % de precisión (y no falla con granizo o nieve).',
    },
    {
      q: '¿Qué prioridad tiene Ataque Rápido?',
      correct: '+1',
      wrong: ['+2', '0', '+3'],
      explain: 'Ataque Rápido tiene prioridad +1.',
    },
    {
      q: '¿Qué prioridad tiene Protección?',
      correct: '+4',
      wrong: ['+3', '+5', '+2'],
      explain: 'Protección tiene prioridad +4.',
    },
    {
      q: '¿Qué prioridad tiene Velocidad Extrema?',
      correct: '+2',
      wrong: ['+1', '+3', '+4'],
      explain: 'Velocidad Extrema tiene prioridad +2.',
    },
    {
      q: '¿Qué prioridad tiene Sorpresa?',
      correct: '+3',
      wrong: ['+1', '+2', '+4'],
      explain: 'Sorpresa tiene prioridad +3 y solo funciona en el primer turno del usuario en combate.',
    },
    {
      q: '¿Cuántos PP tiene Danza Espada?',
      correct: '20',
      wrong: ['30', '10', '15'],
      explain: 'Desde la cuarta generación, Danza Espada tiene 20 PP (antes, 30).',
    },
    {
      q: '¿Cuántos PP tiene Hiperrayo?',
      correct: '5',
      wrong: ['10', '8', '15'],
      explain: 'Hiperrayo tiene 5 PP.',
    },
    {
      q: '¿Cuántos PP tiene Terremoto?',
      correct: '10',
      wrong: ['15', '5', '20'],
      explain: 'Terremoto tiene 10 PP.',
    },
    {
      q: '¿Qué habilidad duplica la Velocidad cuando llueve?',
      correct: 'Nado Rápido',
      wrong: ['Clorofila', 'Ímpetu Arena', 'Quitanieves'],
      explain: 'Nado Rápido funciona con lluvia; Clorofila con sol, Ímpetu Arena con tormenta de arena y Quitanieves con nieve.',
    },
    {
      q: '¿Qué hace la habilidad Robustez?',
      correct: 'Evita ser debilitado de un golpe si tiene los PS al máximo',
      wrong: ['Reduce el daño de los golpes críticos', 'Sube la Defensa al recibir un golpe', 'Impide que bajen sus características'],
      explain: 'Con Robustez, si tiene los PS al máximo, aguanta cualquier golpe con 1 PS.',
    },
    {
      q: '¿Qué hace la habilidad Levitación?',
      correct: 'Da inmunidad a los movimientos de tipo Tierra',
      wrong: ['Duplica la Velocidad con lluvia', 'Evita ser debilitado de un solo golpe', 'Recupera PS al recibir ataques eléctricos'],
      explain: 'Levitación hace que el Pokémon flote y no le afecten los movimientos de tipo Tierra.',
    },
    {
      q: '¿Qué hace la habilidad Intimidación?',
      correct: 'Baja el Ataque de los rivales al entrar en combate',
      wrong: ['Sube el Ataque propio al recibir un golpe', 'Impide que el rival huya', 'Baja la Defensa de los rivales al entrar'],
      explain: 'Intimidación baja un nivel el Ataque de los rivales cuando el Pokémon entra en combate.',
    },
    {
      q: '¿Cuál es la habilidad oculta de Charizard?',
      correct: 'Poder Solar',
      wrong: ['Mar Llamas', 'Absorbe Fuego', 'Cuerpo Llama'],
      explain: 'La habilidad normal de Charizard es Mar Llamas; la oculta, Poder Solar.',
    },
    {
      q: '¿Cuál es la habilidad oculta de Pikachu?',
      correct: 'Pararrayos',
      wrong: ['Electricidad Estática', 'Electromotor', 'Absorbe Electricidad'],
      explain: 'La habilidad normal de Pikachu es Electricidad Estática; la oculta, Pararrayos.',
    },
    {
      q: '¿Cuál de estos movimientos nunca falla?',
      correct: 'Golpe Aéreo',
      wrong: ['Lanzallamas', 'Rayo', 'Surf'],
      explain: 'Golpe Aéreo nunca falla. Lanzallamas, Rayo y Surf tienen 100 % de precisión, pero pueden fallar.',
    },
    {
      q: '¿Qué movimiento eléctrico también daña al usuario por retroceso?',
      correct: 'Placaje Eléctrico',
      wrong: ['Chispa', 'Rayo', 'Puño Trueno'],
      explain: 'Placaje Eléctrico, el movimiento especial de Pikachu, le quita al usuario parte del daño causado.',
    },
    {
      q: '¿Qué efecto adicional puede causar Rayo Hielo?',
      correct: 'Congelar al objetivo',
      wrong: ['Paralizar al objetivo', 'Bajar la Velocidad del objetivo', 'Bajar el Ataque Especial del objetivo'],
      explain: 'Rayo Hielo puede congelar al objetivo.',
    },
    {
      q: '¿Qué hace Danza Dragón?',
      correct: 'Sube el Ataque y la Velocidad del usuario',
      wrong: ['Sube mucho el Ataque del usuario', 'Sube el Ataque y la Defensa del usuario', 'Sube el Ataque Especial y la Defensa Especial del usuario'],
      explain: 'Danza Dragón sube un nivel el Ataque y la Velocidad. Danza Espada sube mucho el Ataque, Corpulencia sube Ataque y Defensa, y Paz Mental sube Ataque Especial y Defensa Especial.',
    },
  ],

  // ── CAMBALACHE: evoluciones, objetos, regiones y curiosidades ──
  cambalache: [
    {
      q: '¿A qué nivel evoluciona Charmander?',
      correct: 'Nivel 16',
      wrong: ['Nivel 14', 'Nivel 18', 'Nivel 20'],
      explain: 'Charmander evoluciona a Charmeleon en el nivel 16.',
    },
    {
      q: '¿A qué nivel evoluciona Charmeleon?',
      correct: 'Nivel 36',
      wrong: ['Nivel 32', 'Nivel 34', 'Nivel 40'],
      explain: 'Charmeleon evoluciona a Charizard en el nivel 36.',
    },
    {
      q: '¿A qué nivel evoluciona Dratini?',
      correct: 'Nivel 30',
      wrong: ['Nivel 28', 'Nivel 32', 'Nivel 35'],
      explain: 'Dratini evoluciona a Dragonair en el nivel 30.',
    },
    {
      q: '¿A qué nivel evoluciona Dragonair?',
      correct: 'Nivel 55',
      wrong: ['Nivel 50', 'Nivel 52', 'Nivel 60'],
      explain: 'Dragonair evoluciona a Dragonite en el nivel 55.',
    },
    {
      q: '¿A qué nivel evoluciona Magikarp?',
      correct: 'Nivel 20',
      wrong: ['Nivel 15', 'Nivel 18', 'Nivel 25'],
      explain: 'Magikarp evoluciona a Gyarados en el nivel 20.',
    },
    {
      q: '¿A qué nivel evoluciona Larvitar?',
      correct: 'Nivel 30',
      wrong: ['Nivel 25', 'Nivel 28', 'Nivel 32'],
      explain: 'Larvitar evoluciona a Pupitar en el nivel 30, y Pupitar a Tyranitar en el 55.',
    },
    {
      q: '¿A qué nivel evoluciona Gible?',
      correct: 'Nivel 24',
      wrong: ['Nivel 22', 'Nivel 26', 'Nivel 28'],
      explain: 'Gible evoluciona a Gabite en el nivel 24, y Gabite a Garchomp en el 48.',
    },
    {
      q: '¿A qué nivel evoluciona Abra?',
      correct: 'Nivel 16',
      wrong: ['Nivel 14', 'Nivel 18', 'Nivel 20'],
      explain: 'Abra evoluciona a Kadabra en el nivel 16; Kadabra evoluciona al ser intercambiado.',
    },
    {
      q: '¿Con qué objeto evoluciona Eevee a Vaporeon?',
      correct: 'Piedra Agua',
      wrong: ['Piedra Hielo', 'Piedra Lunar', 'Piedra Hoja'],
      explain: 'Eevee evoluciona a Vaporeon con una Piedra Agua.',
    },
    {
      q: '¿Qué necesita Eevee para evolucionar a Espeon?',
      correct: 'Mucha amistad, de día',
      wrong: ['Mucha amistad, de noche', 'Una Piedra Solar', 'Una Piedra Día'],
      explain: 'Eevee evoluciona a Espeon con mucha amistad de día, y a Umbreon con mucha amistad de noche.',
    },
    {
      q: '¿Qué objeto debe llevar Onix al ser intercambiado para evolucionar a Steelix?',
      correct: 'Revestimiento Metálico',
      wrong: ['Escama Dragón', 'Roca del Rey', 'Mejora'],
      explain: 'Onix evoluciona a Steelix si se intercambia llevando un Revestimiento Metálico.',
    },
    {
      q: '¿Qué objeto debe llevar Seadra al ser intercambiado para evolucionar?',
      correct: 'Escama Dragón',
      wrong: ['Revestimiento Metálico', 'Mejora', 'Roca del Rey'],
      explain: 'Seadra evoluciona a Kingdra si se intercambia llevando una Escama Dragón.',
    },
    {
      q: '¿Qué objeto debe llevar Porygon al ser intercambiado para evolucionar?',
      correct: 'Mejora',
      wrong: ['Disco Extraño', 'Revestimiento Metálico', 'Electrizador'],
      explain: 'Porygon evoluciona a Porygon2 con la Mejora; Porygon2 a Porygon-Z con el Disco Extraño.',
    },
    {
      q: '¿Con qué objeto evoluciona Clefairy?',
      correct: 'Piedra Lunar',
      wrong: ['Piedra Solar', 'Piedra Alba', 'Piedra Día'],
      explain: 'Clefairy evoluciona a Clefable con una Piedra Lunar.',
    },
    {
      q: '¿Qué objeto hace evolucionar a Gloom en Bellossom?',
      correct: 'Piedra Solar',
      wrong: ['Piedra Hoja', 'Piedra Día', 'Piedra Alba'],
      explain: 'Gloom evoluciona a Bellossom con una Piedra Solar, y a Vileplume con una Piedra Hoja.',
    },
    {
      q: '¿Cuántas evoluciones distintas tiene Eevee?',
      correct: '8',
      wrong: ['7', '9', '6'],
      explain: 'Vaporeon, Jolteon, Flareon, Espeon, Umbreon, Leafeon, Glaceon y Sylveon.',
    },
    {
      q: '¿Cuál de estos Pokémon evoluciona al ser intercambiado?',
      correct: 'Haunter',
      wrong: ['Golbat', 'Kirlia', 'Dragonair'],
      explain: 'Haunter evoluciona a Gengar por intercambio. Golbat lo hace por amistad, Kirlia y Dragonair por nivel.',
    },
    {
      q: '¿Cuál de estos Pokémon evoluciona por amistad?',
      correct: 'Golbat',
      wrong: ['Haunter', 'Pikachu', 'Gloom'],
      explain: 'Golbat evoluciona a Crobat con mucha amistad. Haunter lo hace por intercambio; Pikachu y Gloom con piedras.',
    },
    {
      q: '¿Qué Pokémon legendario aparece en la portada de Pokémon Plata?',
      correct: 'Lugia',
      wrong: ['Ho-Oh', 'Suicune', 'Celebi'],
      explain: 'Lugia es la portada de Pokémon Plata; Ho-Oh, la de Oro.',
    },
    {
      q: '¿Qué Pokémon aparece en la portada de Pokémon Cristal?',
      correct: 'Suicune',
      wrong: ['Lugia', 'Ho-Oh', 'Entei'],
      explain: 'Suicune es la portada de Pokémon Cristal.',
    },
    {
      q: '¿En qué región se introdujo la Megaevolución?',
      correct: 'Kalos',
      wrong: ['Alola', 'Hoenn', 'Teselia'],
      explain: 'La Megaevolución apareció en Pokémon X e Y, ambientados en Kalos.',
    },
    {
      q: '¿En qué región se introdujeron los Movimientos Z?',
      correct: 'Alola',
      wrong: ['Kalos', 'Galar', 'Teselia'],
      explain: 'Los Movimientos Z aparecieron en Pokémon Sol y Luna, ambientados en Alola.',
    },
    {
      q: '¿Cómo se llama el profesor Pokémon de la región de Hoenn?',
      correct: 'Profesor Abedul',
      wrong: ['Profesor Serbal', 'Profesor Elm', 'Profesora Encina'],
      explain: 'El Profesor Abedul es el de Hoenn; Elm el de Johto, Serbal el de Sinnoh y Encina la de Teselia.',
    },
    {
      q: '¿Qué baya cura la parálisis?',
      correct: 'Baya Zreza',
      wrong: ['Baya Atania', 'Baya Meloc', 'Baya Safre'],
      explain: 'Baya Zreza cura la parálisis; Atania el sueño, Meloc el envenenamiento y Safre las quemaduras.',
    },
  ],

  // ── LIGA POKÉMON: el desafío final (líderes, Alto Mando, campeones, legendarios y míticos) ──
  liga: [
    {
      q: '¿Qué medalla entrega Blaine en Isla Canela?',
      correct: 'Medalla Volcán',
      wrong: ['Medalla Pantano', 'Medalla Tierra', 'Medalla Alma'],
      explain: 'Blaine entrega la Medalla Volcán. Sabrina da la Pantano, Giovanni la Tierra y Koga la Alma.',
    },
    {
      q: '¿Qué medalla entrega Giovanni en Ciudad Verde?',
      correct: 'Medalla Tierra',
      wrong: ['Medalla Volcán', 'Medalla Pantano', 'Medalla Roca'],
      explain: 'Giovanni, líder del gimnasio de Ciudad Verde, entrega la Medalla Tierra.',
    },
    {
      q: '¿Qué medalla entrega Misty en Ciudad Celeste?',
      correct: 'Medalla Cascada',
      wrong: ['Medalla Niebla', 'Medalla Glaciar', 'Medalla Lluvia'],
      explain: 'Misty entrega la Medalla Cascada. Las medallas Niebla y Glaciar son de Johto.',
    },
    {
      q: '¿Qué miembro del Alto Mando de Kanto usa Pokémon de tipo Hielo?',
      correct: 'Lorelei',
      wrong: ['Agatha', 'Bruno', 'Karen'],
      explain: 'Lorelei usa Pokémon de tipo Hielo. Agatha usa Fantasma, Bruno Lucha, y Karen es del Alto Mando de Johto.',
    },
    {
      q: '¿Qué miembro del Alto Mando de Kanto usa Pokémon de tipo Lucha?',
      correct: 'Bruno',
      wrong: ['Lorelei', 'Agatha', 'Koga'],
      explain: 'Bruno usa Pokémon de tipo Lucha (y Roca).',
    },
    {
      q: '¿Con qué Pokémon cierra su equipo Lance en Pokémon Rojo y Azul?',
      correct: 'Dragonite',
      wrong: ['Gyarados', 'Aerodactyl', 'Charizard'],
      explain: 'El último Pokémon de Lance es Dragonite.',
    },
    {
      q: '¿Quién es el Campeón de la Liga en Pokémon Oro y Plata?',
      correct: 'Lance',
      wrong: ['Rojo', 'Azul', 'Karen'],
      explain: 'En Oro y Plata, Lance pasa a ser el Campeón tras el Alto Mando de Johto.',
    },
    {
      q: '¿Quién es el Campeón de Teselia en Pokémon Negro y Blanco?',
      correct: 'Mirto',
      wrong: ['Iris', 'Cintia', 'Máximo'],
      explain: 'Mirto es el Campeón en Negro y Blanco; Iris lo es en Negro 2 y Blanco 2.',
    },
    {
      q: '¿Quién es la Campeona de la región de Kalos?',
      correct: 'Dianta',
      wrong: ['Cintia', 'Iris', 'Sabrina'],
      explain: 'Dianta es la Campeona de Kalos en Pokémon X e Y.',
    },
    {
      q: '¿Quién es el Campeón de Hoenn en Pokémon Esmeralda?',
      correct: 'Plubio',
      wrong: ['Máximo', 'Cintia', 'Lance'],
      explain: 'En Esmeralda el Campeón es Plubio; en Rubí y Zafiro, Máximo.',
    },
    {
      q: '¿Qué líder de gimnasio de Johto usa Pokémon de tipo Acero?',
      correct: 'Yasmina',
      wrong: ['Blanca', 'Aníbal', 'Morti'],
      explain: 'Yasmina, de Ciudad Olivo, usa Pokémon de tipo Acero.',
    },
    {
      q: '¿Qué líder de gimnasio de Kanto usa Pokémon de tipo Psíquico?',
      correct: 'Sabrina',
      wrong: ['Erika', 'Koga', 'Agatha'],
      explain: 'Sabrina, de Ciudad Azafrán, usa Pokémon de tipo Psíquico.',
    },
    {
      q: '¿Qué Pokémon de Blanca, líder de Ciudad Trigal, es famoso por ser muy difícil de vencer?',
      correct: 'Miltank',
      wrong: ['Clefairy', 'Snorlax', 'Tauros'],
      explain: 'El Miltank de Blanca, con Rodar y Batido, es un clásico muro de Oro y Plata.',
    },
    {
      q: '¿Qué Pokémon legendario de Sinnoh controla el espacio?',
      correct: 'Palkia',
      wrong: ['Dialga', 'Giratina', 'Arceus'],
      explain: 'Palkia controla el espacio; Dialga, el tiempo.',
    },
    {
      q: '¿Cuál de estos Pokémon es mítico (y no legendario)?',
      correct: 'Jirachi',
      wrong: ['Latias', 'Regirock', 'Kyogre'],
      explain: 'Jirachi es un Pokémon mítico. Latias, Regirock y Kyogre son legendarios.',
    },
    {
      q: '¿Cuál de estos Pokémon es legendario (y no mítico)?',
      correct: 'Cresselia',
      wrong: ['Darkrai', 'Shaymin', 'Manaphy'],
      explain: 'Cresselia es legendaria. Darkrai, Shaymin y Manaphy son míticos.',
    },
    {
      q: '¿De qué tipo es Zapdos?',
      correct: 'Eléctrico/Volador',
      wrong: ['Eléctrico', 'Eléctrico/Dragón', 'Volador'],
      explain: 'Zapdos es de tipo Eléctrico/Volador.',
    },
    {
      q: '¿Qué Pokémon completa el trío de Regirock y Regice?',
      correct: 'Registeel',
      wrong: ['Regigigas', 'Regieleki', 'Regidrago'],
      explain: 'Regirock, Regice y Registeel forman el trío de Hoenn; Regigigas es quien los creó.',
    },
    {
      q: '¿Con qué Pokémon se fusiona Kyurem para convertirse en Kyurem Blanco?',
      correct: 'Reshiram',
      wrong: ['Zekrom', 'Necrozma', 'Solgaleo'],
      explain: 'Kyurem + Reshiram = Kyurem Blanco; Kyurem + Zekrom = Kyurem Negro.',
    },
    {
      q: '¿Qué Pokémon legendario aparece en la portada de Pokémon Sol?',
      correct: 'Solgaleo',
      wrong: ['Lunala', 'Necrozma', 'Tapu Koko'],
      explain: 'Solgaleo es la portada de Pokémon Sol; Lunala, la de Luna.',
    },
    {
      q: '¿Qué número tiene Arceus en la Pokédex Nacional?',
      correct: '#493',
      wrong: ['#491', '#492', '#494'],
      explain: 'Arceus es el #493; Darkrai el #491, Shaymin el #492 y Victini el #494.',
    },
    {
      q: '¿Qué Pokémon devolvió la vida a Raikou, Entei y Suicune tras el incendio de la Torre Quemada?',
      correct: 'Ho-Oh',
      wrong: ['Lugia', 'Celebi', 'Moltres'],
      explain: 'Según la leyenda de Johto, Ho-Oh revivió a los tres Pokémon que murieron en el incendio.',
    },
    {
      q: '¿Qué Pokémon legendario aparece en la portada de Pokémon Esmeralda?',
      correct: 'Rayquaza',
      wrong: ['Kyogre', 'Groudon', 'Deoxys'],
      explain: 'Rayquaza es la portada de Pokémon Esmeralda.',
    },
    {
      q: '¿Qué líder de gimnasio de Kanto pasa a formar parte del Alto Mando en Oro y Plata?',
      correct: 'Koga',
      wrong: ['Brock', 'Sabrina', 'Blaine'],
      explain: 'Koga deja el gimnasio de Fucsia a su hija Sachiko y entra al Alto Mando de Johto.',
    },
  ],
};
