/* Generado por tools/question-gen/gen_tipos.py a partir de datos de PokeAPI. No editar a mano: volver a correr el generador. */
window.QUESTION_BANK = window.QUESTION_BANK || {};
window.QUESTION_BANK.tipos = (window.QUESTION_BANK.tipos || []).concat([
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Normal?", correct: "Acero", wrong: ["Planta", "Hielo", "Veneno"], explain: "El tipo Normal es poco eficaz (x0,5) contra Roca y Acero." },
  { q: "Un ataque de tipo Agua contra Latios (Dragón/Psíquico), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0", "x1", "x0,25"], explain: "Agua contra Dragón es x0,5 y Agua contra Psíquico es x1; en total x0,5." },
  { q: "¿A qué tipo de ataque es débil x4 Wingull?", correct: "Eléctrico", wrong: ["Roca", "Normal", "Acero"], explain: "Wingull es Agua/Volador y recibe x4 de Eléctrico." },
  { q: "Cuando Cacnea evoluciona a Cacturne, ¿qué tipo gana?", correct: "Siniestro", wrong: ["Hielo", "Hada", "Agua"], explain: "Cacnea es Planta y Cacturne pasa a ser Planta/Siniestro." },
  { q: "Un ataque de tipo Siniestro contra Azurill (Normal/Hada), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0,25", "x1", "x0"], explain: "Siniestro contra Normal es x1 y Siniestro contra Hada es x0,5; en total x0,5." },
  { q: "¿De qué tipo es Zekrom?", correct: "Dragón/Eléctrico", wrong: ["Dragón/Psíquico", "Volador/Eléctrico", "Dragón"], explain: "Zekrom combina los tipos Dragón y Eléctrico." },
  { q: "Un ataque de tipo Tierra contra Yanma (Bicho/Volador), ¿cuánto daño hace?", correct: "x0", wrong: ["x4", "x0,25", "x1"], explain: "Tierra contra Bicho es x0,5 y Tierra contra Volador es x0; en total x0." },
  { q: "Un ataque de tipo Planta contra Drifblim (Fantasma/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x1", "x0", "x2"], explain: "Planta contra Fantasma es x1 y Planta contra Volador es x0,5; en total x0,5." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Planta/Fuego?", correct: "3", wrong: ["6", "1", "2"], explain: "La combinación Planta/Fuego es débil a Volador, Veneno y Roca." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Acero puro?", correct: "3", wrong: ["4", "5", "6"], explain: "El tipo Acero puro es débil a Lucha, Tierra y Fuego." },
  { q: "Cuando Riolu evoluciona a Lucario, ¿qué tipo gana?", correct: "Acero", wrong: ["Planta", "Normal", "Fuego"], explain: "Riolu es Lucha y Lucario pasa a ser Lucha/Acero." },
  { q: "¿Cuánto daño hace un ataque de tipo Normal a un Pokémon de tipo Acero/Veneno?", correct: "x0,5", wrong: ["x0,25", "x0", "x2"], explain: "Normal contra Acero es x0,5 y Normal contra Veneno es x1; en total x0,5." },
  { q: "¿Cuánto daño hace un ataque de tipo Eléctrico a un Pokémon de tipo Normal/Dragón?", correct: "x0,5", wrong: ["x0", "x0,25", "x2"], explain: "Eléctrico contra Normal es x1 y Eléctrico contra Dragón es x0,5; en total x0,5." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Psicorrayo (tipo Psíquico)?", correct: "Scraggy", wrong: ["Slaking", "Ambipom", "Minun"], explain: "Scraggy es de tipo Siniestro, inmune a los ataques de tipo Psíquico." },
  { q: "Un ataque de tipo Eléctrico contra Rhydon (Tierra/Roca), ¿cuánto daño hace?", correct: "x0", wrong: ["x4", "x1", "x0,25"], explain: "Eléctrico contra Tierra es x0 y Eléctrico contra Roca es x1; en total x0." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Planta?", correct: "Veneno", wrong: ["Hada", "Fantasma", "Siniestro"], explain: "El tipo Planta es poco eficaz (x0,5) contra Volador, Veneno, Bicho, Acero, Fuego, Planta y Dragón." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Fantasma/Planta?", correct: "x1", wrong: ["x2", "x0,25", "x4"], explain: "Roca contra Fantasma es x1 y Roca contra Planta es x1; en total x1." },
  { q: "¿De qué tipo es Mesprit?", correct: "Psíquico", wrong: ["Psíquico/Hielo", "Veneno/Psíquico", "Roca"], explain: "Mesprit es de tipo Psíquico puro." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Acero?", correct: "Hada", wrong: ["Dragón", "Lucha", "Acero"], explain: "Los ataques de tipo Acero son súper eficaces contra Roca, Hielo y Hada." },
  { q: "Un ataque de tipo Bicho contra Igglybuff (Normal/Hada), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x4", "x0", "x0,25"], explain: "Bicho contra Normal es x1 y Bicho contra Hada es x0,5; en total x0,5." },
  { q: "¿De qué tipo es Shieldon?", correct: "Roca/Acero", wrong: ["Roca/Volador", "Normal/Acero", "Roca"], explain: "Shieldon combina los tipos Roca y Acero." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Eléctrico/Volador?", correct: "2", wrong: ["4", "1", "3"], explain: "La combinación Eléctrico/Volador es débil a Roca y Hielo." },
  { q: "Un ataque de tipo Fuego contra Weepinbell (Planta/Veneno), ¿cuánto daño hace?", correct: "x2", wrong: ["x4", "x0", "x0,5"], explain: "Fuego contra Planta es x2 y Fuego contra Veneno es x1; en total x2." },
  { q: "¿Qué Pokémon de esta lista es de tipo Lucha?", correct: "Flamigo", wrong: ["Solosis", "Palossand", "Sandile"], explain: "Flamigo es de tipo Volador/Lucha." },
  { q: "¿Cuánto daño hace un ataque de tipo Fantasma a un Pokémon de tipo Fuego/Acero?", correct: "x1", wrong: ["x0,5", "x0", "x2"], explain: "Fantasma contra Fuego es x1 y Fantasma contra Acero es x1; en total x1." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Puya Nociva (tipo Veneno)?", correct: "Probopass", wrong: ["Mantine", "Skwovet", "Latias"], explain: "Probopass es de tipo Acero, inmune a los ataques de tipo Veneno." },
  { q: "Un ataque de tipo Planta contra Haunter (Fantasma/Veneno), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0", "x1", "x0,25"], explain: "Planta contra Fantasma es x1 y Planta contra Veneno es x0,5; en total x0,5." },
  { q: "¿A qué tipo de ataque es débil x4 Ho-Oh?", correct: "Roca", wrong: ["Agua", "Eléctrico", "Planta"], explain: "Ho-Oh es Fuego/Volador y recibe x4 de Roca." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Roca?", correct: "Acero", wrong: ["Fuego", "Hielo", "Hada"], explain: "El tipo Roca es poco eficaz (x0,5) contra Lucha, Tierra y Acero." },
  { q: "Un ataque de tipo Fuego contra Binacle (Roca/Agua), ¿cuánto daño hace?", correct: "x0,25", wrong: ["x4", "x1", "x0"], explain: "Fuego contra Roca es x0,5 y Fuego contra Agua es x0,5; en total x0,25." },
  { q: "Un ataque de tipo Normal contra Geodude (Roca/Tierra), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x2", "x1", "x0"], explain: "Normal contra Roca es x0,5 y Normal contra Tierra es x1; en total x0,5." },
  { q: "Cuando Chimchar evoluciona a Monferno, ¿qué tipo gana?", correct: "Lucha", wrong: ["Hielo", "Planta", "Psíquico"], explain: "Chimchar es Fuego y Monferno pasa a ser Fuego/Lucha." },
  { q: "¿Cuánto daño hace un ataque de tipo Veneno a un Pokémon de tipo Bicho/Acero?", correct: "x0", wrong: ["x2", "x0,25", "x1"], explain: "Veneno contra Bicho es x1 y Veneno contra Acero es x0; en total x0." },
  { q: "¿De qué tipo es Loudred?", correct: "Normal", wrong: ["Normal/Lucha", "Fuego/Normal", "Psíquico"], explain: "Loudred es de tipo Normal puro." },
  { q: "¿Qué Pokémon de esta lista es de tipo Dragón?", correct: "Reshiram", wrong: ["Joltik", "Escavalier", "Finizen"], explain: "Reshiram es de tipo Dragón/Fuego." },
  { q: "Cuando Silcoon evoluciona a Beautifly, ¿qué tipo gana?", correct: "Volador", wrong: ["Planta", "Tierra", "Fantasma"], explain: "Silcoon es Bicho y Beautifly pasa a ser Bicho/Volador." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Garra Dragón (tipo Dragón)?", correct: "Spritzee", wrong: ["Drapion", "Meowth", "Dragapult"], explain: "Spritzee es de tipo Hada, inmune a los ataques de tipo Dragón." },
  { q: "¿De qué tipo es Cyndaquil?", correct: "Fuego", wrong: ["Fuego/Fantasma", "Roca/Fuego", "Hada"], explain: "Cyndaquil es de tipo Fuego puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Eléctrico a un Pokémon de tipo Dragón/Eléctrico?", correct: "x0,25", wrong: ["x1", "x0,5", "x2"], explain: "Eléctrico contra Dragón es x0,5 y Eléctrico contra Eléctrico es x0,5; en total x0,25." },
  { q: "¿De qué tipo es Drednaw?", correct: "Agua/Roca", wrong: ["Agua/Acero", "Lucha/Roca", "Agua"], explain: "Drednaw combina los tipos Agua y Roca." },
  { q: "¿Qué Pokémon de esta lista es de tipo Roca?", correct: "Kabutops", wrong: ["Slugma", "Hitmonchan", "Aipom"], explain: "Kabutops es de tipo Roca/Agua." },
  { q: "¿Qué Pokémon de esta lista es de tipo Fantasma?", correct: "Dusclops", wrong: ["Kirlia", "Gible", "Wynaut"], explain: "Dusclops es de tipo Fantasma." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Tierra?", correct: "Roca", wrong: ["Normal", "Lucha", "Fantasma"], explain: "Los ataques de tipo Tierra son súper eficaces contra Veneno, Roca, Acero, Fuego y Eléctrico." },
  { q: "¿Cuánto daño hace un ataque de tipo Agua a un Pokémon de tipo Normal/Lucha?", correct: "x1", wrong: ["x0,5", "x0", "x4"], explain: "Agua contra Normal es x1 y Agua contra Lucha es x1; en total x1." },
  { q: "¿A qué tipo de ataque es débil x4 Togedemaru?", correct: "Tierra", wrong: ["Lucha", "Roca", "Planta"], explain: "Togedemaru es Eléctrico/Acero y recibe x4 de Tierra." },
  { q: "¿A qué tipo de ataque es débil x4 Sewaddle?", correct: "Volador", wrong: ["Bicho", "Lucha", "Acero"], explain: "Sewaddle es Bicho/Planta y recibe x4 de Volador y Fuego." },
  { q: "¿De qué tipo es Skitty?", correct: "Normal", wrong: ["Normal/Agua", "Bicho/Normal", "Eléctrico"], explain: "Skitty es de tipo Normal puro." },
  { q: "¿Qué tipo resiste los ataques de tipo Planta?", correct: "Acero", wrong: ["Normal", "Fantasma", "Eléctrico"], explain: "Resisten los ataques de tipo Planta: Volador, Veneno, Bicho, Acero, Fuego, Planta y Dragón." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Volador?", correct: "Bicho", wrong: ["Hada", "Siniestro", "Psíquico"], explain: "Los ataques de tipo Volador son súper eficaces contra Lucha, Bicho y Planta." },
  { q: "¿A qué tipo de ataque es débil x4 Palpitoad?", correct: "Planta", wrong: ["Fuego", "Agua", "Fantasma"], explain: "Palpitoad es Agua/Tierra y recibe x4 de Planta." },
  { q: "¿Cuánto daño hace un ataque de tipo Planta a un Pokémon de tipo Roca/Veneno?", correct: "x1", wrong: ["x0,5", "x2", "x4"], explain: "Planta contra Roca es x2 y Planta contra Veneno es x0,5; en total x1." },
  { q: "¿A qué tipo de ataque es débil x4 Shiftry?", correct: "Bicho", wrong: ["Fuego", "Hielo", "Roca"], explain: "Shiftry es Planta/Siniestro y recibe x4 de Bicho." },
  { q: "Un ataque de tipo Eléctrico contra Baltoy (Tierra/Psíquico), ¿cuánto daño hace?", correct: "x0", wrong: ["x0,25", "x2", "x0,5"], explain: "Eléctrico contra Tierra es x0 y Eléctrico contra Psíquico es x1; en total x0." },
  { q: "¿A qué tipo de ataque es débil x4 Pupitar?", correct: "Planta", wrong: ["Hielo", "Eléctrico", "Dragón"], explain: "Pupitar es Roca/Tierra y recibe x4 de Agua y Planta." },
  { q: "¿A qué tipo de ataque es débil x4 Exeggutor?", correct: "Bicho", wrong: ["Fantasma", "Siniestro", "Hada"], explain: "Exeggutor es Planta/Psíquico y recibe x4 de Bicho." },
  { q: "¿Qué Pokémon de esta lista es de tipo Normal?", correct: "Smeargle", wrong: ["Beedrill", "Blastoise", "Ledyba"], explain: "Smeargle es de tipo Normal." },
  { q: "Un ataque de tipo Bicho contra Taillow (Normal/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0", "x1", "x4"], explain: "Bicho contra Normal es x1 y Bicho contra Volador es x0,5; en total x0,5." },
  { q: "¿A qué tipo de ataque es débil x4 Toxel?", correct: "Tierra", wrong: ["Psíquico", "Fantasma", "Hada"], explain: "Toxel es Eléctrico/Veneno y recibe x4 de Tierra." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Volador?", correct: "Eléctrico", wrong: ["Tierra", "Siniestro", "Volador"], explain: "El tipo Volador es débil a Roca, Eléctrico y Hielo." },
  { q: "Un ataque de tipo Psíquico contra Larvitar (Roca/Tierra), ¿cuánto daño hace?", correct: "x1", wrong: ["x0,5", "x0,25", "x4"], explain: "Psíquico contra Roca es x1 y Psíquico contra Tierra es x1; en total x1." },
  { q: "Un ataque de tipo Tierra contra Gengar (Fantasma/Veneno), ¿cuánto daño hace?", correct: "x2", wrong: ["x0", "x0,5", "x4"], explain: "Tierra contra Fantasma es x1 y Tierra contra Veneno es x2; en total x2." },
  { q: "Un ataque de tipo Fuego contra Beldum (Acero/Psíquico), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,5", "x0,25", "x4"], explain: "Fuego contra Acero es x2 y Fuego contra Psíquico es x1; en total x2." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Agua?", correct: "Planta", wrong: ["Eléctrico", "Hielo", "Fuego"], explain: "El tipo Agua es poco eficaz (x0,5) contra Agua, Planta y Dragón." },
  { q: "Un ataque de tipo Normal contra Pheromosa (Bicho/Lucha), ¿cuánto daño hace?", correct: "x1", wrong: ["x2", "x4", "x0,5"], explain: "Normal contra Bicho es x1 y Normal contra Lucha es x1; en total x1." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Roca/Hielo?", correct: "x2", wrong: ["x0,25", "x1", "x4"], explain: "Roca contra Roca es x1 y Roca contra Hielo es x2; en total x2." },
  { q: "Un ataque de tipo Agua contra Lapras (Agua/Hielo), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x1", "x0,25", "x0"], explain: "Agua contra Agua es x0,5 y Agua contra Hielo es x1; en total x0,5." },
  { q: "Un ataque de tipo Tierra contra Dustox (Bicho/Veneno), ¿cuánto daño hace?", correct: "x1", wrong: ["x0,5", "x0,25", "x2"], explain: "Tierra contra Bicho es x0,5 y Tierra contra Veneno es x2; en total x1." },
  { q: "Cuando Nidorina evoluciona a Nidoqueen, ¿qué tipo gana?", correct: "Tierra", wrong: ["Dragón", "Hada", "Lucha"], explain: "Nidorina es Veneno y Nidoqueen pasa a ser Veneno/Tierra." },
  { q: "¿De qué tipo es Poliwhirl?", correct: "Agua", wrong: ["Agua/Acero", "Volador/Agua", "Hielo"], explain: "Poliwhirl es de tipo Agua puro." },
  { q: "Un ataque de tipo Siniestro contra Heracross (Bicho/Lucha), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0,25", "x2", "x0"], explain: "Siniestro contra Bicho es x1 y Siniestro contra Lucha es x0,5; en total x0,5." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Pulso Dragón (tipo Dragón)?", correct: "Togetic", wrong: ["Nidoran♀", "Muk", "Grumpig"], explain: "Togetic es de tipo Hada, inmune a los ataques de tipo Dragón." },
  { q: "¿De qué tipo es Pansage?", correct: "Planta", wrong: ["Planta/Tierra", "Volador/Planta", "Fuego"], explain: "Pansage es de tipo Planta puro." },
  { q: "Cuando Seedot evoluciona a Nuzleaf, ¿qué tipo gana?", correct: "Siniestro", wrong: ["Tierra", "Roca", "Bicho"], explain: "Seedot es Planta y Nuzleaf pasa a ser Planta/Siniestro." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Planta/Tierra?", correct: "4", wrong: ["7", "1", "3"], explain: "La combinación Planta/Tierra es débil a Volador, Bicho, Fuego y Hielo." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Confusión (tipo Psíquico)?", correct: "Tyranitar", wrong: ["Espeon", "Grumpig", "Muk"], explain: "Tyranitar es de tipo Siniestro, inmune a los ataques de tipo Psíquico." },
  { q: "¿A qué tipo de ataque es débil x4 Cramorant?", correct: "Eléctrico", wrong: ["Roca", "Planta", "Fantasma"], explain: "Cramorant es Volador/Agua y recibe x4 de Eléctrico." },
  { q: "¿De qué tipo es Beedrill?", correct: "Bicho/Veneno", wrong: ["Bicho/Psíquico", "Fuego/Veneno", "Bicho"], explain: "Beedrill combina los tipos Bicho y Veneno." },
  { q: "Un ataque de tipo Eléctrico contra Swellow (Normal/Volador), ¿cuánto daño hace?", correct: "x2", wrong: ["x4", "x0,25", "x0,5"], explain: "Eléctrico contra Normal es x1 y Eléctrico contra Volador es x2; en total x2." },
  { q: "Un ataque de tipo Tierra contra Pupitar (Roca/Tierra), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,25", "x0", "x0,5"], explain: "Tierra contra Roca es x2 y Tierra contra Tierra es x1; en total x2." },
  { q: "¿Cuánto daño hace un ataque de tipo Bicho a un Pokémon de tipo Dragón/Lucha?", correct: "x0,5", wrong: ["x4", "x0,25", "x0"], explain: "Bicho contra Dragón es x1 y Bicho contra Lucha es x0,5; en total x0,5." },
  { q: "¿A qué tipo de ataque es débil x4 Hoppip?", correct: "Hielo", wrong: ["Fuego", "Eléctrico", "Siniestro"], explain: "Hoppip es Planta/Volador y recibe x4 de Hielo." },
  { q: "Un ataque de tipo Agua contra Gligar (Tierra/Volador), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,25", "x1", "x0,5"], explain: "Agua contra Tierra es x2 y Agua contra Volador es x1; en total x2." },
  { q: "¿Qué tipo es inmune a los ataques de tipo Fantasma?", correct: "Normal", wrong: ["Eléctrico", "Volador", "Agua"], explain: "Los ataques de tipo Fantasma no afectan a Normal." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Fantasma?", correct: "Siniestro", wrong: ["Planta", "Volador", "Bicho"], explain: "El tipo Fantasma es poco eficaz (x0,5) contra Siniestro." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Puño Trueno (tipo Eléctrico)?", correct: "Wooper", wrong: ["Haunter", "Goldeen", "Sneasel"], explain: "Wooper es de tipo Tierra, inmune a los ataques de tipo Eléctrico." },
  { q: "Un ataque de tipo Veneno contra Heatran (Fuego/Acero), ¿cuánto daño hace?", correct: "x0", wrong: ["x1", "x4", "x0,5"], explain: "Veneno contra Fuego es x1 y Veneno contra Acero es x0; en total x0." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Bola Sombra (tipo Fantasma)?", correct: "Farfetch’d", wrong: ["Ivysaur", "Dragonite", "Arcanine"], explain: "Farfetch’d es de tipo Normal, inmune a los ataques de tipo Fantasma." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Lucha/Fantasma?", correct: "4", wrong: ["5", "7", "6"], explain: "La combinación Lucha/Fantasma es débil a Volador, Fantasma, Psíquico y Hada." },
  { q: "¿De qué tipo es Clamperl?", correct: "Agua", wrong: ["Agua/Dragón", "Fantasma/Agua", "Acero"], explain: "Clamperl es de tipo Agua puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Dragón a un Pokémon de tipo Psíquico/Fuego?", correct: "x1", wrong: ["x0,25", "x0", "x2"], explain: "Dragón contra Psíquico es x1 y Dragón contra Fuego es x1; en total x1." },
  { q: "¿Cuánto daño hace un ataque de tipo Dragón a un Pokémon de tipo Psíquico/Hada?", correct: "x0", wrong: ["x4", "x0,25", "x1"], explain: "Dragón contra Psíquico es x1 y Dragón contra Hada es x0; en total x0." },
  { q: "¿De qué tipo es Mismagius?", correct: "Fantasma", wrong: ["Fantasma/Acero", "Agua/Fantasma", "Tierra"], explain: "Mismagius es de tipo Fantasma puro." },
  { q: "Un ataque de tipo Dragón contra Rhyperior (Tierra/Roca), ¿cuánto daño hace?", correct: "x1", wrong: ["x0,5", "x4", "x0"], explain: "Dragón contra Tierra es x1 y Dragón contra Roca es x1; en total x1." },
  { q: "¿A qué tipo de ataque es débil x4 Ledyba?", correct: "Roca", wrong: ["Hielo", "Volador", "Veneno"], explain: "Ledyba es Bicho/Volador y recibe x4 de Roca." },
  { q: "¿De qué tipo es Pangoro?", correct: "Lucha/Siniestro", wrong: ["Lucha/Volador", "Eléctrico/Siniestro", "Lucha"], explain: "Pangoro combina los tipos Lucha y Siniestro." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Eléctrico puro?", correct: "1", wrong: ["4", "0", "3"], explain: "El tipo Eléctrico puro es débil a Tierra." },
  { q: "Un ataque de tipo Hielo contra Fearow (Normal/Volador), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,25", "x0", "x4"], explain: "Hielo contra Normal es x1 y Hielo contra Volador es x2; en total x2." },
  { q: "¿Cuánto daño hace un ataque de tipo Fantasma a un Pokémon de tipo Eléctrico/Normal?", correct: "x0", wrong: ["x2", "x1", "x0,25"], explain: "Fantasma contra Eléctrico es x1 y Fantasma contra Normal es x0; en total x0." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Rayo (tipo Eléctrico)?", correct: "Quagsire", wrong: ["Nidoran♀", "Jumpluff", "Dusclops"], explain: "Quagsire es de tipo Tierra, inmune a los ataques de tipo Eléctrico." },
  { q: "¿A qué tipo de ataque es débil x4 Quagsire?", correct: "Planta", wrong: ["Roca", "Normal", "Bicho"], explain: "Quagsire es Agua/Tierra y recibe x4 de Planta." },
  { q: "Un ataque de tipo Agua contra Jumpluff (Planta/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x2", "x0", "x0,25"], explain: "Agua contra Planta es x0,5 y Agua contra Volador es x1; en total x0,5." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Hiperrayo (tipo Normal)?", correct: "Pecharunt", wrong: ["Quagsire", "Sudowoodo", "Torkoal"], explain: "Pecharunt es de tipo Fantasma, inmune a los ataques de tipo Normal." },
  { q: "¿Qué Pokémon de esta lista es de tipo Agua?", correct: "Suicune", wrong: ["Rapidash", "Noctowl", "Togetic"], explain: "Suicune es de tipo Agua." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Lucha?", correct: "Hielo", wrong: ["Dragón", "Bicho", "Fantasma"], explain: "Los ataques de tipo Lucha son súper eficaces contra Normal, Roca, Acero, Hielo y Siniestro." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Hielo?", correct: "Acero", wrong: ["Psíquico", "Tierra", "Roca"], explain: "El tipo Hielo es poco eficaz (x0,5) contra Acero, Fuego, Agua y Hielo." },
  { q: "Un ataque de tipo Planta contra Noctowl (Normal/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x2", "x0", "x0,25"], explain: "Planta contra Normal es x1 y Planta contra Volador es x0,5; en total x0,5." },
  { q: "¿Cuál de estos Pokémon es de tipo Agua puro?", correct: "Kyogre", wrong: ["Ludicolo", "Froslass", "Zangoose"], explain: "Kyogre es de tipo Agua puro; los demás no." },
  { q: "¿Cuál de estos Pokémon es de tipo Eléctrico puro?", correct: "Luxray", wrong: ["Magnezone", "Gulpin", "Wailord"], explain: "Luxray es de tipo Eléctrico puro; los demás no." },
  { q: "Un ataque de tipo Psíquico contra Skorupi (Veneno/Bicho), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x0", "x0,5"], explain: "Psíquico contra Veneno es x2 y Psíquico contra Bicho es x1; en total x2." },
  { q: "¿Cuánto daño hace un ataque de tipo Hada a un Pokémon de tipo Tierra/Dragón?", correct: "x2", wrong: ["x0,25", "x0", "x0,5"], explain: "Hada contra Tierra es x1 y Hada contra Dragón es x2; en total x2." },
  { q: "¿Qué tipo es inmune a los ataques de tipo Veneno?", correct: "Acero", wrong: ["Roca", "Hielo", "Lucha"], explain: "Los ataques de tipo Veneno no afectan a Acero." },
  { q: "Un ataque de tipo Veneno contra Bulbasaur (Planta/Veneno), ¿cuánto daño hace?", correct: "x1", wrong: ["x2", "x4", "x0,5"], explain: "Veneno contra Planta es x2 y Veneno contra Veneno es x0,5; en total x1." },
  { q: "Un ataque de tipo Dragón contra Gardevoir (Psíquico/Hada), ¿cuánto daño hace?", correct: "x0", wrong: ["x4", "x1", "x0,25"], explain: "Dragón contra Psíquico es x1 y Dragón contra Hada es x0; en total x0." },
  { q: "¿A qué tipo de ataque es débil x4 Yanma?", correct: "Roca", wrong: ["Fuego", "Normal", "Planta"], explain: "Yanma es Bicho/Volador y recibe x4 de Roca." },
  { q: "Un ataque de tipo Eléctrico contra Gloom (Planta/Veneno), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x2", "x0", "x1"], explain: "Eléctrico contra Planta es x0,5 y Eléctrico contra Veneno es x1; en total x0,5." },
  { q: "¿De qué tipo es Magnemite?", correct: "Eléctrico/Acero", wrong: ["Eléctrico/Psíquico", "Siniestro/Acero", "Eléctrico"], explain: "Magnemite combina los tipos Eléctrico y Acero." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Planta/Siniestro?", correct: "7", wrong: ["6", "8", "4"], explain: "La combinación Planta/Siniestro es débil a Lucha, Volador, Veneno, Bicho, Fuego, Hielo y Hada." },
  { q: "¿A qué tipo de ataque es débil x4 Tropius?", correct: "Hielo", wrong: ["Roca", "Volador", "Agua"], explain: "Tropius es Planta/Volador y recibe x4 de Hielo." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Bicho?", correct: "Volador", wrong: ["Siniestro", "Normal", "Hielo"], explain: "El tipo Bicho es débil a Volador, Roca y Fuego." },
  { q: "Un ataque de tipo Volador contra Buzzwole (Bicho/Lucha), ¿cuánto daño hace?", correct: "x4", wrong: ["x0,25", "x2", "x0"], explain: "Volador contra Bicho es x2 y Volador contra Lucha es x2; en total x4." },
  { q: "Cuando Seadra evoluciona a Kingdra, ¿qué tipo gana?", correct: "Dragón", wrong: ["Eléctrico", "Hielo", "Hada"], explain: "Seadra es Agua y Kingdra pasa a ser Agua/Dragón." },
  { q: "Cuando Grotle evoluciona a Torterra, ¿qué tipo gana?", correct: "Tierra", wrong: ["Lucha", "Hielo", "Eléctrico"], explain: "Grotle es Planta y Torterra pasa a ser Planta/Tierra." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Roca/Psíquico?", correct: "x1", wrong: ["x0", "x4", "x0,25"], explain: "Roca contra Roca es x1 y Roca contra Psíquico es x1; en total x1." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Bicho?", correct: "Siniestro", wrong: ["Volador", "Acero", "Agua"], explain: "Los ataques de tipo Bicho son súper eficaces contra Planta, Psíquico y Siniestro." },
  { q: "Un ataque de tipo Fantasma contra Doduo (Normal/Volador), ¿cuánto daño hace?", correct: "x0", wrong: ["x0,5", "x0,25", "x4"], explain: "Fantasma contra Normal es x0 y Fantasma contra Volador es x1; en total x0." },
  { q: "¿A qué tipo de ataque es débil x4 Swampert?", correct: "Planta", wrong: ["Acero", "Fantasma", "Fuego"], explain: "Swampert es Agua/Tierra y recibe x4 de Planta." },
  { q: "¿Cuánto daño hace un ataque de tipo Veneno a un Pokémon de tipo Bicho/Planta?", correct: "x2", wrong: ["x4", "x0", "x1"], explain: "Veneno contra Bicho es x1 y Veneno contra Planta es x2; en total x2." },
  { q: "Un ataque de tipo Normal contra Tentacool (Agua/Veneno), ¿cuánto daño hace?", correct: "x1", wrong: ["x0", "x0,25", "x4"], explain: "Normal contra Agua es x1 y Normal contra Veneno es x1; en total x1." },
  { q: "Un ataque de tipo Hielo contra Masquerain (Bicho/Volador), ¿cuánto daño hace?", correct: "x2", wrong: ["x0", "x0,5", "x4"], explain: "Hielo contra Bicho es x1 y Hielo contra Volador es x2; en total x2." },
  { q: "¿Cuánto daño hace un ataque de tipo Fantasma a un Pokémon de tipo Veneno/Dragón?", correct: "x1", wrong: ["x0,5", "x0", "x4"], explain: "Fantasma contra Veneno es x1 y Fantasma contra Dragón es x1; en total x1." },
  { q: "Un ataque de tipo Roca contra Aerodactyl (Roca/Volador), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x0", "x0,5"], explain: "Roca contra Roca es x1 y Roca contra Volador es x2; en total x2." },
  { q: "Un ataque de tipo Agua contra Victini (Psíquico/Fuego), ¿cuánto daño hace?", correct: "x2", wrong: ["x4", "x0,5", "x0"], explain: "Agua contra Psíquico es x1 y Agua contra Fuego es x2; en total x2." },
  { q: "¿De qué tipo es Azurill?", correct: "Normal/Hada", wrong: ["Normal/Agua", "Eléctrico/Hada", "Normal"], explain: "Azurill combina los tipos Normal y Hada." },
  { q: "¿De qué tipo es Bayleef?", correct: "Planta", wrong: ["Planta/Fuego", "Bicho/Planta", "Tierra"], explain: "Bayleef es de tipo Planta puro." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Cometa Draco (tipo Dragón)?", correct: "Gardevoir", wrong: ["Swinub", "Sneasel", "Slaking"], explain: "Gardevoir es de tipo Hada, inmune a los ataques de tipo Dragón." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Veneno?", correct: "Roca", wrong: ["Hielo", "Planta", "Volador"], explain: "El tipo Veneno es poco eficaz (x0,5) contra Veneno, Tierra, Roca y Fantasma." },
  { q: "¿De qué tipo es Poliwag?", correct: "Agua", wrong: ["Agua/Fuego", "Roca/Agua", "Planta"], explain: "Poliwag es de tipo Agua puro." },
  { q: "¿Qué tipo resiste los ataques de tipo Volador?", correct: "Eléctrico", wrong: ["Dragón", "Bicho", "Planta"], explain: "Resisten los ataques de tipo Volador: Roca, Acero y Eléctrico." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Fuego?", correct: "Coalossal", wrong: ["Gothitelle", "Thundurus", "Aromatisse"], explain: "Coalossal es de tipo Roca/Fuego." },
  { q: "Un ataque de tipo Dragón contra Vibrava (Tierra/Dragón), ¿cuánto daño hace?", correct: "x2", wrong: ["x0", "x1", "x0,25"], explain: "Dragón contra Tierra es x1 y Dragón contra Dragón es x2; en total x2." },
  { q: "Un ataque de tipo Eléctrico contra Vespiquen (Bicho/Volador), ¿cuánto daño hace?", correct: "x2", wrong: ["x4", "x1", "x0,5"], explain: "Eléctrico contra Bicho es x1 y Eléctrico contra Volador es x2; en total x2." },
  { q: "Un ataque de tipo Planta contra Marill (Agua/Hada), ¿cuánto daño hace?", correct: "x2", wrong: ["x0", "x4", "x0,25"], explain: "Planta contra Agua es x2 y Planta contra Hada es x1; en total x2." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Fuego?", correct: "Dragón", wrong: ["Planta", "Siniestro", "Psíquico"], explain: "El tipo Fuego es poco eficaz (x0,5) contra Roca, Fuego, Agua y Dragón." },
  { q: "Un ataque de tipo Bicho contra Combusken (Fuego/Lucha), ¿cuánto daño hace?", correct: "x0,25", wrong: ["x0,5", "x4", "x1"], explain: "Bicho contra Fuego es x0,5 y Bicho contra Lucha es x0,5; en total x0,25." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Bicho?", correct: "Charjabug", wrong: ["Blacephalon", "Carracosta", "Jellicent"], explain: "Charjabug es de tipo Bicho/Eléctrico." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Psíquico puro?", correct: "3", wrong: ["5", "1", "4"], explain: "El tipo Psíquico puro es débil a Bicho, Fantasma y Siniestro." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Dragón/Lucha?", correct: "5", wrong: ["4", "8", "7"], explain: "La combinación Dragón/Lucha es débil a Volador, Psíquico, Hielo, Dragón y Hada." },
  { q: "Un ataque de tipo Lucha contra Tyrantrum (Roca/Dragón), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x0", "x4"], explain: "Lucha contra Roca es x2 y Lucha contra Dragón es x1; en total x2." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Fuego?", correct: "Tierra", wrong: ["Acero", "Psíquico", "Normal"], explain: "El tipo Fuego es débil a Tierra, Roca y Agua." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Veneno puro?", correct: "2", wrong: ["1", "0", "4"], explain: "El tipo Veneno puro es débil a Tierra y Psíquico." },
  { q: "¿Qué Pokémon de esta lista es de tipo Acero?", correct: "Mawile", wrong: ["Mothim", "Luxio", "Skuntank"], explain: "Mawile es de tipo Acero/Hada." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Planta?", correct: "Hielo", wrong: ["Roca", "Eléctrico", "Siniestro"], explain: "El tipo Planta es débil a Volador, Veneno, Bicho, Fuego y Hielo." },
  { q: "¿Cuál de estos Pokémon es de tipo Fuego puro?", correct: "Arcanine", wrong: ["Ho-Oh", "Yanma", "Magcargo"], explain: "Arcanine es de tipo Fuego puro; los demás no." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Tierra Viva (tipo Tierra)?", correct: "Farfetch’d", wrong: ["Psyduck", "Raichu", "Arcanine"], explain: "Farfetch’d es de tipo Volador, inmune a los ataques de tipo Tierra." },
  { q: "Cuando Corphish evoluciona a Crawdaunt, ¿qué tipo gana?", correct: "Siniestro", wrong: ["Psíquico", "Dragón", "Eléctrico"], explain: "Corphish es Agua y Crawdaunt pasa a ser Agua/Siniestro." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Lucha?", correct: "Veneno", wrong: ["Planta", "Siniestro", "Eléctrico"], explain: "El tipo Lucha es poco eficaz (x0,5) contra Volador, Veneno, Bicho, Psíquico y Hada." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Eléctrico?", correct: "Flaaffy", wrong: ["Croconaw", "Chansey", "Grimer"], explain: "Flaaffy es de tipo Eléctrico." },
  { q: "¿Qué tipo resiste los ataques de tipo Bicho?", correct: "Veneno", wrong: ["Psíquico", "Hielo", "Siniestro"], explain: "Resisten los ataques de tipo Bicho: Lucha, Volador, Veneno, Fantasma, Acero, Fuego y Hada." },
  { q: "¿Cuánto daño hace un ataque de tipo Planta a un Pokémon de tipo Agua/Tierra?", correct: "x4", wrong: ["x0,25", "x0", "x0,5"], explain: "Planta contra Agua es x2 y Planta contra Tierra es x2; en total x4." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Acero?", correct: "Shieldon", wrong: ["Chimecho", "Lileep", "Makuhita"], explain: "Shieldon es de tipo Roca/Acero." },
  { q: "¿De qué tipo es Smoliv?", correct: "Planta/Normal", wrong: ["Planta/Fuego", "Hada/Normal", "Planta"], explain: "Smoliv combina los tipos Planta y Normal." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Psíquico?", correct: "Siniestro", wrong: ["Roca", "Dragón", "Volador"], explain: "El tipo Psíquico es débil a Bicho, Fantasma y Siniestro." },
  { q: "¿De qué tipo es Slugma?", correct: "Fuego", wrong: ["Fuego/Normal", "Volador/Fuego", "Siniestro"], explain: "Slugma es de tipo Fuego puro." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Agua?", correct: "Roca", wrong: ["Bicho", "Agua", "Hielo"], explain: "Los ataques de tipo Agua son súper eficaces contra Tierra, Roca y Fuego." },
  { q: "¿De qué tipo es Dunsparce?", correct: "Normal", wrong: ["Normal/Siniestro", "Dragón/Normal", "Hada"], explain: "Dunsparce es de tipo Normal puro." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Volador?", correct: "Dartrix", wrong: ["Gossifleur", "Falinks", "Genesect"], explain: "Dartrix es de tipo Planta/Volador." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Dragón puro?", correct: "3", wrong: ["4", "6", "5"], explain: "El tipo Dragón puro es débil a Hielo, Dragón y Hada." },
  { q: "Un ataque de tipo Bicho contra Ledian (Bicho/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x1", "x2", "x4"], explain: "Bicho contra Bicho es x1 y Bicho contra Volador es x0,5; en total x0,5." },
  { q: "Un ataque de tipo Hada contra Hydreigon (Siniestro/Dragón), ¿cuánto daño hace?", correct: "x4", wrong: ["x2", "x0,25", "x0,5"], explain: "Hada contra Siniestro es x2 y Hada contra Dragón es x2; en total x4." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Hada puro?", correct: "2", wrong: ["4", "1", "0"], explain: "El tipo Hada puro es débil a Veneno y Acero." },
  { q: "¿A qué tipo de ataque es débil x4 Graveler?", correct: "Planta", wrong: ["Lucha", "Tierra", "Normal"], explain: "Graveler es Roca/Tierra y recibe x4 de Agua y Planta." },
  { q: "¿Cuánto daño hace un ataque de tipo Psíquico a un Pokémon de tipo Hielo/Psíquico?", correct: "x0,5", wrong: ["x0", "x1", "x4"], explain: "Psíquico contra Hielo es x1 y Psíquico contra Psíquico es x0,5; en total x0,5." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Agua?", correct: "Eléctrico", wrong: ["Normal", "Roca", "Hielo"], explain: "El tipo Agua es débil a Planta y Eléctrico." },
  { q: "¿A qué tipo de ataque es débil x4 Flygon?", correct: "Hielo", wrong: ["Dragón", "Hada", "Volador"], explain: "Flygon es Tierra/Dragón y recibe x4 de Hielo." },
  { q: "Un ataque de tipo Bicho contra Leavanny (Bicho/Planta), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,5", "x1", "x0"], explain: "Bicho contra Bicho es x1 y Bicho contra Planta es x2; en total x2." },
  { q: "¿De qué tipo es Grimer?", correct: "Veneno", wrong: ["Veneno/Bicho", "Siniestro/Veneno", "Volador"], explain: "Grimer es de tipo Veneno puro." },
  { q: "Un ataque de tipo Tierra contra Houndoom (Siniestro/Fuego), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,25", "x0", "x0,5"], explain: "Tierra contra Siniestro es x1 y Tierra contra Fuego es x2; en total x2." },
  { q: "¿Cuánto daño hace un ataque de tipo Dragón a un Pokémon de tipo Acero/Tierra?", correct: "x0,5", wrong: ["x2", "x1", "x0,25"], explain: "Dragón contra Acero es x0,5 y Dragón contra Tierra es x1; en total x0,5." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Roca/Eléctrico?", correct: "4", wrong: ["5", "1", "2"], explain: "La combinación Roca/Eléctrico es débil a Lucha, Tierra, Agua y Planta." },
  { q: "¿De qué tipo es Porygon-Z?", correct: "Normal", wrong: ["Normal/Psíquico", "Planta/Normal", "Tierra"], explain: "Porygon-Z es de tipo Normal puro." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Psíquico?", correct: "Veneno", wrong: ["Volador", "Planta", "Tierra"], explain: "Los ataques de tipo Psíquico son súper eficaces contra Lucha y Veneno." },
  { q: "Cuando Togepi evoluciona a Togetic, ¿qué tipo gana?", correct: "Volador", wrong: ["Lucha", "Fantasma", "Bicho"], explain: "Togepi es Hada y Togetic pasa a ser Hada/Volador." },
  { q: "¿De qué tipo es Houndoom?", correct: "Siniestro/Fuego", wrong: ["Siniestro/Hada", "Roca/Fuego", "Siniestro"], explain: "Houndoom combina los tipos Siniestro y Fuego." },
  { q: "¿Cuánto daño hace un ataque de tipo Psíquico a un Pokémon de tipo Agua/Siniestro?", correct: "x0", wrong: ["x2", "x0,5", "x1"], explain: "Psíquico contra Agua es x1 y Psíquico contra Siniestro es x0; en total x0." },
  { q: "¿Cuánto daño hace un ataque de tipo Planta a un Pokémon de tipo Bicho/Fantasma?", correct: "x0,5", wrong: ["x1", "x0,25", "x0"], explain: "Planta contra Bicho es x0,5 y Planta contra Fantasma es x1; en total x0,5." },
  { q: "¿De qué tipo es Jynx?", correct: "Hielo/Psíquico", wrong: ["Hielo/Eléctrico", "Dragón/Psíquico", "Hielo"], explain: "Jynx combina los tipos Hielo y Psíquico." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Agua?", correct: "Psyduck", wrong: ["Zubat", "Steelix", "Tyrogue"], explain: "Psyduck es de tipo Agua." },
  { q: "Un ataque de tipo Hada contra Slowbro (Agua/Psíquico), ¿cuánto daño hace?", correct: "x1", wrong: ["x0", "x4", "x2"], explain: "Hada contra Agua es x1 y Hada contra Psíquico es x1; en total x1." },
  { q: "Un ataque de tipo Fantasma contra Jigglypuff (Normal/Hada), ¿cuánto daño hace?", correct: "x0", wrong: ["x1", "x4", "x2"], explain: "Fantasma contra Normal es x0 y Fantasma contra Hada es x1; en total x0." },
  { q: "¿Cuánto daño hace un ataque de tipo Planta a un Pokémon de tipo Agua/Eléctrico?", correct: "x2", wrong: ["x0,25", "x0", "x0,5"], explain: "Planta contra Agua es x2 y Planta contra Eléctrico es x1; en total x2." },
  { q: "Un ataque de tipo Fantasma contra Smoochum (Hielo/Psíquico), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x0,5", "x4"], explain: "Fantasma contra Hielo es x1 y Fantasma contra Psíquico es x2; en total x2." },
  { q: "Un ataque de tipo Fantasma contra Parasect (Bicho/Planta), ¿cuánto daño hace?", correct: "x1", wrong: ["x0", "x0,25", "x4"], explain: "Fantasma contra Bicho es x1 y Fantasma contra Planta es x1; en total x1." },
  { q: "¿De qué tipo es Taillow?", correct: "Normal/Volador", wrong: ["Normal/Tierra", "Psíquico/Volador", "Normal"], explain: "Taillow combina los tipos Normal y Volador." },
  { q: "¿De qué tipo es Zorua?", correct: "Siniestro", wrong: ["Siniestro/Roca", "Planta/Siniestro", "Hada"], explain: "Zorua es de tipo Siniestro puro." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Planta/Hada?", correct: "5", wrong: ["4", "2", "6"], explain: "La combinación Planta/Hada es débil a Volador, Veneno, Acero, Fuego y Hielo." },
  { q: "¿Cuánto daño hace un ataque de tipo Agua a un Pokémon de tipo Planta/Lucha?", correct: "x0,5", wrong: ["x0,25", "x1", "x4"], explain: "Agua contra Planta es x0,5 y Agua contra Lucha es x1; en total x0,5." },
  { q: "Un ataque de tipo Fuego contra Quagsire (Agua/Tierra), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x2", "x1", "x0"], explain: "Fuego contra Agua es x0,5 y Fuego contra Tierra es x1; en total x0,5." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Hielo?", correct: "Smoochum", wrong: ["Abra", "Victreebel", "Hoppip"], explain: "Smoochum es de tipo Hielo/Psíquico." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Normal?", correct: "Lucha", wrong: ["Bicho", "Dragón", "Eléctrico"], explain: "El tipo Normal es débil a Lucha." },
  { q: "¿De qué tipo es Skiploom?", correct: "Planta/Volador", wrong: ["Planta/Tierra", "Siniestro/Volador", "Planta"], explain: "Skiploom combina los tipos Planta y Volador." },
  { q: "¿A qué tipo de ataque es débil x4 Gyarados?", correct: "Eléctrico", wrong: ["Roca", "Volador", "Acero"], explain: "Gyarados es Agua/Volador y recibe x4 de Eléctrico." },
  { q: "¿De qué tipo es Sudowoodo?", correct: "Roca", wrong: ["Roca/Eléctrico", "Acero/Roca", "Hada"], explain: "Sudowoodo es de tipo Roca puro." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Psíquico?", correct: "Claydol", wrong: ["Milotic", "Electivire", "Volbeat"], explain: "Claydol es de tipo Tierra/Psíquico." },
  { q: "Cuando Charmeleon evoluciona a Charizard, ¿qué tipo gana?", correct: "Volador", wrong: ["Lucha", "Eléctrico", "Planta"], explain: "Charmeleon es Fuego y Charizard pasa a ser Fuego/Volador." },
  { q: "Cuando Staryu evoluciona a Starmie, ¿qué tipo gana?", correct: "Psíquico", wrong: ["Bicho", "Veneno", "Roca"], explain: "Staryu es Agua y Starmie pasa a ser Agua/Psíquico." },
  { q: "Un ataque de tipo Hielo contra Azumarill (Agua/Hada), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x2", "x1", "x4"], explain: "Hielo contra Agua es x0,5 y Hielo contra Hada es x1; en total x0,5." },
  { q: "¿Cuánto daño hace un ataque de tipo Psíquico a un Pokémon de tipo Lucha/Hielo?", correct: "x2", wrong: ["x1", "x0,25", "x4"], explain: "Psíquico contra Lucha es x2 y Psíquico contra Hielo es x1; en total x2." },
  { q: "¿A qué tipo de ataque es débil x4 Dipplin?", correct: "Hielo", wrong: ["Hada", "Dragón", "Lucha"], explain: "Dipplin es Planta/Dragón y recibe x4 de Hielo." },
  { q: "Un ataque de tipo Bicho contra Durant (Bicho/Acero), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x4", "x2", "x0"], explain: "Bicho contra Bicho es x1 y Bicho contra Acero es x0,5; en total x0,5." },
  { q: "¿De qué tipo es Girafarig?", correct: "Normal/Psíquico", wrong: ["Normal/Volador", "Dragón/Psíquico", "Normal"], explain: "Girafarig combina los tipos Normal y Psíquico." },
  { q: "¿Qué Pokémon de esta lista es de tipo Fuego?", correct: "Ponyta", wrong: ["Omastar", "Pupitar", "Rhydon"], explain: "Ponyta es de tipo Fuego." },
  { q: "Un ataque de tipo Hada contra Breloom (Planta/Lucha), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,5", "x0,25", "x0"], explain: "Hada contra Planta es x1 y Hada contra Lucha es x2; en total x2." },
  { q: "¿Cuánto daño hace un ataque de tipo Bicho a un Pokémon de tipo Fantasma/Veneno?", correct: "x0,25", wrong: ["x2", "x1", "x4"], explain: "Bicho contra Fantasma es x0,5 y Bicho contra Veneno es x0,5; en total x0,25." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Infortunio (tipo Fantasma)?", correct: "Ditto", wrong: ["Dragapult", "Sunkern", "Ivysaur"], explain: "Ditto es de tipo Normal, inmune a los ataques de tipo Fantasma." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Hada?", correct: "Veneno", wrong: ["Normal", "Eléctrico", "Hada"], explain: "El tipo Hada es débil a Veneno y Acero." },
  { q: "¿Qué tipo es inmune a los ataques de tipo Tierra?", correct: "Volador", wrong: ["Bicho", "Hielo", "Dragón"], explain: "Los ataques de tipo Tierra no afectan a Volador." },
  { q: "¿Qué tipo resiste los ataques de tipo Hielo?", correct: "Agua", wrong: ["Bicho", "Normal", "Veneno"], explain: "Resisten los ataques de tipo Hielo: Acero, Fuego, Agua y Hielo." },
  { q: "¿A qué tipo de ataque es débil x4 Kabutops?", correct: "Planta", wrong: ["Tierra", "Acero", "Dragón"], explain: "Kabutops es Roca/Agua y recibe x4 de Planta." },
  { q: "¿De qué tipo es Nymble?", correct: "Bicho", wrong: ["Bicho/Roca", "Veneno/Bicho", "Tierra"], explain: "Nymble es de tipo Bicho puro." },
  { q: "¿Qué tipo resiste los ataques de tipo Normal?", correct: "Roca", wrong: ["Volador", "Lucha", "Bicho"], explain: "Resisten los ataques de tipo Normal: Roca y Acero." },
  { q: "¿A qué tipo de ataque es débil x4 Yanmega?", correct: "Roca", wrong: ["Eléctrico", "Hielo", "Hada"], explain: "Yanmega es Bicho/Volador y recibe x4 de Roca." },
  { q: "¿De qué tipo es Hoothoot?", correct: "Normal/Volador", wrong: ["Normal/Dragón", "Roca/Volador", "Normal"], explain: "Hoothoot combina los tipos Normal y Volador." },
  { q: "¿De qué tipo es Machop?", correct: "Lucha", wrong: ["Lucha/Veneno", "Eléctrico/Lucha", "Hielo"], explain: "Machop es de tipo Lucha puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Fuego a un Pokémon de tipo Roca/Dragón?", correct: "x0,25", wrong: ["x0,5", "x0", "x1"], explain: "Fuego contra Roca es x0,5 y Fuego contra Dragón es x0,5; en total x0,25." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Tierra?", correct: "Bicho", wrong: ["Dragón", "Fuego", "Normal"], explain: "El tipo Tierra es poco eficaz (x0,5) contra Bicho y Planta." },
  { q: "¿A qué tipo de ataque es débil x4 Geodude?", correct: "Planta", wrong: ["Hielo", "Dragón", "Bicho"], explain: "Geodude es Roca/Tierra y recibe x4 de Agua y Planta." },
  { q: "¿De qué tipo es Delphox?", correct: "Fuego/Psíquico", wrong: ["Fuego/Lucha", "Normal/Psíquico", "Fuego"], explain: "Delphox combina los tipos Fuego y Psíquico." },
  { q: "¿Cuánto daño hace un ataque de tipo Fantasma a un Pokémon de tipo Fuego/Normal?", correct: "x0", wrong: ["x4", "x0,5", "x2"], explain: "Fantasma contra Fuego es x1 y Fantasma contra Normal es x0; en total x0." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Fuego?", correct: "Acero", wrong: ["Fuego", "Lucha", "Siniestro"], explain: "Los ataques de tipo Fuego son súper eficaces contra Bicho, Acero, Planta y Hielo." },
  { q: "¿Cuánto daño hace un ataque de tipo Lucha a un Pokémon de tipo Agua/Acero?", correct: "x2", wrong: ["x4", "x0", "x0,5"], explain: "Lucha contra Agua es x1 y Lucha contra Acero es x2; en total x2." },
  { q: "Un ataque de tipo Psíquico contra Weavile (Siniestro/Hielo), ¿cuánto daño hace?", correct: "x0", wrong: ["x1", "x0,25", "x0,5"], explain: "Psíquico contra Siniestro es x0 y Psíquico contra Hielo es x1; en total x0." },
  { q: "Un ataque de tipo Agua contra Sealeo (Hielo/Agua), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0", "x0,25", "x4"], explain: "Agua contra Hielo es x1 y Agua contra Agua es x0,5; en total x0,5." },
  { q: "Un ataque de tipo Agua contra Probopass (Roca/Acero), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x4", "x0,5"], explain: "Agua contra Roca es x2 y Agua contra Acero es x1; en total x2." },
  { q: "¿Cuánto daño hace un ataque de tipo Psíquico a un Pokémon de tipo Normal/Agua?", correct: "x1", wrong: ["x0,5", "x0,25", "x2"], explain: "Psíquico contra Normal es x1 y Psíquico contra Agua es x1; en total x1." },
  { q: "¿Qué tipo resiste los ataques de tipo Fuego?", correct: "Roca", wrong: ["Lucha", "Psíquico", "Veneno"], explain: "Resisten los ataques de tipo Fuego: Roca, Fuego, Agua y Dragón." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Ataque Rápido (tipo Normal)?", correct: "Banette", wrong: ["Pineco", "Cherrim", "Flaaffy"], explain: "Banette es de tipo Fantasma, inmune a los ataques de tipo Normal." },
  { q: "Un ataque de tipo Roca contra Wingull (Agua/Volador), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,25", "x0,5", "x1"], explain: "Roca contra Agua es x1 y Roca contra Volador es x2; en total x2." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de A Bocajarro (tipo Lucha)?", correct: "Shedinja", wrong: ["Meowth", "Squirtle", "Dragonite"], explain: "Shedinja es de tipo Fantasma, inmune a los ataques de tipo Lucha." },
  { q: "¿Cuánto daño hace un ataque de tipo Siniestro a un Pokémon de tipo Planta/Volador?", correct: "x1", wrong: ["x0", "x0,5", "x0,25"], explain: "Siniestro contra Planta es x1 y Siniestro contra Volador es x1; en total x1." },
  { q: "Un ataque de tipo Bicho contra Qwilfish (Agua/Veneno), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x2", "x1", "x4"], explain: "Bicho contra Agua es x1 y Bicho contra Veneno es x0,5; en total x0,5." },
  { q: "Un ataque de tipo Bicho contra Onix (Roca/Tierra), ¿cuánto daño hace?", correct: "x1", wrong: ["x2", "x4", "x0,25"], explain: "Bicho contra Roca es x1 y Bicho contra Tierra es x1; en total x1." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Siniestro?", correct: "Darkrai", wrong: ["Giratina", "Grumpig", "Registeel"], explain: "Darkrai es de tipo Siniestro." },
  { q: "¿A qué tipo de ataque es débil x4 Kabuto?", correct: "Planta", wrong: ["Tierra", "Acero", "Hada"], explain: "Kabuto es Roca/Agua y recibe x4 de Planta." },
  { q: "¿De qué tipo es Passimian?", correct: "Lucha", wrong: ["Lucha/Siniestro", "Psíquico/Lucha", "Eléctrico"], explain: "Passimian es de tipo Lucha puro." },
  { q: "Un ataque de tipo Siniestro contra Shiinotic (Planta/Hada), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0", "x0,25", "x4"], explain: "Siniestro contra Planta es x1 y Siniestro contra Hada es x0,5; en total x0,5." },
  { q: "Un ataque de tipo Fantasma contra Shedinja (Bicho/Fantasma), ¿cuánto daño hace?", correct: "x2", wrong: ["x0", "x4", "x0,25"], explain: "Fantasma contra Bicho es x1 y Fantasma contra Fantasma es x2; en total x2." },
  { q: "¿Cuál de estos Pokémon es de tipo Planta puro?", correct: "Floragato", wrong: ["Scovillain", "Bewear", "Passimian"], explain: "Floragato es de tipo Planta puro; los demás no." },
  { q: "¿Cuánto daño hace un ataque de tipo Volador a un Pokémon de tipo Tierra/Volador?", correct: "x1", wrong: ["x0,5", "x0,25", "x0"], explain: "Volador contra Tierra es x1 y Volador contra Volador es x1; en total x1." },
  { q: "¿De qué tipo es Kadabra?", correct: "Psíquico", wrong: ["Psíquico/Normal", "Bicho/Psíquico", "Dragón"], explain: "Kadabra es de tipo Psíquico puro." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Lengüetazo (tipo Fantasma)?", correct: "Ambipom", wrong: ["Arcanine", "Hitmonlee", "Alakazam"], explain: "Ambipom es de tipo Normal, inmune a los ataques de tipo Fantasma." },
  { q: "Un ataque de tipo Tierra contra Hawlucha (Lucha/Volador), ¿cuánto daño hace?", correct: "x0", wrong: ["x4", "x1", "x0,25"], explain: "Tierra contra Lucha es x1 y Tierra contra Volador es x0; en total x0." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Acero/Fantasma?", correct: "4", wrong: ["2", "7", "6"], explain: "La combinación Acero/Fantasma es débil a Tierra, Fantasma, Fuego y Siniestro." },
  { q: "¿Cuánto daño hace un ataque de tipo Bicho a un Pokémon de tipo Lucha/Acero?", correct: "x0,25", wrong: ["x2", "x1", "x4"], explain: "Bicho contra Lucha es x0,5 y Bicho contra Acero es x0,5; en total x0,25." },
  { q: "¿De qué tipo es Flaaffy?", correct: "Eléctrico", wrong: ["Eléctrico/Agua", "Psíquico/Eléctrico", "Bicho"], explain: "Flaaffy es de tipo Eléctrico puro." },
  { q: "¿Qué tipo resiste los ataques de tipo Acero?", correct: "Fuego", wrong: ["Hielo", "Siniestro", "Lucha"], explain: "Resisten los ataques de tipo Acero: Acero, Fuego, Agua y Eléctrico." },
  { q: "¿De qué tipo es Haunter?", correct: "Fantasma/Veneno", wrong: ["Fantasma/Planta", "Tierra/Veneno", "Fantasma"], explain: "Haunter combina los tipos Fantasma y Veneno." },
  { q: "Un ataque de tipo Roca contra Surskit (Bicho/Agua), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x4", "x0"], explain: "Roca contra Bicho es x2 y Roca contra Agua es x1; en total x2." },
  { q: "¿De qué tipo es Lickilicky?", correct: "Normal", wrong: ["Normal/Eléctrico", "Agua/Normal", "Hielo"], explain: "Lickilicky es de tipo Normal puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Hada a un Pokémon de tipo Siniestro/Fantasma?", correct: "x2", wrong: ["x0,25", "x1", "x0,5"], explain: "Hada contra Siniestro es x2 y Hada contra Fantasma es x1; en total x2." },
  { q: "¿Qué Pokémon de esta lista es de tipo Normal puro?", correct: "Porygon2", wrong: ["Fearow", "Farfetch’d", "Elekid"], explain: "Porygon2 es de tipo Normal puro; los demás no." },
  { q: "Un ataque de tipo Normal contra Starmie (Agua/Psíquico), ¿cuánto daño hace?", correct: "x1", wrong: ["x0,25", "x2", "x0,5"], explain: "Normal contra Agua es x1 y Normal contra Psíquico es x1; en total x1." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Fantasma puro?", correct: "2", wrong: ["4", "1", "5"], explain: "El tipo Fantasma puro es débil a Fantasma y Siniestro." },
  { q: "¿De qué tipo es Vullaby?", correct: "Siniestro/Volador", wrong: ["Siniestro/Planta", "Hada/Volador", "Siniestro"], explain: "Vullaby combina los tipos Siniestro y Volador." },
  { q: "Un ataque de tipo Hielo contra Ivysaur (Planta/Veneno), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,5", "x1", "x0,25"], explain: "Hielo contra Planta es x2 y Hielo contra Veneno es x1; en total x2." },
  { q: "¿De qué tipo es Snover?", correct: "Planta/Hielo", wrong: ["Planta/Dragón", "Fuego/Hielo", "Planta"], explain: "Snover combina los tipos Planta y Hielo." },
  { q: "Un ataque de tipo Hielo contra Dragonite (Dragón/Volador), ¿cuánto daño hace?", correct: "x4", wrong: ["x0", "x0,25", "x2"], explain: "Hielo contra Dragón es x2 y Hielo contra Volador es x2; en total x4." },
  { q: "¿Cuánto daño hace un ataque de tipo Lucha a un Pokémon de tipo Acero/Roca?", correct: "x4", wrong: ["x1", "x2", "x0,5"], explain: "Lucha contra Acero es x2 y Lucha contra Roca es x2; en total x4." },
  { q: "¿Qué tipo es inmune a los ataques de tipo Normal?", correct: "Fantasma", wrong: ["Hielo", "Tierra", "Siniestro"], explain: "Los ataques de tipo Normal no afectan a Fantasma." },
  { q: "¿De qué tipo es Forretress?", correct: "Bicho/Acero", wrong: ["Bicho/Dragón", "Eléctrico/Acero", "Bicho"], explain: "Forretress combina los tipos Bicho y Acero." },
  { q: "¿A qué tipo de ataque es débil x4 Magneton?", correct: "Tierra", wrong: ["Fuego", "Veneno", "Bicho"], explain: "Magneton es Eléctrico/Acero y recibe x4 de Tierra." },
  { q: "Un ataque de tipo Hielo contra Cloyster (Agua/Hielo), ¿cuánto daño hace?", correct: "x0,25", wrong: ["x1", "x0", "x4"], explain: "Hielo contra Agua es x0,5 y Hielo contra Hielo es x0,5; en total x0,25." },
  { q: "¿A qué tipo de ataque es débil x4 Altaria?", correct: "Hielo", wrong: ["Roca", "Volador", "Lucha"], explain: "Altaria es Dragón/Volador y recibe x4 de Hielo." },
  { q: "Un ataque de tipo Volador contra Hoppip (Planta/Volador), ¿cuánto daño hace?", correct: "x2", wrong: ["x4", "x0", "x1"], explain: "Volador contra Planta es x2 y Volador contra Volador es x1; en total x2." },
  { q: "Cuando Shellder evoluciona a Cloyster, ¿qué tipo gana?", correct: "Hielo", wrong: ["Volador", "Veneno", "Fuego"], explain: "Shellder es Agua y Cloyster pasa a ser Agua/Hielo." },
  { q: "¿A qué tipo de ataque es débil x4 Charizard?", correct: "Roca", wrong: ["Agua", "Normal", "Psíquico"], explain: "Charizard es Fuego/Volador y recibe x4 de Roca." },
  { q: "¿De qué tipo es Togekiss?", correct: "Hada/Volador", wrong: ["Hada/Veneno", "Siniestro/Volador", "Hada"], explain: "Togekiss combina los tipos Hada y Volador." },
  { q: "¿Qué Pokémon de esta lista es de tipo Bicho?", correct: "Whirlipede", wrong: ["Pawmo", "Munna", "Steenee"], explain: "Whirlipede es de tipo Bicho/Veneno." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Excavar (tipo Tierra)?", correct: "Gyarados", wrong: ["Muk", "Misdreavus", "Sudowoodo"], explain: "Gyarados es de tipo Volador, inmune a los ataques de tipo Tierra." },
  { q: "¿De qué tipo es Trapinch?", correct: "Tierra", wrong: ["Tierra/Normal", "Lucha/Tierra", "Acero"], explain: "Trapinch es de tipo Tierra puro." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Hielo?", correct: "Lucha", wrong: ["Psíquico", "Planta", "Veneno"], explain: "El tipo Hielo es débil a Lucha, Roca, Acero y Fuego." },
  { q: "Un ataque de tipo Fantasma contra Swablu (Normal/Volador), ¿cuánto daño hace?", correct: "x0", wrong: ["x1", "x2", "x0,5"], explain: "Fantasma contra Normal es x0 y Fantasma contra Volador es x1; en total x0." },
  { q: "¿A qué tipo de ataque es débil x4 Mantyke?", correct: "Eléctrico", wrong: ["Roca", "Fantasma", "Psíquico"], explain: "Mantyke es Agua/Volador y recibe x4 de Eléctrico." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Planta/Acero?", correct: "2", wrong: ["4", "0", "5"], explain: "La combinación Planta/Acero es débil a Lucha y Fuego." },
  { q: "Un ataque de tipo Planta contra Anorith (Roca/Bicho), ¿cuánto daño hace?", correct: "x1", wrong: ["x2", "x0,5", "x0,25"], explain: "Planta contra Roca es x2 y Planta contra Bicho es x0,5; en total x1." },
  { q: "Un ataque de tipo Bicho contra Hoothoot (Normal/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x4", "x0", "x2"], explain: "Bicho contra Normal es x1 y Bicho contra Volador es x0,5; en total x0,5." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Placaje (tipo Normal)?", correct: "Ceruledge", wrong: ["Sunkern", "Spinda", "Fearow"], explain: "Ceruledge es de tipo Fantasma, inmune a los ataques de tipo Normal." },
  { q: "¿Cuánto daño hace un ataque de tipo Tierra a un Pokémon de tipo Roca/Agua?", correct: "x2", wrong: ["x4", "x0,25", "x0,5"], explain: "Tierra contra Roca es x2 y Tierra contra Agua es x1; en total x2." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Dragón?", correct: "Acero", wrong: ["Volador", "Agua", "Psíquico"], explain: "El tipo Dragón es poco eficaz (x0,5) contra Acero." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Volador puro?", correct: "3", wrong: ["5", "0", "2"], explain: "El tipo Volador puro es débil a Roca, Eléctrico y Hielo." },
  { q: "¿Cuál de estos Pokémon es de tipo Bicho puro?", correct: "Caterpie", wrong: ["Venonat", "Flareon", "Ekans"], explain: "Caterpie es de tipo Bicho puro; los demás no." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Agua puro?", correct: "2", wrong: ["3", "0", "1"], explain: "El tipo Agua puro es débil a Planta y Eléctrico." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Planta/Veneno?", correct: "4", wrong: ["2", "1", "7"], explain: "La combinación Planta/Veneno es débil a Volador, Fuego, Psíquico y Hielo." },
  { q: "¿De qué tipo es Venomoth?", correct: "Bicho/Veneno", wrong: ["Bicho/Dragón", "Siniestro/Veneno", "Bicho"], explain: "Venomoth combina los tipos Bicho y Veneno." },
  { q: "¿De qué tipo es Farfetch’d?", correct: "Normal/Volador", wrong: ["Normal/Acero", "Planta/Volador", "Normal"], explain: "Farfetch’d combina los tipos Normal y Volador." },
  { q: "¿A qué tipo de ataque es débil x4 Abomasnow?", correct: "Fuego", wrong: ["Volador", "Siniestro", "Tierra"], explain: "Abomasnow es Planta/Hielo y recibe x4 de Fuego." },
  { q: "¿De qué tipo es Voltorb?", correct: "Eléctrico", wrong: ["Eléctrico/Veneno", "Tierra/Eléctrico", "Planta"], explain: "Voltorb es de tipo Eléctrico puro." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Veneno?", correct: "Tierra", wrong: ["Acero", "Bicho", "Roca"], explain: "El tipo Veneno es débil a Tierra y Psíquico." },
  { q: "¿Cuál de estos Pokémon es de tipo Normal puro?", correct: "Ursaring", wrong: ["Pidgeot", "Weezing", "Quilava"], explain: "Ursaring es de tipo Normal puro; los demás no." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Chispa (tipo Eléctrico)?", correct: "Quagsire", wrong: ["Registeel", "Honchkrow", "Swablu"], explain: "Quagsire es de tipo Tierra, inmune a los ataques de tipo Eléctrico." },
  { q: "¿De qué tipo es Heatran?", correct: "Fuego/Acero", wrong: ["Fuego/Veneno", "Dragón/Acero", "Fuego"], explain: "Heatran combina los tipos Fuego y Acero." },
  { q: "Un ataque de tipo Hielo contra Shiftry (Planta/Siniestro), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,5", "x0,25", "x0"], explain: "Hielo contra Planta es x2 y Hielo contra Siniestro es x1; en total x2." },
  { q: "¿De qué tipo es Ursaring?", correct: "Normal", wrong: ["Normal/Planta", "Volador/Normal", "Dragón"], explain: "Ursaring es de tipo Normal puro." },
  { q: "¿Qué Pokémon de esta lista es de tipo Eléctrico puro?", correct: "Pikachu", wrong: ["Chinchou", "Moltres", "Celebi"], explain: "Pikachu es de tipo Eléctrico puro; los demás no." },
  { q: "¿Qué tipo resiste los ataques de tipo Veneno?", correct: "Tierra", wrong: ["Psíquico", "Dragón", "Agua"], explain: "Resisten los ataques de tipo Veneno: Veneno, Tierra, Roca y Fantasma." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Onda Certera (tipo Lucha)?", correct: "Dusclops", wrong: ["Psyduck", "Sudowoodo", "Meowth"], explain: "Dusclops es de tipo Fantasma, inmune a los ataques de tipo Lucha." },
  { q: "¿De qué tipo es Sceptile?", correct: "Planta", wrong: ["Planta/Tierra", "Dragón/Planta", "Psíquico"], explain: "Sceptile es de tipo Planta puro." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Bicho?", correct: "Lucha", wrong: ["Agua", "Planta", "Dragón"], explain: "El tipo Bicho es poco eficaz (x0,5) contra Lucha, Volador, Veneno, Fantasma, Acero, Fuego y Hada." },
  { q: "¿Cuánto daño hace un ataque de tipo Agua a un Pokémon de tipo Bicho/Tierra?", correct: "x2", wrong: ["x0", "x0,5", "x1"], explain: "Agua contra Bicho es x1 y Agua contra Tierra es x2; en total x2." },
  { q: "Cuando Slugma evoluciona a Magcargo, ¿qué tipo gana?", correct: "Roca", wrong: ["Acero", "Bicho", "Siniestro"], explain: "Slugma es Fuego y Magcargo pasa a ser Fuego/Roca." },
  { q: "¿A qué tipo de ataque es débil x4 Rhyhorn?", correct: "Planta", wrong: ["Tierra", "Fantasma", "Siniestro"], explain: "Rhyhorn es Tierra/Roca y recibe x4 de Agua y Planta." },
  { q: "Cuando Torchic evoluciona a Combusken, ¿qué tipo gana?", correct: "Lucha", wrong: ["Hada", "Tierra", "Planta"], explain: "Torchic es Fuego y Combusken pasa a ser Fuego/Lucha." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Planta?", correct: "Treecko", wrong: ["Masquerain", "Kecleon", "Garchomp"], explain: "Treecko es de tipo Planta." },
  { q: "Un ataque de tipo Planta contra Cottonee (Planta/Hada), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0", "x2", "x4"], explain: "Planta contra Planta es x0,5 y Planta contra Hada es x1; en total x0,5." },
  { q: "Cuando Dragonair evoluciona a Dragonite, ¿qué tipo gana?", correct: "Volador", wrong: ["Siniestro", "Hada", "Fantasma"], explain: "Dragonair es Dragón y Dragonite pasa a ser Dragón/Volador." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Normal/Lucha?", correct: "4", wrong: ["3", "1", "6"], explain: "La combinación Normal/Lucha es débil a Lucha, Volador, Psíquico y Hada." },
  { q: "¿Qué tipo es inmune a los ataques de tipo Psíquico?", correct: "Siniestro", wrong: ["Dragón", "Fantasma", "Normal"], explain: "Los ataques de tipo Psíquico no afectan a Siniestro." },
  { q: "Un ataque de tipo Tierra contra Lunatone (Roca/Psíquico), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x0,25", "x4"], explain: "Tierra contra Roca es x2 y Tierra contra Psíquico es x1; en total x2." },
  { q: "Un ataque de tipo Volador contra Sawsbuck (Normal/Planta), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,25", "x0", "x0,5"], explain: "Volador contra Normal es x1 y Volador contra Planta es x2; en total x2." },
  { q: "¿De qué tipo es Ralts?", correct: "Psíquico/Hada", wrong: ["Psíquico/Agua", "Tierra/Hada", "Psíquico"], explain: "Ralts combina los tipos Psíquico y Hada." },
  { q: "Un ataque de tipo Psíquico contra Skarmory (Acero/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0,25", "x0", "x4"], explain: "Psíquico contra Acero es x0,5 y Psíquico contra Volador es x1; en total x0,5." },
  { q: "Un ataque de tipo Siniestro contra Girafarig (Normal/Psíquico), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,25", "x0,5", "x4"], explain: "Siniestro contra Normal es x1 y Siniestro contra Psíquico es x2; en total x2." },
  { q: "¿De qué tipo es Aerodactyl?", correct: "Roca/Volador", wrong: ["Roca/Normal", "Lucha/Volador", "Roca"], explain: "Aerodactyl combina los tipos Roca y Volador." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Siniestro?", correct: "Lucha", wrong: ["Fantasma", "Roca", "Fuego"], explain: "El tipo Siniestro es poco eficaz (x0,5) contra Lucha, Siniestro y Hada." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Roca puro?", correct: "5", wrong: ["2", "6", "8"], explain: "El tipo Roca puro es débil a Lucha, Tierra, Acero, Agua y Planta." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Roca?", correct: "Volador", wrong: ["Planta", "Hada", "Acero"], explain: "Los ataques de tipo Roca son súper eficaces contra Volador, Bicho, Fuego y Hielo." },
  { q: "Un ataque de tipo Fuego contra Camerupt (Fuego/Tierra), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x1", "x2", "x4"], explain: "Fuego contra Fuego es x0,5 y Fuego contra Tierra es x1; en total x0,5." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Trueno (tipo Eléctrico)?", correct: "Wooper", wrong: ["Goldeen", "Pineco", "Alakazam"], explain: "Wooper es de tipo Tierra, inmune a los ataques de tipo Eléctrico." },
  { q: "¿De qué tipo es Golduck?", correct: "Agua", wrong: ["Agua/Psíquico", "Lucha/Agua", "Tierra"], explain: "Golduck es de tipo Agua puro." },
  { q: "¿Qué Pokémon de esta lista es de tipo Hielo?", correct: "Delibird", wrong: ["Charmeleon", "Butterfree", "Dugtrio"], explain: "Delibird es de tipo Hielo/Volador." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Fantasma?", correct: "Siniestro", wrong: ["Dragón", "Fuego", "Lucha"], explain: "El tipo Fantasma es débil a Fantasma y Siniestro." },
  { q: "¿De qué tipo es Venonat?", correct: "Bicho/Veneno", wrong: ["Bicho/Psíquico", "Lucha/Veneno", "Bicho"], explain: "Venonat combina los tipos Bicho y Veneno." },
  { q: "¿Cuánto daño hace un ataque de tipo Fantasma a un Pokémon de tipo Psíquico/Volador?", correct: "x2", wrong: ["x0,5", "x1", "x0,25"], explain: "Fantasma contra Psíquico es x2 y Fantasma contra Volador es x1; en total x2." },
  { q: "¿De qué tipo es Combusken?", correct: "Fuego/Lucha", wrong: ["Fuego/Fantasma", "Agua/Lucha", "Fuego"], explain: "Combusken combina los tipos Fuego y Lucha." },
  { q: "Cuando Seel evoluciona a Dewgong, ¿qué tipo gana?", correct: "Hielo", wrong: ["Dragón", "Eléctrico", "Normal"], explain: "Seel es Agua y Dewgong pasa a ser Agua/Hielo." },
  { q: "Un ataque de tipo Lucha contra Exeggutor (Planta/Psíquico), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0", "x4", "x2"], explain: "Lucha contra Planta es x1 y Lucha contra Psíquico es x0,5; en total x0,5." },
  { q: "Cuando Poliwhirl evoluciona a Poliwrath, ¿qué tipo gana?", correct: "Lucha", wrong: ["Planta", "Fuego", "Volador"], explain: "Poliwhirl es Agua y Poliwrath pasa a ser Agua/Lucha." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Lucha puro?", correct: "3", wrong: ["4", "2", "0"], explain: "El tipo Lucha puro es débil a Volador, Psíquico y Hada." },
  { q: "Cuando Nidorino evoluciona a Nidoking, ¿qué tipo gana?", correct: "Tierra", wrong: ["Planta", "Normal", "Lucha"], explain: "Nidorino es Veneno y Nidoking pasa a ser Veneno/Tierra." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Tierra?", correct: "Hielo", wrong: ["Fantasma", "Acero", "Siniestro"], explain: "El tipo Tierra es débil a Agua, Planta y Hielo." },
  { q: "Un ataque de tipo Tierra contra Numel (Fuego/Tierra), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,5", "x0,25", "x0"], explain: "Tierra contra Fuego es x2 y Tierra contra Tierra es x1; en total x2." },
  { q: "¿A qué tipo de ataque es débil x4 Delibird?", correct: "Roca", wrong: ["Fuego", "Dragón", "Hada"], explain: "Delibird es Hielo/Volador y recibe x4 de Roca." },
  { q: "Un ataque de tipo Lucha contra Empoleon (Agua/Acero), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,25", "x0,5", "x0"], explain: "Lucha contra Agua es x1 y Lucha contra Acero es x2; en total x2." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Hielo?", correct: "Tierra", wrong: ["Psíquico", "Hielo", "Siniestro"], explain: "Los ataques de tipo Hielo son súper eficaces contra Volador, Tierra, Planta y Dragón." },
  { q: "¿Qué tipo resiste los ataques de tipo Fantasma?", correct: "Siniestro", wrong: ["Dragón", "Hada", "Hielo"], explain: "Resisten los ataques de tipo Fantasma: Siniestro." },
  { q: "¿De qué tipo es Krabby?", correct: "Agua", wrong: ["Agua/Hielo", "Volador/Agua", "Dragón"], explain: "Krabby es de tipo Agua puro." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Demolición (tipo Lucha)?", correct: "Haunter", wrong: ["Mesprit", "Fearow", "Spearow"], explain: "Haunter es de tipo Fantasma, inmune a los ataques de tipo Lucha." },
  { q: "¿A qué tipo de ataque es débil x4 Celebi?", correct: "Bicho", wrong: ["Volador", "Fantasma", "Lucha"], explain: "Celebi es Psíquico/Planta y recibe x4 de Bicho." },
  { q: "Un ataque de tipo Dragón contra Mime Jr. (Psíquico/Hada), ¿cuánto daño hace?", correct: "x0", wrong: ["x1", "x2", "x0,5"], explain: "Dragón contra Psíquico es x1 y Dragón contra Hada es x0; en total x0." },
  { q: "¿De qué tipo es Diglett?", correct: "Tierra", wrong: ["Tierra/Fuego", "Siniestro/Tierra", "Volador"], explain: "Diglett es de tipo Tierra puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Planta a un Pokémon de tipo Hielo/Volador?", correct: "x0,5", wrong: ["x2", "x4", "x0,25"], explain: "Planta contra Hielo es x1 y Planta contra Volador es x0,5; en total x0,5." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Golpe Kárate (tipo Lucha)?", correct: "Ceruledge", wrong: ["Latias", "Drapion", "Probopass"], explain: "Ceruledge es de tipo Fantasma, inmune a los ataques de tipo Lucha." },
  { q: "Un ataque de tipo Planta contra Altaria (Dragón/Volador), ¿cuánto daño hace?", correct: "x0,25", wrong: ["x1", "x0", "x4"], explain: "Planta contra Dragón es x0,5 y Planta contra Volador es x0,5; en total x0,25." },
  { q: "¿De qué tipo es Uxie?", correct: "Psíquico", wrong: ["Psíquico/Hada", "Acero/Psíquico", "Lucha"], explain: "Uxie es de tipo Psíquico puro." },
  { q: "Un ataque de tipo Hada contra Spinarak (Bicho/Veneno), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0", "x1", "x4"], explain: "Hada contra Bicho es x1 y Hada contra Veneno es x0,5; en total x0,5." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Hada?", correct: "Dedenne", wrong: ["Carkol", "Toxapex", "Durant"], explain: "Dedenne es de tipo Eléctrico/Hada." },
  { q: "Un ataque de tipo Acero contra Poliwrath (Agua/Lucha), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x2", "x0,25", "x4"], explain: "Acero contra Agua es x0,5 y Acero contra Lucha es x1; en total x0,5." },
  { q: "Un ataque de tipo Veneno contra Wo-Chien (Siniestro/Planta), ¿cuánto daño hace?", correct: "x2", wrong: ["x0", "x0,25", "x4"], explain: "Veneno contra Siniestro es x1 y Veneno contra Planta es x2; en total x2." },
  { q: "¿De qué tipo es Electrode?", correct: "Eléctrico", wrong: ["Eléctrico/Hielo", "Planta/Eléctrico", "Psíquico"], explain: "Electrode es de tipo Eléctrico puro." },
  { q: "¿Cuál de estos Pokémon es de tipo Fantasma puro?", correct: "Mismagius", wrong: ["Sableye", "Marshtomp", "Numel"], explain: "Mismagius es de tipo Fantasma puro; los demás no." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Tierra puro?", correct: "3", wrong: ["1", "6", "5"], explain: "El tipo Tierra puro es débil a Agua, Planta y Hielo." },
  { q: "¿A qué tipo de ataque es débil x4 Omastar?", correct: "Planta", wrong: ["Eléctrico", "Roca", "Hielo"], explain: "Omastar es Roca/Agua y recibe x4 de Planta." },
  { q: "¿De qué tipo es Nincada?", correct: "Bicho/Tierra", wrong: ["Bicho/Siniestro", "Agua/Tierra", "Bicho"], explain: "Nincada combina los tipos Bicho y Tierra." },
  { q: "¿De qué tipo es Jumpluff?", correct: "Planta/Volador", wrong: ["Planta/Fantasma", "Siniestro/Volador", "Planta"], explain: "Jumpluff combina los tipos Planta y Volador." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Bicho/Volador?", correct: "x4", wrong: ["x1", "x0", "x0,25"], explain: "Roca contra Bicho es x2 y Roca contra Volador es x2; en total x4." },
  { q: "Un ataque de tipo Roca contra Shuckle (Bicho/Roca), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x0,25", "x4"], explain: "Roca contra Bicho es x2 y Roca contra Roca es x1; en total x2." },
  { q: "Un ataque de tipo Fuego contra Varoom (Acero/Veneno), ¿cuánto daño hace?", correct: "x2", wrong: ["x0", "x4", "x1"], explain: "Fuego contra Acero es x2 y Fuego contra Veneno es x1; en total x2." },
  { q: "¿A qué tipo de ataque es débil x4 Skiploom?", correct: "Hielo", wrong: ["Volador", "Planta", "Bicho"], explain: "Skiploom es Planta/Volador y recibe x4 de Hielo." },
  { q: "¿A qué tipo de ataque es débil x4 Rhyperior?", correct: "Agua", wrong: ["Lucha", "Fantasma", "Roca"], explain: "Rhyperior es Tierra/Roca y recibe x4 de Agua y Planta." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Hielo/Bicho?", correct: "x4", wrong: ["x0,25", "x0", "x2"], explain: "Roca contra Hielo es x2 y Roca contra Bicho es x2; en total x4." },
  { q: "¿De qué tipo es Persian?", correct: "Normal", wrong: ["Normal/Hada", "Hielo/Normal", "Roca"], explain: "Persian es de tipo Normal puro." },
  { q: "¿A qué tipo de ataque es débil x4 Corsola?", correct: "Planta", wrong: ["Tierra", "Lucha", "Bicho"], explain: "Corsola es Agua/Roca y recibe x4 de Planta." },
  { q: "¿Qué tipo resiste los ataques de tipo Eléctrico?", correct: "Dragón", wrong: ["Fuego", "Hielo", "Agua"], explain: "Resisten los ataques de tipo Eléctrico: Planta, Eléctrico y Dragón." },
  { q: "¿De qué tipo es Smeargle?", correct: "Normal", wrong: ["Normal/Hada", "Psíquico/Normal", "Planta"], explain: "Smeargle es de tipo Normal puro." },
  { q: "Un ataque de tipo Normal contra Kabuto (Roca/Agua), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x4", "x0,25", "x0"], explain: "Normal contra Roca es x0,5 y Normal contra Agua es x1; en total x0,5." },
  { q: "¿De qué tipo es Phione?", correct: "Agua", wrong: ["Agua/Dragón", "Fantasma/Agua", "Bicho"], explain: "Phione es de tipo Agua puro." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Siniestro?", correct: "Bicho", wrong: ["Normal", "Siniestro", "Psíquico"], explain: "El tipo Siniestro es débil a Lucha, Bicho y Hada." },
  { q: "¿De qué tipo es Squirtle?", correct: "Agua", wrong: ["Agua/Siniestro", "Dragón/Agua", "Hielo"], explain: "Squirtle es de tipo Agua puro." },
  { q: "¿Qué Pokémon de esta lista es de tipo Veneno puro?", correct: "Koffing", wrong: ["Qwilfish", "Dunsparce", "Clefairy"], explain: "Koffing es de tipo Veneno puro; los demás no." },
  { q: "Cuando Snorunt evoluciona a Froslass, ¿qué tipo gana?", correct: "Fantasma", wrong: ["Veneno", "Roca", "Fuego"], explain: "Snorunt es Hielo y Froslass pasa a ser Hielo/Fantasma." },
  { q: "¿Cuánto daño hace un ataque de tipo Acero a un Pokémon de tipo Fuego/Tierra?", correct: "x0,5", wrong: ["x1", "x0,25", "x2"], explain: "Acero contra Fuego es x0,5 y Acero contra Tierra es x1; en total x0,5." },
  { q: "¿De qué tipo es Magmortar?", correct: "Fuego", wrong: ["Fuego/Hielo", "Psíquico/Fuego", "Volador"], explain: "Magmortar es de tipo Fuego puro." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Dragón?", correct: "Dratini", wrong: ["Tyranitar", "Kangaskhan", "Teddiursa"], explain: "Dratini es de tipo Dragón." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Fuego puro?", correct: "3", wrong: ["6", "4", "1"], explain: "El tipo Fuego puro es débil a Tierra, Roca y Agua." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Fuego/Acero?", correct: "3", wrong: ["5", "2", "1"], explain: "La combinación Fuego/Acero es débil a Lucha, Tierra y Agua." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Garra Umbría (tipo Fantasma)?", correct: "Spinda", wrong: ["Treecko", "Sneasel", "Charizard"], explain: "Spinda es de tipo Normal, inmune a los ataques de tipo Fantasma." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Enfado (tipo Dragón)?", correct: "Snubbull", wrong: ["Spinda", "Sneasel", "Torkoal"], explain: "Snubbull es de tipo Hada, inmune a los ataques de tipo Dragón." },
  { q: "Un ataque de tipo Volador contra Crabominable (Lucha/Hielo), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,5", "x0", "x0,25"], explain: "Volador contra Lucha es x2 y Volador contra Hielo es x1; en total x2." },
  { q: "Un ataque de tipo Roca contra Scyther (Bicho/Volador), ¿cuánto daño hace?", correct: "x4", wrong: ["x0", "x0,25", "x2"], explain: "Roca contra Bicho es x2 y Roca contra Volador es x2; en total x4." },
  { q: "¿De qué tipo es Duskull?", correct: "Fantasma", wrong: ["Fantasma/Roca", "Tierra/Fantasma", "Agua"], explain: "Duskull es de tipo Fantasma puro." },
  { q: "¿De qué tipo es Breloom?", correct: "Planta/Lucha", wrong: ["Planta/Veneno", "Acero/Lucha", "Planta"], explain: "Breloom combina los tipos Planta y Lucha." },
  { q: "¿Qué tipo resiste los ataques de tipo Tierra?", correct: "Bicho", wrong: ["Eléctrico", "Lucha", "Hada"], explain: "Resisten los ataques de tipo Tierra: Bicho y Planta." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Cabezazo Zen (tipo Psíquico)?", correct: "Tyranitar", wrong: ["Grumpig", "Treecko", "Blaziken"], explain: "Tyranitar es de tipo Siniestro, inmune a los ataques de tipo Psíquico." },
  { q: "Un ataque de tipo Bicho contra Escavalier (Bicho/Acero), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0", "x4", "x1"], explain: "Bicho contra Bicho es x1 y Bicho contra Acero es x0,5; en total x0,5." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Bicho/Hada?", correct: "5", wrong: ["2", "6", "8"], explain: "La combinación Bicho/Hada es débil a Volador, Veneno, Roca, Acero y Fuego." },
  { q: "¿De qué tipo es Torracat?", correct: "Fuego", wrong: ["Fuego/Agua", "Acero/Fuego", "Tierra"], explain: "Torracat es de tipo Fuego puro." },
  { q: "¿A qué tipo de ataque es débil x4 Barboach?", correct: "Planta", wrong: ["Hielo", "Bicho", "Roca"], explain: "Barboach es Agua/Tierra y recibe x4 de Planta." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Lucha?", correct: "Volador", wrong: ["Fantasma", "Tierra", "Agua"], explain: "El tipo Lucha es débil a Volador, Psíquico y Hada." },
  { q: "¿Qué Pokémon de esta lista es de tipo Psíquico?", correct: "Metang", wrong: ["Gastrodon", "Skorupi", "Relicanth"], explain: "Metang es de tipo Acero/Psíquico." },
  { q: "¿Qué tipo es inmune a los ataques de tipo Lucha?", correct: "Fantasma", wrong: ["Veneno", "Acero", "Eléctrico"], explain: "Los ataques de tipo Lucha no afectan a Fantasma." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Siniestro?", correct: "Fantasma", wrong: ["Tierra", "Planta", "Fuego"], explain: "Los ataques de tipo Siniestro son súper eficaces contra Fantasma y Psíquico." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Planta/Fuego?", correct: "x2", wrong: ["x0", "x1", "x0,5"], explain: "Roca contra Planta es x1 y Roca contra Fuego es x2; en total x2." },
  { q: "¿Cuánto daño hace un ataque de tipo Psíquico a un Pokémon de tipo Bicho/Lucha?", correct: "x2", wrong: ["x0", "x0,5", "x4"], explain: "Psíquico contra Bicho es x1 y Psíquico contra Lucha es x2; en total x2." },
  { q: "¿De qué tipo es Lopunny?", correct: "Normal", wrong: ["Normal/Tierra", "Volador/Normal", "Veneno"], explain: "Lopunny es de tipo Normal puro." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Volador?", correct: "Roca", wrong: ["Planta", "Normal", "Dragón"], explain: "El tipo Volador es poco eficaz (x0,5) contra Roca, Acero y Eléctrico." },
  { q: "¿Cuánto daño hace un ataque de tipo Dragón a un Pokémon de tipo Siniestro/Dragón?", correct: "x2", wrong: ["x1", "x0,5", "x0,25"], explain: "Dragón contra Siniestro es x1 y Dragón contra Dragón es x2; en total x2." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Residuos (tipo Veneno)?", correct: "Forretress", wrong: ["Ditto", "Slaking", "Ambipom"], explain: "Forretress es de tipo Acero, inmune a los ataques de tipo Veneno." },
  { q: "¿A qué tipo de ataque es débil x4 Toedscruel?", correct: "Hielo", wrong: ["Bicho", "Volador", "Siniestro"], explain: "Toedscruel es Tierra/Planta y recibe x4 de Hielo." },
  { q: "¿A qué tipo de ataque es débil x4 Weavile?", correct: "Lucha", wrong: ["Fuego", "Planta", "Normal"], explain: "Weavile es Siniestro/Hielo y recibe x4 de Lucha." },
  { q: "¿De qué tipo es Bouffalant?", correct: "Normal", wrong: ["Normal/Fantasma", "Bicho/Normal", "Eléctrico"], explain: "Bouffalant es de tipo Normal puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Dragón a un Pokémon de tipo Eléctrico/Volador?", correct: "x1", wrong: ["x0,5", "x2", "x0"], explain: "Dragón contra Eléctrico es x1 y Dragón contra Volador es x1; en total x1." },
  { q: "¿De qué tipo es Yanma?", correct: "Bicho/Volador", wrong: ["Bicho/Agua", "Tierra/Volador", "Bicho"], explain: "Yanma combina los tipos Bicho y Volador." },
  { q: "Un ataque de tipo Acero contra Bombirdier (Volador/Siniestro), ¿cuánto daño hace?", correct: "x1", wrong: ["x4", "x0,25", "x0"], explain: "Acero contra Volador es x1 y Acero contra Siniestro es x1; en total x1." },
  { q: "¿Cuál de estos Pokémon es de tipo Veneno puro?", correct: "Nidoran♀", wrong: ["Venusaur", "Furret", "Sandslash"], explain: "Nidoran♀ es de tipo Veneno puro; los demás no." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Planta?", correct: "Tierra", wrong: ["Planta", "Hada", "Hielo"], explain: "Los ataques de tipo Planta son súper eficaces contra Tierra, Roca y Agua." },
  { q: "¿De qué tipo es Nidoran♂?", correct: "Veneno", wrong: ["Veneno/Bicho", "Eléctrico/Veneno", "Dragón"], explain: "Nidoran♂ es de tipo Veneno puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Dragón a un Pokémon de tipo Planta/Hada?", correct: "x0", wrong: ["x0,25", "x1", "x0,5"], explain: "Dragón contra Planta es x1 y Dragón contra Hada es x0; en total x0." },
  { q: "¿Cuánto daño hace un ataque de tipo Veneno a un Pokémon de tipo Planta/Hielo?", correct: "x2", wrong: ["x4", "x1", "x0"], explain: "Veneno contra Planta es x2 y Veneno contra Hielo es x1; en total x2." },
  { q: "¿Qué tipo es inmune a los ataques de tipo Eléctrico?", correct: "Tierra", wrong: ["Psíquico", "Agua", "Eléctrico"], explain: "Los ataques de tipo Eléctrico no afectan a Tierra." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Bicho/Veneno?", correct: "4", wrong: ["6", "7", "3"], explain: "La combinación Bicho/Veneno es débil a Volador, Roca, Fuego y Psíquico." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Terremoto (tipo Tierra)?", correct: "Dragonite", wrong: ["Nidoran♀", "Bagon", "Duskull"], explain: "Dragonite es de tipo Volador, inmune a los ataques de tipo Tierra." },
  { q: "Un ataque de tipo Tierra contra Dodrio (Normal/Volador), ¿cuánto daño hace?", correct: "x0", wrong: ["x0,25", "x1", "x2"], explain: "Tierra contra Normal es x1 y Tierra contra Volador es x0; en total x0." },
  { q: "Un ataque de tipo Psíquico contra Jirachi (Acero/Psíquico), ¿cuánto daño hace?", correct: "x0,25", wrong: ["x2", "x4", "x1"], explain: "Psíquico contra Acero es x0,5 y Psíquico contra Psíquico es x0,5; en total x0,25." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Eléctrico?", correct: "Volador", wrong: ["Planta", "Fantasma", "Fuego"], explain: "Los ataques de tipo Eléctrico son súper eficaces contra Volador y Agua." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Hielo puro?", correct: "4", wrong: ["1", "2", "3"], explain: "El tipo Hielo puro es débil a Lucha, Roca, Acero y Fuego." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Normal?", correct: "Snorlax", wrong: ["Sandshrew", "Murkrow", "Seaking"], explain: "Snorlax es de tipo Normal." },
  { q: "¿A qué tipo de ataque es débil x4 Rhydon?", correct: "Planta", wrong: ["Hielo", "Eléctrico", "Volador"], explain: "Rhydon es Tierra/Roca y recibe x4 de Agua y Planta." },
  { q: "¿Cuánto daño hace un ataque de tipo Hada a un Pokémon de tipo Fuego/Agua?", correct: "x0,5", wrong: ["x4", "x2", "x0"], explain: "Hada contra Fuego es x0,5 y Hada contra Agua es x1; en total x0,5." },
  { q: "Un ataque de tipo Veneno contra Shieldon (Roca/Acero), ¿cuánto daño hace?", correct: "x0", wrong: ["x0,25", "x4", "x0,5"], explain: "Veneno contra Roca es x0,5 y Veneno contra Acero es x0; en total x0." },
  { q: "¿A qué tipo de ataque es débil x4 Furioseta?", correct: "Bicho", wrong: ["Hada", "Normal", "Planta"], explain: "Furioseta es Planta/Siniestro y recibe x4 de Bicho." },
  { q: "¿De qué tipo es Staryu?", correct: "Agua", wrong: ["Agua/Fuego", "Dragón/Agua", "Siniestro"], explain: "Staryu es de tipo Agua puro." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Bofetón Lodo (tipo Tierra)?", correct: "Yanma", wrong: ["Furret", "Arcanine", "Grumpig"], explain: "Yanma es de tipo Volador, inmune a los ataques de tipo Tierra." },
  { q: "Cuando Metapod evoluciona a Butterfree, ¿qué tipo gana?", correct: "Volador", wrong: ["Planta", "Hada", "Fuego"], explain: "Metapod es Bicho y Butterfree pasa a ser Bicho/Volador." },
  { q: "¿Cuánto daño hace un ataque de tipo Lucha a un Pokémon de tipo Hielo/Fantasma?", correct: "x0", wrong: ["x0,5", "x1", "x2"], explain: "Lucha contra Hielo es x2 y Lucha contra Fantasma es x0; en total x0." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Agua/Volador?", correct: "2", wrong: ["5", "1", "0"], explain: "La combinación Agua/Volador es débil a Roca y Eléctrico." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Acero/Veneno?", correct: "2", wrong: ["3", "1", "5"], explain: "La combinación Acero/Veneno es débil a Tierra y Fuego." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Roca?", correct: "Armaldo", wrong: ["Seviper", "Dusknoir", "Uxie"], explain: "Armaldo es de tipo Roca/Bicho." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Bomba Lodo (tipo Veneno)?", correct: "Probopass", wrong: ["Shroomish", "Fearow", "Psyduck"], explain: "Probopass es de tipo Acero, inmune a los ataques de tipo Veneno." },
  { q: "¿De qué tipo es Moltres?", correct: "Fuego/Volador", wrong: ["Fuego/Agua", "Veneno/Volador", "Fuego"], explain: "Moltres combina los tipos Fuego y Volador." },
  { q: "¿De qué tipo es Gimmighoul?", correct: "Fantasma", wrong: ["Fantasma/Dragón", "Fuego/Fantasma", "Hielo"], explain: "Gimmighoul es de tipo Fantasma puro." },
  { q: "¿De qué tipo es Shinx?", correct: "Eléctrico", wrong: ["Eléctrico/Volador", "Normal/Eléctrico", "Hada"], explain: "Shinx es de tipo Eléctrico puro." },
  { q: "Un ataque de tipo Fuego contra Zapdos (Eléctrico/Volador), ¿cuánto daño hace?", correct: "x1", wrong: ["x2", "x0,25", "x0,5"], explain: "Fuego contra Eléctrico es x1 y Fuego contra Volador es x1; en total x1." },
  { q: "¿Cuánto daño hace un ataque de tipo Psíquico a un Pokémon de tipo Veneno/Volador?", correct: "x2", wrong: ["x0", "x4", "x0,5"], explain: "Psíquico contra Veneno es x2 y Psíquico contra Volador es x1; en total x2." },
  { q: "¿De qué tipo es Raticate?", correct: "Normal", wrong: ["Normal/Planta", "Psíquico/Normal", "Hada"], explain: "Raticate es de tipo Normal puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Fantasma a un Pokémon de tipo Normal/Hada?", correct: "x0", wrong: ["x1", "x0,25", "x4"], explain: "Fantasma contra Normal es x0 y Fantasma contra Hada es x1; en total x0." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Eléctrico/Hielo?", correct: "4", wrong: ["6", "1", "3"], explain: "La combinación Eléctrico/Hielo es débil a Lucha, Tierra, Roca y Fuego." },
  { q: "Cuando Pineco evoluciona a Forretress, ¿qué tipo gana?", correct: "Acero", wrong: ["Fuego", "Psíquico", "Agua"], explain: "Pineco es Bicho y Forretress pasa a ser Bicho/Acero." },
  { q: "¿A qué tipo de ataque es débil x4 Garchomp?", correct: "Hielo", wrong: ["Dragón", "Hada", "Lucha"], explain: "Garchomp es Dragón/Tierra y recibe x4 de Hielo." },
  { q: "¿Cuánto daño hace un ataque de tipo Volador a un Pokémon de tipo Planta/Dragón?", correct: "x2", wrong: ["x0,5", "x4", "x0"], explain: "Volador contra Planta es x2 y Volador contra Dragón es x1; en total x2." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Bicho/Veneno?", correct: "x2", wrong: ["x0", "x0,5", "x1"], explain: "Roca contra Bicho es x2 y Roca contra Veneno es x1; en total x2." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Ácido (tipo Veneno)?", correct: "Beldum", wrong: ["Flaaffy", "Minun", "Dragapult"], explain: "Beldum es de tipo Acero, inmune a los ataques de tipo Veneno." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Veneno?", correct: "Planta", wrong: ["Eléctrico", "Dragón", "Agua"], explain: "Los ataques de tipo Veneno son súper eficaces contra Planta y Hada." },
  { q: "Un ataque de tipo Tierra contra Paras (Bicho/Planta), ¿cuánto daño hace?", correct: "x0,25", wrong: ["x2", "x1", "x0"], explain: "Tierra contra Bicho es x0,5 y Tierra contra Planta es x0,5; en total x0,25." },
  { q: "¿Cuánto daño hace un ataque de tipo Eléctrico a un Pokémon de tipo Agua/Hielo?", correct: "x2", wrong: ["x0,25", "x4", "x1"], explain: "Eléctrico contra Agua es x2 y Eléctrico contra Hielo es x1; en total x2." },
  { q: "¿Cuánto daño hace un ataque de tipo Bicho a un Pokémon de tipo Roca/Planta?", correct: "x2", wrong: ["x4", "x1", "x0,25"], explain: "Bicho contra Roca es x1 y Bicho contra Planta es x2; en total x2." },
  { q: "¿De qué tipo es Jigglypuff?", correct: "Normal/Hada", wrong: ["Normal/Hielo", "Dragón/Hada", "Normal"], explain: "Jigglypuff combina los tipos Normal y Hada." },
  { q: "Cuando Shellos evoluciona a Gastrodon, ¿qué tipo gana?", correct: "Tierra", wrong: ["Veneno", "Fantasma", "Acero"], explain: "Shellos es Agua y Gastrodon pasa a ser Agua/Tierra." },
  { q: "¿A qué tipo de ataque es débil x4 Gible?", correct: "Hielo", wrong: ["Dragón", "Hada", "Veneno"], explain: "Gible es Dragón/Tierra y recibe x4 de Hielo." },
  { q: "¿De qué tipo es Machamp?", correct: "Lucha", wrong: ["Lucha/Normal", "Bicho/Lucha", "Hielo"], explain: "Machamp es de tipo Lucha puro." },
  { q: "¿De qué tipo es Skuntank?", correct: "Veneno/Siniestro", wrong: ["Veneno/Lucha", "Psíquico/Siniestro", "Veneno"], explain: "Skuntank combina los tipos Veneno y Siniestro." },
  { q: "¿Cuánto daño hace un ataque de tipo Hielo a un Pokémon de tipo Psíquico/Fantasma?", correct: "x1", wrong: ["x4", "x0,25", "x0"], explain: "Hielo contra Psíquico es x1 y Hielo contra Fantasma es x1; en total x1." },
  { q: "Cuando Burmy evoluciona a Mothim, ¿qué tipo gana?", correct: "Volador", wrong: ["Agua", "Hada", "Tierra"], explain: "Burmy es Bicho y Mothim pasa a ser Bicho/Volador." },
  { q: "¿A qué tipo de ataque es débil x4 Heracross?", correct: "Volador", wrong: ["Fuego", "Agua", "Acero"], explain: "Heracross es Bicho/Lucha y recibe x4 de Volador." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Eléctrico?", correct: "Tierra", wrong: ["Roca", "Psíquico", "Acero"], explain: "El tipo Eléctrico es débil a Tierra." },
  { q: "¿Qué tipo resiste los ataques de tipo Lucha?", correct: "Hada", wrong: ["Normal", "Agua", "Siniestro"], explain: "Resisten los ataques de tipo Lucha: Volador, Veneno, Bicho, Psíquico y Hada." },
  { q: "Un ataque de tipo Roca contra Beedrill (Bicho/Veneno), ¿cuánto daño hace?", correct: "x2", wrong: ["x4", "x1", "x0,5"], explain: "Roca contra Bicho es x2 y Roca contra Veneno es x1; en total x2." },
  { q: "Un ataque de tipo Acero contra Celebi (Psíquico/Planta), ¿cuánto daño hace?", correct: "x1", wrong: ["x0,5", "x0", "x4"], explain: "Acero contra Psíquico es x1 y Acero contra Planta es x1; en total x1." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Golpe Cuerpo (tipo Normal)?", correct: "Ceruledge", wrong: ["Goldeen", "Swinub", "Surskit"], explain: "Ceruledge es de tipo Fantasma, inmune a los ataques de tipo Normal." },
  { q: "¿Cuánto daño hace un ataque de tipo Fuego a un Pokémon de tipo Agua/Dragón?", correct: "x0,25", wrong: ["x0,5", "x1", "x4"], explain: "Fuego contra Agua es x0,5 y Fuego contra Dragón es x0,5; en total x0,25." },
  { q: "¿De qué tipo es Caterpie?", correct: "Bicho", wrong: ["Bicho/Hada", "Psíquico/Bicho", "Hielo"], explain: "Caterpie es de tipo Bicho puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Eléctrico a un Pokémon de tipo Tierra/Eléctrico?", correct: "x0", wrong: ["x4", "x0,5", "x0,25"], explain: "Eléctrico contra Tierra es x0 y Eléctrico contra Eléctrico es x0,5; en total x0." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Lucha?", correct: "Breloom", wrong: ["Rampardos", "Buizel", "Purugly"], explain: "Breloom es de tipo Planta/Lucha." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Fantasma?", correct: "Gholdengo", wrong: ["Terrakion", "Scatterbug", "Mudsdale"], explain: "Gholdengo es de tipo Acero/Fantasma." },
  { q: "Un ataque de tipo Eléctrico contra Tentacruel (Agua/Veneno), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x0,5", "x0,25"], explain: "Eléctrico contra Agua es x2 y Eléctrico contra Veneno es x1; en total x2." },
  { q: "Un ataque de tipo Hielo contra Dewgong (Agua/Hielo), ¿cuánto daño hace?", correct: "x0,25", wrong: ["x4", "x0,5", "x1"], explain: "Hielo contra Agua es x0,5 y Hielo contra Hielo es x0,5; en total x0,25." },
  { q: "Un ataque de tipo Roca contra Wooper (Agua/Tierra), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0", "x1", "x2"], explain: "Roca contra Agua es x1 y Roca contra Tierra es x0,5; en total x0,5." },
  { q: "Cuando Magikarp evoluciona a Gyarados, ¿qué tipo gana?", correct: "Volador", wrong: ["Hielo", "Bicho", "Psíquico"], explain: "Magikarp es Agua y Gyarados pasa a ser Agua/Volador." },
  { q: "¿Cuánto daño hace un ataque de tipo Acero a un Pokémon de tipo Hada/Lucha?", correct: "x2", wrong: ["x4", "x0,5", "x1"], explain: "Acero contra Hada es x2 y Acero contra Lucha es x1; en total x2." },
  { q: "Un ataque de tipo Normal contra Chandelure (Fantasma/Fuego), ¿cuánto daño hace?", correct: "x0", wrong: ["x0,5", "x4", "x1"], explain: "Normal contra Fantasma es x0 y Normal contra Fuego es x1; en total x0." },
  { q: "Un ataque de tipo Tierra contra Pelipper (Agua/Volador), ¿cuánto daño hace?", correct: "x0", wrong: ["x0,25", "x4", "x1"], explain: "Tierra contra Agua es x1 y Tierra contra Volador es x0; en total x0." },
  { q: "Un ataque de tipo Fantasma contra Gallade (Psíquico/Lucha), ¿cuánto daño hace?", correct: "x2", wrong: ["x4", "x0,5", "x1"], explain: "Fantasma contra Psíquico es x2 y Fantasma contra Lucha es x1; en total x2." },
  { q: "¿De qué tipo es Bastiodon?", correct: "Roca/Acero", wrong: ["Roca/Hielo", "Planta/Acero", "Roca"], explain: "Bastiodon combina los tipos Roca y Acero." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Bicho puro?", correct: "3", wrong: ["1", "0", "6"], explain: "El tipo Bicho puro es débil a Volador, Roca y Fuego." },
  { q: "¿Cuánto daño hace un ataque de tipo Agua a un Pokémon de tipo Bicho/Agua?", correct: "x0,5", wrong: ["x1", "x4", "x0,25"], explain: "Agua contra Bicho es x1 y Agua contra Agua es x0,5; en total x0,5." },
  { q: "¿A qué tipo de ataque es débil x4 Volcarona?", correct: "Roca", wrong: ["Agua", "Volador", "Siniestro"], explain: "Volcarona es Bicho/Fuego y recibe x4 de Roca." },
  { q: "¿Cuál de estos Pokémon es de tipo Lucha puro?", correct: "Hitmontop", wrong: ["Heracross", "Ivysaur", "Ledian"], explain: "Hitmontop es de tipo Lucha puro; los demás no." },
  { q: "¿De qué tipo es Togepi?", correct: "Hada", wrong: ["Hada/Normal", "Veneno/Hada", "Eléctrico"], explain: "Togepi es de tipo Hada puro." },
  { q: "¿A qué tipo de ataque es débil x4 Moltres?", correct: "Roca", wrong: ["Agua", "Veneno", "Acero"], explain: "Moltres es Fuego/Volador y recibe x4 de Roca." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Planta/Lucha?", correct: "6", wrong: ["4", "7", "8"], explain: "La combinación Planta/Lucha es débil a Volador, Veneno, Fuego, Psíquico, Hielo y Hada." },
  { q: "Un ataque de tipo Hada contra Bronzor (Acero/Psíquico), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x4", "x2", "x1"], explain: "Hada contra Acero es x0,5 y Hada contra Psíquico es x1; en total x0,5." },
  { q: "¿Qué tipo resiste los ataques de tipo Roca?", correct: "Acero", wrong: ["Veneno", "Eléctrico", "Dragón"], explain: "Resisten los ataques de tipo Roca: Lucha, Tierra y Acero." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Acero?", correct: "Eléctrico", wrong: ["Veneno", "Siniestro", "Planta"], explain: "El tipo Acero es poco eficaz (x0,5) contra Acero, Fuego, Agua y Eléctrico." },
  { q: "¿Qué Pokémon de esta lista es de tipo Volador?", correct: "Doduo", wrong: ["Scizor", "Slowking", "Venomoth"], explain: "Doduo es de tipo Normal/Volador." },
  { q: "Un ataque de tipo Roca contra Ralts (Psíquico/Hada), ¿cuánto daño hace?", correct: "x1", wrong: ["x0", "x4", "x2"], explain: "Roca contra Psíquico es x1 y Roca contra Hada es x1; en total x1." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Hada?", correct: "Lucha", wrong: ["Volador", "Normal", "Fuego"], explain: "Los ataques de tipo Hada son súper eficaces contra Lucha, Dragón y Siniestro." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Siniestro puro?", correct: "3", wrong: ["0", "5", "4"], explain: "El tipo Siniestro puro es débil a Lucha, Bicho y Hada." },
  { q: "Un ataque de tipo Fantasma contra Metagross (Acero/Psíquico), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x4", "x0"], explain: "Fantasma contra Acero es x1 y Fantasma contra Psíquico es x2; en total x2." },
  { q: "¿De qué tipo es Bellsprout?", correct: "Planta/Veneno", wrong: ["Planta/Agua", "Siniestro/Veneno", "Planta"], explain: "Bellsprout combina los tipos Planta y Veneno." },
  { q: "Un ataque de tipo Acero contra Piloswine (Hielo/Tierra), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,5", "x0,25", "x1"], explain: "Acero contra Hielo es x2 y Acero contra Tierra es x1; en total x2." },
  { q: "¿De qué tipo es Granbull?", correct: "Hada", wrong: ["Hada/Eléctrico", "Lucha/Hada", "Dragón"], explain: "Granbull es de tipo Hada puro." },
  { q: "¿De qué tipo es Kingdra?", correct: "Agua/Dragón", wrong: ["Agua/Bicho", "Acero/Dragón", "Agua"], explain: "Kingdra combina los tipos Agua y Dragón." },
]);
