/* Generado por tools/question-gen/gen_pokedex.py a partir de datos de PokeAPI. No editar a mano: volver a correr el generador. */
window.QUESTION_BANK = window.QUESTION_BANK || {};
window.QUESTION_BANK.pokedex = (window.QUESTION_BANK.pokedex || []).concat([
  { q: "¿Qué número tiene Armaldo en la Pokédex Nacional?", correct: "#348", wrong: ["#350", "#351", "#346"], explain: "Armaldo es el #348 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuál de estos Pokémon es más liviano que Grumpig?", correct: "Wigglytuff", wrong: ["Abomasnow", "Milotic", "Hariyama"], explain: "Grumpig pesa 71,5 kg; Hariyama 253,8 kg, Milotic 162,0 kg, Abomasnow 135,5 kg, Wigglytuff 12,0 kg." },
  { q: "¿Qué Pokémon viene justo después de Cramorant en la Pokédex Nacional?", correct: "Arrokuda", wrong: ["Sandaconda", "Grapploct", "Centiskorch"], explain: "Cramorant es el #845 y Arrokuda el #846." },
  { q: "¿Cuál de estos Pokémon aparece antes que Sigilyph en la Pokédex Nacional?", correct: "Blitzle", wrong: ["Vanilluxe", "Gothorita", "Tirtouga"], explain: "Sigilyph es el #561; Blitzle #522, Tirtouga #564, Gothorita #575, Vanilluxe #584." },
  { q: "¿Qué Pokémon ocupa el número #160 de la Pokédex Nacional?", correct: "Feraligatr", wrong: ["Totodile", "Croconaw", "Typhlosion"], explain: "Feraligatr es el #160; Typhlosion el #157, Totodile el #158, Croconaw el #159." },
  { q: "¿Cuál de estos Pokémon es más bajo que Weezing?", correct: "Primeape", wrong: ["Ferroverdor", "Snorlax", "Dialga"], explain: "Weezing mide 1,2 m; Dialga 5,4 m, Snorlax 2,1 m, Ferroverdor 1,5 m, Primeape 1,0 m." },
  { q: "¿Qué Pokémon ocupa el número #183 de la Pokédex Nacional?", correct: "Marill", wrong: ["Hoppip", "Sudowoodo", "Wooper"], explain: "Marill es el #183; Sudowoodo el #185, Hoppip el #187, Wooper el #194." },
  { q: "¿Cuál de estos Pokémon es más liviano que Metapod?", correct: "Oddish", wrong: ["Sudowoodo", "Sandshrew", "Jolteon"], explain: "Metapod pesa 9,9 kg; Sudowoodo 38,0 kg, Jolteon 24,5 kg, Sandshrew 12,0 kg, Oddish 5,4 kg." },
  { q: "¿En qué región debutó Venomoth?", correct: "Kanto", wrong: ["Hoenn", "Johto", "Alola"], explain: "Venomoth (#049) debutó en la generación 1, la de Kanto." },
  { q: "¿Cuánto pesa Blaziken?", correct: "52,0 kg", wrong: ["36,0 kg", "85,2 kg", "42,4 kg"], explain: "Según la Pokédex, Blaziken pesa 52,0 kg y mide 1,9 m." },
  { q: "¿Qué Pokémon viene justo después de Wobbuffet en la Pokédex Nacional?", correct: "Girafarig", wrong: ["Unown", "Slowking", "Murkrow"], explain: "Wobbuffet es el #202 y Girafarig el #203." },
  { q: "¿Cuál de estos Pokémon es más liviano que Noctowl?", correct: "Prinplup", wrong: ["Garchomp", "Hypno", "Golem"], explain: "Noctowl pesa 40,8 kg; Golem 300,0 kg, Garchomp 95,0 kg, Hypno 75,6 kg, Prinplup 23,0 kg." },
  { q: "¿Cuánto mide Vulpix?", correct: "0,6 m", wrong: ["0,3 m", "1,8 m", "0,2 m"], explain: "Según la Pokédex, Vulpix mide 0,6 m y pesa 9,9 kg." },
  { q: "¿Cuál es la categoría de Delibird en la Pokédex?", correct: "Pokémon Reparto", wrong: ["Pokémon Garra Filo", "Pokémon Narizotas", "Pokémon Milano"], explain: "Delibird es el Pokémon Reparto." },
  { q: "¿Cuál es la categoría de Zeraora en la Pokédex?", correct: "Pokémon Fulgor", wrong: ["Pokémon Brazo Fuerte", "Pokémon Blindaje", "Pokémon Escamas"], explain: "Zeraora es el Pokémon Fulgor." },
  { q: "¿De qué color es Omanyte según la Pokédex?", correct: "Azul", wrong: ["Rosa", "Negro", "Amarillo"], explain: "La Pokédex clasifica a Omanyte como de color azul." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Congelar»?", correct: "Articuno", wrong: ["Jynx", "Haunter", "Victreebel"], explain: "En la Pokédex, Articuno es el Pokémon Congelar." },
  { q: "¿Cuánto pesa Misdreavus?", correct: "1,0 kg", wrong: ["1,4 kg", "0,8 kg", "0,5 kg"], explain: "Según la Pokédex, Misdreavus pesa 1,0 kg y mide 0,7 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Tragaldabas»?", correct: "Guzzlord", wrong: ["Mudsdale", "Togedemaru", "Steenee"], explain: "En la Pokédex, Guzzlord es el Pokémon Tragaldabas." },
  { q: "¿Qué Pokémon viene justo después de Tangela en la Pokédex Nacional?", correct: "Kangaskhan", wrong: ["Chansey", "Rhyhorn", "Weezing"], explain: "Tangela es el #114 y Kangaskhan el #115." },
  { q: "¿De qué color es Wurmple según la Pokédex?", correct: "Rojo", wrong: ["Morado", "Marrón", "Negro"], explain: "La Pokédex clasifica a Wurmple como de color rojo." },
  { q: "¿Cuál de estos Pokémon aparece después que Quaxly en la Pokédex Nacional?", correct: "Pawmot", wrong: ["Eternatus", "Dreepy", "Regieleki"], explain: "Quaxly es el #912; Dreepy #885, Eternatus #890, Regieleki #894, Pawmot #923." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Ninja»?", correct: "Ninjask", wrong: ["Tropius", "Beautifly", "Skitty"], explain: "En la Pokédex, Ninjask es el Pokémon Ninja." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Furtivo»?", correct: "Dragapult", wrong: ["Raboot", "Sirfetch’d", "Clobbopus"], explain: "En la Pokédex, Dragapult es el Pokémon Furtivo." },
  { q: "¿Cuánto mide Wingull?", correct: "0,6 m", wrong: ["1,1 m", "1,8 m", "0,3 m"], explain: "Según la Pokédex, Wingull mide 0,6 m y pesa 9,5 kg." },
  { q: "¿Qué Pokémon ocupa el número #058 de la Pokédex Nacional?", correct: "Growlithe", wrong: ["Paras", "Diglett", "Machoke"], explain: "Growlithe es el #058; Paras el #046, Diglett el #050, Machoke el #067." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Golduck?", correct: "Seel", wrong: ["Surskit", "Arctibax", "Umbreon"], explain: "Golduck y Seel debutaron en Kanto; Surskit de Hoenn, Arctibax de Paldea, Umbreon de Johto." },
  { q: "¿Qué Pokémon ocupa el número #1004 de la Pokédex Nacional?", correct: "Chi-Yu", wrong: ["Chien-Pao", "Wo-Chien", "Ferropaladín"], explain: "Chi-Yu es el #1004; Wo-Chien el #1001, Chien-Pao el #1002, Ferropaladín el #1006." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Lagartija»?", correct: "Charmander", wrong: ["Krabby", "Ponyta", "Dratini"], explain: "En la Pokédex, Charmander es el Pokémon Lagartija." },
  { q: "¿Qué número tiene Espeon en la Pokédex Nacional?", correct: "#196", wrong: ["#188", "#203", "#182"], explain: "Espeon es el #196 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿De qué color es Capsakid según la Pokédex?", correct: "Verde", wrong: ["Negro", "Azul", "Rojo"], explain: "La Pokédex clasifica a Capsakid como de color verde." },
  { q: "¿Cuál es la categoría de Hippopotas en la Pokédex?", correct: "Pokémon Hipo", wrong: ["Pokémon Floración", "Pokémon Enredadera", "Pokémon Festejo"], explain: "Hippopotas es el Pokémon Hipo." },
  { q: "¿Qué Pokémon viene justo después de Rattata en la Pokédex Nacional?", correct: "Raticate", wrong: ["Pidgeot", "Ekans", "Pidgeotto"], explain: "Rattata es el #019 y Raticate el #020." },
  { q: "¿Cuánto pesa Azelf?", correct: "0,3 kg", wrong: ["0,4 kg", "0,9 kg", "0,5 kg"], explain: "Según la Pokédex, Azelf pesa 0,3 kg y mide 0,3 m." },
  { q: "¿Qué Pokémon viene justo después de Leavanny en la Pokédex Nacional?", correct: "Venipede", wrong: ["Swadloon", "Gurdurr", "Seismitoad"], explain: "Leavanny es el #542 y Venipede el #543." },
  { q: "¿Cuál de estos Pokémon es más pesado que Bellossom?", correct: "Typhlosion", wrong: ["Skiploom", "Seedot", "Swablu"], explain: "Bellossom pesa 5,8 kg; Typhlosion 79,5 kg, Seedot 4,0 kg, Swablu 1,2 kg, Skiploom 1,0 kg." },
  { q: "¿Cuál de estos Pokémon es más liviano que Inkay?", correct: "Sinistea", wrong: ["Palkia", "Spiritomb", "Farfetch’d"], explain: "Inkay pesa 3,5 kg; Palkia 336,0 kg, Spiritomb 108,0 kg, Farfetch’d 15,0 kg, Sinistea 0,2 kg." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Gible?", correct: "Budew", wrong: ["Bounsweet", "Swellow", "Sandshrew"], explain: "Gible y Budew debutaron en Sinnoh; Bounsweet de Alola, Swellow de Hoenn, Sandshrew de Kanto." },
  { q: "¿Qué número tiene Slaking en la Pokédex Nacional?", correct: "#289", wrong: ["#280", "#300", "#285"], explain: "Slaking es el #289 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuánto mide Donphan?", correct: "1,1 m", wrong: ["0,7 m", "2,4 m", "0,4 m"], explain: "Según la Pokédex, Donphan mide 1,1 m y pesa 120,0 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Bronce»?", correct: "Bronzor", wrong: ["Shaymin", "Drifloon", "Electivire"], explain: "En la Pokédex, Bronzor es el Pokémon Bronce." },
  { q: "¿Cuál es la categoría de Giratina en la Pokédex?", correct: "Pokémon Renegado", wrong: ["Pokémon Pez Ala", "Pokémon Mimo", "Pokémon Mágico"], explain: "Giratina es el Pokémon Renegado." },
  { q: "¿En qué región debutó Quilladin?", correct: "Kalos", wrong: ["Galar", "Alola", "Paldea"], explain: "Quilladin (#651) debutó en la generación 6, la de Kalos." },
  { q: "¿Cuál de estos Pokémon aparece antes que Phione en la Pokédex Nacional?", correct: "Magmortar", wrong: ["Tranquill", "Emboar", "Serperior"], explain: "Phione es el #489; Magmortar #467, Serperior #497, Emboar #500, Tranquill #520." },
  { q: "¿Cuál de estos Pokémon aparece antes que Kangaskhan en la Pokédex Nacional?", correct: "Marowak", wrong: ["Horsea", "Starmie", "Goldeen"], explain: "Kangaskhan es el #115; Marowak #105, Horsea #116, Goldeen #118, Starmie #121." },
  { q: "¿Cuánto pesa Steelix?", correct: "400,0 kg", wrong: ["300,0 kg", "203,0 kg", "120,0 kg"], explain: "Según la Pokédex, Steelix pesa 400,0 kg y mide 9,2 m." },
  { q: "¿Cuál de estos Pokémon es más pesado que Minun?", correct: "Zeraora", wrong: ["Skiploom", "Rattata", "Haunter"], explain: "Minun pesa 4,2 kg; Zeraora 44,5 kg, Rattata 3,5 kg, Skiploom 1,0 kg, Haunter 0,1 kg." },
  { q: "¿De qué color es Meloetta según la Pokédex?", correct: "Blanco", wrong: ["Negro", "Azul", "Verde"], explain: "La Pokédex clasifica a Meloetta como de color blanco." },
  { q: "¿Cuánto pesa Rayquaza?", correct: "206,5 kg", wrong: ["111,0 kg", "291,0 kg", "135,5 kg"], explain: "Según la Pokédex, Rayquaza pesa 206,5 kg y mide 7,0 m." },
  { q: "¿Cuánto mide Raikou?", correct: "1,9 m", wrong: ["3,8 m", "5,4 m", "0,8 m"], explain: "Según la Pokédex, Raikou mide 1,9 m y pesa 178,0 kg." },
  { q: "¿De qué color es Marill según la Pokédex?", correct: "Azul", wrong: ["Morado", "Rosa", "Marrón"], explain: "La Pokédex clasifica a Marill como de color azul." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Milano»?", correct: "Mantine", wrong: ["Misdreavus", "Piloswine", "Miltank"], explain: "En la Pokédex, Mantine es el Pokémon Milano." },
  { q: "¿Qué Pokémon viene justo antes de Murkrow en la Pokédex Nacional?", correct: "Umbreon", wrong: ["Slowking", "Wooper", "Unown"], explain: "Murkrow es el #198 y Umbreon el #197." },
  { q: "¿Cuánto pesa Salamence?", correct: "102,6 kg", wrong: ["160,0 kg", "87,0 kg", "71,5 kg"], explain: "Según la Pokédex, Salamence pesa 102,6 kg y mide 1,5 m." },
  { q: "¿Qué número tiene Nincada en la Pokédex Nacional?", correct: "#290", wrong: ["#293", "#291", "#288"], explain: "Nincada es el #290 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Dragonite?", correct: "Seaking", wrong: ["Camerupt", "Shuckle", "Dragapult"], explain: "Dragonite y Seaking debutaron en Kanto; Camerupt de Hoenn, Shuckle de Johto, Dragapult de Galar." },
  { q: "¿Cuánto mide Weezing?", correct: "1,2 m", wrong: ["0,7 m", "2,4 m", "3,4 m"], explain: "Según la Pokédex, Weezing mide 1,2 m y pesa 9,5 kg." },
  { q: "¿Cuánto pesa Shieldon?", correct: "57,0 kg", wrong: ["117,0 kg", "25,3 kg", "39,9 kg"], explain: "Según la Pokédex, Shieldon pesa 57,0 kg y mide 0,5 m." },
  { q: "¿Qué Pokémon ocupa el número #721 de la Pokédex Nacional?", correct: "Volcanion", wrong: ["Pumpkaboo", "Trevenant", "Yveltal"], explain: "Volcanion es el #721; Trevenant el #709, Pumpkaboo el #710, Yveltal el #717." },
  { q: "¿Cuál de estos Pokémon aparece después que Sneasel en la Pokédex Nacional?", correct: "Swinub", wrong: ["Heracross", "Shuckle", "Qwilfish"], explain: "Sneasel es el #215; Qwilfish #211, Shuckle #213, Heracross #214, Swinub #220." },
  { q: "¿Cuánto pesa Clawitzer?", correct: "35,3 kg", wrong: ["44,5 kg", "25,0 kg", "19,2 kg"], explain: "Según la Pokédex, Clawitzer pesa 35,3 kg y mide 1,3 m." },
  { q: "¿Qué Pokémon ocupa el número #250 de la Pokédex Nacional?", correct: "Ho-Oh", wrong: ["Mudkip", "Treecko", "Marshtomp"], explain: "Ho-Oh es el #250; Treecko el #252, Mudkip el #258, Marshtomp el #259." },
  { q: "¿Cuál de estos Pokémon es más pesado que Graveler?", correct: "Bastiodon", wrong: ["Weavile", "Azumarill", "Magby"], explain: "Graveler pesa 105,0 kg; Bastiodon 149,5 kg, Weavile 34,0 kg, Azumarill 28,5 kg, Magby 21,4 kg." },
  { q: "¿Cuál de estos Pokémon es más liviano que Psyduck?", correct: "Swinub", wrong: ["Exeggutor", "Honchkrow", "Doduo"], explain: "Psyduck pesa 19,6 kg; Exeggutor 120,0 kg, Doduo 39,2 kg, Honchkrow 27,3 kg, Swinub 6,5 kg." },
  { q: "¿Qué número tiene Squirtle en la Pokédex Nacional?", correct: "#007", wrong: ["#005", "#009", "#010"], explain: "Squirtle es el #007 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Golem?", correct: "Mr. Mime", wrong: ["Dunsparce", "Camerupt", "Prinplup"], explain: "Golem y Mr. Mime debutaron en Kanto; Dunsparce de Johto, Camerupt de Hoenn, Prinplup de Sinnoh." },
  { q: "¿Cuál de estos Pokémon es más pesado que Spewpa?", correct: "Floatzel", wrong: ["Natu", "Caterpie", "Piplup"], explain: "Spewpa pesa 8,4 kg; Floatzel 33,5 kg, Piplup 5,2 kg, Caterpie 2,9 kg, Natu 2,0 kg." },
  { q: "¿Cuál de estos Pokémon aparece antes que Koffing en la Pokédex Nacional?", correct: "Victreebel", wrong: ["Seadra", "Kabuto", "Aerodactyl"], explain: "Koffing es el #109; Victreebel #071, Seadra #117, Kabuto #140, Aerodactyl #142." },
  { q: "¿Qué Pokémon viene justo antes de Lapras en la Pokédex Nacional?", correct: "Gyarados", wrong: ["Ditto", "Tauros", "Vaporeon"], explain: "Lapras es el #131 y Gyarados el #130." },
  { q: "¿De qué color es Raticate según la Pokédex?", correct: "Marrón", wrong: ["Azul", "Negro", "Rosa"], explain: "La Pokédex clasifica a Raticate como de color marrón." },
  { q: "¿Cuál de estos Pokémon aparece antes que Dragonair en la Pokédex Nacional?", correct: "Jolteon", wrong: ["Spinarak", "Azumarill", "Mareep"], explain: "Dragonair es el #148; Jolteon #135, Spinarak #167, Mareep #179, Azumarill #184." },
  { q: "¿Cuánto pesa Absol?", correct: "47,0 kg", wrong: ["27,2 kg", "35,3 kg", "61,9 kg"], explain: "Según la Pokédex, Absol pesa 47,0 kg y mide 1,2 m." },
  { q: "¿Qué Pokémon ocupa el número #052 de la Pokédex Nacional?", correct: "Meowth", wrong: ["Poliwrath", "Arcanine", "Golbat"], explain: "Meowth es el #052; Golbat el #042, Arcanine el #059, Poliwrath el #062." },
  { q: "¿Cuánto mide Clefable?", correct: "1,3 m", wrong: ["3,9 m", "0,7 m", "2,3 m"], explain: "Según la Pokédex, Clefable mide 1,3 m y pesa 40,0 kg." },
  { q: "¿Qué Pokémon viene justo antes de Caterpie en la Pokédex Nacional?", correct: "Blastoise", wrong: ["Metapod", "Pidgeotto", "Bulbasaur"], explain: "Caterpie es el #010 y Blastoise el #009." },
  { q: "¿Qué número tiene Annihilape en la Pokédex Nacional?", correct: "#979", wrong: ["#969", "#993", "#990"], explain: "Annihilape es el #979 de la Pokédex Nacional y debutó en Paldea." },
  { q: "¿Cuál de estos Pokémon es más bajo que Seel?", correct: "Caterpie", wrong: ["Rampardos", "Rhydon", "Lugia"], explain: "Seel mide 1,1 m; Lugia 5,2 m, Rhydon 1,9 m, Rampardos 1,6 m, Caterpie 0,3 m." },
  { q: "¿Cuál de estos Pokémon es más liviano que Shellos?", correct: "Litwick", wrong: ["Hawlucha", "Giratina", "Duskull"], explain: "Shellos pesa 6,3 kg; Giratina 750,0 kg, Hawlucha 21,5 kg, Duskull 15,0 kg, Litwick 3,1 kg." },
  { q: "¿Qué Pokémon ocupa el número #389 de la Pokédex Nacional?", correct: "Torterra", wrong: ["Turtwig", "Monferno", "Deoxys"], explain: "Torterra es el #389; Deoxys el #386, Turtwig el #387, Monferno el #391." },
  { q: "¿Cuál de estos Pokémon aparece después que Corsola en la Pokédex Nacional?", correct: "Smeargle", wrong: ["Hoppip", "Sneasel", "Politoed"], explain: "Corsola es el #222; Politoed #186, Hoppip #187, Sneasel #215, Smeargle #235." },
  { q: "¿Qué Pokémon ocupa el número #340 de la Pokédex Nacional?", correct: "Whiscash", wrong: ["Corphish", "Lunatone", "Barboach"], explain: "Whiscash es el #340; Lunatone el #337, Barboach el #339, Corphish el #341." },
  { q: "¿Cuál es la categoría de Swalot en la Pokédex?", correct: "Pokémon Bolsa Veneno", wrong: ["Pokémon Susurro", "Pokémon Ánimo", "Pokémon Gato Hurón"], explain: "Swalot es el Pokémon Bolsa Veneno." },
  { q: "¿Qué Pokémon ocupa el número #363 de la Pokédex Nacional?", correct: "Spheal", wrong: ["Beldum", "Shelgon", "Luvdisc"], explain: "Spheal es el #363; Luvdisc el #370, Shelgon el #372, Beldum el #374." },
  { q: "¿Cuánto mide Pincurchin?", correct: "0,3 m", wrong: ["0,5 m", "0,8 m", "0,1 m"], explain: "Según la Pokédex, Pincurchin mide 0,3 m y pesa 1,0 kg." },
  { q: "¿Cuál de estos Pokémon aparece después que Shinx en la Pokédex Nacional?", correct: "Mothim", wrong: ["Staravia", "Piplup", "Bibarel"], explain: "Shinx es el #403; Piplup #393, Staravia #397, Bibarel #400, Mothim #414." },
  { q: "¿Qué Pokémon viene justo antes de Shellder en la Pokédex Nacional?", correct: "Muk", wrong: ["Cloyster", "Magneton", "Slowbro"], explain: "Shellder es el #090 y Muk el #089." },
  { q: "¿Qué número tiene Espathra en la Pokédex Nacional?", correct: "#956", wrong: ["#945", "#961", "#969"], explain: "Espathra es el #956 de la Pokédex Nacional y debutó en Paldea." },
  { q: "¿Cuál de estos Pokémon es más bajo que Slugma?", correct: "Spearow", wrong: ["Floatzel", "Seaking", "Giratina"], explain: "Slugma mide 0,7 m; Giratina 4,5 m, Seaking 1,3 m, Floatzel 1,1 m, Spearow 0,3 m." },
  { q: "¿Cuál es la categoría de Bayleef en la Pokédex?", correct: "Pokémon Hoja", wrong: ["Pokémon Caparazón", "Pokémon Reparto", "Pokémon Tenaza"], explain: "Bayleef es el Pokémon Hoja." },
  { q: "¿Cuál de estos Pokémon es más pesado que Beedrill?", correct: "Lairon", wrong: ["Shinx", "Ditto", "Petilil"], explain: "Beedrill pesa 29,5 kg; Lairon 120,0 kg, Shinx 9,5 kg, Petilil 6,6 kg, Ditto 4,0 kg." },
  { q: "¿Qué Pokémon viene justo después de Haunter en la Pokédex Nacional?", correct: "Gengar", wrong: ["Gastly", "Shellder", "Cloyster"], explain: "Haunter es el #093 y Gengar el #094." },
  { q: "¿Cuánto pesa Shiftry?", correct: "59,6 kg", wrong: ["130,5 kg", "18,5 kg", "29,0 kg"], explain: "Según la Pokédex, Shiftry pesa 59,6 kg y mide 1,3 m." },
  { q: "¿Qué número tiene Manaphy en la Pokédex Nacional?", correct: "#490", wrong: ["#487", "#493", "#489"], explain: "Manaphy es el #490 de la Pokédex Nacional y debutó en Sinnoh." },
  { q: "¿En qué región debutó Lunatone?", correct: "Hoenn", wrong: ["Johto", "Paldea", "Kanto"], explain: "Lunatone (#337) debutó en la generación 3, la de Hoenn." },
  { q: "¿Cuál de estos Pokémon es más bajo que Lairon?", correct: "Marill", wrong: ["Alomomola", "Golduck", "Feraligatr"], explain: "Lairon mide 0,9 m; Feraligatr 2,3 m, Golduck 1,7 m, Alomomola 1,2 m, Marill 0,4 m." },
  { q: "¿Qué número tiene Entei en la Pokédex Nacional?", correct: "#244", wrong: ["#240", "#253", "#254"], explain: "Entei es el #244 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Qué Pokémon viene justo antes de Roselia en la Pokédex Nacional?", correct: "Illumise", wrong: ["Gulpin", "Plusle", "Sharpedo"], explain: "Roselia es el #315 y Illumise el #314." },
  { q: "¿Cuánto pesa Gligar?", correct: "64,8 kg", wrong: ["36,0 kg", "149,5 kg", "106,6 kg"], explain: "Según la Pokédex, Gligar pesa 64,8 kg y mide 1,1 m." },
  { q: "¿Qué número tiene Kabuto en la Pokédex Nacional?", correct: "#140", wrong: ["#150", "#137", "#131"], explain: "Kabuto es el #140 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál de estos Pokémon aparece antes que Diglett en la Pokédex Nacional?", correct: "Ekans", wrong: ["Grimer", "Seel", "Weepinbell"], explain: "Diglett es el #050; Ekans #023, Weepinbell #070, Seel #086, Grimer #088." },
  { q: "¿Qué Pokémon ocupa el número #002 de la Pokédex Nacional?", correct: "Ivysaur", wrong: ["Charmander", "Bulbasaur", "Venusaur"], explain: "Ivysaur es el #002; Bulbasaur el #001, Venusaur el #003, Charmander el #004." },
  { q: "¿Cuánto mide Drapion?", correct: "1,3 m", wrong: ["0,7 m", "1,7 m", "3,9 m"], explain: "Según la Pokédex, Drapion mide 1,3 m y pesa 61,5 kg." },
  { q: "¿Cuánto mide Escavalier?", correct: "1,0 m", wrong: ["1,9 m", "0,6 m", "0,3 m"], explain: "Según la Pokédex, Escavalier mide 1,0 m y pesa 33,0 kg." },
  { q: "¿Cuál de estos Pokémon aparece antes que Colmilargo en la Pokédex Nacional?", correct: "Toedscool", wrong: ["Poltchageist", "Bramaluna", "Electrofuria"], explain: "Colmilargo es el #984; Toedscool #948, Bramaluna #1005, Poltchageist #1012, Electrofuria #1021." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Explosión»?", correct: "Magmortar", wrong: ["Chimchar", "Cresselia", "Munchlax"], explain: "En la Pokédex, Magmortar es el Pokémon Explosión." },
  { q: "¿Cuánto pesa Togekiss?", correct: "38,0 kg", wrong: ["47,0 kg", "29,7 kg", "72,0 kg"], explain: "Según la Pokédex, Togekiss pesa 38,0 kg y mide 1,5 m." },
  { q: "¿Qué número tiene Illumise en la Pokédex Nacional?", correct: "#314", wrong: ["#309", "#299", "#327"], explain: "Illumise es el #314 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuál es la categoría de Aromatisse en la Pokédex?", correct: "Pokémon Fragancia", wrong: ["Pokémon Tiraescamas", "Pokémon Jardín", "Pokémon Creación"], explain: "Aromatisse es el Pokémon Fragancia." },
  { q: "¿Cuál de estos Pokémon es más pesado que Inkay?", correct: "Pidgeotto", wrong: ["Spearow", "Igglybuff", "Hoppip"], explain: "Inkay pesa 3,5 kg; Pidgeotto 30,0 kg, Spearow 2,0 kg, Igglybuff 1,0 kg, Hoppip 0,5 kg." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Sharpedo?", correct: "Sealeo", wrong: ["Frosmoth", "Azumarill", "Darkrai"], explain: "Sharpedo y Sealeo debutaron en Hoenn; Frosmoth de Galar, Azumarill de Johto, Darkrai de Sinnoh." },
  { q: "¿Cuál de estos Pokémon es más liviano que Pupitar?", correct: "Skiploom", wrong: ["Dragonite", "Hippowdon", "Steelix"], explain: "Pupitar pesa 152,0 kg; Steelix 400,0 kg, Hippowdon 300,0 kg, Dragonite 210,0 kg, Skiploom 1,0 kg." },
  { q: "¿Cuánto pesa Golduck?", correct: "76,6 kg", wrong: ["40,0 kg", "149,5 kg", "93,0 kg"], explain: "Según la Pokédex, Golduck pesa 76,6 kg y mide 1,7 m." },
  { q: "¿Cuál de estos Pokémon aparece después que Tyranitar en la Pokédex Nacional?", correct: "Treecko", wrong: ["Magby", "Swinub", "Heracross"], explain: "Tyranitar es el #248; Heracross #214, Swinub #220, Magby #240, Treecko #252." },
  { q: "¿Cuánto mide Dewgong?", correct: "1,7 m", wrong: ["3,0 m", "0,6 m", "4,5 m"], explain: "Según la Pokédex, Dewgong mide 1,7 m y pesa 120,0 kg." },
  { q: "¿De qué color es Miltank según la Pokédex?", correct: "Rosa", wrong: ["Morado", "Marrón", "Negro"], explain: "La Pokédex clasifica a Miltank como de color rosa." },
  { q: "¿En qué región debutó Geodude?", correct: "Kanto", wrong: ["Johto", "Hoenn", "Teselia"], explain: "Geodude (#074) debutó en la generación 1, la de Kanto." },
  { q: "¿En qué región debutó Ponyta?", correct: "Kanto", wrong: ["Kalos", "Hoenn", "Teselia"], explain: "Ponyta (#077) debutó en la generación 1, la de Kanto." },
  { q: "¿Qué número tiene Murkrow en la Pokédex Nacional?", correct: "#198", wrong: ["#201", "#200", "#197"], explain: "Murkrow es el #198 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Qué número tiene Weedle en la Pokédex Nacional?", correct: "#013", wrong: ["#011", "#015", "#010"], explain: "Weedle es el #013 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Qué número tiene Tangela en la Pokédex Nacional?", correct: "#114", wrong: ["#099", "#126", "#122"], explain: "Tangela es el #114 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál de estos Pokémon es más liviano que Goldeen?", correct: "Glameow", wrong: ["Riolu", "Machoke", "Dustox"], explain: "Goldeen pesa 15,0 kg; Machoke 70,5 kg, Dustox 31,6 kg, Riolu 20,2 kg, Glameow 3,9 kg." },
  { q: "¿Cuál de estos Pokémon es más bajo que Minun?", correct: "Joltik", wrong: ["Floatzel", "Xatu", "Inteleon"], explain: "Minun mide 0,4 m; Inteleon 1,9 m, Xatu 1,5 m, Floatzel 1,1 m, Joltik 0,1 m." },
  { q: "¿Cuál de estos Pokémon es más bajo que Doduo?", correct: "Bidoof", wrong: ["Moltres", "Solgaleo", "Lugia"], explain: "Doduo mide 1,4 m; Lugia 5,2 m, Solgaleo 3,4 m, Moltres 2,0 m, Bidoof 0,5 m." },
  { q: "¿Qué Pokémon ocupa el número #017 de la Pokédex Nacional?", correct: "Pidgeotto", wrong: ["Pidgey", "Kakuna", "Beedrill"], explain: "Pidgeotto es el #017; Kakuna el #014, Beedrill el #015, Pidgey el #016." },
  { q: "¿Cuánto mide Omastar?", correct: "1,0 m", wrong: ["2,7 m", "1,9 m", "0,6 m"], explain: "Según la Pokédex, Omastar mide 1,0 m y pesa 35,0 kg." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Spearow?", correct: "Kabuto", wrong: ["Bergmite", "Shuppet", "Nymble"], explain: "Spearow y Kabuto debutaron en Kanto; Bergmite de Kalos, Shuppet de Hoenn, Nymble de Paldea." },
  { q: "¿Cuál de estos Pokémon aparece después que Gastly en la Pokédex Nacional?", correct: "Mr. Mime", wrong: ["Bellsprout", "Farfetch’d", "Slowpoke"], explain: "Gastly es el #092; Bellsprout #069, Slowpoke #079, Farfetch’d #083, Mr. Mime #122." },
  { q: "¿Qué número tiene Guzzlord en la Pokédex Nacional?", correct: "#799", wrong: ["#810", "#803", "#789"], explain: "Guzzlord es el #799 de la Pokédex Nacional y debutó en Alola." },
  { q: "¿Cuánto pesa Seedot?", correct: "4,0 kg", wrong: ["8,3 kg", "5,6 kg", "2,8 kg"], explain: "Según la Pokédex, Seedot pesa 4,0 kg y mide 0,5 m." },
  { q: "¿Qué Pokémon ocupa el número #384 de la Pokédex Nacional?", correct: "Rayquaza", wrong: ["Kyogre", "Groudon", "Turtwig"], explain: "Rayquaza es el #384; Kyogre el #382, Groudon el #383, Turtwig el #387." },
  { q: "¿De qué color es Rattata según la Pokédex?", correct: "Morado", wrong: ["Azul", "Verde", "Marrón"], explain: "La Pokédex clasifica a Rattata como de color morado." },
  { q: "¿Cuál de estos Pokémon es más bajo que Plusle?", correct: "Burmy", wrong: ["Gligar", "Krookodile", "Crobat"], explain: "Plusle mide 0,4 m; Crobat 1,8 m, Krookodile 1,5 m, Gligar 1,1 m, Burmy 0,2 m." },
  { q: "¿Cuál es la categoría de Budew en la Pokédex?", correct: "Pokémon Brote", wrong: ["Pokémon Milano", "Pokémon Comilón", "Pokémon Cereza"], explain: "Budew es el Pokémon Brote." },
  { q: "¿Qué número tiene Chimchar en la Pokédex Nacional?", correct: "#390", wrong: ["#379", "#402", "#383"], explain: "Chimchar es el #390 de la Pokédex Nacional y debutó en Sinnoh." },
  { q: "¿Qué Pokémon ocupa el número #512 de la Pokédex Nacional?", correct: "Simisage", wrong: ["Musharna", "Stoutland", "Herdier"], explain: "Simisage es el #512; Herdier el #507, Stoutland el #508, Musharna el #518." },
  { q: "¿Qué Pokémon viene justo antes de Treecko en la Pokédex Nacional?", correct: "Celebi", wrong: ["Grovyle", "Larvitar", "Raikou"], explain: "Treecko es el #252 y Celebi el #251." },
  { q: "¿Cuánto mide Drifblim?", correct: "1,2 m", wrong: ["1,8 m", "2,7 m", "0,8 m"], explain: "Según la Pokédex, Drifblim mide 1,2 m y pesa 15,0 kg." },
  { q: "¿Cuál de estos Pokémon es más alto que Shedinja?", correct: "Aggron", wrong: ["Poochyena", "Azurill", "Pineco"], explain: "Shedinja mide 0,8 m; Aggron 2,1 m, Pineco 0,6 m, Poochyena 0,5 m, Azurill 0,2 m." },
  { q: "¿Cuánto mide Marowak?", correct: "1,0 m", wrong: ["2,2 m", "0,6 m", "1,4 m"], explain: "Según la Pokédex, Marowak mide 1,0 m y pesa 45,0 kg." },
  { q: "¿Cuál es la categoría de Weezing en la Pokédex?", correct: "Pokémon Gas Venenoso", wrong: ["Pokémon Pato Salvaje", "Pokémon Cobra", "Pokémon Gusano"], explain: "Weezing es el Pokémon Gas Venenoso." },
  { q: "¿Cuál de estos Pokémon aparece después que Toxicroak en la Pokédex Nacional?", correct: "Mantyke", wrong: ["Croagunk", "Hippowdon", "Munchlax"], explain: "Toxicroak es el #454; Munchlax #446, Hippowdon #450, Croagunk #453, Mantyke #458." },
  { q: "¿En qué región debutó Mawile?", correct: "Hoenn", wrong: ["Galar", "Teselia", "Paldea"], explain: "Mawile (#303) debutó en la generación 3, la de Hoenn." },
  { q: "¿En qué región debutó Barbaracle?", correct: "Kalos", wrong: ["Johto", "Galar", "Teselia"], explain: "Barbaracle (#689) debutó en la generación 6, la de Kalos." },
  { q: "¿Cuál de estos Pokémon es más alto que Slugma?", correct: "Clefable", wrong: ["Clamperl", "Diglett", "Lotad"], explain: "Slugma mide 0,7 m; Clefable 1,3 m, Lotad 0,5 m, Clamperl 0,4 m, Diglett 0,2 m." },
  { q: "¿Qué número tiene Nidorino en la Pokédex Nacional?", correct: "#033", wrong: ["#031", "#032", "#035"], explain: "Nidorino es el #033 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuánto pesa Munchlax?", correct: "105,0 kg", wrong: ["71,0 kg", "49,8 kg", "220,0 kg"], explain: "Según la Pokédex, Munchlax pesa 105,0 kg y mide 0,6 m." },
  { q: "¿Qué Pokémon ocupa el número #290 de la Pokédex Nacional?", correct: "Nincada", wrong: ["Shroomish", "Exploud", "Slakoth"], explain: "Nincada es el #290; Shroomish el #285, Slakoth el #287, Exploud el #295." },
  { q: "¿Cuál es la categoría de Sunflora en la Pokédex?", correct: "Pokémon Sol", wrong: ["Pokémon 5 Estrellas", "Pokémon Regio", "Pokémon Lana"], explain: "Sunflora es el Pokémon Sol." },
  { q: "¿Cuánto pesa Buizel?", correct: "29,5 kg", wrong: ["19,6 kg", "11,0 kg", "60,2 kg"], explain: "Según la Pokédex, Buizel pesa 29,5 kg y mide 0,7 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Magnético»?", correct: "Magnezone", wrong: ["Prinplup", "Gallade", "Bronzong"], explain: "En la Pokédex, Magnezone es el Pokémon Magnético." },
  { q: "¿En qué región debutó Pikachu?", correct: "Kanto", wrong: ["Paldea", "Alola", "Kalos"], explain: "Pikachu (#025) debutó en la generación 1, la de Kanto." },
  { q: "¿Cuál de estos Pokémon aparece antes que Claydol en la Pokédex Nacional?", correct: "Lairon", wrong: ["Clamperl", "Latios", "Regice"], explain: "Claydol es el #344; Lairon #305, Clamperl #366, Regice #378, Latios #381." },
  { q: "¿Qué Pokémon ocupa el número #330 de la Pokédex Nacional?", correct: "Flygon", wrong: ["Vibrava", "Swablu", "Cacnea"], explain: "Flygon es el #330; Vibrava el #329, Cacnea el #331, Swablu el #333." },
  { q: "¿Cuál de estos Pokémon es más bajo que Dusknoir?", correct: "Sandshrew", wrong: ["Kyurem", "Milotic", "Ho-Oh"], explain: "Dusknoir mide 2,2 m; Milotic 6,2 m, Ho-Oh 3,8 m, Kyurem 3,0 m, Sandshrew 0,6 m." },
  { q: "¿Qué Pokémon ocupa el número #442 de la Pokédex Nacional?", correct: "Spiritomb", wrong: ["Skorupi", "Riolu", "Hippopotas"], explain: "Spiritomb es el #442; Riolu el #447, Hippopotas el #449, Skorupi el #451." },
  { q: "¿En qué región debutó Castform?", correct: "Hoenn", wrong: ["Johto", "Galar", "Teselia"], explain: "Castform (#351) debutó en la generación 3, la de Hoenn." },
  { q: "¿Qué Pokémon viene justo después de Arbok en la Pokédex Nacional?", correct: "Pikachu", wrong: ["Ekans", "Spearow", "Fearow"], explain: "Arbok es el #024 y Pikachu el #025." },
  { q: "¿Qué Pokémon viene justo antes de Lucario en la Pokédex Nacional?", correct: "Riolu", wrong: ["Hippopotas", "Garchomp", "Gabite"], explain: "Lucario es el #448 y Riolu el #447." },
  { q: "¿Cuál de estos Pokémon es más liviano que Carracosta?", correct: "Goldeen", wrong: ["Oinkologne", "Registeel", "Dialga"], explain: "Carracosta pesa 81,0 kg; Dialga 683,0 kg, Registeel 205,0 kg, Oinkologne 120,0 kg, Goldeen 15,0 kg." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Regice?", correct: "Wailord", wrong: ["Buizel", "Poliwag", "Raikou"], explain: "Regice y Wailord debutaron en Hoenn; Buizel de Sinnoh, Poliwag de Kanto, Raikou de Johto." },
  { q: "¿Cuál de estos Pokémon es más alto que Zapdos?", correct: "Eternatus", wrong: ["Baltoy", "Bagon", "Porygon"], explain: "Zapdos mide 1,6 m; Eternatus 20,0 m, Porygon 0,8 m, Bagon 0,6 m, Baltoy 0,5 m." },
  { q: "¿Cuál es la categoría de Luxio en la Pokédex?", correct: "Pokémon Chispa", wrong: ["Pokémon Mach", "Pokémon Grilletes", "Pokémon Ramillete"], explain: "Luxio es el Pokémon Chispa." },
  { q: "¿Cuál de estos Pokémon es más pesado que Oshawott?", correct: "Aipom", wrong: ["Wiglett", "Manaphy", "Gossifleur"], explain: "Oshawott pesa 5,9 kg; Aipom 11,5 kg, Gossifleur 2,2 kg, Wiglett 1,8 kg, Manaphy 1,4 kg." },
  { q: "¿Cuánto pesa Zapdos?", correct: "52,6 kg", wrong: ["75,6 kg", "122,0 kg", "23,3 kg"], explain: "Según la Pokédex, Zapdos pesa 52,6 kg y mide 1,6 m." },
  { q: "¿En qué región debutó Octillery?", correct: "Johto", wrong: ["Hoenn", "Kanto", "Sinnoh"], explain: "Octillery (#224) debutó en la generación 2, la de Johto." },
  { q: "¿Cuánto mide Cresselia?", correct: "1,5 m", wrong: ["2,4 m", "1,9 m", "0,8 m"], explain: "Según la Pokédex, Cresselia mide 1,5 m y pesa 85,6 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Ascuas»?", correct: "Magby", wrong: ["Murkrow", "Qwilfish", "Scizor"], explain: "En la Pokédex, Magby es el Pokémon Ascuas." },
  { q: "¿Cuánto pesa Magcargo?", correct: "55,0 kg", wrong: ["76,0 kg", "97,0 kg", "40,6 kg"], explain: "Según la Pokédex, Magcargo pesa 55,0 kg y mide 0,8 m." },
  { q: "¿Cuánto mide Bombirdier?", correct: "1,5 m", wrong: ["2,1 m", "0,8 m", "0,4 m"], explain: "Según la Pokédex, Bombirdier mide 1,5 m y pesa 42,9 kg." },
  { q: "¿Cuánto pesa Cloyster?", correct: "132,5 kg", wrong: ["90,5 kg", "202,0 kg", "66,2 kg"], explain: "Según la Pokédex, Cloyster pesa 132,5 kg y mide 1,5 m." },
  { q: "¿Cuánto mide Clamperl?", correct: "0,4 m", wrong: ["0,7 m", "0,2 m", "0,3 m"], explain: "Según la Pokédex, Clamperl mide 0,4 m y pesa 52,5 kg." },
  { q: "¿En qué región debutó Politoed?", correct: "Johto", wrong: ["Kanto", "Sinnoh", "Hoenn"], explain: "Politoed (#186) debutó en la generación 2, la de Johto." },
  { q: "¿Qué Pokémon ocupa el número #639 de la Pokédex Nacional?", correct: "Terrakion", wrong: ["Quilladin", "Heatmor", "Rufflet"], explain: "Terrakion es el #639; Rufflet el #627, Heatmor el #631, Quilladin el #651." },
  { q: "¿Cuánto pesa Sunkern?", correct: "1,8 kg", wrong: ["3,3 kg", "2,2 kg", "1,3 kg"], explain: "Según la Pokédex, Sunkern pesa 1,8 kg y mide 0,3 m." },
  { q: "¿Cuál de estos Pokémon es más pesado que Lunatone?", correct: "Coalossal", wrong: ["Zubat", "Combusken", "Slowbro"], explain: "Lunatone pesa 168,0 kg; Coalossal 310,5 kg, Slowbro 78,5 kg, Combusken 19,5 kg, Zubat 7,5 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Peleón»?", correct: "Tyrogue", wrong: ["Magby", "Furret", "Aipom"], explain: "En la Pokédex, Tyrogue es el Pokémon Peleón." },
  { q: "¿Qué número tiene Sandshrew en la Pokédex Nacional?", correct: "#027", wrong: ["#032", "#015", "#012"], explain: "Sandshrew es el #027 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿En qué región debutó Houndoom?", correct: "Johto", wrong: ["Kalos", "Alola", "Galar"], explain: "Houndoom (#229) debutó en la generación 2, la de Johto." },
  { q: "¿Qué número tiene Surskit en la Pokédex Nacional?", correct: "#283", wrong: ["#292", "#272", "#274"], explain: "Surskit es el #283 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuál es la categoría de Regigigas en la Pokédex?", correct: "Pokémon Colosal", wrong: ["Pokémon Escorpiogro", "Pokémon Escorpión", "Pokémon Espacial"], explain: "Regigigas es el Pokémon Colosal." },
  { q: "¿Cuál es la categoría de Kakuna en la Pokédex?", correct: "Pokémon Capullo", wrong: ["Pokémon Estrella", "Pokémon Barrera", "Pokémon Escupefuego"], explain: "Kakuna es el Pokémon Capullo." },
  { q: "¿Cuál es la categoría de Solrock en la Pokédex?", correct: "Pokémon Meteorito", wrong: ["Pokémon Espina", "Pokémon Resistencia", "Pokémon Cita"], explain: "Solrock es el Pokémon Meteorito." },
  { q: "¿Cuál de estos Pokémon es más bajo que Seaking?", correct: "Rolycoly", wrong: ["Steelix", "Eelektross", "Rayquaza"], explain: "Seaking mide 1,3 m; Steelix 9,2 m, Rayquaza 7,0 m, Eelektross 2,1 m, Rolycoly 0,3 m." },
  { q: "¿Qué número tiene Vulpix en la Pokédex Nacional?", correct: "#037", wrong: ["#040", "#036", "#038"], explain: "Vulpix es el #037 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál de estos Pokémon es más liviano que Scovillain?", correct: "Kakuna", wrong: ["Politoed", "Reuniclus", "Tropius"], explain: "Scovillain pesa 15,0 kg; Tropius 100,0 kg, Politoed 33,9 kg, Reuniclus 20,1 kg, Kakuna 10,0 kg." },
  { q: "¿Cuánto mide Rattata?", correct: "0,3 m", wrong: ["0,9 m", "0,1 m", "0,2 m"], explain: "Según la Pokédex, Rattata mide 0,3 m y pesa 3,5 kg." },
  { q: "¿En qué región debutó Surskit?", correct: "Hoenn", wrong: ["Teselia", "Johto", "Kanto"], explain: "Surskit (#283) debutó en la generación 3, la de Hoenn." },
  { q: "¿Cuál de estos Pokémon es más alto que Kricketune?", correct: "Latios", wrong: ["Celebi", "Krabby", "Glameow"], explain: "Kricketune mide 1,0 m; Latios 2,0 m, Celebi 0,6 m, Glameow 0,5 m, Krabby 0,4 m." },
  { q: "¿Cuánto mide Politoed?", correct: "1,1 m", wrong: ["1,5 m", "2,0 m", "2,8 m"], explain: "Según la Pokédex, Politoed mide 1,1 m y pesa 33,9 kg." },
  { q: "¿En qué región debutó Toxicroak?", correct: "Sinnoh", wrong: ["Hoenn", "Teselia", "Paldea"], explain: "Toxicroak (#454) debutó en la generación 4, la de Sinnoh." },
  { q: "¿Cuánto pesa Uxie?", correct: "0,3 kg", wrong: ["0,7 kg", "0,5 kg", "0,2 kg"], explain: "Según la Pokédex, Uxie pesa 0,3 kg y mide 0,3 m." },
  { q: "¿Qué Pokémon ocupa el número #310 de la Pokédex Nacional?", correct: "Manectric", wrong: ["Meditite", "Electrike", "Medicham"], explain: "Manectric es el #310; Meditite el #307, Medicham el #308, Electrike el #309." },
  { q: "¿En qué región debutó Kricketune?", correct: "Sinnoh", wrong: ["Johto", "Paldea", "Kalos"], explain: "Kricketune (#402) debutó en la generación 4, la de Sinnoh." },
  { q: "¿Cuál es la categoría de Exeggutor en la Pokédex?", correct: "Pokémon Coco", wrong: ["Pokémon Psi", "Pokémon Ratón", "Pokémon Misterioso"], explain: "Exeggutor es el Pokémon Coco." },
  { q: "¿Cuál de estos Pokémon aparece después que Pachirisu en la Pokédex Nacional?", correct: "Drifloon", wrong: ["Roserade", "Groudon", "Vespiquen"], explain: "Pachirisu es el #417; Groudon #383, Roserade #407, Vespiquen #416, Drifloon #425." },
  { q: "¿Qué Pokémon viene justo después de Altaria en la Pokédex Nacional?", correct: "Zangoose", wrong: ["Swablu", "Flygon", "Lunatone"], explain: "Altaria es el #334 y Zangoose el #335." },
  { q: "¿Qué Pokémon viene justo después de Illumise en la Pokédex Nacional?", correct: "Roselia", wrong: ["Volbeat", "Electrike", "Manectric"], explain: "Illumise es el #314 y Roselia el #315." },
  { q: "¿Cuál es la categoría de Grotle en la Pokédex?", correct: "Pokémon Arboleda", wrong: ["Pokémon Chispa", "Pokémon Emperador", "Pokémon Doscolmillos"], explain: "Grotle es el Pokémon Arboleda." },
  { q: "¿Cuánto pesa Stantler?", correct: "71,2 kg", wrong: ["31,6 kg", "21,6 kg", "130,0 kg"], explain: "Según la Pokédex, Stantler pesa 71,2 kg y mide 1,4 m." },
  { q: "¿De qué color es Regice según la Pokédex?", correct: "Azul", wrong: ["Blanco", "Negro", "Marrón"], explain: "La Pokédex clasifica a Regice como de color azul." },
  { q: "¿En qué región debutó Marowak?", correct: "Kanto", wrong: ["Hoenn", "Johto", "Paldea"], explain: "Marowak (#105) debutó en la generación 1, la de Kanto." },
  { q: "¿Qué Pokémon ocupa el número #349 de la Pokédex Nacional?", correct: "Feebas", wrong: ["Kecleon", "Milotic", "Anorith"], explain: "Feebas es el #349; Anorith el #347, Milotic el #350, Kecleon el #352." },
  { q: "¿Cuál es la categoría de Barboach en la Pokédex?", correct: "Pokémon Bigotudo", wrong: ["Pokémon Atrayente", "Pokémon Muda", "Pokémon Panda Topos"], explain: "Barboach es el Pokémon Bigotudo." },
  { q: "¿Qué Pokémon ocupa el número #221 de la Pokédex Nacional?", correct: "Piloswine", wrong: ["Houndoom", "Octillery", "Remoraid"], explain: "Piloswine es el #221; Remoraid el #223, Octillery el #224, Houndoom el #229." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Magmortar?", correct: "Rhyperior", wrong: ["Starmie", "Lileep", "Araquanid"], explain: "Magmortar y Rhyperior debutaron en Sinnoh; Starmie de Kanto, Lileep de Hoenn, Araquanid de Alola." },
  { q: "¿En qué región debutó Bulbasaur?", correct: "Kanto", wrong: ["Johto", "Hoenn", "Galar"], explain: "Bulbasaur (#001) debutó en la generación 1, la de Kanto." },
  { q: "¿Cuánto mide Dragonite?", correct: "2,2 m", wrong: ["2,6 m", "4,0 m", "1,5 m"], explain: "Según la Pokédex, Dragonite mide 2,2 m y pesa 210,0 kg." },
  { q: "¿Cuál es la categoría de Primeape en la Pokédex?", correct: "Pokémon Mono Cerdo", wrong: ["Pokémon Enredadera", "Pokémon Perrito", "Pokémon Forma Humana"], explain: "Primeape es el Pokémon Mono Cerdo." },
  { q: "¿Cuál de estos Pokémon es más alto que Gastly?", correct: "Onix", wrong: ["Sunflora", "Roselia", "Snubbull"], explain: "Gastly mide 1,3 m; Onix 8,8 m, Sunflora 0,8 m, Snubbull 0,6 m, Roselia 0,3 m." },
  { q: "¿Cuál es la categoría de Dugtrio en la Pokédex?", correct: "Pokémon Topo", wrong: ["Pokémon Estrella", "Pokémon Congelar", "Pokémon Clavos"], explain: "Dugtrio es el Pokémon Topo." },
  { q: "¿Cuál de estos Pokémon es más alto que Voltorb?", correct: "Haunter", wrong: ["Sinistea", "Litten", "Weedle"], explain: "Voltorb mide 0,5 m; Haunter 1,6 m, Litten 0,4 m, Weedle 0,3 m, Sinistea 0,1 m." },
  { q: "¿Cuánto mide Chikorita?", correct: "0,9 m", wrong: ["2,7 m", "1,2 m", "0,3 m"], explain: "Según la Pokédex, Chikorita mide 0,9 m y pesa 6,4 kg." },
  { q: "¿Cuánto pesa Entei?", correct: "198,0 kg", wrong: ["86,4 kg", "305,0 kg", "145,0 kg"], explain: "Según la Pokédex, Entei pesa 198,0 kg y mide 2,1 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Buche»?", correct: "Swellow", wrong: ["Wurmple", "Bagon", "Barboach"], explain: "En la Pokédex, Swellow es el Pokémon Buche." },
  { q: "¿En qué región debutó Magmar?", correct: "Kanto", wrong: ["Alola", "Kalos", "Paldea"], explain: "Magmar (#126) debutó en la generación 1, la de Kanto." },
  { q: "¿Cuál de estos Pokémon aparece después que Trapinch en la Pokédex Nacional?", correct: "Corphish", wrong: ["Gulpin", "Makuhita", "Minun"], explain: "Trapinch es el #328; Makuhita #296, Minun #312, Gulpin #316, Corphish #341." },
  { q: "¿Cuál de estos Pokémon es más bajo que Mightyena?", correct: "Squirtle", wrong: ["Regirock", "Wailord", "Entei"], explain: "Mightyena mide 1,0 m; Wailord 14,5 m, Entei 2,1 m, Regirock 1,7 m, Squirtle 0,5 m." },
  { q: "¿Cuánto pesa Charjabug?", correct: "10,5 kg", wrong: ["14,3 kg", "5,0 kg", "31,0 kg"], explain: "Según la Pokédex, Charjabug pesa 10,5 kg y mide 0,5 m." },
  { q: "¿Cuánto mide Hitmonchan?", correct: "1,4 m", wrong: ["3,9 m", "1,9 m", "2,8 m"], explain: "Según la Pokédex, Hitmonchan mide 1,4 m y pesa 50,2 kg." },
  { q: "¿En qué región debutó Shaymin?", correct: "Sinnoh", wrong: ["Alola", "Galar", "Paldea"], explain: "Shaymin (#492) debutó en la generación 4, la de Sinnoh." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Lana»?", correct: "Mareep", wrong: ["Larvitar", "Sunflora", "Celebi"], explain: "En la Pokédex, Mareep es el Pokémon Lana." },
  { q: "¿Cuál de estos Pokémon aparece antes que Hitmonlee en la Pokédex Nacional?", correct: "Electrode", wrong: ["Eevee", "Jynx", "Kabuto"], explain: "Hitmonlee es el #106; Electrode #101, Jynx #124, Eevee #133, Kabuto #140." },
  { q: "¿Cuál de estos Pokémon aparece antes que Groudon en la Pokédex Nacional?", correct: "Milotic", wrong: ["Mothim", "Burmy", "Cranidos"], explain: "Groudon es el #383; Milotic #350, Cranidos #408, Burmy #412, Mothim #414." },
  { q: "¿Cuál de estos Pokémon es más bajo que Dachsbun?", correct: "Ditto", wrong: ["Kirlia", "Palkia", "Zapdos"], explain: "Dachsbun mide 0,5 m; Palkia 4,2 m, Zapdos 1,6 m, Kirlia 0,8 m, Ditto 0,3 m." },
  { q: "¿Cuál es la categoría de Igglybuff en la Pokédex?", correct: "Pokémon Globo", wrong: ["Pokémon Lana", "Pokémon Pez Agua", "Pokémon Dragón"], explain: "Igglybuff es el Pokémon Globo." },
  { q: "¿Cuál de estos Pokémon es más liviano que Machoke?", correct: "Litleo", wrong: ["Graveler", "Rayquaza", "Cloyster"], explain: "Machoke pesa 70,5 kg; Rayquaza 206,5 kg, Cloyster 132,5 kg, Graveler 105,0 kg, Litleo 13,5 kg." },
  { q: "¿Cuál de estos Pokémon es más pesado que Unown?", correct: "Quaquaval", wrong: ["Manaphy", "Wattrel", "Barboach"], explain: "Unown pesa 5,0 kg; Quaquaval 61,9 kg, Wattrel 3,6 kg, Barboach 1,9 kg, Manaphy 1,4 kg." },
  { q: "¿Cuál es la categoría de Grimer en la Pokédex?", correct: "Pokémon Lodo", wrong: ["Pokémon Globo", "Pokémon Zorro", "Pokémon Hierbajo"], explain: "Grimer es el Pokémon Lodo." },
  { q: "¿Qué Pokémon ocupa el número #013 de la Pokédex Nacional?", correct: "Weedle", wrong: ["Butterfree", "Beedrill", "Kakuna"], explain: "Weedle es el #013; Butterfree el #012, Kakuna el #014, Beedrill el #015." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Evolución»?", correct: "Eevee", wrong: ["Primeape", "Exeggcute", "Golem"], explain: "En la Pokédex, Eevee es el Pokémon Evolución." },
  { q: "¿Cuánto pesa Machamp?", correct: "130,0 kg", wrong: ["95,0 kg", "154,0 kg", "74,2 kg"], explain: "Según la Pokédex, Machamp pesa 130,0 kg y mide 1,6 m." },
  { q: "¿Qué número tiene Flareon en la Pokédex Nacional?", correct: "#136", wrong: ["#144", "#148", "#146"], explain: "Flareon es el #136 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿De qué color es Buneary según la Pokédex?", correct: "Marrón", wrong: ["Verde", "Negro", "Gris"], explain: "La Pokédex clasifica a Buneary como de color marrón." },
  { q: "¿Cuánto mide Dodrio?", correct: "1,8 m", wrong: ["0,8 m", "3,7 m", "2,6 m"], explain: "Según la Pokédex, Dodrio mide 1,8 m y pesa 85,2 kg." },
  { q: "¿Cuál es la categoría de Lickitung en la Pokédex?", correct: "Pokémon Lametazo", wrong: ["Pokémon Coco", "Pokémon Eléctrico", "Pokémon Ave Gemela"], explain: "Lickitung es el Pokémon Lametazo." },
  { q: "¿En qué región debutó Gengar?", correct: "Kanto", wrong: ["Sinnoh", "Kalos", "Johto"], explain: "Gengar (#094) debutó en la generación 1, la de Kanto." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Numel?", correct: "Seviper", wrong: ["Heracross", "Flareon", "Skrelp"], explain: "Numel y Seviper debutaron en Hoenn; Heracross de Johto, Flareon de Kanto, Skrelp de Kalos." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Mineral»?", correct: "Boldore", wrong: ["Alomomola", "Golurk", "Carracosta"], explain: "En la Pokédex, Boldore es el Pokémon Mineral." },
  { q: "¿Cuál de estos Pokémon es más bajo que Corviknight?", correct: "Poliwag", wrong: ["Palkia", "Xerneas", "Gyarados"], explain: "Corviknight mide 2,2 m; Gyarados 6,5 m, Palkia 4,2 m, Xerneas 3,0 m, Poliwag 0,6 m." },
  { q: "¿Cuál de estos Pokémon es más liviano que Barboach?", correct: "Misdreavus", wrong: ["Absol", "Meditite", "Giratina"], explain: "Barboach pesa 1,9 kg; Giratina 750,0 kg, Absol 47,0 kg, Meditite 11,2 kg, Misdreavus 1,0 kg." },
  { q: "¿Qué Pokémon viene justo antes de Nidorino en la Pokédex Nacional?", correct: "Nidoran♂", wrong: ["Nidoking", "Nidoran♀", "Vulpix"], explain: "Nidorino es el #033 y Nidoran♂ el #032." },
  { q: "¿Cuánto pesa Carnivine?", correct: "27,0 kg", wrong: ["44,0 kg", "63,0 kg", "15,0 kg"], explain: "Según la Pokédex, Carnivine pesa 27,0 kg y mide 1,4 m." },
  { q: "¿Cuánto pesa Nidoran♀?", correct: "7,0 kg", wrong: ["5,9 kg", "10,5 kg", "4,4 kg"], explain: "Según la Pokédex, Nidoran♀ pesa 7,0 kg y mide 0,4 m." },
  { q: "¿En qué región debutó Sandslash?", correct: "Kanto", wrong: ["Hoenn", "Johto", "Kalos"], explain: "Sandslash (#028) debutó en la generación 1, la de Kanto." },
  { q: "¿Qué Pokémon ocupa el número #421 de la Pokédex Nacional?", correct: "Cherrim", wrong: ["Chingling", "Pachirisu", "Honchkrow"], explain: "Cherrim es el #421; Pachirisu el #417, Honchkrow el #430, Chingling el #433." },
  { q: "¿Qué número tiene Zangoose en la Pokédex Nacional?", correct: "#335", wrong: ["#336", "#333", "#332"], explain: "Zangoose es el #335 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuánto mide Ninetales?", correct: "1,1 m", wrong: ["1,5 m", "2,3 m", "3,3 m"], explain: "Según la Pokédex, Ninetales mide 1,1 m y pesa 19,9 kg." },
  { q: "¿Cuál de estos Pokémon es más bajo que Leavanny?", correct: "Skorupi", wrong: ["Copperajah", "Lapras", "Moltres"], explain: "Leavanny mide 1,2 m; Copperajah 3,0 m, Lapras 2,5 m, Moltres 2,0 m, Skorupi 0,8 m." },
  { q: "¿Qué número tiene Kakuna en la Pokédex Nacional?", correct: "#014", wrong: ["#020", "#019", "#025"], explain: "Kakuna es el #014 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Finneon?", correct: "Bidoof", wrong: ["Sudowoodo", "Pelipper", "Cubone"], explain: "Finneon y Bidoof debutaron en Sinnoh; Sudowoodo de Johto, Pelipper de Hoenn, Cubone de Kanto." },
  { q: "¿En qué región debutó Sunflora?", correct: "Johto", wrong: ["Kanto", "Paldea", "Kalos"], explain: "Sunflora (#192) debutó en la generación 2, la de Johto." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Deoxys?", correct: "Ralts", wrong: ["Ariados", "Nidoran♀", "Chingling"], explain: "Deoxys y Ralts debutaron en Hoenn; Ariados de Johto, Nidoran♀ de Kanto, Chingling de Sinnoh." },
  { q: "¿Qué Pokémon ocupa el número #426 de la Pokédex Nacional?", correct: "Drifblim", wrong: ["Drifloon", "Mismagius", "Ambipom"], explain: "Drifblim es el #426; Ambipom el #424, Drifloon el #425, Mismagius el #429." },
  { q: "¿Qué número tiene Sprigatito en la Pokédex Nacional?", correct: "#906", wrong: ["#892", "#916", "#897"], explain: "Sprigatito es el #906 de la Pokédex Nacional y debutó en Paldea." },
  { q: "¿Cuál de estos Pokémon es más liviano que Dugtrio?", correct: "Solosis", wrong: ["Scyther", "Tropius", "Electivire"], explain: "Dugtrio pesa 33,3 kg; Electivire 138,6 kg, Tropius 100,0 kg, Scyther 56,0 kg, Solosis 1,0 kg." },
  { q: "¿Qué número tiene Primeape en la Pokédex Nacional?", correct: "#057", wrong: ["#055", "#054", "#056"], explain: "Primeape es el #057 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál de estos Pokémon es más bajo que Zarude?", correct: "Metang", wrong: ["Wailord", "Giratina", "Dragapult"], explain: "Zarude mide 1,8 m; Wailord 14,5 m, Giratina 4,5 m, Dragapult 3,0 m, Metang 1,2 m." },
  { q: "¿En qué región debutó Xatu?", correct: "Johto", wrong: ["Hoenn", "Sinnoh", "Kanto"], explain: "Xatu (#178) debutó en la generación 2, la de Johto." },
  { q: "¿En qué región debutó Smoochum?", correct: "Johto", wrong: ["Teselia", "Kanto", "Alola"], explain: "Smoochum (#238) debutó en la generación 2, la de Johto." },
  { q: "¿Cuál de estos Pokémon es más alto que Koffing?", correct: "Lunatone", wrong: ["Maushold", "Nidoran♀", "Wormadam"], explain: "Koffing mide 0,6 m; Lunatone 1,0 m, Wormadam 0,5 m, Nidoran♀ 0,4 m, Maushold 0,3 m." },
  { q: "¿Cuál de estos Pokémon aparece después que Drowzee en la Pokédex Nacional?", correct: "Goldeen", wrong: ["Farfetch’d", "Rapidash", "Slowpoke"], explain: "Drowzee es el #096; Rapidash #078, Slowpoke #079, Farfetch’d #083, Goldeen #118." },
  { q: "¿Cuál de estos Pokémon es más pesado que Budew?", correct: "Gardevoir", wrong: ["Uxie", "Tadbulb", "Flabébé"], explain: "Budew pesa 1,2 kg; Gardevoir 48,4 kg, Tadbulb 0,4 kg, Uxie 0,3 kg, Flabébé 0,1 kg." },
  { q: "¿Cuánto mide Palkia?", correct: "4,2 m", wrong: ["2,6 m", "8,8 m", "12,0 m"], explain: "Según la Pokédex, Palkia mide 4,2 m y pesa 336,0 kg." },
  { q: "¿Cuánto mide Latios?", correct: "2,0 m", wrong: ["0,6 m", "3,9 m", "1,1 m"], explain: "Según la Pokédex, Latios mide 2,0 m y pesa 60,0 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Místico»?", correct: "Flygon", wrong: ["Breloom", "Slaking", "Kyogre"], explain: "En la Pokédex, Flygon es el Pokémon Místico." },
  { q: "¿Qué Pokémon viene justo después de Octillery en la Pokédex Nacional?", correct: "Delibird", wrong: ["Remoraid", "Skarmory", "Houndour"], explain: "Octillery es el #224 y Delibird el #225." },
  { q: "¿Qué número tiene Clefairy en la Pokédex Nacional?", correct: "#035", wrong: ["#032", "#033", "#036"], explain: "Clefairy es el #035 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál es la categoría de Ralts en la Pokédex?", correct: "Pokémon Sensible", wrong: ["Pokémon Mariposa", "Pokémon Oscuridad", "Pokémon Gusano"], explain: "Ralts es el Pokémon Sensible." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Pez»?", correct: "Magikarp", wrong: ["Lickitung", "Caterpie", "Scyther"], explain: "En la Pokédex, Magikarp es el Pokémon Pez." },
  { q: "¿Qué Pokémon ocupa el número #102 de la Pokédex Nacional?", correct: "Exeggcute", wrong: ["Cubone", "Hypno", "Lickitung"], explain: "Exeggcute es el #102; Hypno el #097, Cubone el #104, Lickitung el #108." },
  { q: "¿Cuál de estos Pokémon es más pesado que Zangoose?", correct: "Torkoal", wrong: ["Piplup", "Drifblim", "Taillow"], explain: "Zangoose pesa 40,3 kg; Torkoal 80,4 kg, Drifblim 15,0 kg, Piplup 5,2 kg, Taillow 2,3 kg." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Slugma?", correct: "Blissey", wrong: ["Roggenrola", "Dodrio", "Swablu"], explain: "Slugma y Blissey debutaron en Johto; Roggenrola de Teselia, Dodrio de Kanto, Swablu de Hoenn." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Meowth?", correct: "Primeape", wrong: ["Banette", "Espeon", "Carnivine"], explain: "Meowth y Primeape debutaron en Kanto; Banette de Hoenn, Espeon de Johto, Carnivine de Sinnoh." },
  { q: "¿Cuánto mide Crawdaunt?", correct: "1,1 m", wrong: ["3,3 m", "2,4 m", "0,7 m"], explain: "Según la Pokédex, Crawdaunt mide 1,1 m y pesa 32,8 kg." },
  { q: "¿Qué Pokémon viene justo después de Purrloin en la Pokédex Nacional?", correct: "Liepard", wrong: ["Stoutland", "Simisage", "Patrat"], explain: "Purrloin es el #509 y Liepard el #510." },
  { q: "¿Cuál de estos Pokémon aparece después que Metang en la Pokédex Nacional?", correct: "Turtwig", wrong: ["Salamence", "Relicanth", "Walrein"], explain: "Metang es el #375; Walrein #365, Relicanth #369, Salamence #373, Turtwig #387." },
  { q: "¿Qué número tiene Roselia en la Pokédex Nacional?", correct: "#315", wrong: ["#312", "#313", "#317"], explain: "Roselia es el #315 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Avaricia»?", correct: "Greedent", wrong: ["Indeedee", "Duraludon", "Toxel"], explain: "En la Pokédex, Greedent es el Pokémon Avaricia." },
  { q: "¿En qué región debutó Oranguru?", correct: "Alola", wrong: ["Kalos", "Paldea", "Galar"], explain: "Oranguru (#765) debutó en la generación 7, la de Alola." },
  { q: "¿Cuánto mide Buzzwole?", correct: "2,4 m", wrong: ["2,0 m", "7,2 m", "3,4 m"], explain: "Según la Pokédex, Buzzwole mide 2,4 m y pesa 333,6 kg." },
  { q: "¿Cuál de estos Pokémon es más liviano que Turtwig?", correct: "Karrablast", wrong: ["Slowbro", "Croconaw", "Suicune"], explain: "Turtwig pesa 10,2 kg; Suicune 187,0 kg, Slowbro 78,5 kg, Croconaw 25,0 kg, Karrablast 5,9 kg." },
  { q: "¿Qué Pokémon ocupa el número #038 de la Pokédex Nacional?", correct: "Ninetales", wrong: ["Clefable", "Golbat", "Clefairy"], explain: "Ninetales es el #038; Clefairy el #035, Clefable el #036, Golbat el #042." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Broncefante»?", correct: "Copperajah", wrong: ["Eldegoss", "Centiskorch", "Yamper"], explain: "En la Pokédex, Copperajah es el Pokémon Broncefante." },
  { q: "¿Qué número tiene Rapidash en la Pokédex Nacional?", correct: "#078", wrong: ["#077", "#079", "#080"], explain: "Rapidash es el #078 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Qué Pokémon viene justo después de Ludicolo en la Pokédex Nacional?", correct: "Seedot", wrong: ["Lombre", "Pelipper", "Swellow"], explain: "Ludicolo es el #272 y Seedot el #273." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Bewear?", correct: "Komala", wrong: ["Sunkern", "Wigglytuff", "Glastrier"], explain: "Bewear y Komala debutaron en Alola; Sunkern de Johto, Wigglytuff de Kanto, Glastrier de Galar." },
  { q: "¿De qué color es Lopunny según la Pokédex?", correct: "Marrón", wrong: ["Negro", "Amarillo", "Morado"], explain: "La Pokédex clasifica a Lopunny como de color marrón." },
  { q: "¿Cuánto pesa Dragonite?", correct: "210,0 kg", wrong: ["160,0 kg", "380,0 kg", "110,5 kg"], explain: "Según la Pokédex, Dragonite pesa 210,0 kg y mide 2,2 m." },
  { q: "¿Cuál de estos Pokémon aparece antes que Lunatone en la Pokédex Nacional?", correct: "Trapinch", wrong: ["Luvdisc", "Salamence", "Shelgon"], explain: "Lunatone es el #337; Trapinch #328, Luvdisc #370, Shelgon #372, Salamence #373." },
  { q: "¿Qué Pokémon ocupa el número #076 de la Pokédex Nacional?", correct: "Golem", wrong: ["Doduo", "Machoke", "Geodude"], explain: "Golem es el #076; Machoke el #067, Geodude el #074, Doduo el #084." },
  { q: "¿Cuál de estos Pokémon aparece después que Lilligant en la Pokédex Nacional?", correct: "Scraggy", wrong: ["Sawk", "Scolipede", "Throh"], explain: "Lilligant es el #549; Throh #538, Sawk #539, Scolipede #545, Scraggy #559." },
  { q: "¿Cuánto pesa Pelipper?", correct: "28,0 kg", wrong: ["40,8 kg", "16,0 kg", "82,8 kg"], explain: "Según la Pokédex, Pelipper pesa 28,0 kg y mide 1,2 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Siete Puntos»?", correct: "Orbeetle", wrong: ["Arrokuda", "Thievul", "Silicobra"], explain: "En la Pokédex, Orbeetle es el Pokémon Siete Puntos." },
  { q: "¿Qué Pokémon viene justo después de Kingdra en la Pokédex Nacional?", correct: "Phanpy", wrong: ["Houndoom", "Piloswine", "Elekid"], explain: "Kingdra es el #230 y Phanpy el #231." },
  { q: "¿Qué Pokémon viene justo después de Growlithe en la Pokédex Nacional?", correct: "Arcanine", wrong: ["Primeape", "Psyduck", "Poliwhirl"], explain: "Growlithe es el #058 y Arcanine el #059." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Kangaskhan?", correct: "Metapod", wrong: ["Riolu", "Chikorita", "Groudon"], explain: "Kangaskhan y Metapod debutaron en Kanto; Riolu de Sinnoh, Chikorita de Johto, Groudon de Hoenn." },
  { q: "¿Cuánto mide Claydol?", correct: "1,5 m", wrong: ["3,5 m", "2,4 m", "0,5 m"], explain: "Según la Pokédex, Claydol mide 1,5 m y pesa 108,0 kg." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Houndstone?", correct: "Wo-Chien", wrong: ["Noctowl", "Chewtle", "Gastly"], explain: "Houndstone y Wo-Chien debutaron en Paldea; Noctowl de Johto, Chewtle de Galar, Gastly de Kanto." },
  { q: "¿Qué número tiene Floatzel en la Pokédex Nacional?", correct: "#419", wrong: ["#406", "#408", "#423"], explain: "Floatzel es el #419 de la Pokédex Nacional y debutó en Sinnoh." },
  { q: "¿Cuánto mide Moltres?", correct: "2,0 m", wrong: ["3,5 m", "1,6 m", "1,3 m"], explain: "Según la Pokédex, Moltres mide 2,0 m y pesa 60,0 kg." },
  { q: "¿Cuánto mide Regice?", correct: "1,8 m", wrong: ["2,4 m", "2,9 m", "1,4 m"], explain: "Según la Pokédex, Regice mide 1,8 m y pesa 175,0 kg." },
  { q: "¿De qué color es Ariados según la Pokédex?", correct: "Rojo", wrong: ["Azul", "Negro", "Rosa"], explain: "La Pokédex clasifica a Ariados como de color rojo." },
  { q: "¿Qué número tiene Budew en la Pokédex Nacional?", correct: "#406", wrong: ["#395", "#413", "#401"], explain: "Budew es el #406 de la Pokédex Nacional y debutó en Sinnoh." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Serpiente Tierra»?", correct: "Dunsparce", wrong: ["Hitmontop", "Suicune", "Feraligatr"], explain: "En la Pokédex, Dunsparce es el Pokémon Serpiente Tierra." },
  { q: "¿De qué color es Snover según la Pokédex?", correct: "Blanco", wrong: ["Gris", "Negro", "Morado"], explain: "La Pokédex clasifica a Snover como de color blanco." },
  { q: "¿De qué color es Sneasel según la Pokédex?", correct: "Negro", wrong: ["Verde", "Gris", "Rosa"], explain: "La Pokédex clasifica a Sneasel como de color negro." },
  { q: "¿Qué Pokémon ocupa el número #111 de la Pokédex Nacional?", correct: "Rhyhorn", wrong: ["Goldeen", "Voltorb", "Starmie"], explain: "Rhyhorn es el #111; Voltorb el #100, Goldeen el #118, Starmie el #121." },
  { q: "¿Cuál es la categoría de Victreebel en la Pokédex?", correct: "Pokémon Matamoscas", wrong: ["Pokémon Enredadera", "Pokémon Estrella", "Pokémon Armazón"], explain: "Victreebel es el Pokémon Matamoscas." },
  { q: "¿Cuál de estos Pokémon es más liviano que Qwilfish?", correct: "Mesprit", wrong: ["Exeggutor", "Kakuna", "Croconaw"], explain: "Qwilfish pesa 3,9 kg; Exeggutor 120,0 kg, Croconaw 25,0 kg, Kakuna 10,0 kg, Mesprit 0,3 kg." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Mew?", correct: "Pinsir", wrong: ["Yamper", "Shaymin", "Porygon2"], explain: "Mew y Pinsir debutaron en Kanto; Yamper de Galar, Shaymin de Sinnoh, Porygon2 de Johto." },
  { q: "¿Cuál es la categoría de Swinub en la Pokédex?", correct: "Pokémon Cerdo", wrong: ["Pokémon Algadón", "Pokémon Arcoíris", "Pokémon Ratoncito"], explain: "Swinub es el Pokémon Cerdo." },
  { q: "¿En qué región debutó Vespiquen?", correct: "Sinnoh", wrong: ["Alola", "Galar", "Kalos"], explain: "Vespiquen (#416) debutó en la generación 4, la de Sinnoh." },
  { q: "¿De qué color es Nidorina según la Pokédex?", correct: "Azul", wrong: ["Rojo", "Verde", "Blanco"], explain: "La Pokédex clasifica a Nidorina como de color azul." },
  { q: "¿Cuál de estos Pokémon es más bajo que Parasect?", correct: "Porygon2", wrong: ["Corviknight", "Tauros", "Kingdra"], explain: "Parasect mide 1,0 m; Corviknight 2,2 m, Kingdra 1,8 m, Tauros 1,4 m, Porygon2 0,6 m." },
  { q: "¿Cuál de estos Pokémon es más liviano que Machop?", correct: "Bellossom", wrong: ["Omastar", "Snorlax", "Seel"], explain: "Machop pesa 19,5 kg; Snorlax 460,0 kg, Seel 90,0 kg, Omastar 35,0 kg, Bellossom 5,8 kg." },
  { q: "¿Cuál de estos Pokémon es más pesado que Ditto?", correct: "Tyrogue", wrong: ["Diglett", "Chingling", "Dedenne"], explain: "Ditto pesa 4,0 kg; Tyrogue 21,0 kg, Dedenne 2,2 kg, Diglett 0,8 kg, Chingling 0,6 kg." },
  { q: "¿Cuál de estos Pokémon es más bajo que Mew?", correct: "Burmy", wrong: ["Poochyena", "Electrike", "Weezing"], explain: "Mew mide 0,4 m; Weezing 1,2 m, Electrike 0,6 m, Poochyena 0,5 m, Burmy 0,2 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Matamoscas»?", correct: "Weepinbell", wrong: ["Charizard", "Fearow", "Paras"], explain: "En la Pokédex, Weepinbell es el Pokémon Matamoscas." },
  { q: "¿Qué Pokémon ocupa el número #394 de la Pokédex Nacional?", correct: "Prinplup", wrong: ["Torterra", "Luxio", "Turtwig"], explain: "Prinplup es el #394; Turtwig el #387, Torterra el #389, Luxio el #404." },
  { q: "¿Cuál es la categoría de Snorlax en la Pokédex?", correct: "Pokémon Dormir", wrong: ["Pokémon Tortuga", "Pokémon Sombra", "Pokémon Medusa"], explain: "Snorlax es el Pokémon Dormir." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Bolsa Veneno»?", correct: "Swalot", wrong: ["Sceptile", "Trapinch", "Relicanth"], explain: "En la Pokédex, Swalot es el Pokémon Bolsa Veneno." },
  { q: "¿En qué región debutó Hitmontop?", correct: "Johto", wrong: ["Teselia", "Galar", "Paldea"], explain: "Hitmontop (#237) debutó en la generación 2, la de Johto." },
  { q: "¿En qué región debutó Manaphy?", correct: "Sinnoh", wrong: ["Galar", "Alola", "Paldea"], explain: "Manaphy (#490) debutó en la generación 4, la de Sinnoh." },
  { q: "¿Cuál de estos Pokémon es más pesado que Ferropolilla?", correct: "Torkoal", wrong: ["Totodile", "Basculin", "Mew"], explain: "Ferropolilla pesa 36,0 kg; Torkoal 80,4 kg, Basculin 18,0 kg, Totodile 9,5 kg, Mew 4,0 kg." },
  { q: "¿Qué número tiene Mewtwo en la Pokédex Nacional?", correct: "#150", wrong: ["#151", "#148", "#147"], explain: "Mewtwo es el #150 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Qué número tiene Girafarig en la Pokédex Nacional?", correct: "#203", wrong: ["#200", "#205", "#201"], explain: "Girafarig es el #203 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Cuál de estos Pokémon es más bajo que Abra?", correct: "Kabuto", wrong: ["Sceptile", "Zangoose", "Dialga"], explain: "Abra mide 0,9 m; Dialga 5,4 m, Sceptile 1,7 m, Zangoose 1,3 m, Kabuto 0,5 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Arremetida»?", correct: "Arrokuda", wrong: ["Frosmoth", "Sobble", "Dreepy"], explain: "En la Pokédex, Arrokuda es el Pokémon Arremetida." },
  { q: "¿De qué color es Sharpedo según la Pokédex?", correct: "Azul", wrong: ["Rojo", "Blanco", "Gris"], explain: "La Pokédex clasifica a Sharpedo como de color azul." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Hipo»?", correct: "Hippopotas", wrong: ["Gible", "Roserade", "Snover"], explain: "En la Pokédex, Hippopotas es el Pokémon Hipo." },
  { q: "¿Cuál de estos Pokémon es más bajo que Relicanth?", correct: "Geodude", wrong: ["Rampardos", "Entei", "Falinks"], explain: "Relicanth mide 1,0 m; Falinks 3,0 m, Entei 2,1 m, Rampardos 1,6 m, Geodude 0,4 m." },
  { q: "¿Cuánto pesa Hoothoot?", correct: "21,2 kg", wrong: ["39,2 kg", "30,7 kg", "25,0 kg"], explain: "Según la Pokédex, Hoothoot pesa 21,2 kg y mide 0,7 m." },
  { q: "¿De qué color es Furret según la Pokédex?", correct: "Marrón", wrong: ["Rojo", "Gris", "Blanco"], explain: "La Pokédex clasifica a Furret como de color marrón." },
  { q: "¿Cuál de estos Pokémon es más liviano que Finneon?", correct: "Togepi", wrong: ["Porygon2", "Smeargle", "Klink"], explain: "Finneon pesa 7,0 kg; Smeargle 58,0 kg, Porygon2 32,5 kg, Klink 21,0 kg, Togepi 1,5 kg." },
  { q: "¿Qué Pokémon viene justo después de Rowlet en la Pokédex Nacional?", correct: "Dartrix", wrong: ["Volcanion", "Pikipek", "Avalugg"], explain: "Rowlet es el #722 y Dartrix el #723." },
  { q: "¿Cuál es la categoría de Wooloo en la Pokédex?", correct: "Pokémon Oveja", wrong: ["Pokémon Megalito", "Pokémon Rey", "Pokémon Pato Salvaje"], explain: "Wooloo es el Pokémon Oveja." },
  { q: "¿Cuál de estos Pokémon es más alto que Venonat?", correct: "Gliscor", wrong: ["Plusle", "Minior", "Hoothoot"], explain: "Venonat mide 1,0 m; Gliscor 2,0 m, Hoothoot 0,7 m, Plusle 0,4 m, Minior 0,3 m." },
  { q: "¿Cuánto mide Dunsparce?", correct: "1,5 m", wrong: ["0,8 m", "2,8 m", "4,5 m"], explain: "Según la Pokédex, Dunsparce mide 1,5 m y pesa 14,0 kg." },
  { q: "¿Qué Pokémon ocupa el número #086 de la Pokédex Nacional?", correct: "Seel", wrong: ["Graveler", "Hypno", "Rapidash"], explain: "Seel es el #086; Graveler el #075, Rapidash el #078, Hypno el #097." },
  { q: "¿En qué región debutó Haxorus?", correct: "Teselia", wrong: ["Galar", "Johto", "Alola"], explain: "Haxorus (#612) debutó en la generación 5, la de Teselia." },
  { q: "¿En qué región debutó Houndour?", correct: "Johto", wrong: ["Galar", "Kanto", "Hoenn"], explain: "Houndour (#228) debutó en la generación 2, la de Johto." },
  { q: "¿En qué región debutó Miltank?", correct: "Johto", wrong: ["Kalos", "Sinnoh", "Teselia"], explain: "Miltank (#241) debutó en la generación 2, la de Johto." },
  { q: "¿Qué número tiene Beldum en la Pokédex Nacional?", correct: "#374", wrong: ["#384", "#362", "#385"], explain: "Beldum es el #374 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Qué número tiene Parasect en la Pokédex Nacional?", correct: "#047", wrong: ["#044", "#049", "#045"], explain: "Parasect es el #047 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Escupesoga»?", correct: "Spinarak", wrong: ["Ariados", "Stantler", "Ho-Oh"], explain: "En la Pokédex, Spinarak es el Pokémon Escupesoga." },
  { q: "¿Cuál de estos Pokémon es más pesado que Yanma?", correct: "Rhyhorn", wrong: ["Masquerain", "Anorith", "Budew"], explain: "Yanma pesa 38,0 kg; Rhyhorn 115,0 kg, Anorith 12,5 kg, Masquerain 3,6 kg, Budew 1,2 kg." },
  { q: "¿Cuál es la categoría de Wartortle en la Pokédex?", correct: "Pokémon Tortuga", wrong: ["Pokémon Topo", "Pokémon Pin Veneno", "Pokémon Evolución"], explain: "Wartortle es el Pokémon Tortuga." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Puerco»?", correct: "Piloswine", wrong: ["Celebi", "Cleffa", "Cyndaquil"], explain: "En la Pokédex, Piloswine es el Pokémon Puerco." },
  { q: "¿En qué región debutó Quagsire?", correct: "Johto", wrong: ["Sinnoh", "Hoenn", "Kanto"], explain: "Quagsire (#195) debutó en la generación 2, la de Johto." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Pineco?", correct: "Quilava", wrong: ["Meowth", "Armaldo", "Chandelure"], explain: "Pineco y Quilava debutaron en Johto; Meowth de Kanto, Armaldo de Hoenn, Chandelure de Teselia." },
  { q: "¿Cuál de estos Pokémon es más pesado que Dragalge?", correct: "Ursaluna", wrong: ["Indeedee", "Dugtrio", "Paras"], explain: "Dragalge pesa 81,5 kg; Ursaluna 290,0 kg, Dugtrio 33,3 kg, Indeedee 28,0 kg, Paras 5,4 kg." },
  { q: "¿Qué número tiene Mothim en la Pokédex Nacional?", correct: "#414", wrong: ["#407", "#417", "#399"], explain: "Mothim es el #414 de la Pokédex Nacional y debutó en Sinnoh." },
  { q: "¿En qué región debutó Absol?", correct: "Hoenn", wrong: ["Kanto", "Johto", "Sinnoh"], explain: "Absol (#359) debutó en la generación 3, la de Hoenn." },
  { q: "¿En qué región debutó Hypno?", correct: "Kanto", wrong: ["Hoenn", "Paldea", "Teselia"], explain: "Hypno (#097) debutó en la generación 1, la de Kanto." },
  { q: "¿Qué Pokémon ocupa el número #021 de la Pokédex Nacional?", correct: "Spearow", wrong: ["Weedle", "Nidoran♂", "Butterfree"], explain: "Spearow es el #021; Butterfree el #012, Weedle el #013, Nidoran♂ el #032." },
  { q: "¿Cuál de estos Pokémon aparece antes que Kyogre en la Pokédex Nacional?", correct: "Latias", wrong: ["Cranidos", "Wormadam", "Torterra"], explain: "Kyogre es el #382; Latias #380, Torterra #389, Cranidos #408, Wormadam #413." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Símbolo»?", correct: "Unown", wrong: ["Magby", "Pineco", "Umbreon"], explain: "En la Pokédex, Unown es el Pokémon Símbolo." },
  { q: "¿Cuánto mide Phanpy?", correct: "0,5 m", wrong: ["0,3 m", "0,6 m", "0,8 m"], explain: "Según la Pokédex, Phanpy mide 0,5 m y pesa 33,5 kg." },
  { q: "¿De qué color es Krabby según la Pokédex?", correct: "Rojo", wrong: ["Morado", "Amarillo", "Blanco"], explain: "La Pokédex clasifica a Krabby como de color rojo." },
  { q: "¿De qué color es Spoink según la Pokédex?", correct: "Negro", wrong: ["Rosa", "Azul", "Morado"], explain: "La Pokédex clasifica a Spoink como de color negro." },
  { q: "¿Cuánto pesa Bronzong?", correct: "187,0 kg", wrong: ["74,2 kg", "374,0 kg", "125,0 kg"], explain: "Según la Pokédex, Bronzong pesa 187,0 kg y mide 1,3 m." },
  { q: "¿De qué color es Abra según la Pokédex?", correct: "Marrón", wrong: ["Amarillo", "Blanco", "Azul"], explain: "La Pokédex clasifica a Abra como de color marrón." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Magcargo?", correct: "Raikou", wrong: ["Boltund", "Wynaut", "Magnemite"], explain: "Magcargo y Raikou debutaron en Johto; Boltund de Galar, Wynaut de Hoenn, Magnemite de Kanto." },
  { q: "¿Cuánto mide Sentret?", correct: "0,8 m", wrong: ["1,5 m", "1,1 m", "2,4 m"], explain: "Según la Pokédex, Sentret mide 0,8 m y pesa 6,0 kg." },
  { q: "¿Qué Pokémon ocupa el número #865 de la Pokédex Nacional?", correct: "Sirfetch’d", wrong: ["Sinistea", "Indeedee", "Perrserker"], explain: "Sirfetch’d es el #865; Sinistea el #854, Perrserker el #863, Indeedee el #876." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «ADN»?", correct: "Deoxys", wrong: ["Seedot", "Lotad", "Kecleon"], explain: "En la Pokédex, Deoxys es el Pokémon ADN." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Bocado»?", correct: "Karrablast", wrong: ["Sewaddle", "Braviary", "Herdier"], explain: "En la Pokédex, Karrablast es el Pokémon Bocado." },
  { q: "¿Cuánto pesa Weedle?", correct: "3,2 kg", wrong: ["7,3 kg", "1,1 kg", "1,6 kg"], explain: "Según la Pokédex, Weedle pesa 3,2 kg y mide 0,3 m." },
  { q: "¿Qué Pokémon ocupa el número #223 de la Pokédex Nacional?", correct: "Remoraid", wrong: ["Piloswine", "Scizor", "Donphan"], explain: "Remoraid es el #223; Scizor el #212, Piloswine el #221, Donphan el #232." },
  { q: "¿Cuánto pesa Sandslash?", correct: "29,5 kg", wrong: ["55,4 kg", "9,2 kg", "17,3 kg"], explain: "Según la Pokédex, Sandslash pesa 29,5 kg y mide 1,0 m." },
  { q: "¿En qué región debutó Combusken?", correct: "Hoenn", wrong: ["Kalos", "Johto", "Alola"], explain: "Combusken (#256) debutó en la generación 3, la de Hoenn." },
  { q: "¿Cuánto pesa Bulbasaur?", correct: "6,9 kg", wrong: ["15,3 kg", "10,0 kg", "4,9 kg"], explain: "Según la Pokédex, Bulbasaur pesa 6,9 kg y mide 0,7 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Moho»?", correct: "Shuckle", wrong: ["Blissey", "Suicune", "Bellossom"], explain: "En la Pokédex, Shuckle es el Pokémon Moho." },
  { q: "¿Cuál de estos Pokémon es más bajo que Heatran?", correct: "Kabuto", wrong: ["Dhelmise", "Slaking", "Orthworm"], explain: "Heatran mide 1,7 m; Dhelmise 3,9 m, Orthworm 2,5 m, Slaking 2,0 m, Kabuto 0,5 m." },
  { q: "¿Cuál de estos Pokémon es más alto que Helioptile?", correct: "Bayleef", wrong: ["Ditto", "Shroodle", "Poltchageist"], explain: "Helioptile mide 0,5 m; Bayleef 1,2 m, Ditto 0,3 m, Shroodle 0,2 m, Poltchageist 0,1 m." },
  { q: "¿Qué Pokémon ocupa el número #318 de la Pokédex Nacional?", correct: "Carvanha", wrong: ["Wailmer", "Roselia", "Wailord"], explain: "Carvanha es el #318; Roselia el #315, Wailmer el #320, Wailord el #321." },
  { q: "¿Qué Pokémon ocupa el número #008 de la Pokédex Nacional?", correct: "Wartortle", wrong: ["Charizard", "Kakuna", "Pidgeot"], explain: "Wartortle es el #008; Charizard el #006, Kakuna el #014, Pidgeot el #018." },
  { q: "¿Cuánto mide Wailmer?", correct: "2,0 m", wrong: ["1,4 m", "2,5 m", "3,2 m"], explain: "Según la Pokédex, Wailmer mide 2,0 m y pesa 130,0 kg." },
  { q: "¿De qué color es Bronzong según la Pokédex?", correct: "Verde", wrong: ["Rojo", "Marrón", "Azul"], explain: "La Pokédex clasifica a Bronzong como de color verde." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Vikavolt?", correct: "Lunala", wrong: ["Slugma", "Tranquill", "Cascoon"], explain: "Vikavolt y Lunala debutaron en Alola; Slugma de Johto, Tranquill de Teselia, Cascoon de Hoenn." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Voluntad»?", correct: "Azelf", wrong: ["Budew", "Lickilicky", "Happiny"], explain: "En la Pokédex, Azelf es el Pokémon Voluntad." },
  { q: "¿Cuál es la categoría de Ho-Oh en la Pokédex?", correct: "Pokémon Arcoíris", wrong: ["Pokémon Conejo Agua", "Pokémon Volcán", "Pokémon Coral"], explain: "Ho-Oh es el Pokémon Arcoíris." },
  { q: "¿Cuál de estos Pokémon es más liviano que Kangaskhan?", correct: "Prinplup", wrong: ["Arctovish", "Onix", "Salamence"], explain: "Kangaskhan pesa 80,0 kg; Onix 210,0 kg, Arctovish 175,0 kg, Salamence 102,6 kg, Prinplup 23,0 kg." },
  { q: "¿Cuál de estos Pokémon aparece después que Cleffa en la Pokédex Nacional?", correct: "Togepi", wrong: ["Furret", "Hoothoot", "Ledyba"], explain: "Cleffa es el #173; Furret #162, Hoothoot #163, Ledyba #165, Togepi #175." },
  { q: "¿Cuál de estos Pokémon es más pesado que Tauros?", correct: "Ho-Oh", wrong: ["Yanma", "Mr. Mime", "Polteageist"], explain: "Tauros pesa 88,4 kg; Ho-Oh 199,0 kg, Mr. Mime 54,5 kg, Yanma 38,0 kg, Polteageist 0,4 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Boca Abajo»?", correct: "Hitmontop", wrong: ["Politoed", "Natu", "Skiploom"], explain: "En la Pokédex, Hitmontop es el Pokémon Boca Abajo." },
  { q: "¿Qué Pokémon ocupa el número #229 de la Pokédex Nacional?", correct: "Houndoom", wrong: ["Phanpy", "Tyrogue", "Remoraid"], explain: "Houndoom es el #229; Remoraid el #223, Phanpy el #231, Tyrogue el #236." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Feroz»?", correct: "Carvanha", wrong: ["Camerupt", "Tropius", "Kirlia"], explain: "En la Pokédex, Carvanha es el Pokémon Feroz." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Mágico»?", correct: "Mismagius", wrong: ["Palkia", "Roserade", "Skorupi"], explain: "En la Pokédex, Mismagius es el Pokémon Mágico." },
  { q: "¿Qué Pokémon viene justo después de Sandshrew en la Pokédex Nacional?", correct: "Sandslash", wrong: ["Raichu", "Raticate", "Ekans"], explain: "Sandshrew es el #027 y Sandslash el #028." },
  { q: "¿Qué Pokémon viene justo después de Scizor en la Pokédex Nacional?", correct: "Shuckle", wrong: ["Qwilfish", "Dunsparce", "Gligar"], explain: "Scizor es el #212 y Shuckle el #213." },
  { q: "¿Qué número tiene Electabuzz en la Pokédex Nacional?", correct: "#125", wrong: ["#127", "#124", "#126"], explain: "Electabuzz es el #125 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál de estos Pokémon aparece después que Torkoal en la Pokédex Nacional?", correct: "Seviper", wrong: ["Sharpedo", "Camerupt", "Volbeat"], explain: "Torkoal es el #324; Volbeat #313, Sharpedo #319, Camerupt #323, Seviper #336." },
  { q: "¿Qué Pokémon ocupa el número #657 de la Pokédex Nacional?", correct: "Frogadier", wrong: ["Keldeo", "Fennekin", "Chespin"], explain: "Frogadier es el #657; Keldeo el #647, Chespin el #650, Fennekin el #653." },
  { q: "¿Cuánto pesa Poliwag?", correct: "12,4 kg", wrong: ["17,4 kg", "22,6 kg", "6,5 kg"], explain: "Según la Pokédex, Poliwag pesa 12,4 kg y mide 0,6 m." },
  { q: "¿Qué Pokémon ocupa el número #215 de la Pokédex Nacional?", correct: "Sneasel", wrong: ["Dunsparce", "Swinub", "Granbull"], explain: "Sneasel es el #215; Dunsparce el #206, Granbull el #210, Swinub el #220." },
  { q: "¿Cuál es la categoría de Solosis en la Pokédex?", correct: "Pokémon Célula", wrong: ["Pokémon Cristal", "Pokémon Hormigacero", "Pokémon Salpicadura"], explain: "Solosis es el Pokémon Célula." },
  { q: "¿Cuál de estos Pokémon es más liviano que Banette?", correct: "Jigglypuff", wrong: ["Tangrowth", "Camerupt", "Hippowdon"], explain: "Banette pesa 12,5 kg; Hippowdon 300,0 kg, Camerupt 220,0 kg, Tangrowth 128,6 kg, Jigglypuff 5,5 kg." },
  { q: "¿En qué región debutó Jirachi?", correct: "Hoenn", wrong: ["Sinnoh", "Paldea", "Kalos"], explain: "Jirachi (#385) debutó en la generación 3, la de Hoenn." },
  { q: "¿Cuál de estos Pokémon es más bajo que Sandygast?", correct: "Combee", wrong: ["Gible", "Cresselia", "Kecleon"], explain: "Sandygast mide 0,5 m; Cresselia 1,5 m, Kecleon 1,0 m, Gible 0,7 m, Combee 0,3 m." },
  { q: "¿Qué número tiene Hippopotas en la Pokédex Nacional?", correct: "#449", wrong: ["#448", "#452", "#447"], explain: "Hippopotas es el #449 de la Pokédex Nacional y debutó en Sinnoh." },
  { q: "¿Qué Pokémon viene justo después de Wooper en la Pokédex Nacional?", correct: "Quagsire", wrong: ["Yanma", "Sunflora", "Murkrow"], explain: "Wooper es el #194 y Quagsire el #195." },
  { q: "¿Qué Pokémon viene justo antes de Boldore en la Pokédex Nacional?", correct: "Roggenrola", wrong: ["Gigalith", "Gurdurr", "Tympole"], explain: "Boldore es el #525 y Roggenrola el #524." },
  { q: "¿En qué región debutó Quilava?", correct: "Johto", wrong: ["Sinnoh", "Paldea", "Teselia"], explain: "Quilava (#156) debutó en la generación 2, la de Johto." },
  { q: "¿De qué color es Gligar según la Pokédex?", correct: "Morado", wrong: ["Rosa", "Azul", "Negro"], explain: "La Pokédex clasifica a Gligar como de color morado." },
  { q: "¿Cuál de estos Pokémon aparece antes que Dewgong en la Pokédex Nacional?", correct: "Diglett", wrong: ["Exeggutor", "Mr. Mime", "Kingler"], explain: "Dewgong es el #087; Diglett #050, Kingler #099, Exeggutor #103, Mr. Mime #122." },
  { q: "¿Qué Pokémon viene justo después de Thievul en la Pokédex Nacional?", correct: "Gossifleur", wrong: ["Nickit", "Greedent", "Rookidee"], explain: "Thievul es el #828 y Gossifleur el #829." },
  { q: "¿Qué número tiene Munchlax en la Pokédex Nacional?", correct: "#446", wrong: ["#437", "#450", "#434"], explain: "Munchlax es el #446 de la Pokédex Nacional y debutó en Sinnoh." },
  { q: "¿Qué número tiene Metagross en la Pokédex Nacional?", correct: "#376", wrong: ["#364", "#387", "#381"], explain: "Metagross es el #376 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuál de estos Pokémon es más bajo que Combusken?", correct: "Hoppip", wrong: ["Dodrio", "Gastly", "Celesteela"], explain: "Combusken mide 0,9 m; Celesteela 9,2 m, Dodrio 1,8 m, Gastly 1,3 m, Hoppip 0,4 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Apilahueso»?", correct: "Marowak", wrong: ["Charmander", "Arbok", "Omanyte"], explain: "En la Pokédex, Marowak es el Pokémon Apilahueso." },
  { q: "¿Cuál de estos Pokémon es más pesado que Pupitar?", correct: "Bramaluna", wrong: ["Gliscor", "Politoed", "Meditite"], explain: "Pupitar pesa 152,0 kg; Bramaluna 380,0 kg, Gliscor 42,5 kg, Politoed 33,9 kg, Meditite 11,2 kg." },
  { q: "¿Cuál de estos Pokémon es más alto que Elekid?", correct: "Sceptile", wrong: ["Zigzagoon", "Oddish", "Shaymin"], explain: "Elekid mide 0,6 m; Sceptile 1,7 m, Oddish 0,5 m, Zigzagoon 0,4 m, Shaymin 0,2 m." },
  { q: "¿Cuánto pesa Lombre?", correct: "32,5 kg", wrong: ["19,9 kg", "11,5 kg", "59,1 kg"], explain: "Según la Pokédex, Lombre pesa 32,5 kg y mide 1,2 m." },
  { q: "¿Qué número tiene Natu en la Pokédex Nacional?", correct: "#177", wrong: ["#179", "#176", "#175"], explain: "Natu es el #177 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Cuál es la categoría de Dracovish en la Pokédex?", correct: "Pokémon Fósil", wrong: ["Pokémon Cuervo", "Pokémon Silencio", "Pokémon Calma"], explain: "Dracovish es el Pokémon Fósil." },
  { q: "¿Qué número tiene Flaaffy en la Pokédex Nacional?", correct: "#180", wrong: ["#181", "#183", "#182"], explain: "Flaaffy es el #180 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Aggron?", correct: "Trapinch", wrong: ["Sylveon", "Electrode", "Pichu"], explain: "Aggron y Trapinch debutaron en Hoenn; Sylveon de Kalos, Electrode de Kanto, Pichu de Johto." },
  { q: "¿Qué número tiene Kricketune en la Pokédex Nacional?", correct: "#402", wrong: ["#407", "#391", "#409"], explain: "Kricketune es el #402 de la Pokédex Nacional y debutó en Sinnoh." },
  { q: "¿Qué Pokémon ocupa el número #120 de la Pokédex Nacional?", correct: "Staryu", wrong: ["Tauros", "Scyther", "Rhyhorn"], explain: "Staryu es el #120; Rhyhorn el #111, Scyther el #123, Tauros el #128." },
  { q: "¿Qué Pokémon viene justo después de Mankey en la Pokédex Nacional?", correct: "Primeape", wrong: ["Golduck", "Venomoth", "Kadabra"], explain: "Mankey es el #056 y Primeape el #057." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Drifblim?", correct: "Mismagius", wrong: ["Wigglytuff", "Linoone", "Chien-Pao"], explain: "Drifblim y Mismagius debutaron en Sinnoh; Wigglytuff de Kanto, Linoone de Hoenn, Chien-Pao de Paldea." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Arcoíris»?", correct: "Ho-Oh", wrong: ["Marill", "Blissey", "Gligar"], explain: "En la Pokédex, Ho-Oh es el Pokémon Arcoíris." },
  { q: "¿Qué Pokémon ocupa el número #163 de la Pokédex Nacional?", correct: "Hoothoot", wrong: ["Cleffa", "Lanturn", "Totodile"], explain: "Hoothoot es el #163; Totodile el #158, Lanturn el #171, Cleffa el #173." },
  { q: "¿De qué color es Rhyhorn según la Pokédex?", correct: "Gris", wrong: ["Amarillo", "Rojo", "Blanco"], explain: "La Pokédex clasifica a Rhyhorn como de color gris." },
  { q: "¿En qué región debutó Oddish?", correct: "Kanto", wrong: ["Kalos", "Alola", "Paldea"], explain: "Oddish (#043) debutó en la generación 1, la de Kanto." },
  { q: "¿En qué región debutó Nosepass?", correct: "Hoenn", wrong: ["Johto", "Paldea", "Galar"], explain: "Nosepass (#299) debutó en la generación 3, la de Hoenn." },
  { q: "¿Qué número tiene Mareep en la Pokédex Nacional?", correct: "#179", wrong: ["#169", "#189", "#192"], explain: "Mareep es el #179 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Cuánto mide Meowth?", correct: "0,4 m", wrong: ["0,7 m", "0,3 m", "0,2 m"], explain: "Según la Pokédex, Meowth mide 0,4 m y pesa 4,2 kg." },
  { q: "¿En qué región debutó Rapidash?", correct: "Kanto", wrong: ["Alola", "Kalos", "Teselia"], explain: "Rapidash (#078) debutó en la generación 1, la de Kanto." },
  { q: "¿Qué Pokémon ocupa el número #034 de la Pokédex Nacional?", correct: "Nidoking", wrong: ["Paras", "Vileplume", "Golbat"], explain: "Nidoking es el #034; Golbat el #042, Vileplume el #045, Paras el #046." },
  { q: "¿Cuánto pesa Seaking?", correct: "39,0 kg", wrong: ["59,1 kg", "102,5 kg", "18,8 kg"], explain: "Según la Pokédex, Seaking pesa 39,0 kg y mide 1,3 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Muñeca Barro»?", correct: "Claydol", wrong: ["Plusle", "Sableye", "Wailord"], explain: "En la Pokédex, Claydol es el Pokémon Muñeca Barro." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Escandaloso»?", correct: "Exploud", wrong: ["Camerupt", "Carvanha", "Cacnea"], explain: "En la Pokédex, Exploud es el Pokémon Escandaloso." },
  { q: "¿Qué Pokémon viene justo antes de Phanpy en la Pokédex Nacional?", correct: "Kingdra", wrong: ["Donphan", "Skarmory", "Elekid"], explain: "Phanpy es el #231 y Kingdra el #230." },
  { q: "¿Cuál es la categoría de Metang en la Pokédex?", correct: "Pokémon Garra Hierro", wrong: ["Pokémon Hongo", "Pokémon Tierno", "Pokémon Gusano"], explain: "Metang es el Pokémon Garra Hierro." },
  { q: "¿Qué número tiene Teddiursa en la Pokédex Nacional?", correct: "#216", wrong: ["#220", "#230", "#226"], explain: "Teddiursa es el #216 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Cuál de estos Pokémon aparece antes que Spearow en la Pokédex Nacional?", correct: "Butterfree", wrong: ["Paras", "Golbat", "Vileplume"], explain: "Spearow es el #021; Butterfree #012, Golbat #042, Vileplume #045, Paras #046." },
  { q: "¿Cuál de estos Pokémon es más bajo que Hoothoot?", correct: "Swinub", wrong: ["Mr. Mime", "Cofagrigus", "Venusaur"], explain: "Hoothoot mide 0,7 m; Venusaur 2,0 m, Cofagrigus 1,7 m, Mr. Mime 1,3 m, Swinub 0,4 m." },
  { q: "¿Cuál es la categoría de Poliwhirl en la Pokédex?", correct: "Pokémon Renacuajo", wrong: ["Pokémon Apilahueso", "Pokémon Atrocidad", "Pokémon Pico"], explain: "Poliwhirl es el Pokémon Renacuajo." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Slowpoke?", correct: "Bulbasaur", wrong: ["Minun", "Manaphy", "Wooper"], explain: "Slowpoke y Bulbasaur debutaron en Kanto; Minun de Hoenn, Manaphy de Sinnoh, Wooper de Johto." },
  { q: "¿Qué número tiene Venonat en la Pokédex Nacional?", correct: "#048", wrong: ["#047", "#049", "#045"], explain: "Venonat es el #048 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál es la categoría de Wynaut en la Pokédex?", correct: "Pokémon Radiante", wrong: ["Pokémon Cantor", "Pokémon Lanzado", "Pokémon Garra Hierro"], explain: "Wynaut es el Pokémon Radiante." },
  { q: "¿Cuál de estos Pokémon aparece después que Magcargo en la Pokédex Nacional?", correct: "Piloswine", wrong: ["Slugma", "Ursaring", "Heracross"], explain: "Magcargo es el #219; Heracross #214, Ursaring #217, Slugma #218, Piloswine #221." },
  { q: "¿Qué número tiene Orthworm en la Pokédex Nacional?", correct: "#968", wrong: ["#965", "#970", "#967"], explain: "Orthworm es el #968 de la Pokédex Nacional y debutó en Paldea." },
  { q: "¿Qué Pokémon viene justo después de Carracosta en la Pokédex Nacional?", correct: "Archen", wrong: ["Tirtouga", "Zoroark", "Cinccino"], explain: "Carracosta es el #565 y Archen el #566." },
  { q: "¿De qué color es Lairon según la Pokédex?", correct: "Gris", wrong: ["Rosa", "Blanco", "Verde"], explain: "La Pokédex clasifica a Lairon como de color gris." },
  { q: "¿Cuál de estos Pokémon es más alto que Tentacool?", correct: "Pidgeot", wrong: ["Chinchou", "Togepi", "Togetic"], explain: "Tentacool mide 0,9 m; Pidgeot 1,5 m, Togetic 0,6 m, Chinchou 0,5 m, Togepi 0,3 m." },
  { q: "¿Cuál de estos Pokémon es más bajo que Totodile?", correct: "Hoppip", wrong: ["Tentacruel", "Delibird", "Ariados"], explain: "Totodile mide 0,6 m; Tentacruel 1,6 m, Ariados 1,1 m, Delibird 0,9 m, Hoppip 0,4 m." },
  { q: "¿Qué número tiene Alakazam en la Pokédex Nacional?", correct: "#065", wrong: ["#069", "#056", "#055"], explain: "Alakazam es el #065 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Qué número tiene Clamperl en la Pokédex Nacional?", correct: "#366", wrong: ["#355", "#353", "#358"], explain: "Clamperl es el #366 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuál de estos Pokémon es más alto que Exeggutor?", correct: "Palkia", wrong: ["Chespin", "Throh", "Golbat"], explain: "Exeggutor mide 2,0 m; Palkia 4,2 m, Golbat 1,6 m, Throh 1,3 m, Chespin 0,4 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Cuerno»?", correct: "Heracross", wrong: ["Xatu", "Misdreavus", "Blissey"], explain: "En la Pokédex, Heracross es el Pokémon Cuerno." },
  { q: "¿Cuál de estos Pokémon es más pesado que Tentacool?", correct: "Salamence", wrong: ["Applin", "Cyndaquil", "Espurr"], explain: "Tentacool pesa 45,5 kg; Salamence 102,6 kg, Cyndaquil 7,9 kg, Espurr 3,5 kg, Applin 0,5 kg." },
  { q: "¿Cuál es la categoría de Piloswine en la Pokédex?", correct: "Pokémon Puerco", wrong: ["Pokémon Coral", "Pokémon Beso", "Pokémon Pez Agua"], explain: "Piloswine es el Pokémon Puerco." },
  { q: "¿Cuál de estos Pokémon es más alto que Breloom?", correct: "Skarmory", wrong: ["Flaaffy", "Porygon2", "Yamask"], explain: "Breloom mide 1,2 m; Skarmory 1,7 m, Flaaffy 0,8 m, Porygon2 0,6 m, Yamask 0,5 m." },
  { q: "¿Cuál de estos Pokémon aparece antes que Wooper en la Pokédex Nacional?", correct: "Bellossom", wrong: ["Wobbuffet", "Forretress", "Slowking"], explain: "Wooper es el #194; Bellossom #182, Slowking #199, Wobbuffet #202, Forretress #205." },
  { q: "¿Qué Pokémon viene justo después de Dugtrio en la Pokédex Nacional?", correct: "Meowth", wrong: ["Diglett", "Venonat", "Parasect"], explain: "Dugtrio es el #051 y Meowth el #052." },
  { q: "¿Cuál de estos Pokémon es más liviano que Bunnelby?", correct: "Wurmple", wrong: ["Tranquill", "Regigigas", "Lapras"], explain: "Bunnelby pesa 5,0 kg; Regigigas 420,0 kg, Lapras 220,0 kg, Tranquill 15,0 kg, Wurmple 3,6 kg." },
  { q: "¿Cuál de estos Pokémon es más bajo que Ferrothorn?", correct: "Skiploom", wrong: ["Metagross", "Blaziken", "Ho-Oh"], explain: "Ferrothorn mide 1,0 m; Ho-Oh 3,8 m, Blaziken 1,9 m, Metagross 1,6 m, Skiploom 0,6 m." },
  { q: "¿Cuánto mide Pichu?", correct: "0,3 m", wrong: ["0,8 m", "0,6 m", "0,2 m"], explain: "Según la Pokédex, Pichu mide 0,3 m y pesa 2,0 kg." },
  { q: "¿Cuál de estos Pokémon es más bajo que Croconaw?", correct: "Poochyena", wrong: ["Venomoth", "Arctovish", "Seviper"], explain: "Croconaw mide 1,1 m; Seviper 2,7 m, Arctovish 2,0 m, Venomoth 1,5 m, Poochyena 0,5 m." },
  { q: "¿Cuánto mide Hakamo-o?", correct: "1,2 m", wrong: ["0,8 m", "1,5 m", "2,1 m"], explain: "Según la Pokédex, Hakamo-o mide 1,2 m y pesa 47,0 kg." },
  { q: "¿Qué Pokémon ocupa el número #347 de la Pokédex Nacional?", correct: "Anorith", wrong: ["Solrock", "Lileep", "Castform"], explain: "Anorith es el #347; Solrock el #338, Lileep el #345, Castform el #351." },
  { q: "¿Qué Pokémon ocupa el número #192 de la Pokédex Nacional?", correct: "Sunflora", wrong: ["Wobbuffet", "Murkrow", "Marill"], explain: "Sunflora es el #192; Marill el #183, Murkrow el #198, Wobbuffet el #202." },
  { q: "¿Cuál es la categoría de Shuckle en la Pokédex?", correct: "Pokémon Moho", wrong: ["Pokémon Paciente", "Pokémon Algadón", "Pokémon Pez Agua"], explain: "Shuckle es el Pokémon Moho." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Tramposo»?", correct: "Mawile", wrong: ["Latias", "Swampert", "Banette"], explain: "En la Pokédex, Mawile es el Pokémon Tramposo." },
  { q: "¿Cuánto mide Ursaring?", correct: "1,8 m", wrong: ["0,6 m", "3,0 m", "5,2 m"], explain: "Según la Pokédex, Ursaring mide 1,8 m y pesa 125,8 kg." },
  { q: "¿Qué Pokémon ocupa el número #369 de la Pokédex Nacional?", correct: "Relicanth", wrong: ["Huntail", "Regice", "Latios"], explain: "Relicanth es el #369; Huntail el #367, Regice el #378, Latios el #381." },
  { q: "¿Cuál de estos Pokémon es más bajo que Torchic?", correct: "Pichu", wrong: ["Froslass", "Lugia", "Chikorita"], explain: "Torchic mide 0,4 m; Lugia 5,2 m, Froslass 1,3 m, Chikorita 0,9 m, Pichu 0,3 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Transformación»?", correct: "Ditto", wrong: ["Nidoran♂", "Koffing", "Scyther"], explain: "En la Pokédex, Ditto es el Pokémon Transformación." },
  { q: "¿Qué Pokémon viene justo antes de Tangrowth en la Pokédex Nacional?", correct: "Rhyperior", wrong: ["Electivire", "Mamoswine", "Yanmega"], explain: "Tangrowth es el #465 y Rhyperior el #464." },
  { q: "¿Cuánto pesa Delcatty?", correct: "32,6 kg", wrong: ["23,4 kg", "45,0 kg", "97,8 kg"], explain: "Según la Pokédex, Delcatty pesa 32,6 kg y mide 1,1 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Felicidad»?", correct: "Blissey", wrong: ["Typhlosion", "Natu", "Porygon2"], explain: "En la Pokédex, Blissey es el Pokémon Felicidad." },
  { q: "¿Cuál de estos Pokémon aparece después que Snivy en la Pokédex Nacional?", correct: "Herdier", wrong: ["Snover", "Carnivine", "Victini"], explain: "Snivy es el #495; Carnivine #455, Snover #459, Victini #494, Herdier #507." },
  { q: "¿Cuál es la categoría de Tentacruel en la Pokédex?", correct: "Pokémon Medusa", wrong: ["Pokémon Pez", "Pokémon Topo", "Pokémon Coco"], explain: "Tentacruel es el Pokémon Medusa." },
  { q: "¿Qué Pokémon viene justo antes de Relicanth en la Pokédex Nacional?", correct: "Gorebyss", wrong: ["Luvdisc", "Walrein", "Clamperl"], explain: "Relicanth es el #369 y Gorebyss el #368." },
  { q: "¿Qué número tiene Combusken en la Pokédex Nacional?", correct: "#256", wrong: ["#259", "#254", "#258"], explain: "Combusken es el #256 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Shelgon?", correct: "Numel", wrong: ["Starmie", "Manaphy", "Ariados"], explain: "Shelgon y Numel debutaron en Hoenn; Starmie de Kanto, Manaphy de Sinnoh, Ariados de Johto." },
  { q: "¿Cuánto mide Pidgeot?", correct: "1,5 m", wrong: ["2,1 m", "2,9 m", "4,5 m"], explain: "Según la Pokédex, Pidgeot mide 1,5 m y pesa 39,5 kg." },
  { q: "¿Qué Pokémon viene justo después de Spoink en la Pokédex Nacional?", correct: "Grumpig", wrong: ["Torkoal", "Sharpedo", "Zangoose"], explain: "Spoink es el #325 y Grumpig el #326." },
  { q: "¿Cuál es la categoría de Abomasnow en la Pokédex?", correct: "Pokémon Árbol Nieve", wrong: ["Pokémon Campana Bronce", "Pokémon Mimo", "Pokémon Temporal"], explain: "Abomasnow es el Pokémon Árbol Nieve." },
  { q: "¿Cuál es la categoría de Nuzleaf en la Pokédex?", correct: "Pokémon Astuto", wrong: ["Pokémon Ballenaflot", "Pokémon Rodabola", "Pokémon Mariposa"], explain: "Nuzleaf es el Pokémon Astuto." },
  { q: "¿De qué color es Granbull según la Pokédex?", correct: "Morado", wrong: ["Rojo", "Amarillo", "Azul"], explain: "La Pokédex clasifica a Granbull como de color morado." },
  { q: "¿Cuál de estos Pokémon aparece después que Infernape en la Pokédex Nacional?", correct: "Kricketot", wrong: ["Monferno", "Jirachi", "Deoxys"], explain: "Infernape es el #392; Jirachi #385, Deoxys #386, Monferno #391, Kricketot #401." },
  { q: "¿Cuál de estos Pokémon aparece después que Rhyperior en la Pokédex Nacional?", correct: "Froslass", wrong: ["Munchlax", "Hippowdon", "Glameow"], explain: "Rhyperior es el #464; Glameow #431, Munchlax #446, Hippowdon #450, Froslass #478." },
  { q: "¿Cuál de estos Pokémon aparece antes que Machamp en la Pokédex Nacional?", correct: "Arcanine", wrong: ["Electrode", "Dewgong", "Drowzee"], explain: "Machamp es el #068; Arcanine #059, Dewgong #087, Drowzee #096, Electrode #101." },
  { q: "¿Cuál de estos Pokémon aparece después que Snorlax en la Pokédex Nacional?", correct: "Dragonair", wrong: ["Omanyte", "Flareon", "Kabutops"], explain: "Snorlax es el #143; Flareon #136, Omanyte #138, Kabutops #141, Dragonair #148." },
  { q: "¿Cuál de estos Pokémon es más pesado que Omanyte?", correct: "Heatran", wrong: ["Slurpuff", "Igglybuff", "Shellder"], explain: "Omanyte pesa 7,5 kg; Heatran 430,0 kg, Slurpuff 5,0 kg, Shellder 4,0 kg, Igglybuff 1,0 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Imitación»?", correct: "Sudowoodo", wrong: ["Igglybuff", "Politoed", "Dunsparce"], explain: "En la Pokédex, Sudowoodo es el Pokémon Imitación." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Yanma?", correct: "Larvitar", wrong: ["Weedle", "Shedinja", "Sigilyph"], explain: "Yanma y Larvitar debutaron en Johto; Weedle de Kanto, Shedinja de Hoenn, Sigilyph de Teselia." },
  { q: "¿Qué Pokémon ocupa el número #093 de la Pokédex Nacional?", correct: "Haunter", wrong: ["Cloyster", "Onix", "Gastly"], explain: "Haunter es el #093; Cloyster el #091, Gastly el #092, Onix el #095." },
  { q: "¿Cuánto pesa Poliwrath?", correct: "54,0 kg", wrong: ["40,5 kg", "29,0 kg", "91,0 kg"], explain: "Según la Pokédex, Poliwrath pesa 54,0 kg y mide 1,3 m." },
  { q: "¿Cuál de estos Pokémon es más alto que Feraligatr?", correct: "Milotic", wrong: ["Shelgon", "Hypno", "Popplio"], explain: "Feraligatr mide 2,3 m; Milotic 6,2 m, Hypno 1,6 m, Shelgon 1,1 m, Popplio 0,4 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Garra Hierro»?", correct: "Metang", wrong: ["Bagon", "Chimecho", "Aron"], explain: "En la Pokédex, Metang es el Pokémon Garra Hierro." },
  { q: "¿Qué número tiene Zapdos en la Pokédex Nacional?", correct: "#145", wrong: ["#138", "#142", "#160"], explain: "Zapdos es el #145 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál es la categoría de Magby en la Pokédex?", correct: "Pokémon Ascuas", wrong: ["Pokémon Búho", "Pokémon Cerdo", "Pokémon Coral"], explain: "Magby es el Pokémon Ascuas." },
  { q: "¿Cuál de estos Pokémon es más liviano que Totodile?", correct: "Caterpie", wrong: ["Ninjask", "Kadabra", "Lombre"], explain: "Totodile pesa 9,5 kg; Kadabra 56,5 kg, Lombre 32,5 kg, Ninjask 12,0 kg, Caterpie 2,9 kg." },
  { q: "¿Cuánto pesa Jolteon?", correct: "24,5 kg", wrong: ["15,2 kg", "34,0 kg", "9,8 kg"], explain: "Según la Pokédex, Jolteon pesa 24,5 kg y mide 0,8 m." },
  { q: "¿Cuánto mide Gardevoir?", correct: "1,6 m", wrong: ["2,3 m", "1,1 m", "2,9 m"], explain: "Según la Pokédex, Gardevoir mide 1,6 m y pesa 48,4 kg." },
]);
