/* Generado por tools/question-gen/gen_pokedex.py a partir de datos de PokeAPI. No editar a mano: volver a correr el generador. */
window.QUESTION_BANK = window.QUESTION_BANK || {};
window.QUESTION_BANK.pokedex = (window.QUESTION_BANK.pokedex || []).concat([
  { q: "¿En qué región debutó Lotad?", correct: "Hoenn", wrong: ["Alola", "Johto", "Kanto"], explain: "Lotad (#270) debutó en la generación 3, la de Hoenn." },
  { q: "¿Cuál de estos Pokémon es más bajo que Golduck?", correct: "Salandit", wrong: ["Lugia", "Wailord", "Onix"], explain: "Golduck mide 1,7 m; Wailord 14,5 m, Onix 8,8 m, Lugia 5,2 m, Salandit 0,6 m." },
  { q: "¿Qué Pokémon viene justo después de Armaldo en la Pokédex Nacional?", correct: "Feebas", wrong: ["Lunatone", "Swablu", "Crawdaunt"], explain: "Armaldo es el #348 y Feebas el #349." },
  { q: "¿Qué Pokémon viene justo después de Arrokuda en la Pokédex Nacional?", correct: "Barraskewda", wrong: ["Rillaboom", "Thievul", "Blipbug"], explain: "Arrokuda es el #846 y Barraskewda el #847." },
  { q: "¿Qué Pokémon viene justo después de Orbeetle en la Pokédex Nacional?", correct: "Nickit", wrong: ["Inteleon", "Necrozma", "Morgrem"], explain: "Orbeetle es el #826 y Nickit el #827." },
  { q: "¿Qué Pokémon ocupa el número #551 de la Pokédex Nacional?", correct: "Sandile", wrong: ["Beheeyem", "Throh", "Seismitoad"], explain: "Sandile es el #551; Seismitoad el #537, Throh el #538, Beheeyem el #606." },
  { q: "¿Cuál es la categoría de Zangoose en la Pokédex?", correct: "Pokémon Gato Hurón", wrong: ["Pokémon Caniche", "Pokémon Tocón", "Pokémon Lodo"], explain: "Zangoose es el Pokémon Gato Hurón." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Evolución»?", correct: "Eevee", wrong: ["Cranidos", "Bastiodon", "Shellder"], explain: "En la Pokédex, Eevee es el Pokémon Evolución." },
  { q: "¿En qué región debutó Ariados?", correct: "Johto", wrong: ["Kanto", "Teselia", "Galar"], explain: "Ariados (#168) debutó en la generación 2, la de Johto." },
  { q: "¿Qué Pokémon ocupa el número #180 de la Pokédex Nacional?", correct: "Flaaffy", wrong: ["Skiploom", "Wooper", "Quagsire"], explain: "Flaaffy es el #180; Skiploom el #188, Wooper el #194, Quagsire el #195." },
  { q: "¿Cuánto pesa Krabby?", correct: "6,5 kg", wrong: ["3,1 kg", "19,2 kg", "34,3 kg"], explain: "Según la Pokédex, Krabby pesa 6,5 kg y mide 0,4 m." },
  { q: "¿Cuál es la categoría de Kingler en la Pokédex?", correct: "Pokémon Tenaza", wrong: ["Pokémon Equilibrio", "Pokémon Alargado", "Pokémon Bivalvo"], explain: "Kingler es el Pokémon Tenaza." },
  { q: "¿Cuál de estos Pokémon aparece antes que Pikachu en la Pokédex Nacional?", correct: "Spearow", wrong: ["Abra", "Weepinbell", "Nidorina"], explain: "Pikachu es el #025; Spearow #021, Nidorina #030, Abra #063, Weepinbell #070." },
  { q: "¿Qué Pokémon ocupa el número #481 de la Pokédex Nacional?", correct: "Mesprit", wrong: ["Rotom", "Froslass", "Dialga"], explain: "Mesprit es el #481; Froslass el #478, Rotom el #479, Dialga el #483." },
  { q: "¿Cuánto mide Jynx?", correct: "1,4 m", wrong: ["2,6 m", "4,5 m", "0,7 m"], explain: "Según la Pokédex, Jynx mide 1,4 m y pesa 40,6 kg." },
  { q: "¿Qué número tiene Parasect en la Pokédex Nacional?", correct: "#047", wrong: ["#044", "#049", "#045"], explain: "Parasect es el #047 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Qué número tiene Electabuzz en la Pokédex Nacional?", correct: "#125", wrong: ["#131", "#121", "#130"], explain: "Electabuzz es el #125 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Qué número tiene Celebi en la Pokédex Nacional?", correct: "#251", wrong: ["#239", "#228", "#234"], explain: "Celebi es el #251 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Fragancia»?", correct: "Aromatisse", wrong: ["Dragonite", "Kecleon", "Staraptor"], explain: "En la Pokédex, Aromatisse es el Pokémon Fragancia." },
  { q: "¿Cuánto mide Mew?", correct: "0,4 m", wrong: ["1,9 m", "1,1 m", "0,2 m"], explain: "Según la Pokédex, Mew mide 0,4 m y pesa 4,0 kg." },
  { q: "¿Qué Pokémon ocupa el número #211 de la Pokédex Nacional?", correct: "Qwilfish", wrong: ["Snubbull", "Heracross", "Scizor"], explain: "Qwilfish es el #211; Snubbull el #209, Scizor el #212, Heracross el #214." },
  { q: "¿Cuál de estos Pokémon es más bajo que Kricketune?", correct: "Cleffa", wrong: ["Ekans", "Serperior", "Melmetal"], explain: "Kricketune mide 1,0 m; Serperior 3,3 m, Melmetal 2,5 m, Ekans 2,0 m, Cleffa 0,3 m." },
  { q: "¿Cuánto pesa Maushold?", correct: "2,8 kg", wrong: ["16,0 kg", "5,4 kg", "9,2 kg"], explain: "Según la Pokédex, Maushold pesa 2,8 kg y mide 0,3 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Ave Agua»?", correct: "Ducklett", wrong: ["Ninjask", "Paras", "Rattata"], explain: "En la Pokédex, Ducklett es el Pokémon Ave Agua." },
  { q: "¿De qué color es Shuckle según la Pokédex?", correct: "Amarillo", wrong: ["Gris", "Rojo", "Blanco"], explain: "La Pokédex clasifica a Shuckle como de color amarillo." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Agente»?", correct: "Inteleon", wrong: ["Trapinch", "Aerodactyl", "Skiploom"], explain: "En la Pokédex, Inteleon es el Pokémon Agente." },
  { q: "¿Cuál de estos Pokémon es más pesado que Chimecho?", correct: "Sentret", wrong: ["Haunter", "Sinistea", "Applin"], explain: "Chimecho pesa 1,0 kg; Sentret 6,0 kg, Applin 0,5 kg, Sinistea 0,2 kg, Haunter 0,1 kg." },
  { q: "¿Cuánto pesa Magnemite?", correct: "6,0 kg", wrong: ["16,3 kg", "4,2 kg", "11,2 kg"], explain: "Según la Pokédex, Magnemite pesa 6,0 kg y mide 0,3 m." },
  { q: "¿Cuánto mide Gardevoir?", correct: "1,6 m", wrong: ["5,5 m", "3,0 m", "0,9 m"], explain: "Según la Pokédex, Gardevoir mide 1,6 m y pesa 48,4 kg." },
  { q: "¿Qué Pokémon viene justo antes de Dunsparce en la Pokédex Nacional?", correct: "Forretress", wrong: ["Gligar", "Wobbuffet", "Granbull"], explain: "Dunsparce es el #206 y Forretress el #205." },
  { q: "¿Qué número tiene Togepi en la Pokédex Nacional?", correct: "#175", wrong: ["#190", "#121", "#240"], explain: "Togepi es el #175 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Qué Pokémon ocupa el número #321 de la Pokédex Nacional?", correct: "Wailord", wrong: ["Slaking", "Beautifly", "Solrock"], explain: "Wailord es el #321; Beautifly el #267, Slaking el #289, Solrock el #338." },
  { q: "¿Cuál de estos Pokémon es más pesado que Manectric?", correct: "Rampardos", wrong: ["Skitty", "Mareep", "Victreebel"], explain: "Manectric pesa 40,2 kg; Rampardos 102,5 kg, Victreebel 15,5 kg, Skitty 11,0 kg, Mareep 7,8 kg." },
  { q: "¿En qué región debutó Bagon?", correct: "Hoenn", wrong: ["Kanto", "Galar", "Teselia"], explain: "Bagon (#371) debutó en la generación 3, la de Hoenn." },
  { q: "¿En qué región debutó Houndour?", correct: "Johto", wrong: ["Alola", "Kanto", "Paldea"], explain: "Houndour (#228) debutó en la generación 2, la de Johto." },
  { q: "¿Qué número tiene Clamperl en la Pokédex Nacional?", correct: "#366", wrong: ["#355", "#353", "#358"], explain: "Clamperl es el #366 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuál de estos Pokémon es más alto que Doduo?", correct: "Dhelmise", wrong: ["Bulbasaur", "Roselia", "Kabuto"], explain: "Doduo mide 1,4 m; Dhelmise 3,9 m, Bulbasaur 0,7 m, Kabuto 0,5 m, Roselia 0,3 m." },
  { q: "¿Cuál de estos Pokémon es más bajo que Oinkologne?", correct: "Qwilfish", wrong: ["Furret", "Arceus", "Dialga"], explain: "Oinkologne mide 1,0 m; Dialga 5,4 m, Arceus 3,2 m, Furret 1,8 m, Qwilfish 0,5 m." },
  { q: "¿Qué número tiene Munchlax en la Pokédex Nacional?", correct: "#446", wrong: ["#437", "#441", "#431"], explain: "Munchlax es el #446 de la Pokédex Nacional y debutó en Sinnoh." },
  { q: "¿Cuánto pesa Larvesta?", correct: "28,8 kg", wrong: ["78,2 kg", "14,2 kg", "50,0 kg"], explain: "Según la Pokédex, Larvesta pesa 28,8 kg y mide 1,1 m." },
  { q: "¿Qué Pokémon ocupa el número #590 de la Pokédex Nacional?", correct: "Foongus", wrong: ["Cofagrigus", "Beheeyem", "Whirlipede"], explain: "Foongus es el #590; Whirlipede el #544, Cofagrigus el #563, Beheeyem el #606." },
  { q: "¿En qué región debutó Tentacool?", correct: "Kanto", wrong: ["Kalos", "Teselia", "Hoenn"], explain: "Tentacool (#072) debutó en la generación 1, la de Kanto." },
  { q: "¿Qué Pokémon ocupa el número #279 de la Pokédex Nacional?", correct: "Pelipper", wrong: ["Masquerain", "Ho-Oh", "Linoone"], explain: "Pelipper es el #279; Ho-Oh el #250, Linoone el #264, Masquerain el #284." },
  { q: "¿Qué número tiene Whismur en la Pokédex Nacional?", correct: "#293", wrong: ["#281", "#297", "#298"], explain: "Whismur es el #293 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Solrock?", correct: "Beldum", wrong: ["Pidgeotto", "Orbeetle", "Shinx"], explain: "Solrock y Beldum debutaron en Hoenn; Pidgeotto de Kanto, Orbeetle de Galar, Shinx de Sinnoh." },
  { q: "¿Cuál de estos Pokémon es más pesado que Tentacruel?", correct: "Graveler", wrong: ["Cyndaquil", "Slakoth", "Mismagius"], explain: "Tentacruel pesa 55,0 kg; Graveler 105,0 kg, Slakoth 24,0 kg, Cyndaquil 7,9 kg, Mismagius 4,4 kg." },
  { q: "¿Cuánto mide Dragonair?", correct: "4,0 m", wrong: ["1,5 m", "2,2 m", "5,8 m"], explain: "Según la Pokédex, Dragonair mide 4,0 m y pesa 16,5 kg." },
  { q: "¿Qué número tiene Cloyster en la Pokédex Nacional?", correct: "#091", wrong: ["#122", "#169", "#063"], explain: "Cloyster es el #091 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál es la categoría de Caterpie en la Pokédex?", correct: "Pokémon Gusano", wrong: ["Pokémon Mono Cerdo", "Pokémon Pin Veneno", "Pokémon Estrella"], explain: "Caterpie es el Pokémon Gusano." },
  { q: "¿Cuál de estos Pokémon es más pesado que Cyndaquil?", correct: "Tropius", wrong: ["Mew", "Pidgey", "Haunter"], explain: "Cyndaquil pesa 7,9 kg; Tropius 100,0 kg, Mew 4,0 kg, Pidgey 1,8 kg, Haunter 0,1 kg." },
  { q: "¿Cuánto pesa Weedle?", correct: "3,2 kg", wrong: ["12,2 kg", "7,0 kg", "1,4 kg"], explain: "Según la Pokédex, Weedle pesa 3,2 kg y mide 0,3 m." },
  { q: "¿De qué color es Alakazam según la Pokédex?", correct: "Marrón", wrong: ["Morado", "Blanco", "Rojo"], explain: "La Pokédex clasifica a Alakazam como de color marrón." },
  { q: "¿Qué Pokémon ocupa el número #461 de la Pokédex Nacional?", correct: "Weavile", wrong: ["Skorupi", "Carnivine", "Yanmega"], explain: "Weavile es el #461; Skorupi el #451, Carnivine el #455, Yanmega el #469." },
  { q: "¿Qué número tiene Scizor en la Pokédex Nacional?", correct: "#212", wrong: ["#144", "#169", "#289"], explain: "Scizor es el #212 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Qué Pokémon ocupa el número #133 de la Pokédex Nacional?", correct: "Eevee", wrong: ["Magmar", "Zapdos", "Porygon"], explain: "Eevee es el #133; Magmar el #126, Porygon el #137, Zapdos el #145." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Machamp?", correct: "Seel", wrong: ["Glastrier", "Probopass", "Swellow"], explain: "Machamp y Seel debutaron en Kanto; Glastrier de Galar, Probopass de Sinnoh, Swellow de Hoenn." },
  { q: "¿Cuál de estos Pokémon aparece antes que Altaria en la Pokédex Nacional?", correct: "Minun", wrong: ["Banette", "Kyogre", "Sealeo"], explain: "Altaria es el #334; Minun #312, Banette #354, Sealeo #364, Kyogre #382." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Espiral»?", correct: "Omastar", wrong: ["Snover", "Nidorina", "Paras"], explain: "En la Pokédex, Omastar es el Pokémon Espiral." },
  { q: "¿Cuál de estos Pokémon aparece después que Tangela en la Pokédex Nacional?", correct: "Jynx", wrong: ["Hitmonchan", "Exeggcute", "Hitmonlee"], explain: "Tangela es el #114; Exeggcute #102, Hitmonlee #106, Hitmonchan #107, Jynx #124." },
  { q: "¿Cuánto mide Fraxure?", correct: "1,0 m", wrong: ["0,3 m", "3,6 m", "2,0 m"], explain: "Según la Pokédex, Fraxure mide 1,0 m y pesa 36,0 kg." },
  { q: "¿Cuánto pesa Grumpig?", correct: "71,5 kg", wrong: ["185,0 kg", "30,7 kg", "52,6 kg"], explain: "Según la Pokédex, Grumpig pesa 71,5 kg y mide 0,9 m." },
  { q: "¿De qué color es Banette según la Pokédex?", correct: "Negro", wrong: ["Morado", "Blanco", "Rosa"], explain: "La Pokédex clasifica a Banette como de color negro." },
  { q: "¿De qué color es Rhyhorn según la Pokédex?", correct: "Gris", wrong: ["Rosa", "Azul", "Amarillo"], explain: "La Pokédex clasifica a Rhyhorn como de color gris." },
  { q: "¿Cuál de estos Pokémon es más alto que Beedrill?", correct: "Wailmer", wrong: ["Swinub", "Drilbur", "Dreepy"], explain: "Beedrill mide 1,0 m; Wailmer 2,0 m, Dreepy 0,5 m, Swinub 0,4 m, Drilbur 0,3 m." },
  { q: "¿Cuál de estos Pokémon es más pesado que Tyranitar?", correct: "Kyogre", wrong: ["Jolteon", "Miltank", "Lickilicky"], explain: "Tyranitar pesa 202,0 kg; Kyogre 352,0 kg, Lickilicky 140,0 kg, Miltank 75,5 kg, Jolteon 24,5 kg." },
  { q: "¿Qué Pokémon viene justo antes de Moltres en la Pokédex Nacional?", correct: "Zapdos", wrong: ["Dratini", "Snorlax", "Dragonite"], explain: "Moltres es el #146 y Zapdos el #145." },
  { q: "¿Cuál de estos Pokémon es más liviano que Baxcalibur?", correct: "Claydol", wrong: ["Flamariete", "Mamoswine", "Snorlax"], explain: "Baxcalibur pesa 210,0 kg; Flamariete 590,0 kg, Snorlax 460,0 kg, Mamoswine 291,0 kg, Claydol 108,0 kg." },
  { q: "¿Qué Pokémon viene justo antes de Dratini en la Pokédex Nacional?", correct: "Moltres", wrong: ["Natu", "Togepi", "Crobat"], explain: "Dratini es el #147 y Moltres el #146." },
  { q: "¿Qué número tiene Diglett en la Pokédex Nacional?", correct: "#050", wrong: ["#092", "#035", "#033"], explain: "Diglett es el #050 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Qué número tiene Kricketune en la Pokédex Nacional?", correct: "#402", wrong: ["#397", "#413", "#408"], explain: "Kricketune es el #402 de la Pokédex Nacional y debutó en Sinnoh." },
  { q: "¿Qué número tiene Nickit en la Pokédex Nacional?", correct: "#827", wrong: ["#797", "#881", "#776"], explain: "Nickit es el #827 de la Pokédex Nacional y debutó en Galar." },
  { q: "¿Cuál es la categoría de Mime Jr. en la Pokédex?", correct: "Pokémon Mimo", wrong: ["Pokémon Melodía", "Pokémon Leoncito", "Pokémon Topo"], explain: "Mime Jr. es el Pokémon Mimo." },
  { q: "¿Cuál de estos Pokémon aparece antes que Magnezone en la Pokédex Nacional?", correct: "Skorupi", wrong: ["Gliscor", "Yanmega", "Tangrowth"], explain: "Magnezone es el #462; Skorupi #451, Tangrowth #465, Yanmega #469, Gliscor #472." },
  { q: "¿Cuál es la categoría de Poliwag en la Pokédex?", correct: "Pokémon Renacuajo", wrong: ["Pokémon Pez", "Pokémon Taladro", "Pokémon Tortuguita"], explain: "Poliwag es el Pokémon Renacuajo." },
  { q: "¿De qué color es Ho-Oh según la Pokédex?", correct: "Rojo", wrong: ["Azul", "Blanco", "Negro"], explain: "La Pokédex clasifica a Ho-Oh como de color rojo." },
  { q: "¿Cuál de estos Pokémon es más pesado que Hitmontop?", correct: "Registeel", wrong: ["Ledyba", "Houndoom", "Eevee"], explain: "Hitmontop pesa 48,0 kg; Registeel 205,0 kg, Houndoom 35,0 kg, Ledyba 10,8 kg, Eevee 6,5 kg." },
  { q: "¿En qué región debutó Articuno?", correct: "Kanto", wrong: ["Teselia", "Sinnoh", "Hoenn"], explain: "Articuno (#144) debutó en la generación 1, la de Kanto." },
  { q: "¿En qué región debutó Xerneas?", correct: "Kalos", wrong: ["Hoenn", "Kanto", "Alola"], explain: "Xerneas (#716) debutó en la generación 6, la de Kalos." },
  { q: "¿Qué número tiene Snubbull en la Pokédex Nacional?", correct: "#209", wrong: ["#224", "#261", "#171"], explain: "Snubbull es el #209 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Muñeca Barro»?", correct: "Claydol", wrong: ["Swalot", "Beldum", "Nuzleaf"], explain: "En la Pokédex, Claydol es el Pokémon Muñeca Barro." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Heracross?", correct: "Ledyba", wrong: ["Baltoy", "Dialga", "Psyduck"], explain: "Heracross y Ledyba debutaron en Johto; Baltoy de Hoenn, Dialga de Sinnoh, Psyduck de Kanto." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Castor»?", correct: "Bibarel", wrong: ["Umbreon", "Vigoroth", "Masquerain"], explain: "En la Pokédex, Bibarel es el Pokémon Castor." },
  { q: "¿Qué número tiene Chinchou en la Pokédex Nacional?", correct: "#170", wrong: ["#135", "#125", "#245"], explain: "Chinchou es el #170 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿En qué región debutó Shuppet?", correct: "Hoenn", wrong: ["Alola", "Kanto", "Johto"], explain: "Shuppet (#353) debutó en la generación 3, la de Hoenn." },
  { q: "¿Cuál de estos Pokémon aparece antes que Rhyhorn en la Pokédex Nacional?", correct: "Magnemite", wrong: ["Porygon", "Articuno", "Dratini"], explain: "Rhyhorn es el #111; Magnemite #081, Porygon #137, Articuno #144, Dratini #147." },
  { q: "¿Cuál de estos Pokémon es más pesado que Kabuto?", correct: "Porygon2", wrong: ["Jumpluff", "Chimchar", "Milcery"], explain: "Kabuto pesa 11,5 kg; Porygon2 32,5 kg, Chimchar 6,2 kg, Jumpluff 3,0 kg, Milcery 0,3 kg." },
  { q: "¿Qué Pokémon ocupa el número #273 de la Pokédex Nacional?", correct: "Seedot", wrong: ["Shiftry", "Gardevoir", "Shroomish"], explain: "Seedot es el #273; Shiftry el #275, Gardevoir el #282, Shroomish el #285." },
  { q: "¿Cuál es la categoría de Honedge en la Pokédex?", correct: "Pokémon Tizona", wrong: ["Pokémon Petirrojo", "Pokémon Dos Manos", "Pokémon Erizo"], explain: "Honedge es el Pokémon Tizona." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Chirrido»?", correct: "Misdreavus", wrong: ["Starly", "Burmy", "Bidoof"], explain: "En la Pokédex, Misdreavus es el Pokémon Chirrido." },
  { q: "¿Qué número tiene Magikarp en la Pokédex Nacional?", correct: "#129", wrong: ["#063", "#183", "#167"], explain: "Magikarp es el #129 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Místico»?", correct: "Xatu", wrong: ["Slugma", "Ledian", "Quagsire"], explain: "En la Pokédex, Xatu es el Pokémon Místico." },
  { q: "¿Qué número tiene Chikorita en la Pokédex Nacional?", correct: "#152", wrong: ["#161", "#148", "#138"], explain: "Chikorita es el #152 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Cuánto mide Nihilego?", correct: "1,2 m", wrong: ["3,7 m", "2,2 m", "6,2 m"], explain: "Según la Pokédex, Nihilego mide 1,2 m y pesa 55,5 kg." },
  { q: "¿Cuál de estos Pokémon aparece después que Cleffa en la Pokédex Nacional?", correct: "Tyrogue", wrong: ["Furret", "Ditto", "Kangaskhan"], explain: "Cleffa es el #173; Kangaskhan #115, Ditto #132, Furret #162, Tyrogue #236." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Linoone?", correct: "Sharpedo", wrong: ["Jigglypuff", "Phanpy", "Crustle"], explain: "Linoone y Sharpedo debutaron en Hoenn; Jigglypuff de Kanto, Phanpy de Johto, Crustle de Teselia." },
  { q: "¿Cuál de estos Pokémon aparece después que Gloom en la Pokédex Nacional?", correct: "Magneton", wrong: ["Golbat", "Weedle", "Arbok"], explain: "Gloom es el #044; Weedle #013, Arbok #024, Golbat #042, Magneton #082." },
  { q: "¿Qué Pokémon ocupa el número #359 de la Pokédex Nacional?", correct: "Absol", wrong: ["Dusclops", "Wynaut", "Chimecho"], explain: "Absol es el #359; Dusclops el #356, Chimecho el #358, Wynaut el #360." },
  { q: "¿En qué región debutó Togedemaru?", correct: "Alola", wrong: ["Sinnoh", "Paldea", "Kanto"], explain: "Togedemaru (#777) debutó en la generación 7, la de Alola." },
  { q: "¿Cuál es la categoría de Munchlax en la Pokédex?", correct: "Pokémon Comilón", wrong: ["Pokémon Algadón", "Pokémon Hibernante", "Pokémon Corchea"], explain: "Munchlax es el Pokémon Comilón." },
  { q: "¿De qué color es Dratini según la Pokédex?", correct: "Azul", wrong: ["Blanco", "Marrón", "Rojo"], explain: "La Pokédex clasifica a Dratini como de color azul." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Clima»?", correct: "Castform", wrong: ["Kabutops", "Ivysaur", "Relicanth"], explain: "En la Pokédex, Castform es el Pokémon Clima." },
  { q: "¿Qué Pokémon ocupa el número #029 de la Pokédex Nacional?", correct: "Nidoran♀", wrong: ["Ekans", "Nidoqueen", "Ninetales"], explain: "Nidoran♀ es el #029; Ekans el #023, Nidoqueen el #031, Ninetales el #038." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Escandaloso»?", correct: "Exploud", wrong: ["Ludicolo", "Metagross", "Cacturne"], explain: "En la Pokédex, Exploud es el Pokémon Escandaloso." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Slowbro?", correct: "Graveler", wrong: ["Ho-Oh", "Munkidori", "Inkay"], explain: "Slowbro y Graveler debutaron en Kanto; Ho-Oh de Johto, Munkidori de Paldea, Inkay de Kalos." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Búho»?", correct: "Hoothoot", wrong: ["Pupitar", "Machamp", "Corphish"], explain: "En la Pokédex, Hoothoot es el Pokémon Búho." },
  { q: "¿Cuánto mide Mienshao?", correct: "1,4 m", wrong: ["1,1 m", "2,2 m", "0,7 m"], explain: "Según la Pokédex, Mienshao mide 1,4 m y pesa 35,5 kg." },
  { q: "¿Cuál de estos Pokémon aparece después que Anorith en la Pokédex Nacional?", correct: "Wynaut", wrong: ["Whiscash", "Crawdaunt", "Lunatone"], explain: "Anorith es el #347; Lunatone #337, Whiscash #340, Crawdaunt #342, Wynaut #360." },
  { q: "¿Qué número tiene Azurill en la Pokédex Nacional?", correct: "#298", wrong: ["#342", "#351", "#339"], explain: "Azurill es el #298 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuál de estos Pokémon aparece después que Espeon en la Pokédex Nacional?", correct: "Steelix", wrong: ["Sunkern", "Aipom", "Sunflora"], explain: "Espeon es el #196; Aipom #190, Sunkern #191, Sunflora #192, Steelix #208." },
  { q: "¿Cuánto mide Drifblim?", correct: "1,2 m", wrong: ["1,7 m", "3,4 m", "0,6 m"], explain: "Según la Pokédex, Drifblim mide 1,2 m y pesa 15,0 kg." },
  { q: "¿Cuál de estos Pokémon aparece después que Wobbuffet en la Pokédex Nacional?", correct: "Mantine", wrong: ["Hitmonlee", "Jynx", "Dragonair"], explain: "Wobbuffet es el #202; Hitmonlee #106, Jynx #124, Dragonair #148, Mantine #226." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Lagartija»?", correct: "Charmander", wrong: ["Luxio", "Bonsly", "Mawile"], explain: "En la Pokédex, Charmander es el Pokémon Lagartija." },
  { q: "¿Cuál de estos Pokémon es más pesado que Ledian?", correct: "Ondulagua", wrong: ["Spinda", "Zigzagoon", "Sprigatito"], explain: "Ledian pesa 35,6 kg; Ondulagua 280,0 kg, Zigzagoon 17,5 kg, Spinda 5,0 kg, Sprigatito 4,1 kg." },
  { q: "¿Cuál de estos Pokémon es más bajo que Lileep?", correct: "Pikachu", wrong: ["Gliscor", "Melmetal", "Lugia"], explain: "Lileep mide 1,0 m; Lugia 5,2 m, Melmetal 2,5 m, Gliscor 2,0 m, Pikachu 0,4 m." },
  { q: "¿Qué Pokémon ocupa el número #407 de la Pokédex Nacional?", correct: "Roserade", wrong: ["Pachirisu", "Shieldon", "Wormadam"], explain: "Roserade es el #407; Shieldon el #410, Wormadam el #413, Pachirisu el #417." },
  { q: "¿En qué región debutó Machoke?", correct: "Kanto", wrong: ["Kalos", "Teselia", "Johto"], explain: "Machoke (#067) debutó en la generación 1, la de Kanto." },
  { q: "¿Cuál es la categoría de Axew en la Pokédex?", correct: "Pokémon Colmillo", wrong: ["Pokémon Candente", "Pokémon Megaciempiés", "Pokémon Estacional"], explain: "Axew es el Pokémon Colmillo." },
  { q: "¿Cuál de estos Pokémon es más alto que Farfetch’d?", correct: "Melmetal", wrong: ["Eevee", "Wooper", "Natu"], explain: "Farfetch’d mide 0,8 m; Melmetal 2,5 m, Wooper 0,4 m, Eevee 0,3 m, Natu 0,2 m." },
  { q: "¿Cuánto mide Sunflora?", correct: "0,8 m", wrong: ["0,6 m", "1,5 m", "1,2 m"], explain: "Según la Pokédex, Sunflora mide 0,8 m y pesa 8,5 kg." },
  { q: "¿De qué color es Kricketot según la Pokédex?", correct: "Rojo", wrong: ["Rosa", "Marrón", "Morado"], explain: "La Pokédex clasifica a Kricketot como de color rojo." },
  { q: "¿Qué número tiene Drifloon en la Pokédex Nacional?", correct: "#425", wrong: ["#379", "#354", "#392"], explain: "Drifloon es el #425 de la Pokédex Nacional y debutó en Sinnoh." },
  { q: "¿Qué Pokémon viene justo después de Octillery en la Pokédex Nacional?", correct: "Delibird", wrong: ["Suicune", "Slowking", "Magby"], explain: "Octillery es el #224 y Delibird el #225." },
  { q: "¿De qué color es Diglett según la Pokédex?", correct: "Marrón", wrong: ["Morado", "Negro", "Amarillo"], explain: "La Pokédex clasifica a Diglett como de color marrón." },
  { q: "¿Qué número tiene Zangoose en la Pokédex Nacional?", correct: "#335", wrong: ["#332", "#346", "#349"], explain: "Zangoose es el #335 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuál es la categoría de Litleo en la Pokédex?", correct: "Pokémon Leoncito", wrong: ["Pokémon Lucha Libre", "Pokémon Travesura", "Pokémon Regio"], explain: "Litleo es el Pokémon Leoncito." },
  { q: "¿Cuánto pesa Eevee?", correct: "6,5 kg", wrong: ["28,4 kg", "15,0 kg", "1,5 kg"], explain: "Según la Pokédex, Eevee pesa 6,5 kg y mide 0,3 m." },
  { q: "¿Cuál de estos Pokémon es más liviano que Gliscor?", correct: "Goldeen", wrong: ["Pupitar", "Flygon", "Dusknoir"], explain: "Gliscor pesa 42,5 kg; Pupitar 152,0 kg, Dusknoir 106,6 kg, Flygon 82,0 kg, Goldeen 15,0 kg." },
  { q: "¿Cuál de estos Pokémon es más alto que Lopunny?", correct: "Necrozma", wrong: ["Bagon", "Maushold", "Venipede"], explain: "Lopunny mide 1,2 m; Necrozma 2,4 m, Bagon 0,6 m, Venipede 0,4 m, Maushold 0,3 m." },
  { q: "¿Cuánto pesa Flygon?", correct: "82,0 kg", wrong: ["28,4 kg", "125,8 kg", "53,0 kg"], explain: "Según la Pokédex, Flygon pesa 82,0 kg y mide 2,0 m." },
  { q: "¿Cuánto mide Igglybuff?", correct: "0,3 m", wrong: ["0,8 m", "1,8 m", "0,1 m"], explain: "Según la Pokédex, Igglybuff mide 0,3 m y pesa 1,0 kg." },
  { q: "¿Cuál de estos Pokémon es más liviano que Raticate?", correct: "Skitty", wrong: ["Octillery", "Zebstrika", "Hariyama"], explain: "Raticate pesa 18,5 kg; Hariyama 253,8 kg, Zebstrika 79,5 kg, Octillery 28,5 kg, Skitty 11,0 kg." },
  { q: "¿Cuánto mide Sentret?", correct: "0,8 m", wrong: ["1,7 m", "3,2 m", "0,2 m"], explain: "Según la Pokédex, Sentret mide 0,8 m y pesa 6,0 kg." },
  { q: "¿Qué Pokémon viene justo después de Mawile en la Pokédex Nacional?", correct: "Aron", wrong: ["Sableye", "Manectric", "Minun"], explain: "Mawile es el #303 y Aron el #304." },
  { q: "¿Cuál de estos Pokémon es más pesado que Jigglypuff?", correct: "Anorith", wrong: ["Skiploom", "Chatot", "Cleffa"], explain: "Jigglypuff pesa 5,5 kg; Anorith 12,5 kg, Cleffa 3,0 kg, Chatot 1,9 kg, Skiploom 1,0 kg." },
  { q: "¿Cuál de estos Pokémon es más bajo que Medicham?", correct: "Porygon2", wrong: ["Crobat", "Arbok", "Stakataka"], explain: "Medicham mide 1,3 m; Stakataka 5,5 m, Arbok 3,5 m, Crobat 1,8 m, Porygon2 0,6 m." },
  { q: "¿Cuánto pesa Pawniard?", correct: "10,2 kg", wrong: ["34,0 kg", "3,3 kg", "1,8 kg"], explain: "Según la Pokédex, Pawniard pesa 10,2 kg y mide 0,5 m." },
  { q: "¿En qué región debutó Scyther?", correct: "Kanto", wrong: ["Galar", "Hoenn", "Kalos"], explain: "Scyther (#123) debutó en la generación 1, la de Kanto." },
  { q: "¿Cuál de estos Pokémon es más alto que Ambipom?", correct: "Blastoise", wrong: ["Natu", "Stunfisk", "Mew"], explain: "Ambipom mide 1,2 m; Blastoise 1,6 m, Stunfisk 0,7 m, Mew 0,4 m, Natu 0,2 m." },
  { q: "¿Cuál de estos Pokémon aparece después que Carnivine en la Pokédex Nacional?", correct: "Darmanitan", wrong: ["Dusclops", "Purugly", "Claydol"], explain: "Carnivine es el #455; Claydol #344, Dusclops #356, Purugly #432, Darmanitan #555." },
  { q: "¿Qué número tiene Slowbro en la Pokédex Nacional?", correct: "#080", wrong: ["#139", "#041", "#017"], explain: "Slowbro es el #080 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál de estos Pokémon es más bajo que Hippopotas?", correct: "Shellder", wrong: ["Virizion", "Regigigas", "Haunter"], explain: "Hippopotas mide 0,8 m; Regigigas 3,7 m, Virizion 2,0 m, Haunter 1,6 m, Shellder 0,3 m." },
  { q: "¿Cuál es la categoría de Gible en la Pokédex?", correct: "Pokémon Terrascualo", wrong: ["Pokémon Enredadera", "Pokémon Mágico", "Pokémon Chispa"], explain: "Gible es el Pokémon Terrascualo." },
  { q: "¿Cuánto pesa Koffing?", correct: "1,0 kg", wrong: ["0,2 kg", "0,4 kg", "4,5 kg"], explain: "Según la Pokédex, Koffing pesa 1,0 kg y mide 0,6 m." },
  { q: "¿Cuál es la categoría de Flaaffy en la Pokédex?", correct: "Pokémon Lana", wrong: ["Pokémon Imitación", "Pokémon Místico", "Pokémon Puerco"], explain: "Flaaffy es el Pokémon Lana." },
  { q: "¿En qué región debutó Entei?", correct: "Johto", wrong: ["Kalos", "Alola", "Paldea"], explain: "Entei (#244) debutó en la generación 2, la de Johto." },
  { q: "¿Cuánto mide Noctowl?", correct: "1,6 m", wrong: ["1,1 m", "2,4 m", "3,5 m"], explain: "Según la Pokédex, Noctowl mide 1,6 m y pesa 40,8 kg." },
  { q: "¿Cuál de estos Pokémon aparece después que Shedinja en la Pokédex Nacional?", correct: "Volbeat", wrong: ["Celebi", "Seedot", "Ninjask"], explain: "Shedinja es el #292; Celebi #251, Seedot #273, Ninjask #291, Volbeat #313." },
  { q: "¿Qué número tiene Manaphy en la Pokédex Nacional?", correct: "#490", wrong: ["#487", "#493", "#489"], explain: "Manaphy es el #490 de la Pokédex Nacional y debutó en Sinnoh." },
  { q: "¿Cuál es la categoría de Bellsprout en la Pokédex?", correct: "Pokémon Flor", wrong: ["Pokémon Antenas", "Pokémon Puñetazo", "Pokémon Tundra"], explain: "Bellsprout es el Pokémon Flor." },
  { q: "¿Cuál es la categoría de Spearow en la Pokédex?", correct: "Pokémon Pajarito", wrong: ["Pokémon Insecto", "Pokémon Murciélago", "Pokémon Llama"], explain: "Spearow es el Pokémon Pajarito." },
  { q: "¿Cuál de estos Pokémon es más pesado que Jellicent?", correct: "Cosmoem", wrong: ["Feebas", "Gible", "Shroomish"], explain: "Jellicent pesa 135,0 kg; Cosmoem 999,9 kg, Gible 20,5 kg, Feebas 7,4 kg, Shroomish 4,5 kg." },
  { q: "¿Cuánto pesa Misdreavus?", correct: "1,0 kg", wrong: ["2,9 kg", "1,4 kg", "1,9 kg"], explain: "Según la Pokédex, Misdreavus pesa 1,0 kg y mide 0,7 m." },
  { q: "¿Cuál de estos Pokémon es más alto que Growlithe?", correct: "Ledian", wrong: ["Smoliv", "Surskit", "Plusle"], explain: "Growlithe mide 0,7 m; Ledian 1,4 m, Surskit 0,5 m, Plusle 0,4 m, Smoliv 0,3 m." },
  { q: "¿Qué Pokémon ocupa el número #390 de la Pokédex Nacional?", correct: "Chimchar", wrong: ["Snorunt", "Armaldo", "Latias"], explain: "Chimchar es el #390; Armaldo el #348, Snorunt el #361, Latias el #380." },
  { q: "¿Qué Pokémon ocupa el número #058 de la Pokédex Nacional?", correct: "Growlithe", wrong: ["Poliwrath", "Bellsprout", "Machoke"], explain: "Growlithe es el #058; Poliwrath el #062, Machoke el #067, Bellsprout el #069." },
  { q: "¿Qué número tiene Magnemite en la Pokédex Nacional?", correct: "#081", wrong: ["#137", "#092", "#094"], explain: "Magnemite es el #081 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál de estos Pokémon es más pesado que Pineco?", correct: "Poliwag", wrong: ["Morelull", "Wattrel", "Koffing"], explain: "Pineco pesa 7,2 kg; Poliwag 12,4 kg, Wattrel 3,6 kg, Morelull 1,5 kg, Koffing 1,0 kg." },
  { q: "¿Cuánto pesa Blaziken?", correct: "52,0 kg", wrong: ["31,2 kg", "115,5 kg", "19,8 kg"], explain: "Según la Pokédex, Blaziken pesa 52,0 kg y mide 1,9 m." },
  { q: "¿Cuál es la categoría de Pupitar en la Pokédex?", correct: "Pokémon Caparazón", wrong: ["Pokémon Tenaza", "Pokémon Símbolo", "Pokémon Dragón"], explain: "Pupitar es el Pokémon Caparazón." },
  { q: "¿De qué color es Sunkern según la Pokédex?", correct: "Amarillo", wrong: ["Rojo", "Rosa", "Morado"], explain: "La Pokédex clasifica a Sunkern como de color amarillo." },
  { q: "¿De qué color es Poliwag según la Pokédex?", correct: "Azul", wrong: ["Negro", "Rojo", "Rosa"], explain: "La Pokédex clasifica a Poliwag como de color azul." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Nidoqueen?", correct: "Metapod", wrong: ["Tyrogue", "Drifloon", "Loudred"], explain: "Nidoqueen y Metapod debutaron en Kanto; Tyrogue de Johto, Drifloon de Sinnoh, Loudred de Hoenn." },
  { q: "¿Cuál de estos Pokémon aparece antes que Riolu en la Pokédex Nacional?", correct: "Wynaut", wrong: ["Archen", "Leafeon", "Weavile"], explain: "Riolu es el #447; Wynaut #360, Weavile #461, Leafeon #470, Archen #566." },
  { q: "¿Cuánto pesa Dialga?", correct: "683,0 kg", wrong: ["200,0 kg", "106,6 kg", "380,0 kg"], explain: "Según la Pokédex, Dialga pesa 683,0 kg y mide 5,4 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Atontado»?", correct: "Slowpoke", wrong: ["Poliwrath", "Krabby", "Marowak"], explain: "En la Pokédex, Slowpoke es el Pokémon Atontado." },
  { q: "¿Cuál de estos Pokémon es más pesado que Swellow?", correct: "Mightyena", wrong: ["Marill", "Unown", "Wigglytuff"], explain: "Swellow pesa 19,8 kg; Mightyena 37,0 kg, Wigglytuff 12,0 kg, Marill 8,5 kg, Unown 5,0 kg." },
  { q: "¿De qué color es Dewott según la Pokédex?", correct: "Azul", wrong: ["Amarillo", "Blanco", "Gris"], explain: "La Pokédex clasifica a Dewott como de color azul." },
  { q: "¿Cuál de estos Pokémon es más bajo que Clefable?", correct: "Sunflora", wrong: ["Onix", "Dracovish", "Groudon"], explain: "Clefable mide 1,3 m; Onix 8,8 m, Groudon 3,5 m, Dracovish 2,3 m, Sunflora 0,8 m." },
  { q: "¿Cuánto pesa Lanturn?", correct: "22,5 kg", wrong: ["5,4 kg", "72,0 kg", "12,2 kg"], explain: "Según la Pokédex, Lanturn pesa 22,5 kg y mide 1,2 m." },
  { q: "¿Cuál de estos Pokémon es más bajo que Jynx?", correct: "Porygon2", wrong: ["Dialga", "Kangaskhan", "Ho-Oh"], explain: "Jynx mide 1,4 m; Dialga 5,4 m, Ho-Oh 3,8 m, Kangaskhan 2,2 m, Porygon2 0,6 m." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Transformación»?", correct: "Ditto", wrong: ["Drapion", "Mantyke", "Bonsly"], explain: "En la Pokédex, Ditto es el Pokémon Transformación." },
  { q: "¿Cuánto pesa Gurdurr?", correct: "40,0 kg", wrong: ["23,8 kg", "68,0 kg", "9,9 kg"], explain: "Según la Pokédex, Gurdurr pesa 40,0 kg y mide 1,2 m." },
  { q: "¿Cuál de estos Pokémon es más pesado que Bayleef?", correct: "Mamoswine", wrong: ["Caterpie", "Shellos", "Kricketot"], explain: "Bayleef pesa 15,8 kg; Mamoswine 291,0 kg, Shellos 6,3 kg, Caterpie 2,9 kg, Kricketot 2,2 kg." },
  { q: "¿De qué color es Aipom según la Pokédex?", correct: "Morado", wrong: ["Negro", "Verde", "Rojo"], explain: "La Pokédex clasifica a Aipom como de color morado." },
  { q: "¿Qué número tiene Armaldo en la Pokédex Nacional?", correct: "#348", wrong: ["#357", "#337", "#336"], explain: "Armaldo es el #348 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Qué número tiene Delibird en la Pokédex Nacional?", correct: "#225", wrong: ["#255", "#273", "#152"], explain: "Delibird es el #225 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Cuál de estos Pokémon es más bajo que Seaking?", correct: "Poliwag", wrong: ["Rayquaza", "Regigigas", "Dragapult"], explain: "Seaking mide 1,3 m; Rayquaza 7,0 m, Regigigas 3,7 m, Dragapult 3,0 m, Poliwag 0,6 m." },
  { q: "¿Cuál de estos Pokémon aparece antes que Stoutland en la Pokédex Nacional?", correct: "Giratina", wrong: ["Sewaddle", "Whirlipede", "Conkeldurr"], explain: "Stoutland es el #508; Giratina #487, Conkeldurr #534, Sewaddle #540, Whirlipede #544." },
  { q: "¿Cuál de estos Pokémon es más bajo que Leafeon?", correct: "Raticate", wrong: ["Manectric", "Steelix", "Raikou"], explain: "Leafeon mide 1,0 m; Steelix 9,2 m, Raikou 1,9 m, Manectric 1,5 m, Raticate 0,7 m." },
  { q: "¿Cuál es la categoría de Glameow en la Pokédex?", correct: "Pokémon Gastuto", wrong: ["Pokémon Virtual", "Pokémon Brújula", "Pokémon Escorpión"], explain: "Glameow es el Pokémon Gastuto." },
  { q: "¿Cuál de estos Pokémon es más liviano que Aipom?", correct: "Spritzee", wrong: ["Glastrier", "Sharpedo", "Marshadow"], explain: "Aipom pesa 11,5 kg; Glastrier 800,0 kg, Sharpedo 88,8 kg, Marshadow 22,2 kg, Spritzee 0,5 kg." },
  { q: "¿Cuál de estos Pokémon es más liviano que Clefable?", correct: "Togetic", wrong: ["Regigigas", "Graveler", "Ferroverdor"], explain: "Clefable pesa 40,0 kg; Regigigas 420,0 kg, Ferroverdor 125,0 kg, Graveler 105,0 kg, Togetic 3,2 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Serpiente Roca»?", correct: "Onix", wrong: ["Scyther", "Nidorina", "Growlithe"], explain: "En la Pokédex, Onix es el Pokémon Serpiente Roca." },
  { q: "¿Cuál es la categoría de Igglybuff en la Pokédex?", correct: "Pokémon Globo", wrong: ["Pokémon Pajarito", "Pokémon Ratón Fuego", "Pokémon Reactor"], explain: "Igglybuff es el Pokémon Globo." },
  { q: "¿Cuál de estos Pokémon es más alto que Scovillain?", correct: "Scolipede", wrong: ["Starly", "Ralts", "Rookidee"], explain: "Scovillain mide 0,9 m; Scolipede 2,5 m, Ralts 0,4 m, Starly 0,3 m, Rookidee 0,2 m." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Ivysaur?", correct: "Golbat", wrong: ["Tropius", "Toxicroak", "Kleavor"], explain: "Ivysaur y Golbat debutaron en Kanto; Tropius de Hoenn, Toxicroak de Sinnoh, Kleavor de Galar." },
  { q: "¿Cuál de estos Pokémon es más pesado que Sealeo?", correct: "Hippowdon", wrong: ["Dugtrio", "Burmy", "Jolteon"], explain: "Sealeo pesa 87,6 kg; Hippowdon 300,0 kg, Dugtrio 33,3 kg, Jolteon 24,5 kg, Burmy 3,4 kg." },
  { q: "¿En qué región debutó Bramaluna?", correct: "Paldea", wrong: ["Johto", "Alola", "Galar"], explain: "Bramaluna (#1005) debutó en la generación 9, la de Paldea." },
  { q: "¿Cuál de estos Pokémon es más pesado que Sandslash?", correct: "Drapion", wrong: ["Abra", "Wurmple", "Unown"], explain: "Sandslash pesa 29,5 kg; Drapion 61,5 kg, Abra 19,5 kg, Unown 5,0 kg, Wurmple 3,6 kg." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Crobat?", correct: "Sudowoodo", wrong: ["Sceptile", "Fuecoco", "Snover"], explain: "Crobat y Sudowoodo debutaron en Johto; Sceptile de Hoenn, Fuecoco de Paldea, Snover de Sinnoh." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Gratitud»?", correct: "Shaymin", wrong: ["Nuzleaf", "Persian", "Happiny"], explain: "En la Pokédex, Shaymin es el Pokémon Gratitud." },
  { q: "¿Qué Pokémon ocupa el número #101 de la Pokédex Nacional?", correct: "Electrode", wrong: ["Krabby", "Exeggutor", "Cubone"], explain: "Electrode es el #101; Krabby el #098, Exeggutor el #103, Cubone el #104." },
  { q: "¿Cuánto mide Chikorita?", correct: "0,9 m", wrong: ["0,3 m", "2,5 m", "1,5 m"], explain: "Según la Pokédex, Chikorita mide 0,9 m y pesa 6,4 kg." },
  { q: "¿En qué región debutó Cloyster?", correct: "Kanto", wrong: ["Teselia", "Kalos", "Johto"], explain: "Cloyster (#091) debutó en la generación 1, la de Kanto." },
  { q: "¿De qué color es Weezing según la Pokédex?", correct: "Morado", wrong: ["Verde", "Azul", "Blanco"], explain: "La Pokédex clasifica a Weezing como de color morado." },
  { q: "¿En qué región debutó Shedinja?", correct: "Hoenn", wrong: ["Galar", "Sinnoh", "Teselia"], explain: "Shedinja (#292) debutó en la generación 3, la de Hoenn." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Latios?", correct: "Dustox", wrong: ["Golbat", "Slurpuff", "Cryogonal"], explain: "Latios y Dustox debutaron en Hoenn; Golbat de Kanto, Slurpuff de Kalos, Cryogonal de Teselia." },
  { q: "¿Qué Pokémon ocupa el número #001 de la Pokédex Nacional?", correct: "Bulbasaur", wrong: ["Paras", "Raticate", "Growlithe"], explain: "Bulbasaur es el #001; Raticate el #020, Paras el #046, Growlithe el #058." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Tortuguita»?", correct: "Squirtle", wrong: ["Turtwig", "Seviper", "Staraptor"], explain: "En la Pokédex, Squirtle es el Pokémon Tortuguita." },
  { q: "¿Cuánto pesa Mantine?", correct: "220,0 kg", wrong: ["125,8 kg", "53,0 kg", "480,0 kg"], explain: "Según la Pokédex, Mantine pesa 220,0 kg y mide 2,1 m." },
  { q: "¿Qué número tiene Kakuna en la Pokédex Nacional?", correct: "#014", wrong: ["#092", "#062", "#046"], explain: "Kakuna es el #014 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál de estos Pokémon es más alto que Trapinch?", correct: "Slaking", wrong: ["Uxie", "Marill", "Elgyem"], explain: "Trapinch mide 0,7 m; Slaking 2,0 m, Elgyem 0,5 m, Marill 0,4 m, Uxie 0,3 m." },
  { q: "¿En qué región debutó Haunter?", correct: "Kanto", wrong: ["Kalos", "Sinnoh", "Teselia"], explain: "Haunter (#093) debutó en la generación 1, la de Kanto." },
  { q: "¿Cuál es la categoría de Wurmple en la Pokédex?", correct: "Pokémon Gusano", wrong: ["Pokémon Pez Lodo", "Pokémon Monte", "Pokémon Alegre"], explain: "Wurmple es el Pokémon Gusano." },
  { q: "¿Cuál de estos Pokémon aparece después que Mesprit en la Pokédex Nacional?", correct: "Sigilyph", wrong: ["Uxie", "Bonsly", "Finneon"], explain: "Mesprit es el #481; Bonsly #438, Finneon #456, Uxie #480, Sigilyph #561." },
  { q: "¿Cuánto pesa Hariyama?", correct: "253,8 kg", wrong: ["68,0 kg", "430,0 kg", "38,5 kg"], explain: "Según la Pokédex, Hariyama pesa 253,8 kg y mide 2,3 m." },
  { q: "¿Cuál de estos Pokémon es más bajo que Carvanha?", correct: "Cosmog", wrong: ["Claydol", "Zacian", "Onix"], explain: "Carvanha mide 0,8 m; Onix 8,8 m, Zacian 2,8 m, Claydol 1,5 m, Cosmog 0,2 m." },
  { q: "¿Qué Pokémon viene justo antes de Cottonee en la Pokédex Nacional?", correct: "Scolipede", wrong: ["Swadloon", "Throh", "Herdier"], explain: "Cottonee es el #546 y Scolipede el #545." },
  { q: "¿Cuál de estos Pokémon es más liviano que Dreepy?", correct: "Skiploom", wrong: ["Bronzor", "Pidgeotto", "Machamp"], explain: "Dreepy pesa 2,0 kg; Machamp 130,0 kg, Bronzor 60,5 kg, Pidgeotto 30,0 kg, Skiploom 1,0 kg." },
  { q: "¿Cuánto mide Loudred?", correct: "1,0 m", wrong: ["1,5 m", "1,9 m", "0,8 m"], explain: "Según la Pokédex, Loudred mide 1,0 m y pesa 40,5 kg." },
  { q: "¿En qué región debutó Girafarig?", correct: "Johto", wrong: ["Kalos", "Alola", "Teselia"], explain: "Girafarig (#203) debutó en la generación 2, la de Johto." },
  { q: "¿De qué color es Jolteon según la Pokédex?", correct: "Amarillo", wrong: ["Verde", "Negro", "Marrón"], explain: "La Pokédex clasifica a Jolteon como de color amarillo." },
  { q: "¿Cuál de estos Pokémon es más liviano que Suicune?", correct: "Alakazam", wrong: ["Snorlax", "Torterra", "Gyarados"], explain: "Suicune pesa 187,0 kg; Snorlax 460,0 kg, Torterra 310,0 kg, Gyarados 235,0 kg, Alakazam 48,0 kg." },
  { q: "¿Qué Pokémon ocupa el número #159 de la Pokédex Nacional?", correct: "Croconaw", wrong: ["Tauros", "Voltorb", "Flareon"], explain: "Croconaw es el #159; Voltorb el #100, Tauros el #128, Flareon el #136." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Casita»?", correct: "Happiny", wrong: ["Snorlax", "Exeggutor", "Houndour"], explain: "En la Pokédex, Happiny es el Pokémon Casita." },
  { q: "¿En qué región debutó Teddiursa?", correct: "Johto", wrong: ["Sinnoh", "Kanto", "Teselia"], explain: "Teddiursa (#216) debutó en la generación 2, la de Johto." },
  { q: "¿Qué número tiene Beldum en la Pokédex Nacional?", correct: "#374", wrong: ["#332", "#451", "#431"], explain: "Beldum es el #374 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuál es la categoría de Volbeat en la Pokédex?", correct: "Pokémon Luciérnaga", wrong: ["Pokémon Espantajo", "Pokémon Gatito", "Pokémon Cactus"], explain: "Volbeat es el Pokémon Luciérnaga." },
  { q: "¿En qué región debutó Carnivine?", correct: "Sinnoh", wrong: ["Johto", "Hoenn", "Galar"], explain: "Carnivine (#455) debutó en la generación 4, la de Sinnoh." },
  { q: "¿Cuál de estos Pokémon aparece antes que Skiploom en la Pokédex Nacional?", correct: "Aerodactyl", wrong: ["Masquerain", "Elekid", "Slowking"], explain: "Skiploom es el #188; Aerodactyl #142, Slowking #199, Elekid #239, Masquerain #284." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Temporal»?", correct: "Dialga", wrong: ["Froslass", "Prinplup", "Empoleon"], explain: "En la Pokédex, Dialga es el Pokémon Temporal." },
  { q: "¿Qué Pokémon viene justo antes de Vibrava en la Pokédex Nacional?", correct: "Trapinch", wrong: ["Glalie", "Camerupt", "Baltoy"], explain: "Vibrava es el #329 y Trapinch el #328." },
  { q: "¿Qué número tiene Slaking en la Pokédex Nacional?", correct: "#289", wrong: ["#258", "#320", "#341"], explain: "Slaking es el #289 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuál de estos Pokémon aparece después que Falinks en la Pokédex Nacional?", correct: "Fidough", wrong: ["Hatenna", "Sizzlipede", "Solgaleo"], explain: "Falinks es el #870; Solgaleo #791, Sizzlipede #850, Hatenna #856, Fidough #926." },
  { q: "¿En qué región debutó Magmar?", correct: "Kanto", wrong: ["Kalos", "Johto", "Teselia"], explain: "Magmar (#126) debutó en la generación 1, la de Kanto." },
  { q: "¿Qué número tiene Pidgeot en la Pokédex Nacional?", correct: "#018", wrong: ["#020", "#021", "#017"], explain: "Pidgeot es el #018 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál es la categoría de Butterfree en la Pokédex?", correct: "Pokémon Mariposa", wrong: ["Pokémon Meteorito", "Pokémon Radiador", "Pokémon Hierro"], explain: "Butterfree es el Pokémon Mariposa." },
  { q: "¿Qué Pokémon viene justo antes de Golduck en la Pokédex Nacional?", correct: "Psyduck", wrong: ["Mankey", "Arcanine", "Alakazam"], explain: "Golduck es el #055 y Psyduck el #054." },
  { q: "¿Cuál de estos Pokémon es más liviano que Cubone?", correct: "Dratini", wrong: ["Slowbro", "Keldeo", "Spheal"], explain: "Cubone pesa 6,5 kg; Slowbro 78,5 kg, Keldeo 48,5 kg, Spheal 39,5 kg, Dratini 3,3 kg." },
  { q: "¿Qué Pokémon viene justo después de Golbat en la Pokédex Nacional?", correct: "Oddish", wrong: ["Clefable", "Charmander", "Butterfree"], explain: "Golbat es el #042 y Oddish el #043." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Escudo»?", correct: "Shieldon", wrong: ["Mesprit", "Kricketune", "Monferno"], explain: "En la Pokédex, Shieldon es el Pokémon Escudo." },
  { q: "¿Cuál es la categoría de Raikou en la Pokédex?", correct: "Pokémon Trueno", wrong: ["Pokémon Prohibido", "Pokémon Sombra", "Pokémon Fragancia"], explain: "Raikou es el Pokémon Trueno." },
  { q: "¿Cuánto mide Wailmer?", correct: "2,0 m", wrong: ["1,1 m", "3,2 m", "4,5 m"], explain: "Según la Pokédex, Wailmer mide 2,0 m y pesa 130,0 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Alargado»?", correct: "Furret", wrong: ["Tyranitar", "Natu", "Chinchou"], explain: "En la Pokédex, Furret es el Pokémon Alargado." },
  { q: "¿Cuál de estos Pokémon es más bajo que Sunflora?", correct: "Poliwag", wrong: ["Sudowoodo", "Machamp", "Raikou"], explain: "Sunflora mide 0,8 m; Raikou 1,9 m, Machamp 1,6 m, Sudowoodo 1,2 m, Poliwag 0,6 m." },
  { q: "¿Qué Pokémon viene justo después de Articuno en la Pokédex Nacional?", correct: "Zapdos", wrong: ["Snorlax", "Dratini", "Dragonair"], explain: "Articuno es el #144 y Zapdos el #145." },
  { q: "¿Cuál de estos Pokémon aparece después que Sealeo en la Pokédex Nacional?", correct: "Huntail", wrong: ["Dusclops", "Glalie", "Banette"], explain: "Sealeo es el #364; Banette #354, Dusclops #356, Glalie #362, Huntail #367." },
  { q: "¿Cuál de estos Pokémon aparece después que Wigglytuff en la Pokédex Nacional?", correct: "Venonat", wrong: ["Nidoking", "Clefairy", "Jigglypuff"], explain: "Wigglytuff es el #040; Nidoking #034, Clefairy #035, Jigglypuff #039, Venonat #048." },
  { q: "¿De qué color es Absol según la Pokédex?", correct: "Blanco", wrong: ["Azul", "Negro", "Rosa"], explain: "La Pokédex clasifica a Absol como de color blanco." },
  { q: "¿En qué región debutó Krabby?", correct: "Kanto", wrong: ["Teselia", "Alola", "Paldea"], explain: "Krabby (#098) debutó en la generación 1, la de Kanto." },
  { q: "¿En qué región debutó Pineco?", correct: "Johto", wrong: ["Paldea", "Sinnoh", "Alola"], explain: "Pineco (#204) debutó en la generación 2, la de Johto." },
  { q: "¿En qué región debutó Flaaffy?", correct: "Johto", wrong: ["Kalos", "Teselia", "Hoenn"], explain: "Flaaffy (#180) debutó en la generación 2, la de Johto." },
  { q: "¿Cuál es la categoría de Shiinotic en la Pokédex?", correct: "Pokémon Luminiscente", wrong: ["Pokémon Vigilante", "Pokémon Protostrella", "Pokémon Mosca Abeja"], explain: "Shiinotic es el Pokémon Luminiscente." },
  { q: "¿Qué número tiene Wynaut en la Pokédex Nacional?", correct: "#360", wrong: ["#345", "#366", "#354"], explain: "Wynaut es el #360 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿En qué región debutó Rapidash?", correct: "Kanto", wrong: ["Hoenn", "Alola", "Kalos"], explain: "Rapidash (#078) debutó en la generación 1, la de Kanto." },
  { q: "¿Cuánto pesa Seel?", correct: "90,0 kg", wrong: ["33,0 kg", "380,7 kg", "225,0 kg"], explain: "Según la Pokédex, Seel pesa 90,0 kg y mide 1,1 m." },
  { q: "¿Cuánto mide Weepinbell?", correct: "1,0 m", wrong: ["1,5 m", "0,4 m", "2,5 m"], explain: "Según la Pokédex, Weepinbell mide 1,0 m y pesa 6,4 kg." },
  { q: "¿Cuál de estos Pokémon es más bajo que Dusknoir?", correct: "Buneary", wrong: ["Dragonair", "Steelix", "Lugia"], explain: "Dusknoir mide 2,2 m; Steelix 9,2 m, Lugia 5,2 m, Dragonair 4,0 m, Buneary 0,4 m." },
  { q: "¿Cuánto pesa Kingdra?", correct: "152,0 kg", wrong: ["400,0 kg", "25,0 kg", "84,5 kg"], explain: "Según la Pokédex, Kingdra pesa 152,0 kg y mide 1,8 m." },
  { q: "¿Qué número tiene Enamorus en la Pokédex Nacional?", correct: "#905", wrong: ["#904", "#902", "#903"], explain: "Enamorus es el #905 de la Pokédex Nacional y debutó en Galar." },
  { q: "¿Qué Pokémon ocupa el número #317 de la Pokédex Nacional?", correct: "Swalot", wrong: ["Electrike", "Roselia", "Wailord"], explain: "Swalot es el #317; Electrike el #309, Roselia el #315, Wailord el #321." },
  { q: "¿Qué Pokémon viene justo después de Houndstone en la Pokédex Nacional?", correct: "Flamigo", wrong: ["Wo-Chien", "Dondozo", "Mabosstiff"], explain: "Houndstone es el #972 y Flamigo el #973." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Togetic?", correct: "Hoppip", wrong: ["Phione", "Jangmo-o", "Froakie"], explain: "Togetic y Hoppip debutaron en Johto; Phione de Sinnoh, Jangmo-o de Alola, Froakie de Kalos." },
  { q: "¿Qué Pokémon viene justo después de Ambipom en la Pokédex Nacional?", correct: "Drifloon", wrong: ["Gastrodon", "Buizel", "Buneary"], explain: "Ambipom es el #424 y Drifloon el #425." },
  { q: "¿Cuál de estos Pokémon es más alto que Krabby?", correct: "Mamoswine", wrong: ["Kricketot", "Chingling", "Poltchageist"], explain: "Krabby mide 0,4 m; Mamoswine 2,5 m, Kricketot 0,3 m, Chingling 0,2 m, Poltchageist 0,1 m." },
  { q: "¿Qué Pokémon ocupa el número #170 de la Pokédex Nacional?", correct: "Chinchou", wrong: ["Ampharos", "Bellossom", "Xatu"], explain: "Chinchou es el #170; Xatu el #178, Ampharos el #181, Bellossom el #182." },
  { q: "¿Cuál de estos Pokémon es más bajo que Psyduck?", correct: "Swinub", wrong: ["Manectric", "Gorebyss", "Dragonair"], explain: "Psyduck mide 0,8 m; Dragonair 4,0 m, Gorebyss 1,8 m, Manectric 1,5 m, Swinub 0,4 m." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Breloom?", correct: "Baltoy", wrong: ["Snivy", "Crobat", "Snover"], explain: "Breloom y Baltoy debutaron en Hoenn; Snivy de Teselia, Crobat de Johto, Snover de Sinnoh." },
  { q: "¿Qué Pokémon ocupa el número #028 de la Pokédex Nacional?", correct: "Sandslash", wrong: ["Nidorina", "Sandshrew", "Nidoran♀"], explain: "Sandslash es el #028; Sandshrew el #027, Nidoran♀ el #029, Nidorina el #030." },
  { q: "¿Qué Pokémon viene justo antes de Arctovish en la Pokédex Nacional?", correct: "Dracovish", wrong: ["Duraludon", "Dreepy", "Copperajah"], explain: "Arctovish es el #883 y Dracovish el #882." },
  { q: "¿Qué número tiene Roselia en la Pokédex Nacional?", correct: "#315", wrong: ["#318", "#314", "#316"], explain: "Roselia es el #315 de la Pokédex Nacional y debutó en Hoenn." },
  { q: "¿Cuál de estos Pokémon aparece después que Zapdos en la Pokédex Nacional?", correct: "Entei", wrong: ["Nidoran♂", "Jynx", "Nidoran♀"], explain: "Zapdos es el #145; Nidoran♀ #029, Nidoran♂ #032, Jynx #124, Entei #244." },
  { q: "¿Cuál de estos Pokémon aparece antes que Porygon en la Pokédex Nacional?", correct: "Voltorb", wrong: ["Mewtwo", "Corsola", "Kingdra"], explain: "Porygon es el #137; Voltorb #100, Mewtwo #150, Corsola #222, Kingdra #230." },
  { q: "¿Cuál es la categoría de Blissey en la Pokédex?", correct: "Pokémon Felicidad", wrong: ["Pokémon Ratón Agua", "Pokémon Buceo", "Pokémon Búho"], explain: "Blissey es el Pokémon Felicidad." },
  { q: "¿Qué Pokémon viene justo antes de Raikou en la Pokédex Nacional?", correct: "Blissey", wrong: ["Smeargle", "Celebi", "Granbull"], explain: "Raikou es el #243 y Blissey el #242." },
  { q: "¿Cuánto mide Clawitzer?", correct: "1,3 m", wrong: ["1,9 m", "2,9 m", "3,9 m"], explain: "Según la Pokédex, Clawitzer mide 1,3 m y pesa 35,3 kg." },
  { q: "¿Cuál es la categoría de Nidorino en la Pokédex?", correct: "Pokémon Pin Veneno", wrong: ["Pokémon Semilla", "Pokémon Serpiente", "Pokémon Eléctrico"], explain: "Nidorino es el Pokémon Pin Veneno." },
  { q: "¿Cuál de estos Pokémon aparece después que Qwilfish en la Pokédex Nacional?", correct: "Ho-Oh", wrong: ["Skiploom", "Pineco", "Lanturn"], explain: "Qwilfish es el #211; Lanturn #171, Skiploom #188, Pineco #204, Ho-Oh #250." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Ratón Agua»?", correct: "Marill", wrong: ["Qwilfish", "Ledian", "Scizor"], explain: "En la Pokédex, Marill es el Pokémon Ratón Agua." },
  { q: "¿En qué región debutó Arceus?", correct: "Sinnoh", wrong: ["Teselia", "Kanto", "Hoenn"], explain: "Arceus (#493) debutó en la generación 4, la de Sinnoh." },
  { q: "¿De qué color es Mesprit según la Pokédex?", correct: "Rosa", wrong: ["Amarillo", "Verde", "Rojo"], explain: "La Pokédex clasifica a Mesprit como de color rosa." },
  { q: "¿Cuál de estos Pokémon aparece después que Ledian en la Pokédex Nacional?", correct: "Chinchou", wrong: ["Dragonair", "Flareon", "Graveler"], explain: "Ledian es el #166; Graveler #075, Flareon #136, Dragonair #148, Chinchou #170." },
  { q: "¿Qué Pokémon ocupa el número #421 de la Pokédex Nacional?", correct: "Cherrim", wrong: ["Carnivine", "Starly", "Finneon"], explain: "Cherrim es el #421; Starly el #396, Carnivine el #455, Finneon el #456." },
  { q: "¿Cuál de estos Pokémon es más alto que Armaldo?", correct: "Houndstone", wrong: ["Burmy", "Bibarel", "Popplio"], explain: "Armaldo mide 1,5 m; Houndstone 2,0 m, Bibarel 1,0 m, Popplio 0,4 m, Burmy 0,2 m." },
  { q: "¿Cuál de estos Pokémon es más bajo que Brambleghast?", correct: "Bonsly", wrong: ["Veluza", "Ekans", "Dragonair"], explain: "Brambleghast mide 1,2 m; Dragonair 4,0 m, Veluza 2,5 m, Ekans 2,0 m, Bonsly 0,5 m." },
  { q: "¿Qué Pokémon viene justo antes de Cacturne en la Pokédex Nacional?", correct: "Cacnea", wrong: ["Swablu", "Vibrava", "Trapinch"], explain: "Cacturne es el #332 y Cacnea el #331." },
  { q: "¿En qué región debutó Wigglytuff?", correct: "Kanto", wrong: ["Johto", "Alola", "Galar"], explain: "Wigglytuff (#040) debutó en la generación 1, la de Kanto." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Nueva Especie»?", correct: "Mew", wrong: ["Stunky", "Suicune", "Budew"], explain: "En la Pokédex, Mew es el Pokémon Nueva Especie." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Delibird?", correct: "Mantine", wrong: ["Kleavor", "Metapod", "Baltoy"], explain: "Delibird y Mantine debutaron en Johto; Kleavor de Galar, Metapod de Kanto, Baltoy de Hoenn." },
  { q: "¿Cuánto pesa Ursaring?", correct: "125,8 kg", wrong: ["220,0 kg", "95,1 kg", "68,2 kg"], explain: "Según la Pokédex, Ursaring pesa 125,8 kg y mide 1,8 m." },
  { q: "¿Cuál es la categoría de Dugtrio en la Pokédex?", correct: "Pokémon Topo", wrong: ["Pokémon Tigre Gato", "Pokémon Libélula", "Pokémon Fruto Espina"], explain: "Dugtrio es el Pokémon Topo." },
  { q: "¿De qué color es Deoxys según la Pokédex?", correct: "Rojo", wrong: ["Azul", "Blanco", "Marrón"], explain: "La Pokédex clasifica a Deoxys como de color rojo." },
  { q: "¿Cuál de estos Pokémon es más bajo que Azurill?", correct: "Cutiefly", wrong: ["Machoke", "Grotle", "Nidoran♀"], explain: "Azurill mide 0,2 m; Machoke 1,5 m, Grotle 1,1 m, Nidoran♀ 0,4 m, Cutiefly 0,1 m." },
  { q: "¿Cuánto mide Lileep?", correct: "1,0 m", wrong: ["1,9 m", "1,4 m", "0,3 m"], explain: "Según la Pokédex, Lileep mide 1,0 m y pesa 23,8 kg." },
  { q: "¿De qué color es Clefable según la Pokédex?", correct: "Rosa", wrong: ["Blanco", "Gris", "Amarillo"], explain: "La Pokédex clasifica a Clefable como de color rosa." },
  { q: "¿Qué número tiene Growlithe en la Pokédex Nacional?", correct: "#058", wrong: ["#056", "#060", "#055"], explain: "Growlithe es el #058 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál de estos Pokémon es más liviano que Oddish?", correct: "Budew", wrong: ["Growlithe", "Slowbro", "Donphan"], explain: "Oddish pesa 5,4 kg; Donphan 120,0 kg, Slowbro 78,5 kg, Growlithe 19,0 kg, Budew 1,2 kg." },
  { q: "¿Cuál de estos Pokémon es más bajo que Spheal?", correct: "Smoochum", wrong: ["Ekans", "Togekiss", "Rhyperior"], explain: "Spheal mide 0,8 m; Rhyperior 2,4 m, Ekans 2,0 m, Togekiss 1,5 m, Smoochum 0,4 m." },
  { q: "¿Cuál de estos Pokémon es más alto que Exeggcute?", correct: "Luxio", wrong: ["Cleffa", "Budew", "Comfey"], explain: "Exeggcute mide 0,4 m; Luxio 0,9 m, Cleffa 0,3 m, Budew 0,2 m, Comfey 0,1 m." },
  { q: "¿Cuánto mide Celebi?", correct: "0,6 m", wrong: ["0,2 m", "1,4 m", "2,4 m"], explain: "Según la Pokédex, Celebi mide 0,6 m y pesa 5,0 kg." },
  { q: "¿Qué Pokémon ocupa el número #384 de la Pokédex Nacional?", correct: "Rayquaza", wrong: ["Kyogre", "Groudon", "Turtwig"], explain: "Rayquaza es el #384; Kyogre el #382, Groudon el #383, Turtwig el #387." },
  { q: "¿Cuál de estos Pokémon es más bajo que Cherubi?", correct: "Azurill", wrong: ["Spiritomb", "Hawlucha", "Machamp"], explain: "Cherubi mide 0,4 m; Machamp 1,6 m, Spiritomb 1,0 m, Hawlucha 0,8 m, Azurill 0,2 m." },
  { q: "¿Qué Pokémon ocupa el número #187 de la Pokédex Nacional?", correct: "Hoppip", wrong: ["Natu", "Mareep", "Murkrow"], explain: "Hoppip es el #187; Natu el #177, Mareep el #179, Murkrow el #198." },
  { q: "¿Qué Pokémon ocupa el número #325 de la Pokédex Nacional?", correct: "Spoink", wrong: ["Gorebyss", "Wurmple", "Medicham"], explain: "Spoink es el #325; Wurmple el #265, Medicham el #308, Gorebyss el #368." },
  { q: "¿Cuál de estos Pokémon es más pesado que Aerodactyl?", correct: "Dewgong", wrong: ["Grafaiai", "Wigglytuff", "Weezing"], explain: "Aerodactyl pesa 59,0 kg; Dewgong 120,0 kg, Grafaiai 27,2 kg, Wigglytuff 12,0 kg, Weezing 9,5 kg." },
  { q: "¿Qué Pokémon viene justo después de Quaxwell en la Pokédex Nacional?", correct: "Quaquaval", wrong: ["Klawf", "Toedscruel", "Stonjourner"], explain: "Quaxwell es el #913 y Quaquaval el #914." },
  { q: "¿Qué Pokémon viene justo después de Oddish en la Pokédex Nacional?", correct: "Gloom", wrong: ["Poliwag", "Magnemite", "Arbok"], explain: "Oddish es el #043 y Gloom el #044." },
  { q: "¿En qué región debutó Geodude?", correct: "Kanto", wrong: ["Teselia", "Kalos", "Galar"], explain: "Geodude (#074) debutó en la generación 1, la de Kanto." },
  { q: "¿Cuál es la categoría de Polteageist en la Pokédex?", correct: "Pokémon Té", wrong: ["Pokémon Mordisco", "Pokémon Punki", "Pokémon Jiu-Jitsu"], explain: "Polteageist es el Pokémon Té." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Cubone?", correct: "Onix", wrong: ["Trapinch", "Yungoos", "Steelix"], explain: "Cubone y Onix debutaron en Kanto; Trapinch de Hoenn, Yungoos de Alola, Steelix de Johto." },
  { q: "¿Cuál de estos Pokémon es más pesado que Pidgey?", correct: "Persian", wrong: ["Gastly", "Diglett", "Cottonee"], explain: "Pidgey pesa 1,8 kg; Persian 32,0 kg, Diglett 0,8 kg, Cottonee 0,6 kg, Gastly 0,1 kg." },
  { q: "¿Qué número tiene Raticate en la Pokédex Nacional?", correct: "#020", wrong: ["#015", "#014", "#031"], explain: "Raticate es el #020 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿En qué región debutó Golem?", correct: "Kanto", wrong: ["Galar", "Teselia", "Kalos"], explain: "Golem (#076) debutó en la generación 1, la de Kanto." },
  { q: "¿Qué número tiene Golem en la Pokédex Nacional?", correct: "#076", wrong: ["#028", "#100", "#048"], explain: "Golem es el #076 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuánto pesa Kabuto?", correct: "11,5 kg", wrong: ["52,6 kg", "6,2 kg", "26,0 kg"], explain: "Según la Pokédex, Kabuto pesa 11,5 kg y mide 0,5 m." },
  { q: "¿Qué número tiene Blissey en la Pokédex Nacional?", correct: "#242", wrong: ["#246", "#233", "#232"], explain: "Blissey es el #242 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Magcargo?", correct: "Ampharos", wrong: ["Dachsbun", "Bulbasaur", "Sableye"], explain: "Magcargo y Ampharos debutaron en Johto; Dachsbun de Paldea, Bulbasaur de Kanto, Sableye de Hoenn." },
  { q: "¿Qué número tiene Paras en la Pokédex Nacional?", correct: "#046", wrong: ["#049", "#048", "#045"], explain: "Paras es el #046 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál de estos Pokémon es más liviano que Quilava?", correct: "Squirtle", wrong: ["Hitmontop", "Smeargle", "Arceus"], explain: "Quilava pesa 19,0 kg; Arceus 320,0 kg, Smeargle 58,0 kg, Hitmontop 48,0 kg, Squirtle 9,0 kg." },
  { q: "¿Cuánto pesa Beartic?", correct: "260,0 kg", wrong: ["71,5 kg", "39,5 kg", "125,0 kg"], explain: "Según la Pokédex, Beartic pesa 260,0 kg y mide 2,6 m." },
  { q: "¿Cuál es la categoría de Miltank en la Pokédex?", correct: "Pokémon Lechera", wrong: ["Pokémon Reparto", "Pokémon Coraza Ave", "Pokémon Boca Abajo"], explain: "Miltank es el Pokémon Lechera." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Luz»?", correct: "Ampharos", wrong: ["Finneon", "Deoxys", "Tyrogue"], explain: "En la Pokédex, Ampharos es el Pokémon Luz." },
  { q: "¿Cuánto mide Gastly?", correct: "1,3 m", wrong: ["2,2 m", "5,2 m", "0,4 m"], explain: "Según la Pokédex, Gastly mide 1,3 m y pesa 0,1 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Rana»?", correct: "Politoed", wrong: ["Teddiursa", "Ampharos", "Raikou"], explain: "En la Pokédex, Politoed es el Pokémon Rana." },
  { q: "¿Qué Pokémon viene justo después de Latias en la Pokédex Nacional?", correct: "Latios", wrong: ["Bidoof", "Deoxys", "Gorebyss"], explain: "Latias es el #380 y Latios el #381." },
  { q: "¿Cuál de estos Pokémon aparece antes que Stantler en la Pokédex Nacional?", correct: "Totodile", wrong: ["Grumpig", "Swablu", "Grovyle"], explain: "Stantler es el #234; Totodile #158, Grovyle #253, Grumpig #326, Swablu #333." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Swinub?", correct: "Cyndaquil", wrong: ["Clefable", "Minun", "Zamazenta"], explain: "Swinub y Cyndaquil debutaron en Johto; Clefable de Kanto, Minun de Hoenn, Zamazenta de Galar." },
  { q: "¿Cuál es la categoría de Castform en la Pokédex?", correct: "Pokémon Clima", wrong: ["Pokémon Generador", "Pokémon Púgil", "Pokémon Imán"], explain: "Castform es el Pokémon Clima." },
  { q: "¿Qué número tiene Larvitar en la Pokédex Nacional?", correct: "#246", wrong: ["#227", "#297", "#319"], explain: "Larvitar es el #246 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Serpiente Tierra»?", correct: "Dunsparce", wrong: ["Magby", "Smoochum", "Natu"], explain: "En la Pokédex, Dunsparce es el Pokémon Serpiente Tierra." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Horsea?", correct: "Nidoran♀", wrong: ["Tyrogue", "Shellos", "Corphish"], explain: "Horsea y Nidoran♀ debutaron en Kanto; Tyrogue de Johto, Shellos de Sinnoh, Corphish de Hoenn." },
  { q: "¿Cuánto mide Rayquaza?", correct: "7,0 m", wrong: ["2,4 m", "3,8 m", "5,2 m"], explain: "Según la Pokédex, Rayquaza mide 7,0 m y pesa 206,5 kg." },
  { q: "¿Cuánto pesa Grovyle?", correct: "21,6 kg", wrong: ["4,8 kg", "52,2 kg", "12,4 kg"], explain: "Según la Pokédex, Grovyle pesa 21,6 kg y mide 0,9 m." },
  { q: "¿De qué color es Vulpix según la Pokédex?", correct: "Marrón", wrong: ["Blanco", "Amarillo", "Gris"], explain: "La Pokédex clasifica a Vulpix como de color marrón." },
  { q: "¿Qué número tiene Hippopotas en la Pokédex Nacional?", correct: "#449", wrong: ["#444", "#443", "#438"], explain: "Hippopotas es el #449 de la Pokédex Nacional y debutó en Sinnoh." },
  { q: "¿Qué Pokémon viene justo después de Guzzlord en la Pokédex Nacional?", correct: "Necrozma", wrong: ["Meltan", "Passimian", "Mimikyu"], explain: "Guzzlord es el #799 y Necrozma el #800." },
  { q: "¿Cuánto pesa Leafeon?", correct: "25,5 kg", wrong: ["34,0 kg", "76,5 kg", "21,6 kg"], explain: "Según la Pokédex, Leafeon pesa 25,5 kg y mide 1,0 m." },
  { q: "¿Cuánto pesa Regice?", correct: "175,0 kg", wrong: ["333,6 kg", "40,6 kg", "81,9 kg"], explain: "Según la Pokédex, Regice pesa 175,0 kg y mide 1,8 m." },
  { q: "¿Cuál de estos Pokémon aparece después que Dialga en la Pokédex Nacional?", correct: "Giratina", wrong: ["Probopass", "Registeel", "Gible"], explain: "Dialga es el #483; Registeel #379, Gible #443, Probopass #476, Giratina #487." },
  { q: "¿Cuánto mide Morelull?", correct: "0,2 m", wrong: ["0,1 m", "0,6 m", "0,4 m"], explain: "Según la Pokédex, Morelull mide 0,2 m y pesa 1,5 kg." },
  { q: "¿Cuánto mide Arboliva?", correct: "1,4 m", wrong: ["3,4 m", "6,5 m", "0,8 m"], explain: "Según la Pokédex, Arboliva mide 1,4 m y pesa 48,2 kg." },
  { q: "¿Cuánto mide Hitmonchan?", correct: "1,4 m", wrong: ["6,2 m", "2,7 m", "0,6 m"], explain: "Según la Pokédex, Hitmonchan mide 1,4 m y pesa 50,2 kg." },
  { q: "¿Qué Pokémon ocupa el número #311 de la Pokédex Nacional?", correct: "Plusle", wrong: ["Slakoth", "Lileep", "Luvdisc"], explain: "Plusle es el #311; Slakoth el #287, Lileep el #345, Luvdisc el #370." },
  { q: "¿Cuánto mide Miltank?", correct: "1,2 m", wrong: ["5,2 m", "0,5 m", "2,9 m"], explain: "Según la Pokédex, Miltank mide 1,2 m y pesa 75,5 kg." },
  { q: "¿Cuál de estos Pokémon es más pesado que Lickitung?", correct: "Glalie", wrong: ["Victreebel", "Kricketune", "Rolycoly"], explain: "Lickitung pesa 65,5 kg; Glalie 256,5 kg, Kricketune 25,5 kg, Victreebel 15,5 kg, Rolycoly 12,0 kg." },
  { q: "¿En qué región debutó Mismagius?", correct: "Sinnoh", wrong: ["Paldea", "Alola", "Teselia"], explain: "Mismagius (#429) debutó en la generación 4, la de Sinnoh." },
  { q: "¿Qué Pokémon viene justo antes de Cetoddle en la Pokédex Nacional?", correct: "Flamigo", wrong: ["Cetitan", "Dondozo", "Greavard"], explain: "Cetoddle es el #974 y Flamigo el #973." },
  { q: "¿Cuál de estos Pokémon es más alto que Sneasel?", correct: "Dewgong", wrong: ["Geodude", "Flittle", "Cottonee"], explain: "Sneasel mide 0,9 m; Dewgong 1,7 m, Geodude 0,4 m, Cottonee 0,3 m, Flittle 0,2 m." },
  { q: "¿Cuánto mide Voltorb?", correct: "0,5 m", wrong: ["1,5 m", "0,7 m", "1,1 m"], explain: "Según la Pokédex, Voltorb mide 0,5 m y pesa 10,4 kg." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Hoothoot?", correct: "Slowking", wrong: ["Snorlax", "Grumpig", "Snover"], explain: "Hoothoot y Slowking debutaron en Johto; Snorlax de Kanto, Grumpig de Hoenn, Snover de Sinnoh." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Tundra»?", correct: "Aurorus", wrong: ["Aegislash", "Chesnaught", "Tyrantrum"], explain: "En la Pokédex, Aurorus es el Pokémon Tundra." },
  { q: "¿Cuánto pesa Nuzleaf?", correct: "28,0 kg", wrong: ["111,0 kg", "58,5 kg", "16,5 kg"], explain: "Según la Pokédex, Nuzleaf pesa 28,0 kg y mide 1,0 m." },
  { q: "¿Cuál es la categoría de Ekans en la Pokédex?", correct: "Pokémon Serpiente", wrong: ["Pokémon Dragón", "Pokémon Insecto", "Pokémon Hierbajo"], explain: "Ekans es el Pokémon Serpiente." },
  { q: "¿En qué región debutó Sableye?", correct: "Hoenn", wrong: ["Alola", "Paldea", "Kanto"], explain: "Sableye (#302) debutó en la generación 3, la de Hoenn." },
  { q: "¿Qué Pokémon ocupa el número #169 de la Pokédex Nacional?", correct: "Crobat", wrong: ["Spinarak", "Lanturn", "Feraligatr"], explain: "Crobat es el #169; Feraligatr el #160, Spinarak el #167, Lanturn el #171." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Bolsa Basura»?", correct: "Trubbish", wrong: ["Stoutland", "Venipede", "Pawniard"], explain: "En la Pokédex, Trubbish es el Pokémon Bolsa Basura." },
  { q: "¿En qué región debutó Gyarados?", correct: "Kanto", wrong: ["Galar", "Hoenn", "Sinnoh"], explain: "Gyarados (#130) debutó en la generación 1, la de Kanto." },
  { q: "¿Cuál de estos Pokémon es más liviano que Swinub?", correct: "Pachirisu", wrong: ["Girafarig", "Tentacruel", "Ninetales"], explain: "Swinub pesa 6,5 kg; Tentacruel 55,0 kg, Girafarig 41,5 kg, Ninetales 19,9 kg, Pachirisu 3,9 kg." },
  { q: "¿En qué región debutó Reptalada?", correct: "Paldea", wrong: ["Alola", "Kanto", "Hoenn"], explain: "Reptalada (#988) debutó en la generación 9, la de Paldea." },
  { q: "¿Cuánto pesa Medicham?", correct: "31,5 kg", wrong: ["18,0 kg", "24,0 kg", "61,9 kg"], explain: "Según la Pokédex, Medicham pesa 31,5 kg y mide 1,3 m." },
  { q: "¿Cuánto mide Togekiss?", correct: "1,5 m", wrong: ["2,6 m", "2,0 m", "1,2 m"], explain: "Según la Pokédex, Togekiss mide 1,5 m y pesa 38,0 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Hierba»?", correct: "Meganium", wrong: ["Tauros", "Xatu", "Mantyke"], explain: "En la Pokédex, Meganium es el Pokémon Hierba." },
  { q: "¿Cuánto pesa Slowpoke?", correct: "36,0 kg", wrong: ["65,0 kg", "26,6 kg", "88,8 kg"], explain: "Según la Pokédex, Slowpoke pesa 36,0 kg y mide 1,2 m." },
  { q: "¿Qué Pokémon ocupa el número #305 de la Pokédex Nacional?", correct: "Lairon", wrong: ["Ludicolo", "Swalot", "Dusclops"], explain: "Lairon es el #305; Ludicolo el #272, Swalot el #317, Dusclops el #356." },
  { q: "¿Cuál de estos Pokémon aparece después que Ninjask en la Pokédex Nacional?", correct: "Crawdaunt", wrong: ["Wingull", "Larvitar", "Magby"], explain: "Ninjask es el #291; Magby #240, Larvitar #246, Wingull #278, Crawdaunt #342." },
  { q: "¿Cuál de estos Pokémon es más bajo que Toxicroak?", correct: "Shaymin", wrong: ["Orthworm", "Solgaleo", "Kyogre"], explain: "Toxicroak mide 1,3 m; Kyogre 4,5 m, Solgaleo 3,4 m, Orthworm 2,5 m, Shaymin 0,2 m." },
  { q: "¿Qué número tiene Sprigatito en la Pokédex Nacional?", correct: "#906", wrong: ["#837", "#881", "#986"], explain: "Sprigatito es el #906 de la Pokédex Nacional y debutó en Paldea." },
  { q: "¿Cuál es la categoría de Aggron en la Pokédex?", correct: "Pokémon Coraza Férrea", wrong: ["Pokémon Calambre", "Pokémon Bivalvo", "Pokémon Astuto"], explain: "Aggron es el Pokémon Coraza Férrea." },
  { q: "¿En qué región debutó Sudowoodo?", correct: "Johto", wrong: ["Kanto", "Sinnoh", "Hoenn"], explain: "Sudowoodo (#185) debutó en la generación 2, la de Johto." },
  { q: "¿Cuánto mide Mantine?", correct: "2,1 m", wrong: ["1,0 m", "5,5 m", "0,4 m"], explain: "Según la Pokédex, Mantine mide 2,1 m y pesa 220,0 kg." },
  { q: "¿Cuál es la categoría de Latias en la Pokédex?", correct: "Pokémon Eón", wrong: ["Pokémon Catástrofe", "Pokémon Escucha", "Pokémon Colmena"], explain: "Latias es el Pokémon Eón." },
  { q: "¿En qué región debutó Glalie?", correct: "Hoenn", wrong: ["Paldea", "Kanto", "Galar"], explain: "Glalie (#362) debutó en la generación 3, la de Hoenn." },
  { q: "¿Qué Pokémon ocupa el número #493 de la Pokédex Nacional?", correct: "Arceus", wrong: ["Skorupi", "Swoobat", "Hippopotas"], explain: "Arceus es el #493; Hippopotas el #449, Skorupi el #451, Swoobat el #528." },
  { q: "¿Cuánto mide Feraligatr?", correct: "2,3 m", wrong: ["1,7 m", "1,0 m", "3,7 m"], explain: "Según la Pokédex, Feraligatr mide 2,3 m y pesa 88,8 kg." },
  { q: "¿En qué región debutó Dewgong?", correct: "Kanto", wrong: ["Kalos", "Paldea", "Johto"], explain: "Dewgong (#087) debutó en la generación 1, la de Kanto." },
  { q: "¿Cuál de estos Pokémon es más bajo que Charcadet?", correct: "Terapagos", wrong: ["Yanmega", "Jynx", "Omastar"], explain: "Charcadet mide 0,6 m; Yanmega 1,9 m, Jynx 1,4 m, Omastar 1,0 m, Terapagos 0,2 m." },
  { q: "¿De qué color es Skorupi según la Pokédex?", correct: "Morado", wrong: ["Amarillo", "Azul", "Verde"], explain: "La Pokédex clasifica a Skorupi como de color morado." },
  { q: "¿Cuánto pesa Pidove?", correct: "2,1 kg", wrong: ["8,0 kg", "0,5 kg", "4,5 kg"], explain: "Según la Pokédex, Pidove pesa 2,1 kg y mide 0,3 m." },
  { q: "¿Cuánto mide Roserade?", correct: "0,9 m", wrong: ["5,4 m", "0,2 m", "1,9 m"], explain: "Según la Pokédex, Roserade mide 0,9 m y pesa 14,5 kg." },
  { q: "¿Cuál de estos Pokémon es más pesado que Smoochum?", correct: "Dewgong", wrong: ["Togetic", "Gastly", "Shedinja"], explain: "Smoochum pesa 6,0 kg; Dewgong 120,0 kg, Togetic 3,2 kg, Shedinja 1,2 kg, Gastly 0,1 kg." },
  { q: "¿Cuál de estos Pokémon aparece antes que Spearow en la Pokédex Nacional?", correct: "Ivysaur", wrong: ["Wigglytuff", "Venomoth", "Vulpix"], explain: "Spearow es el #021; Ivysaur #002, Vulpix #037, Wigglytuff #040, Venomoth #049." },
  { q: "¿Cuál de estos Pokémon es más liviano que Hippowdon?", correct: "Staravia", wrong: ["Groudon", "Metagross", "Giratina"], explain: "Hippowdon pesa 300,0 kg; Groudon 950,0 kg, Giratina 750,0 kg, Metagross 550,0 kg, Staravia 15,5 kg." },
  { q: "¿Qué Pokémon viene justo antes de Probopass en la Pokédex Nacional?", correct: "Gallade", wrong: ["Dusknoir", "Togekiss", "Gliscor"], explain: "Probopass es el #476 y Gallade el #475." },
  { q: "¿De qué color es Delibird según la Pokédex?", correct: "Rojo", wrong: ["Gris", "Negro", "Morado"], explain: "La Pokédex clasifica a Delibird como de color rojo." },
  { q: "¿Cuánto mide Latios?", correct: "2,0 m", wrong: ["4,5 m", "0,5 m", "0,9 m"], explain: "Según la Pokédex, Latios mide 2,0 m y pesa 60,0 kg." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Blissey?", correct: "Slugma", wrong: ["Dugtrio", "Dragapult", "Reuniclus"], explain: "Blissey y Slugma debutaron en Johto; Dugtrio de Kanto, Dragapult de Galar, Reuniclus de Teselia." },
  { q: "¿De qué color es Torchic según la Pokédex?", correct: "Rojo", wrong: ["Verde", "Gris", "Azul"], explain: "La Pokédex clasifica a Torchic como de color rojo." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Llameante»?", correct: "Blaziken", wrong: ["Sealeo", "Swalot", "Relicanth"], explain: "En la Pokédex, Blaziken es el Pokémon Llameante." },
  { q: "¿Qué Pokémon ocupa el número #226 de la Pokédex Nacional?", correct: "Mantine", wrong: ["Porygon2", "Gligar", "Pupitar"], explain: "Mantine es el #226; Gligar el #207, Porygon2 el #233, Pupitar el #247." },
  { q: "¿En qué región debutó Absol?", correct: "Hoenn", wrong: ["Teselia", "Galar", "Paldea"], explain: "Absol (#359) debutó en la generación 3, la de Hoenn." },
  { q: "¿Cuál es la categoría de Cleffa en la Pokédex?", correct: "Pokémon Estrella", wrong: ["Pokémon Pajarito", "Pokémon Luz", "Pokémon Peleón"], explain: "Cleffa es el Pokémon Estrella." },
  { q: "¿Cuál de estos Pokémon es más pesado que Butterfree?", correct: "Turtonator", wrong: ["Pichu", "Steenee", "Tranquill"], explain: "Butterfree pesa 32,0 kg; Turtonator 212,0 kg, Tranquill 15,0 kg, Steenee 8,2 kg, Pichu 2,0 kg." },
  { q: "¿Cuál de estos Pokémon aparece antes que Delcatty en la Pokédex Nacional?", correct: "Mightyena", wrong: ["Altaria", "Carvanha", "Cacturne"], explain: "Delcatty es el #301; Mightyena #262, Carvanha #318, Cacturne #332, Altaria #334." },
  { q: "¿Qué Pokémon ocupa el número #027 de la Pokédex Nacional?", correct: "Sandshrew", wrong: ["Vulpix", "Pikachu", "Pidgeotto"], explain: "Sandshrew es el #027; Pidgeotto el #017, Pikachu el #025, Vulpix el #037." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Mapachito»?", correct: "Zigzagoon", wrong: ["Spoink", "Breloom", "Cascoon"], explain: "En la Pokédex, Zigzagoon es el Pokémon Mapachito." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Hibernante»?", correct: "Ursaring", wrong: ["Tangrowth", "Deoxys", "Rhydon"], explain: "En la Pokédex, Ursaring es el Pokémon Hibernante." },
  { q: "¿Qué número tiene Natu en la Pokédex Nacional?", correct: "#177", wrong: ["#184", "#189", "#171"], explain: "Natu es el #177 de la Pokédex Nacional y debutó en Johto." },
  { q: "¿Qué Pokémon viene justo después de Wooper en la Pokédex Nacional?", correct: "Quagsire", wrong: ["Magcargo", "Sentret", "Shuckle"], explain: "Wooper es el #194 y Quagsire el #195." },
  { q: "¿Qué número tiene Gliscor en la Pokédex Nacional?", correct: "#472", wrong: ["#428", "#501", "#460"], explain: "Gliscor es el #472 de la Pokédex Nacional y debutó en Sinnoh." },
  { q: "¿Cuánto pesa Finneon?", correct: "7,0 kg", wrong: ["2,8 kg", "5,1 kg", "14,9 kg"], explain: "Según la Pokédex, Finneon pesa 7,0 kg y mide 0,4 m." },
  { q: "¿Cuál de estos Pokémon es más alto que Araquanid?", correct: "Wailord", wrong: ["Lampent", "Masquerain", "Sunkern"], explain: "Araquanid mide 1,8 m; Wailord 14,5 m, Masquerain 0,8 m, Lampent 0,6 m, Sunkern 0,3 m." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Skarmory?", correct: "Octillery", wrong: ["Drowzee", "Claydol", "Glameow"], explain: "Skarmory y Octillery debutaron en Johto; Drowzee de Kanto, Claydol de Hoenn, Glameow de Sinnoh." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Gato Araña»?", correct: "Meowth", wrong: ["Arcanine", "Mamoswine", "Magnemite"], explain: "En la Pokédex, Meowth es el Pokémon Gato Araña." },
  { q: "¿Cuál de estos Pokémon es más alto que Voltorb?", correct: "Alakazam", wrong: ["Morpeko", "Natu", "Torchic"], explain: "Voltorb mide 0,5 m; Alakazam 1,5 m, Torchic 0,4 m, Morpeko 0,3 m, Natu 0,2 m." },
  { q: "¿Cuál de estos Pokémon es más liviano que Larvitar?", correct: "Yanma", wrong: ["Mewtwo", "Bastiodon", "Makuhita"], explain: "Larvitar pesa 72,0 kg; Bastiodon 149,5 kg, Mewtwo 122,0 kg, Makuhita 86,4 kg, Yanma 38,0 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Sensible»?", correct: "Ralts", wrong: ["Mankey", "Geodude", "Starmie"], explain: "En la Pokédex, Ralts es el Pokémon Sensible." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Feroz»?", correct: "Carvanha", wrong: ["Lapras", "Castform", "Dustox"], explain: "En la Pokédex, Carvanha es el Pokémon Feroz." },
  { q: "¿Cuál de estos Pokémon es más alto que Marshtomp?", correct: "Mantine", wrong: ["Pachirisu", "Jirachi", "Unown"], explain: "Marshtomp mide 0,7 m; Mantine 2,1 m, Unown 0,5 m, Pachirisu 0,4 m, Jirachi 0,3 m." },
  { q: "¿Qué Pokémon ocupa el número #379 de la Pokédex Nacional?", correct: "Registeel", wrong: ["Torterra", "Rampardos", "Chimchar"], explain: "Registeel es el #379; Torterra el #389, Chimchar el #390, Rampardos el #409." },
  { q: "¿Qué número tiene Bruxish en la Pokédex Nacional?", correct: "#779", wrong: ["#820", "#703", "#747"], explain: "Bruxish es el #779 de la Pokédex Nacional y debutó en Alola." },
  { q: "¿Cuánto mide Escavalier?", correct: "1,0 m", wrong: ["1,9 m", "0,6 m", "0,3 m"], explain: "Según la Pokédex, Escavalier mide 1,0 m y pesa 33,0 kg." },
  { q: "¿Qué número tiene Pinsir en la Pokédex Nacional?", correct: "#127", wrong: ["#116", "#134", "#142"], explain: "Pinsir es el #127 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Qué Pokémon ocupa el número #056 de la Pokédex Nacional?", correct: "Mankey", wrong: ["Muk", "Pidgeotto", "Vileplume"], explain: "Mankey es el #056; Pidgeotto el #017, Vileplume el #045, Muk el #089." },
  { q: "¿Cuánto mide Politoed?", correct: "1,1 m", wrong: ["0,3 m", "2,4 m", "4,5 m"], explain: "Según la Pokédex, Politoed mide 1,1 m y pesa 33,9 kg." },
  { q: "¿Cuál es la categoría de Anorith en la Pokédex?", correct: "Pokémon Camarón", wrong: ["Pokémon Ninja", "Pokémon Morasombra", "Pokémon Chillón"], explain: "Anorith es el Pokémon Camarón." },
  { q: "¿Qué Pokémon viene justo después de Bellsprout en la Pokédex Nacional?", correct: "Weepinbell", wrong: ["Clefable", "Meowth", "Hitmonchan"], explain: "Bellsprout es el #069 y Weepinbell el #070." },
  { q: "¿Qué número tiene Haunter en la Pokédex Nacional?", correct: "#093", wrong: ["#075", "#152", "#054"], explain: "Haunter es el #093 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál de estos Pokémon aparece después que Haxorus en la Pokédex Nacional?", correct: "Trumbeak", wrong: ["Zoroark", "Vanillite", "Snivy"], explain: "Haxorus es el #612; Snivy #495, Zoroark #571, Vanillite #582, Trumbeak #732." },
  { q: "¿Qué Pokémon ocupa el número #426 de la Pokédex Nacional?", correct: "Drifblim", wrong: ["Ambipom", "Gastrodon", "Bronzor"], explain: "Drifblim es el #426; Gastrodon el #423, Ambipom el #424, Bronzor el #436." },
  { q: "¿Cuál de estos Pokémon es más alto que Staravia?", correct: "Hypno", wrong: ["Eevee", "Natu", "Cutiefly"], explain: "Staravia mide 0,6 m; Hypno 1,6 m, Eevee 0,3 m, Natu 0,2 m, Cutiefly 0,1 m." },
  { q: "¿Cuánto mide Dugtrio?", correct: "0,7 m", wrong: ["1,1 m", "0,5 m", "0,9 m"], explain: "Según la Pokédex, Dugtrio mide 0,7 m y pesa 33,3 kg." },
  { q: "¿Cuál de estos Pokémon es más liviano que Misdreavus?", correct: "Haunter", wrong: ["Skarmory", "Nidorina", "Fraxure"], explain: "Misdreavus pesa 1,0 kg; Skarmory 50,5 kg, Fraxure 36,0 kg, Nidorina 20,0 kg, Haunter 0,1 kg." },
  { q: "¿Cuál es la categoría de Vulpix en la Pokédex?", correct: "Pokémon Zorro", wrong: ["Pokémon Simiestro", "Pokémon Erupción", "Pokémon Solitario"], explain: "Vulpix es el Pokémon Zorro." },
  { q: "¿Qué Pokémon ocupa el número #808 de la Pokédex Nacional?", correct: "Meltan", wrong: ["Toxel", "Magearna", "Buzzwole"], explain: "Meltan es el #808; Buzzwole el #794, Magearna el #801, Toxel el #848." },
  { q: "¿Cuánto mide Heracross?", correct: "1,5 m", wrong: ["8,8 m", "2,8 m", "0,5 m"], explain: "Según la Pokédex, Heracross mide 1,5 m y pesa 54,0 kg." },
  { q: "¿Cuál de estos Pokémon aparece después que Skeledirge en la Pokédex Nacional?", correct: "Nacli", wrong: ["Stonjourner", "Kleavor", "Regieleki"], explain: "Skeledirge es el #911; Stonjourner #874, Regieleki #894, Kleavor #900, Nacli #932." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Pata Larga»?", correct: "Ariados", wrong: ["Sharpedo", "Relicanth", "Forretress"], explain: "En la Pokédex, Ariados es el Pokémon Pata Larga." },
  { q: "¿Cuál de estos Pokémon es más pesado que Kabutops?", correct: "Veluza", wrong: ["Pineco", "Vulpix", "Wigglytuff"], explain: "Kabutops pesa 40,5 kg; Veluza 90,0 kg, Wigglytuff 12,0 kg, Vulpix 9,9 kg, Pineco 7,2 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Mariposa»?", correct: "Beautifly", wrong: ["Elekid", "Solrock", "Clefable"], explain: "En la Pokédex, Beautifly es el Pokémon Mariposa." },
  { q: "¿Qué Pokémon viene justo después de Tangela en la Pokédex Nacional?", correct: "Kangaskhan", wrong: ["Electabuzz", "Porygon", "Starmie"], explain: "Tangela es el #114 y Kangaskhan el #115." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Broncefante»?", correct: "Cufant", wrong: ["Flapple", "Obstagoon", "Drednaw"], explain: "En la Pokédex, Cufant es el Pokémon Broncefante." },
  { q: "¿Cuánto pesa Drifblim?", correct: "15,0 kg", wrong: ["54,5 kg", "2,8 kg", "9,0 kg"], explain: "Según la Pokédex, Drifblim pesa 15,0 kg y mide 1,2 m." },
  { q: "¿Qué Pokémon viene justo después de Bagon en la Pokédex Nacional?", correct: "Shelgon", wrong: ["Tropius", "Grotle", "Zangoose"], explain: "Bagon es el #371 y Shelgon el #372." },
  { q: "¿Qué número tiene Flareon en la Pokédex Nacional?", correct: "#136", wrong: ["#175", "#087", "#094"], explain: "Flareon es el #136 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿En qué región debutó Eternatus?", correct: "Galar", wrong: ["Sinnoh", "Paldea", "Kanto"], explain: "Eternatus (#890) debutó en la generación 8, la de Galar." },
  { q: "¿Qué Pokémon ocupa el número #022 de la Pokédex Nacional?", correct: "Fearow", wrong: ["Slowbro", "Mankey", "Zubat"], explain: "Fearow es el #022; Zubat el #041, Mankey el #056, Slowbro el #080." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Chatot?", correct: "Gliscor", wrong: ["Koraidon", "Flaaffy", "Bagon"], explain: "Chatot y Gliscor debutaron en Sinnoh; Koraidon de Paldea, Flaaffy de Johto, Bagon de Hoenn." },
  { q: "¿Qué número tiene Gengar en la Pokédex Nacional?", correct: "#094", wrong: ["#104", "#109", "#086"], explain: "Gengar es el #094 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuál es la categoría de Minun en la Pokédex?", correct: "Pokémon Ánimo", wrong: ["Pokémon Hongo", "Pokémon Tramposo", "Pokémon Dragón"], explain: "Minun es el Pokémon Ánimo." },
  { q: "¿De qué color es Hippopotas según la Pokédex?", correct: "Marrón", wrong: ["Negro", "Morado", "Blanco"], explain: "La Pokédex clasifica a Hippopotas como de color marrón." },
  { q: "¿Cuál de estos Pokémon es más bajo que Weavile?", correct: "Unown", wrong: ["Mamoswine", "Gyarados", "Spectrier"], explain: "Weavile mide 1,1 m; Gyarados 6,5 m, Mamoswine 2,5 m, Spectrier 2,0 m, Unown 0,5 m." },
  { q: "¿Qué Pokémon ocupa el número #183 de la Pokédex Nacional?", correct: "Marill", wrong: ["Mew", "Electabuzz", "Omastar"], explain: "Marill es el #183; Electabuzz el #125, Omastar el #139, Mew el #151." },
  { q: "¿Cuánto pesa Marill?", correct: "8,5 kg", wrong: ["6,3 kg", "13,3 kg", "16,5 kg"], explain: "Según la Pokédex, Marill pesa 8,5 kg y mide 0,4 m." },
  { q: "¿En qué región debutó Luxio?", correct: "Sinnoh", wrong: ["Teselia", "Kanto", "Kalos"], explain: "Luxio (#404) debutó en la generación 4, la de Sinnoh." },
  { q: "¿Qué Pokémon ocupa el número #386 de la Pokédex Nacional?", correct: "Deoxys", wrong: ["Munchlax", "Relicanth", "Chingling"], explain: "Deoxys es el #386; Relicanth el #369, Chingling el #433, Munchlax el #446." },
  { q: "¿Cuál de estos Pokémon aparece después que Skarmory en la Pokédex Nacional?", correct: "Breloom", wrong: ["Aipom", "Hitmonchan", "Steelix"], explain: "Skarmory es el #227; Hitmonchan #107, Aipom #190, Steelix #208, Breloom #286." },
  { q: "¿Cuál de estos Pokémon es más liviano que Hitmonchan?", correct: "Nidorina", wrong: ["Tyrantrum", "Metagross", "Wailmer"], explain: "Hitmonchan pesa 50,2 kg; Metagross 550,0 kg, Tyrantrum 270,0 kg, Wailmer 130,0 kg, Nidorina 20,0 kg." },
  { q: "¿Cuál de estos Pokémon es más bajo que Cyndaquil?", correct: "Pichu", wrong: ["Lickitung", "Kangaskhan", "Alakazam"], explain: "Cyndaquil mide 0,5 m; Kangaskhan 2,2 m, Alakazam 1,5 m, Lickitung 1,2 m, Pichu 0,3 m." },
  { q: "¿Cuál de estos Pokémon es más pesado que Magnezone?", correct: "Regigigas", wrong: ["Forretress", "Tropius", "Yanmega"], explain: "Magnezone pesa 180,0 kg; Regigigas 420,0 kg, Forretress 125,8 kg, Tropius 100,0 kg, Yanmega 51,5 kg." },
  { q: "¿Cuánto pesa Luvdisc?", correct: "8,7 kg", wrong: ["10,5 kg", "5,1 kg", "6,5 kg"], explain: "Según la Pokédex, Luvdisc pesa 8,7 kg y mide 0,6 m." },
  { q: "¿Cuál de estos Pokémon es más liviano que Grafaiai?", correct: "Pancham", wrong: ["Torkoal", "Electivire", "Kyurem"], explain: "Grafaiai pesa 27,2 kg; Kyurem 325,0 kg, Electivire 138,6 kg, Torkoal 80,4 kg, Pancham 8,0 kg." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Lanturn?", correct: "Blissey", wrong: ["Arcanine", "Illumise", "Kilowattrel"], explain: "Lanturn y Blissey debutaron en Johto; Arcanine de Kanto, Illumise de Hoenn, Kilowattrel de Paldea." },
  { q: "¿Cuánto mide Seadra?", correct: "1,2 m", wrong: ["3,0 m", "5,5 m", "0,7 m"], explain: "Según la Pokédex, Seadra mide 1,2 m y pesa 25,0 kg." },
  { q: "¿Qué número tiene Rapidash en la Pokédex Nacional?", correct: "#078", wrong: ["#074", "#083", "#082"], explain: "Rapidash es el #078 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Qué Pokémon viene justo después de Omastar en la Pokédex Nacional?", correct: "Kabuto", wrong: ["Sentret", "Moltres", "Togepi"], explain: "Omastar es el #139 y Kabuto el #140." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Resistencia»?", correct: "Shelgon", wrong: ["Barboach", "Combusken", "Breloom"], explain: "En la Pokédex, Shelgon es el Pokémon Resistencia." },
  { q: "¿Cuál es la categoría de Elgyem en la Pokédex?", correct: "Pokémon Cerebro", wrong: ["Pokémon Lagartija", "Pokémon Valiente", "Pokémon Vínculo"], explain: "Elgyem es el Pokémon Cerebro." },
  { q: "¿Cuánto pesa Clefairy?", correct: "7,5 kg", wrong: ["18,6 kg", "34,3 kg", "4,0 kg"], explain: "Según la Pokédex, Clefairy pesa 7,5 kg y mide 0,6 m." },
  { q: "¿Cuál es la categoría de Squirtle en la Pokédex?", correct: "Pokémon Tortuguita", wrong: ["Pokémon Mantis", "Pokémon Campana Bronce", "Pokémon Ciempiés"], explain: "Squirtle es el Pokémon Tortuguita." },
  { q: "¿Cuánto pesa Slowbro?", correct: "78,5 kg", wrong: ["22,6 kg", "38,6 kg", "11,9 kg"], explain: "Según la Pokédex, Slowbro pesa 78,5 kg y mide 1,6 m." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Tentacool?", correct: "Moltres", wrong: ["Fletchinder", "Solrock", "Guzzlord"], explain: "Tentacool y Moltres debutaron en Kanto; Fletchinder de Kalos, Solrock de Hoenn, Guzzlord de Alola." },
  { q: "¿Cuál de estos Pokémon es más alto que Girafarig?", correct: "Regidrago", wrong: ["Chansey", "Combusken", "Caterpie"], explain: "Girafarig mide 1,5 m; Regidrago 2,1 m, Chansey 1,1 m, Combusken 0,9 m, Caterpie 0,3 m." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Haunter?", correct: "Gastly", wrong: ["Electivire", "Torkoal", "Sneasel"], explain: "Haunter y Gastly debutaron en Kanto; Electivire de Sinnoh, Torkoal de Hoenn, Sneasel de Johto." },
  { q: "¿Qué número tiene Sandslash en la Pokédex Nacional?", correct: "#028", wrong: ["#039", "#033", "#025"], explain: "Sandslash es el #028 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Qué Pokémon ocupa el número #394 de la Pokédex Nacional?", correct: "Prinplup", wrong: ["Empoleon", "Infernape", "Staravia"], explain: "Prinplup es el #394; Infernape el #392, Empoleon el #395, Staravia el #397." },
  { q: "¿Qué Pokémon ocupa el número #121 de la Pokédex Nacional?", correct: "Starmie", wrong: ["Mr. Mime", "Scyther", "Seaking"], explain: "Starmie es el #121; Seaking el #119, Mr. Mime el #122, Scyther el #123." },
  { q: "¿Cuál es la categoría de Espeon en la Pokédex?", correct: "Pokémon Sol", wrong: ["Pokémon Prisma", "Pokémon Ramillete", "Pokémon Doscolmillos"], explain: "Espeon es el Pokémon Sol." },
  { q: "¿Cuál de estos Pokémon aparece después que Magby en la Pokédex Nacional?", correct: "Swablu", wrong: ["Delibird", "Vaporeon", "Eevee"], explain: "Magby es el #240; Eevee #133, Vaporeon #134, Delibird #225, Swablu #333." },
  { q: "¿Cuánto pesa Barbaracle?", correct: "96,0 kg", wrong: ["51,5 kg", "71,2 kg", "150,5 kg"], explain: "Según la Pokédex, Barbaracle pesa 96,0 kg y mide 1,3 m." },
  { q: "¿Cuánto mide Meowth?", correct: "0,4 m", wrong: ["2,3 m", "0,7 m", "0,2 m"], explain: "Según la Pokédex, Meowth mide 0,4 m y pesa 4,2 kg." },
  { q: "¿Qué Pokémon ocupa el número #178 de la Pokédex Nacional?", correct: "Xatu", wrong: ["Flaaffy", "Mareep", "Togepi"], explain: "Xatu es el #178; Togepi el #175, Mareep el #179, Flaaffy el #180." },
  { q: "¿Qué Pokémon viene justo antes de Mismagius en la Pokédex Nacional?", correct: "Lopunny", wrong: ["Honchkrow", "Drifblim", "Purugly"], explain: "Mismagius es el #429 y Lopunny el #428." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Pinsir?", correct: "Venonat", wrong: ["Sentret", "Regirock", "Bronzong"], explain: "Pinsir y Venonat debutaron en Kanto; Sentret de Johto, Regirock de Hoenn, Bronzong de Sinnoh." },
  { q: "¿Cuál de estos Pokémon es más liviano que Zangoose?", correct: "Finneon", wrong: ["Kangaskhan", "Kyogre", "Electivire"], explain: "Zangoose pesa 40,3 kg; Kyogre 352,0 kg, Electivire 138,6 kg, Kangaskhan 80,0 kg, Finneon 7,0 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Ala Clara»?", correct: "Yanma", wrong: ["Heracross", "Sentret", "Piloswine"], explain: "En la Pokédex, Yanma es el Pokémon Ala Clara." },
  { q: "¿Qué Pokémon viene justo antes de Torterra en la Pokédex Nacional?", correct: "Grotle", wrong: ["Chimchar", "Bidoof", "Empoleon"], explain: "Torterra es el #389 y Grotle el #388." },
  { q: "¿Cuál es la categoría de Starmie en la Pokédex?", correct: "Pokémon Misterioso", wrong: ["Pokémon Violento", "Pokémon Ave Corral", "Pokémon Zorro"], explain: "Starmie es el Pokémon Misterioso." },
  { q: "¿Qué Pokémon viene justo antes de Shuckle en la Pokédex Nacional?", correct: "Scizor", wrong: ["Heracross", "Granbull", "Snubbull"], explain: "Shuckle es el #213 y Scizor el #212." },
  { q: "¿Qué Pokémon viene justo antes de Poipole en la Pokédex Nacional?", correct: "Marshadow", wrong: ["Naganadel", "Blacephalon", "Necrozma"], explain: "Poipole es el #803 y Marshadow el #802." },
  { q: "¿Qué Pokémon viene justo antes de Rhyhorn en la Pokédex Nacional?", correct: "Weezing", wrong: ["Lapras", "Gengar", "Porygon"], explain: "Rhyhorn es el #111 y Weezing el #110." },
  { q: "¿Cuál de estos Pokémon aparece antes que Thundurus en la Pokédex Nacional?", correct: "Yamask", wrong: ["Reshiram", "Sliggoo", "Phantump"], explain: "Thundurus es el #642; Yamask #562, Reshiram #643, Sliggoo #705, Phantump #708." },
  { q: "¿Cuál de estos Pokémon aparece después que Mew en la Pokédex Nacional?", correct: "Sentret", wrong: ["Moltres", "Kabuto", "Aerodactyl"], explain: "Mew es el #151; Kabuto #140, Aerodactyl #142, Moltres #146, Sentret #161." },
  { q: "¿Cuál de estos Pokémon es más pesado que Claydol?", correct: "Mamoswine", wrong: ["Cyndaquil", "Weepinbell", "Ivysaur"], explain: "Claydol pesa 108,0 kg; Mamoswine 291,0 kg, Ivysaur 13,0 kg, Cyndaquil 7,9 kg, Weepinbell 6,4 kg." },
  { q: "¿En qué región debutó Porygon?", correct: "Kanto", wrong: ["Teselia", "Galar", "Paldea"], explain: "Porygon (#137) debutó en la generación 1, la de Kanto." },
  { q: "¿Cuál de estos Pokémon debutó en la misma región que Remoraid?", correct: "Umbreon", wrong: ["Houndstone", "Charizard", "Nuzleaf"], explain: "Remoraid y Umbreon debutaron en Johto; Houndstone de Paldea, Charizard de Kanto, Nuzleaf de Hoenn." },
  { q: "¿De qué color es Abomasnow según la Pokédex?", correct: "Blanco", wrong: ["Morado", "Rojo", "Azul"], explain: "La Pokédex clasifica a Abomasnow como de color blanco." },
  { q: "¿En qué región debutó Kricketune?", correct: "Sinnoh", wrong: ["Johto", "Hoenn", "Alola"], explain: "Kricketune (#402) debutó en la generación 4, la de Sinnoh." },
  { q: "¿Qué Pokémon ocupa el número #031 de la Pokédex Nacional?", correct: "Nidoqueen", wrong: ["Sandshrew", "Spearow", "Jigglypuff"], explain: "Nidoqueen es el #031; Spearow el #021, Sandshrew el #027, Jigglypuff el #039." },
  { q: "¿Qué número tiene Runerigus en la Pokédex Nacional?", correct: "#867", wrong: ["#935", "#841", "#900"], explain: "Runerigus es el #867 de la Pokédex Nacional y debutó en Galar." },
  { q: "¿Cuál de estos Pokémon es más alto que Wobbuffet?", correct: "Naganadel", wrong: ["Bagon", "Swablu", "Unown"], explain: "Wobbuffet mide 1,3 m; Naganadel 3,6 m, Bagon 0,6 m, Unown 0,5 m, Swablu 0,4 m." },
  { q: "¿Cuál es la categoría de Camerupt en la Pokédex?", correct: "Pokémon Erupción", wrong: ["Pokémon Gato Fuego", "Pokémon Flor", "Pokémon Paleozoico"], explain: "Camerupt es el Pokémon Erupción." },
  { q: "¿Cuál es la categoría de Torkoal en la Pokédex?", correct: "Pokémon Carbón", wrong: ["Pokémon Astuto", "Pokémon Aplauso", "Pokémon Sensorio"], explain: "Torkoal es el Pokémon Carbón." },
  { q: "¿Cuánto mide Raikou?", correct: "1,9 m", wrong: ["3,3 m", "1,0 m", "0,6 m"], explain: "Según la Pokédex, Raikou mide 1,9 m y pesa 178,0 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Radomo»?", correct: "Dottler", wrong: ["Azelf", "Mightyena", "Lopunny"], explain: "En la Pokédex, Dottler es el Pokémon Radomo." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Voraz»?", correct: "Sharpedo", wrong: ["Zigzagoon", "Sableye", "Sealeo"], explain: "En la Pokédex, Sharpedo es el Pokémon Voraz." },
  { q: "¿Cuánto mide Corsola?", correct: "0,6 m", wrong: ["0,2 m", "1,0 m", "1,6 m"], explain: "Según la Pokédex, Corsola mide 0,6 m y pesa 5,0 kg." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Sabiduría»?", correct: "Uxie", wrong: ["Bastiodon", "Rotom", "Arceus"], explain: "En la Pokédex, Uxie es el Pokémon Sabiduría." },
  { q: "¿De qué color es Giratina según la Pokédex?", correct: "Negro", wrong: ["Verde", "Marrón", "Azul"], explain: "La Pokédex clasifica a Giratina como de color negro." },
  { q: "¿Qué Pokémon ocupa el número #089 de la Pokédex Nacional?", correct: "Muk", wrong: ["Dodrio", "Kingler", "Onix"], explain: "Muk es el #089; Dodrio el #085, Onix el #095, Kingler el #099." },
  { q: "¿Qué Pokémon es conocido como el Pokémon «Relámpago»?", correct: "Jolteon", wrong: ["Primeape", "Starmie", "Kadabra"], explain: "En la Pokédex, Jolteon es el Pokémon Relámpago." },
  { q: "¿Cuánto pesa Primeape?", correct: "32,0 kg", wrong: ["75,5 kg", "14,0 kg", "20,6 kg"], explain: "Según la Pokédex, Primeape pesa 32,0 kg y mide 1,0 m." },
  { q: "¿Qué número tiene Magneton en la Pokédex Nacional?", correct: "#082", wrong: ["#022", "#039", "#135"], explain: "Magneton es el #082 de la Pokédex Nacional y debutó en Kanto." },
  { q: "¿Cuánto mide Exeggcute?", correct: "0,4 m", wrong: ["2,4 m", "1,1 m", "0,2 m"], explain: "Según la Pokédex, Exeggcute mide 0,4 m y pesa 2,5 kg." },
  { q: "¿Qué Pokémon viene justo después de Vileplume en la Pokédex Nacional?", correct: "Paras", wrong: ["Gloom", "Meowth", "Ninetales"], explain: "Vileplume es el #045 y Paras el #046." },
  { q: "¿Qué Pokémon ocupa el número #474 de la Pokédex Nacional?", correct: "Porygon-Z", wrong: ["Rhyperior", "Rotom", "Magnezone"], explain: "Porygon-Z es el #474; Magnezone el #462, Rhyperior el #464, Rotom el #479." },
  { q: "¿Cuánto pesa Glalie?", correct: "256,5 kg", wrong: ["82,8 kg", "150,6 kg", "42,5 kg"], explain: "Según la Pokédex, Glalie pesa 256,5 kg y mide 1,5 m." },
  { q: "¿Cuánto pesa Bulbasaur?", correct: "6,9 kg", wrong: ["34,5 kg", "14,2 kg", "2,4 kg"], explain: "Según la Pokédex, Bulbasaur pesa 6,9 kg y mide 0,7 m." },
  { q: "¿Cuánto pesa Hitmonlee?", correct: "49,8 kg", wrong: ["115,0 kg", "20,6 kg", "9,9 kg"], explain: "Según la Pokédex, Hitmonlee pesa 49,8 kg y mide 1,5 m." },
  { q: "¿Qué Pokémon ocupa el número #633 de la Pokédex Nacional?", correct: "Deino", wrong: ["Rufflet", "Lampent", "Axew"], explain: "Deino es el #633; Lampent el #608, Axew el #610, Rufflet el #627." },
  { q: "¿Cuál de estos Pokémon aparece después que Clefairy en la Pokédex Nacional?", correct: "Parasect", wrong: ["Pidgeotto", "Wartortle", "Raticate"], explain: "Clefairy es el #035; Wartortle #008, Pidgeotto #017, Raticate #020, Parasect #047." },
]);
