/* Generado por tools/question-gen/gen_tipos.py a partir de datos de PokeAPI. No editar a mano: volver a correr el generador. */
window.QUESTION_BANK = window.QUESTION_BANK || {};
window.QUESTION_BANK.tipos = (window.QUESTION_BANK.tipos || []).concat([
  { q: "¿De qué tipo es Zorua?", correct: "Siniestro", wrong: ["Dragón", "Planta", "Siniestro/Psíquico"], explain: "Zorua es de tipo Siniestro puro." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Hiperrayo (tipo Normal)?", correct: "Drifblim", wrong: ["Squirtle", "Aerodactyl", "Altaria"], explain: "Drifblim es de tipo Fantasma, inmune a los ataques de tipo Normal." },
  { q: "Un ataque de tipo Veneno contra Baltoy (Tierra/Psíquico), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x2", "x0", "x1"], explain: "Veneno contra Tierra es x0,5 y Veneno contra Psíquico es x1; en total x0,5." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Fuego puro?", correct: "Agua", wrong: ["Eléctrico", "Normal", "Planta"], explain: "El tipo Fuego es débil a Tierra, Roca y Agua." },
  { q: "Un ataque de tipo Volador contra Snom (Hielo/Bicho), ¿cuánto daño hace?", correct: "x2", wrong: ["x4", "x1", "x0"], explain: "Volador contra Hielo es x1 y Volador contra Bicho es x2; en total x2." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Eléctrico?", correct: "Volador", wrong: ["Roca", "Normal", "Lucha"], explain: "Los ataques de tipo Eléctrico son súper eficaces contra Volador y Agua." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Trueno (tipo Eléctrico)?", correct: "Nidoqueen", wrong: ["Muk", "Rayquaza", "Cherrim"], explain: "Nidoqueen es de tipo Tierra, inmune a los ataques de tipo Eléctrico." },
  { q: "¿De qué tipo es Farfetch’d?", correct: "Normal/Volador", wrong: ["Normal/Agua", "Dragón/Volador", "Lucha"], explain: "Farfetch’d combina los tipos Normal y Volador." },
  { q: "¿Cuánto daño hace un ataque de tipo Lucha a un Pokémon de tipo Fuego/Acero?", correct: "x2", wrong: ["x1", "x0", "x4"], explain: "Lucha contra Fuego es x1 y Lucha contra Acero es x2; en total x2." },
  { q: "¿A qué tipo de ataque es débil x4 Omastar?", correct: "Planta", wrong: ["Tierra", "Psíquico", "Fuego"], explain: "Omastar es Roca/Agua y recibe x4 de Planta." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Siniestro?", correct: "Psíquico", wrong: ["Normal", "Volador", "Bicho"], explain: "Los ataques de tipo Siniestro son súper eficaces contra Fantasma y Psíquico." },
  { q: "Cuando Poliwhirl evoluciona a Poliwrath, ¿qué tipo gana?", correct: "Lucha", wrong: ["Hielo", "Planta", "Tierra"], explain: "Poliwhirl es Agua y Poliwrath pasa a ser Agua/Lucha." },
  { q: "¿Cuál de estos Pokémon es de tipo Dragón puro?", correct: "Dratini", wrong: ["Kingdra", "Ekans", "Gengar"], explain: "Dratini es de tipo Dragón puro; los demás no." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Acero?", correct: "Fuego", wrong: ["Agua", "Hielo", "Psíquico"], explain: "El tipo Acero es débil a Lucha, Tierra y Fuego." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Psíquico puro?", correct: "Siniestro", wrong: ["Planta", "Tierra", "Veneno"], explain: "El tipo Psíquico es débil a Bicho, Fantasma y Siniestro." },
  { q: "¿Cuánto daño hace un ataque de tipo Veneno a un Pokémon de tipo Roca/Veneno?", correct: "x0,25", wrong: ["x0", "x2", "x1"], explain: "Veneno contra Roca es x0,5 y Veneno contra Veneno es x0,5; en total x0,25." },
  { q: "¿De qué tipo es Kingdra?", correct: "Agua/Dragón", wrong: ["Agua/Siniestro", "Veneno/Dragón", "Acero"], explain: "Kingdra combina los tipos Agua y Dragón." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Golpe Cuerpo (tipo Normal)?", correct: "Banette", wrong: ["Croconaw", "Rhyperior", "Nidorino"], explain: "Banette es de tipo Fantasma, inmune a los ataques de tipo Normal." },
  { q: "¿De qué tipo es Magmortar?", correct: "Fuego", wrong: ["Tierra", "Acero", "Fuego/Siniestro"], explain: "Magmortar es de tipo Fuego puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Bicho/Fuego?", correct: "x4", wrong: ["x0,25", "x0", "x2"], explain: "Roca contra Bicho es x2 y Roca contra Fuego es x2; en total x4." },
  { q: "¿A qué tipo de ataque es débil x4 Okidogi?", correct: "Psíquico", wrong: ["Tierra", "Roca", "Dragón"], explain: "Okidogi es Veneno/Lucha y recibe x4 de Psíquico." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Siniestro/Acero?", correct: "3", wrong: ["2", "0", "4"], explain: "La combinación Siniestro/Acero es débil a Lucha, Tierra y Fuego." },
  { q: "¿De qué tipo es Staryu?", correct: "Agua", wrong: ["Dragón", "Fuego", "Agua/Eléctrico"], explain: "Staryu es de tipo Agua puro." },
  { q: "¿Qué tipo de ataque es poco eficaz contra el tipo Siniestro?", correct: "Fantasma", wrong: ["Tierra", "Bicho", "Hada"], explain: "Contra el tipo Siniestro son poco eficaces: Fantasma y Siniestro." },
  { q: "¿Qué Pokémon de esta lista es de tipo Psíquico puro?", correct: "Drowzee", wrong: ["Slowking", "Rhyhorn", "Pidgeot"], explain: "Drowzee es de tipo Psíquico puro; los demás no." },
  { q: "¿A qué tipo de ataques es inmune el tipo Fantasma?", correct: "Normal", wrong: ["Acero", "Fantasma", "Roca"], explain: "El tipo Fantasma no recibe daño de ataques de tipo Normal y Lucha." },
  { q: "Un ataque de tipo Roca contra Charizard (Fuego/Volador), ¿cuánto daño hace?", correct: "x4", wrong: ["x1", "x0,25", "x0"], explain: "Roca contra Fuego es x2 y Roca contra Volador es x2; en total x4." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Excavar (tipo Tierra)?", correct: "Swablu", wrong: ["Octillery", "Kingdra", "Bellossom"], explain: "Swablu es de tipo Volador, inmune a los ataques de tipo Tierra." },
  { q: "Cuando Dragonair evoluciona a Dragonite, ¿qué tipo gana?", correct: "Volador", wrong: ["Hada", "Agua", "Roca"], explain: "Dragonair es Dragón y Dragonite pasa a ser Dragón/Volador." },
  { q: "Un ataque de tipo Eléctrico contra Mantine (Agua/Volador), ¿cuánto daño hace?", correct: "x4", wrong: ["x0", "x0,25", "x1"], explain: "Eléctrico contra Agua es x2 y Eléctrico contra Volador es x2; en total x4." },
  { q: "Un ataque de tipo Siniestro contra Monferno (Fuego/Lucha), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x4", "x0", "x1"], explain: "Siniestro contra Fuego es x1 y Siniestro contra Lucha es x0,5; en total x0,5." },
  { q: "Un ataque de tipo Veneno contra Piloswine (Hielo/Tierra), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x1", "x0,25", "x4"], explain: "Veneno contra Hielo es x1 y Veneno contra Tierra es x0,5; en total x0,5." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Tierra Viva (tipo Tierra)?", correct: "Pidgey", wrong: ["Cherrim", "Mareep", "Aron"], explain: "Pidgey es de tipo Volador, inmune a los ataques de tipo Tierra." },
  { q: "Un ataque de tipo Bicho contra Pidgeot (Normal/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0,25", "x4", "x1"], explain: "Bicho contra Normal es x1 y Bicho contra Volador es x0,5; en total x0,5." },
  { q: "¿De qué tipo es Machop?", correct: "Lucha", wrong: ["Eléctrico", "Hada", "Planta/Lucha"], explain: "Machop es de tipo Lucha puro." },
  { q: "Cuando Seadra evoluciona a Kingdra, ¿qué tipo gana?", correct: "Dragón", wrong: ["Acero", "Eléctrico", "Psíquico"], explain: "Seadra es Agua y Kingdra pasa a ser Agua/Dragón." },
  { q: "¿A qué tipo de ataques es inmune el tipo Normal?", correct: "Fantasma", wrong: ["Fuego", "Planta", "Psíquico"], explain: "El tipo Normal no recibe daño de ataques de tipo Fantasma." },
  { q: "¿De qué tipo es Taillow?", correct: "Normal/Volador", wrong: ["Normal/Tierra", "Siniestro/Volador", "Fantasma"], explain: "Taillow combina los tipos Normal y Volador." },
  { q: "¿Cuánto daño hace un ataque de tipo Lucha a un Pokémon de tipo Roca/Planta?", correct: "x2", wrong: ["x0", "x4", "x1"], explain: "Lucha contra Roca es x2 y Lucha contra Planta es x1; en total x2." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Lucha?", correct: "Hielo", wrong: ["Planta", "Veneno", "Fuego"], explain: "Los ataques de tipo Lucha son súper eficaces contra Normal, Roca, Acero, Hielo y Siniestro." },
  { q: "¿Qué tipo de ataque es poco eficaz contra el tipo Tierra?", correct: "Veneno", wrong: ["Lucha", "Fantasma", "Bicho"], explain: "Contra el tipo Tierra son poco eficaces: Veneno y Roca." },
  { q: "¿A qué tipo de ataque es débil x4 Articuno?", correct: "Roca", wrong: ["Eléctrico", "Fantasma", "Hielo"], explain: "Articuno es Hielo/Volador y recibe x4 de Roca." },
  { q: "¿A qué tipo de ataque es débil x4 Forretress?", correct: "Fuego", wrong: ["Siniestro", "Acero", "Psíquico"], explain: "Forretress es Bicho/Acero y recibe x4 de Fuego." },
  { q: "¿A qué tipo de ataque es débil x4 Pawniard?", correct: "Lucha", wrong: ["Tierra", "Normal", "Psíquico"], explain: "Pawniard es Siniestro/Acero y recibe x4 de Lucha." },
  { q: "¿A qué tipo de ataques es inmune el tipo Hada?", correct: "Dragón", wrong: ["Planta", "Eléctrico", "Fuego"], explain: "El tipo Hada no recibe daño de ataques de tipo Dragón." },
  { q: "Un ataque de tipo Hielo contra Venusaur (Planta/Veneno), ¿cuánto daño hace?", correct: "x2", wrong: ["x0", "x4", "x0,25"], explain: "Hielo contra Planta es x2 y Hielo contra Veneno es x1; en total x2." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Planta?", correct: "Acero", wrong: ["Hada", "Lucha", "Roca"], explain: "El tipo Planta es poco eficaz (x0,5) contra Volador, Veneno, Bicho, Acero, Fuego, Planta y Dragón." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Veneno puro?", correct: "Tierra", wrong: ["Fuego", "Hada", "Siniestro"], explain: "El tipo Veneno es débil a Tierra y Psíquico." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Roca?", correct: "Bicho", wrong: ["Hada", "Psíquico", "Eléctrico"], explain: "Los ataques de tipo Roca son súper eficaces contra Volador, Bicho, Fuego y Hielo." },
  { q: "¿Qué tipo de ataque resiste el tipo Siniestro?", correct: "Fantasma", wrong: ["Hielo", "Dragón", "Volador"], explain: "El tipo Siniestro recibe la mitad de daño de: Fantasma y Siniestro." },
  { q: "¿Qué tipo de ataque es poco eficaz contra el tipo Dragón?", correct: "Eléctrico", wrong: ["Lucha", "Volador", "Hielo"], explain: "Contra el tipo Dragón son poco eficaces: Fuego, Agua, Planta y Eléctrico." },
  { q: "Un ataque de tipo Hada contra Crobat (Veneno/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x1", "x4", "x0,25"], explain: "Hada contra Veneno es x0,5 y Hada contra Volador es x1; en total x0,5." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Veneno?", correct: "Psíquico", wrong: ["Volador", "Acero", "Fuego"], explain: "El tipo Veneno es débil a Tierra y Psíquico." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Hada puro?", correct: "2", wrong: ["4", "5", "1"], explain: "El tipo Hada puro es débil a Veneno y Acero." },
  { q: "Un ataque de tipo Planta contra Snover (Planta/Hielo), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x2", "x0,25", "x1"], explain: "Planta contra Planta es x0,5 y Planta contra Hielo es x1; en total x0,5." },
  { q: "Un ataque de tipo Planta contra Delibird (Hielo/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x4", "x0", "x1"], explain: "Planta contra Hielo es x1 y Planta contra Volador es x0,5; en total x0,5." },
  { q: "Un ataque de tipo Bicho contra Parasect (Bicho/Planta), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x0", "x0,5"], explain: "Bicho contra Bicho es x1 y Bicho contra Planta es x2; en total x2." },
  { q: "¿De qué tipo es Pangoro?", correct: "Lucha/Siniestro", wrong: ["Lucha/Veneno", "Acero/Siniestro", "Fantasma"], explain: "Pangoro combina los tipos Lucha y Siniestro." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Terremoto (tipo Tierra)?", correct: "Beautifly", wrong: ["Aggron", "Sneasel", "Squirtle"], explain: "Beautifly es de tipo Volador, inmune a los ataques de tipo Tierra." },
  { q: "Un ataque de tipo Dragón contra Staraptor (Normal/Volador), ¿cuánto daño hace?", correct: "x1", wrong: ["x0,25", "x4", "x0,5"], explain: "Dragón contra Normal es x1 y Dragón contra Volador es x1; en total x1." },
  { q: "¿Cuál de estos Pokémon es de tipo Planta puro?", correct: "Eldegoss", wrong: ["Ferrothorn", "Chewtle", "Furioseta"], explain: "Eldegoss es de tipo Planta puro; los demás no." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Bicho?", correct: "Fuego", wrong: ["Siniestro", "Psíquico", "Hada"], explain: "El tipo Bicho es débil a Volador, Roca y Fuego." },
  { q: "¿Cuánto daño hace un ataque de tipo Fuego a un Pokémon de tipo Eléctrico/Veneno?", correct: "x1", wrong: ["x0", "x4", "x0,25"], explain: "Fuego contra Eléctrico es x1 y Fuego contra Veneno es x1; en total x1." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Lucha puro?", correct: "Volador", wrong: ["Lucha", "Eléctrico", "Fantasma"], explain: "El tipo Lucha es débil a Volador, Psíquico y Hada." },
  { q: "Un ataque de tipo Lucha contra Pelipper (Agua/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x1", "x4", "x0"], explain: "Lucha contra Agua es x1 y Lucha contra Volador es x0,5; en total x0,5." },
  { q: "Cuando Shellder evoluciona a Cloyster, ¿qué tipo gana?", correct: "Hielo", wrong: ["Eléctrico", "Hada", "Bicho"], explain: "Shellder es Agua y Cloyster pasa a ser Agua/Hielo." },
  { q: "¿Cuál de estos Pokémon es de tipo Hielo puro?", correct: "Glaceon", wrong: ["Sealeo", "Torkoal", "Mightyena"], explain: "Glaceon es de tipo Hielo puro; los demás no." },
  { q: "Un ataque de tipo Tierra contra Kilowattrel (Eléctrico/Volador), ¿cuánto daño hace?", correct: "x0", wrong: ["x2", "x4", "x1"], explain: "Tierra contra Eléctrico es x2 y Tierra contra Volador es x0; en total x0." },
  { q: "¿Cuánto daño hace un ataque de tipo Psíquico a un Pokémon de tipo Siniestro/Fuego?", correct: "x0", wrong: ["x4", "x0,5", "x0,25"], explain: "Psíquico contra Siniestro es x0 y Psíquico contra Fuego es x1; en total x0." },
  { q: "Un ataque de tipo Planta contra Lanturn (Agua/Eléctrico), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x0", "x4"], explain: "Planta contra Agua es x2 y Planta contra Eléctrico es x1; en total x2." },
  { q: "¿De qué tipo es Lickilicky?", correct: "Normal", wrong: ["Hada", "Psíquico", "Normal/Dragón"], explain: "Lickilicky es de tipo Normal puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Veneno/Fuego?", correct: "x2", wrong: ["x1", "x0,5", "x0,25"], explain: "Roca contra Veneno es x1 y Roca contra Fuego es x2; en total x2." },
  { q: "¿Cuál de estos Pokémon es de tipo Veneno puro?", correct: "Nidoran♀", wrong: ["Ariados", "Lickitung", "Piloswine"], explain: "Nidoran♀ es de tipo Veneno puro; los demás no." },
  { q: "Un ataque de tipo Eléctrico contra Veluza (Agua/Psíquico), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,5", "x0,25", "x4"], explain: "Eléctrico contra Agua es x2 y Eléctrico contra Psíquico es x1; en total x2." },
  { q: "¿De qué tipo es Mesprit?", correct: "Psíquico", wrong: ["Veneno", "Agua", "Psíquico/Hada"], explain: "Mesprit es de tipo Psíquico puro." },
  { q: "Cuando Seedot evoluciona a Nuzleaf, ¿qué tipo gana?", correct: "Siniestro", wrong: ["Tierra", "Eléctrico", "Psíquico"], explain: "Seedot es Planta y Nuzleaf pasa a ser Planta/Siniestro." },
  { q: "Cuando Cacnea evoluciona a Cacturne, ¿qué tipo gana?", correct: "Siniestro", wrong: ["Acero", "Roca", "Veneno"], explain: "Cacnea es Planta y Cacturne pasa a ser Planta/Siniestro." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Volador?", correct: "Hielo", wrong: ["Hada", "Veneno", "Bicho"], explain: "El tipo Volador es débil a Roca, Eléctrico y Hielo." },
  { q: "¿Qué tipo de ataque resiste el tipo Dragón?", correct: "Eléctrico", wrong: ["Psíquico", "Fantasma", "Siniestro"], explain: "El tipo Dragón recibe la mitad de daño de: Fuego, Agua, Planta y Eléctrico." },
  { q: "¿De qué tipo es Smeargle?", correct: "Normal", wrong: ["Volador", "Agua", "Normal/Psíquico"], explain: "Smeargle es de tipo Normal puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Bicho a un Pokémon de tipo Normal/Hada?", correct: "x0,5", wrong: ["x4", "x1", "x0,25"], explain: "Bicho contra Normal es x1 y Bicho contra Hada es x0,5; en total x0,5." },
  { q: "¿Qué Pokémon de esta lista es de tipo Lucha puro?", correct: "Tyrogue", wrong: ["Poliwrath", "Exeggutor", "Magikarp"], explain: "Tyrogue es de tipo Lucha puro; los demás no." },
  { q: "¿De qué tipo es Caterpie?", correct: "Bicho", wrong: ["Volador", "Normal", "Tierra/Bicho"], explain: "Caterpie es de tipo Bicho puro." },
  { q: "¿Qué Pokémon de esta lista es de tipo Fuego puro?", correct: "Ponyta", wrong: ["Ho-Oh", "Larvitar", "Pichu"], explain: "Ponyta es de tipo Fuego puro; los demás no." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Tierra puro?", correct: "3", wrong: ["2", "5", "0"], explain: "El tipo Tierra puro es débil a Agua, Planta y Hielo." },
  { q: "Un ataque de tipo Hielo contra Flamariete (Fuego/Dragón), ¿cuánto daño hace?", correct: "x1", wrong: ["x0", "x2", "x4"], explain: "Hielo contra Fuego es x0,5 y Hielo contra Dragón es x2; en total x1." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Fuego?", correct: "Roca", wrong: ["Bicho", "Tierra", "Normal"], explain: "El tipo Fuego es poco eficaz (x0,5) contra Roca, Fuego, Agua y Dragón." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Planta?", correct: "Veneno", wrong: ["Planta", "Agua", "Lucha"], explain: "El tipo Planta es débil a Volador, Veneno, Bicho, Fuego y Hielo." },
  { q: "Un ataque de tipo Hielo contra Bellsprout (Planta/Veneno), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x0", "x0,25"], explain: "Hielo contra Planta es x2 y Hielo contra Veneno es x1; en total x2." },
  { q: "¿Cuánto daño hace un ataque de tipo Siniestro a un Pokémon de tipo Tierra/Volador?", correct: "x1", wrong: ["x4", "x0", "x0,25"], explain: "Siniestro contra Tierra es x1 y Siniestro contra Volador es x1; en total x1." },
  { q: "¿Qué Pokémon de esta lista es de tipo Volador?", correct: "Farfetch’d", wrong: ["Primeape", "Meowth", "Phanpy"], explain: "Farfetch’d es de tipo Normal/Volador." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Siniestro puro?", correct: "Lucha", wrong: ["Roca", "Fantasma", "Fuego"], explain: "El tipo Siniestro es débil a Lucha, Bicho y Hada." },
  { q: "¿De qué tipo es Cyndaquil?", correct: "Fuego", wrong: ["Dragón", "Hielo", "Lucha/Fuego"], explain: "Cyndaquil es de tipo Fuego puro." },
  { q: "¿De qué tipo es Raticate?", correct: "Normal", wrong: ["Veneno", "Volador", "Normal/Planta"], explain: "Raticate es de tipo Normal puro." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Hada?", correct: "Siniestro", wrong: ["Fantasma", "Roca", "Planta"], explain: "Los ataques de tipo Hada son súper eficaces contra Lucha, Dragón y Siniestro." },
  { q: "Un ataque de tipo Lucha contra Corsola (Agua/Roca), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x4", "x0"], explain: "Lucha contra Agua es x1 y Lucha contra Roca es x2; en total x2." },
  { q: "¿Cuál de estos Pokémon es de tipo Fuego puro?", correct: "Flareon", wrong: ["Charizard", "Dunsparce", "Exeggcute"], explain: "Flareon es de tipo Fuego puro; los demás no." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Dragón/Fuego?", correct: "3", wrong: ["4", "5", "2"], explain: "La combinación Dragón/Fuego es débil a Tierra, Roca y Dragón." },
  { q: "¿De qué tipo es Lopunny?", correct: "Normal", wrong: ["Acero", "Veneno", "Fuego/Normal"], explain: "Lopunny es de tipo Normal puro." },
  { q: "¿De qué tipo es Poliwhirl?", correct: "Agua", wrong: ["Bicho", "Fuego", "Agua/Veneno"], explain: "Poliwhirl es de tipo Agua puro." },
  { q: "¿A qué tipo de ataque es débil x4 Magnemite?", correct: "Tierra", wrong: ["Lucha", "Volador", "Planta"], explain: "Magnemite es Eléctrico/Acero y recibe x4 de Tierra." },
  { q: "Un ataque de tipo Planta contra Taillow (Normal/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x2", "x1", "x0"], explain: "Planta contra Normal es x1 y Planta contra Volador es x0,5; en total x0,5." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Volador?", correct: "Crobat", wrong: ["Hitmonchan", "Gloom", "Tentacruel"], explain: "Crobat es de tipo Veneno/Volador." },
  { q: "¿De qué tipo es Magmar?", correct: "Fuego", wrong: ["Normal", "Agua", "Veneno/Fuego"], explain: "Magmar es de tipo Fuego puro." },
  { q: "Un ataque de tipo Normal contra Forretress (Bicho/Acero), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0", "x0,25", "x4"], explain: "Normal contra Bicho es x1 y Normal contra Acero es x0,5; en total x0,5." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Normal puro?", correct: "Lucha", wrong: ["Volador", "Veneno", "Planta"], explain: "El tipo Normal es débil a Lucha." },
  { q: "¿De qué tipo es Ledian?", correct: "Bicho/Volador", wrong: ["Bicho/Fantasma", "Siniestro/Volador", "Tierra"], explain: "Ledian combina los tipos Bicho y Volador." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Garra Umbría (tipo Fantasma)?", correct: "Pidgey", wrong: ["Mime Jr.", "Magearna", "Aron"], explain: "Pidgey es de tipo Normal, inmune a los ataques de tipo Fantasma." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Bicho puro?", correct: "3", wrong: ["4", "1", "0"], explain: "El tipo Bicho puro es débil a Volador, Roca y Fuego." },
  { q: "¿A qué tipo de ataque es débil x4 Celebi?", correct: "Bicho", wrong: ["Fantasma", "Dragón", "Eléctrico"], explain: "Celebi es Psíquico/Planta y recibe x4 de Bicho." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Dragón?", correct: "Acero", wrong: ["Bicho", "Agua", "Fuego"], explain: "El tipo Dragón es poco eficaz (x0,5) contra Acero." },
  { q: "Cuando Shroomish evoluciona a Breloom, ¿qué tipo gana?", correct: "Lucha", wrong: ["Bicho", "Tierra", "Fuego"], explain: "Shroomish es Planta y Breloom pasa a ser Planta/Lucha." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Confusión (tipo Psíquico)?", correct: "Krokorok", wrong: ["Nidoking", "Squirtle", "Beautifly"], explain: "Krokorok es de tipo Siniestro, inmune a los ataques de tipo Psíquico." },
  { q: "Cuando Silcoon evoluciona a Beautifly, ¿qué tipo gana?", correct: "Volador", wrong: ["Fantasma", "Dragón", "Tierra"], explain: "Silcoon es Bicho y Beautifly pasa a ser Bicho/Volador." },
  { q: "¿De qué tipo es Poliwag?", correct: "Agua", wrong: ["Siniestro", "Psíquico", "Eléctrico/Agua"], explain: "Poliwag es de tipo Agua puro." },
  { q: "Un ataque de tipo Fantasma contra Heatran (Fuego/Acero), ¿cuánto daño hace?", correct: "x1", wrong: ["x4", "x0,5", "x0,25"], explain: "Fantasma contra Fuego es x1 y Fantasma contra Acero es x1; en total x1." },
  { q: "¿Cuál de estos Pokémon es de tipo Psíquico puro?", correct: "Espeon", wrong: ["Lugia", "Misdreavus", "Tentacool"], explain: "Espeon es de tipo Psíquico puro; los demás no." },
  { q: "¿Qué Pokémon de esta lista es de tipo Hielo?", correct: "Smoochum", wrong: ["Blastoise", "Skarmory", "Magcargo"], explain: "Smoochum es de tipo Hielo/Psíquico." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Lucha?", correct: "Hitmonlee", wrong: ["Scizor", "Donphan", "Wobbuffet"], explain: "Hitmonlee es de tipo Lucha." },
  { q: "¿De qué tipo es Trapinch?", correct: "Tierra", wrong: ["Siniestro", "Bicho", "Hada/Tierra"], explain: "Trapinch es de tipo Tierra puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Acero/Dragón?", correct: "x0,5", wrong: ["x0", "x2", "x1"], explain: "Roca contra Acero es x0,5 y Roca contra Dragón es x1; en total x0,5." },
  { q: "¿De qué tipo es Persian?", correct: "Normal", wrong: ["Lucha", "Siniestro", "Normal/Planta"], explain: "Persian es de tipo Normal puro." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Hada?", correct: "Lucha", wrong: ["Psíquico", "Tierra", "Agua"], explain: "Los ataques de tipo Hada son súper eficaces contra Lucha, Dragón y Siniestro." },
  { q: "Un ataque de tipo Fantasma contra Doduo (Normal/Volador), ¿cuánto daño hace?", correct: "x0", wrong: ["x4", "x0,25", "x2"], explain: "Fantasma contra Normal es x0 y Fantasma contra Volador es x1; en total x0." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Cabezazo Zen (tipo Psíquico)?", correct: "Sneasel", wrong: ["Altaria", "Primarina", "Aron"], explain: "Sneasel es de tipo Siniestro, inmune a los ataques de tipo Psíquico." },
  { q: "¿A qué tipo de ataques es inmune el tipo Acero?", correct: "Veneno", wrong: ["Hielo", "Volador", "Planta"], explain: "El tipo Acero no recibe daño de ataques de tipo Veneno." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Fantasma?", correct: "Shuppet", wrong: ["Slakoth", "Delcatty", "Munchlax"], explain: "Shuppet es de tipo Fantasma." },
  { q: "¿Qué tipo es inmune a los ataques de tipo Fantasma?", correct: "Normal", wrong: ["Tierra", "Eléctrico", "Acero"], explain: "Los ataques de tipo Fantasma no afectan a Normal." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Chispa (tipo Eléctrico)?", correct: "Krokorok", wrong: ["Beautifly", "Croconaw", "Feebas"], explain: "Krokorok es de tipo Tierra, inmune a los ataques de tipo Eléctrico." },
  { q: "¿Cuánto daño hace un ataque de tipo Hada a un Pokémon de tipo Fuego/Lucha?", correct: "x1", wrong: ["x2", "x0,25", "x0"], explain: "Hada contra Fuego es x0,5 y Hada contra Lucha es x2; en total x1." },
  { q: "¿Cuánto daño hace un ataque de tipo Tierra a un Pokémon de tipo Acero/Fantasma?", correct: "x2", wrong: ["x4", "x0,25", "x0"], explain: "Tierra contra Acero es x2 y Tierra contra Fantasma es x1; en total x2." },
  { q: "¿Cuánto daño hace un ataque de tipo Veneno a un Pokémon de tipo Siniestro/Fantasma?", correct: "x0,5", wrong: ["x0,25", "x4", "x0"], explain: "Veneno contra Siniestro es x1 y Veneno contra Fantasma es x0,5; en total x0,5." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Siniestro?", correct: "Psíquico", wrong: ["Planta", "Hada", "Fuego"], explain: "Los ataques de tipo Siniestro son súper eficaces contra Fantasma y Psíquico." },
  { q: "Un ataque de tipo Lucha contra Jumpluff (Planta/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0", "x2", "x0,25"], explain: "Lucha contra Planta es x1 y Lucha contra Volador es x0,5; en total x0,5." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Hielo?", correct: "Regice", wrong: ["Seedot", "Dusknoir", "Empoleon"], explain: "Regice es de tipo Hielo." },
  { q: "¿A qué tipo de ataque es débil x4 Corsola?", correct: "Planta", wrong: ["Eléctrico", "Tierra", "Volador"], explain: "Corsola es Agua/Roca y recibe x4 de Planta." },
  { q: "¿De qué tipo es Bouffalant?", correct: "Normal", wrong: ["Veneno", "Lucha", "Psíquico/Normal"], explain: "Bouffalant es de tipo Normal puro." },
  { q: "¿Qué Pokémon de esta lista es de tipo Roca?", correct: "Coalossal", wrong: ["Stoutland", "Helioptile", "Bewear"], explain: "Coalossal es de tipo Roca/Fuego." },
  { q: "¿Qué tipo de ataque resiste el tipo Volador?", correct: "Lucha", wrong: ["Acero", "Veneno", "Psíquico"], explain: "El tipo Volador recibe la mitad de daño de: Lucha, Bicho y Planta." },
  { q: "Cuando Chimchar evoluciona a Monferno, ¿qué tipo gana?", correct: "Lucha", wrong: ["Tierra", "Dragón", "Normal"], explain: "Chimchar es Fuego y Monferno pasa a ser Fuego/Lucha." },
  { q: "¿De qué tipo es Haunter?", correct: "Fantasma/Veneno", wrong: ["Fantasma/Eléctrico", "Normal/Veneno", "Fuego"], explain: "Haunter combina los tipos Fantasma y Veneno." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Acero?", correct: "Eléctrico", wrong: ["Dragón", "Hada", "Fantasma"], explain: "El tipo Acero es poco eficaz (x0,5) contra Acero, Fuego, Agua y Eléctrico." },
  { q: "¿Qué Pokémon de esta lista es de tipo Tierra?", correct: "Onix", wrong: ["Snubbull", "Hitmontop", "Mantine"], explain: "Onix es de tipo Roca/Tierra." },
  { q: "¿De qué tipo es Aerodactyl?", correct: "Roca/Volador", wrong: ["Roca/Agua", "Eléctrico/Volador", "Lucha"], explain: "Aerodactyl combina los tipos Roca y Volador." },
  { q: "¿Cuánto daño hace un ataque de tipo Fuego a un Pokémon de tipo Bicho/Eléctrico?", correct: "x2", wrong: ["x1", "x4", "x0"], explain: "Fuego contra Bicho es x2 y Fuego contra Eléctrico es x1; en total x2." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de A Bocajarro (tipo Lucha)?", correct: "Dusclops", wrong: ["Swablu", "Nuzleaf", "Cubone"], explain: "Dusclops es de tipo Fantasma, inmune a los ataques de tipo Lucha." },
  { q: "¿Cuánto daño hace un ataque de tipo Acero a un Pokémon de tipo Planta/Dragón?", correct: "x1", wrong: ["x2", "x0,5", "x0"], explain: "Acero contra Planta es x1 y Acero contra Dragón es x1; en total x1." },
  { q: "¿Qué tipo resiste los ataques de tipo Volador?", correct: "Roca", wrong: ["Volador", "Tierra", "Bicho"], explain: "Resisten los ataques de tipo Volador: Roca, Acero y Eléctrico." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Agua?", correct: "Roca", wrong: ["Planta", "Lucha", "Volador"], explain: "Los ataques de tipo Agua son súper eficaces contra Tierra, Roca y Fuego." },
  { q: "¿De qué tipo es Hoothoot?", correct: "Normal/Volador", wrong: ["Normal/Planta", "Dragón/Volador", "Tierra"], explain: "Hoothoot combina los tipos Normal y Volador." },
  { q: "Cuando Nidorina evoluciona a Nidoqueen, ¿qué tipo gana?", correct: "Tierra", wrong: ["Lucha", "Psíquico", "Hada"], explain: "Nidorina es Veneno y Nidoqueen pasa a ser Veneno/Tierra." },
  { q: "Cuando Nidorino evoluciona a Nidoking, ¿qué tipo gana?", correct: "Tierra", wrong: ["Acero", "Volador", "Bicho"], explain: "Nidorino es Veneno y Nidoking pasa a ser Veneno/Tierra." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Residuos (tipo Veneno)?", correct: "Heatran", wrong: ["Rhyperior", "Thundurus", "Misdreavus"], explain: "Heatran es de tipo Acero, inmune a los ataques de tipo Veneno." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Hielo puro?", correct: "Fuego", wrong: ["Agua", "Planta", "Veneno"], explain: "El tipo Hielo es débil a Lucha, Roca, Acero y Fuego." },
  { q: "Un ataque de tipo Veneno contra Tentacool (Agua/Veneno), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x2", "x0,25", "x4"], explain: "Veneno contra Agua es x1 y Veneno contra Veneno es x0,5; en total x0,5." },
  { q: "¿De qué tipo es Pansage?", correct: "Planta", wrong: ["Lucha", "Fuego", "Planta/Hada"], explain: "Pansage es de tipo Planta puro." },
  { q: "Un ataque de tipo Tierra contra Golbat (Veneno/Volador), ¿cuánto daño hace?", correct: "x0", wrong: ["x0,25", "x0,5", "x4"], explain: "Tierra contra Veneno es x2 y Tierra contra Volador es x0; en total x0." },
  { q: "¿Cuánto daño hace un ataque de tipo Acero a un Pokémon de tipo Dragón/Psíquico?", correct: "x1", wrong: ["x0,25", "x0", "x2"], explain: "Acero contra Dragón es x1 y Acero contra Psíquico es x1; en total x1." },
  { q: "¿De qué tipo es Passimian?", correct: "Lucha", wrong: ["Fantasma", "Roca", "Lucha/Siniestro"], explain: "Passimian es de tipo Lucha puro." },
  { q: "¿A qué tipo de ataque es débil x4 Onix?", correct: "Planta", wrong: ["Lucha", "Acero", "Psíquico"], explain: "Onix es Roca/Tierra y recibe x4 de Agua y Planta." },
  { q: "¿Qué tipo resiste los ataques de tipo Bicho?", correct: "Volador", wrong: ["Bicho", "Hielo", "Normal"], explain: "Resisten los ataques de tipo Bicho: Lucha, Volador, Veneno, Fantasma, Acero, Fuego y Hada." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Fuego?", correct: "Hielo", wrong: ["Siniestro", "Normal", "Fantasma"], explain: "Los ataques de tipo Fuego son súper eficaces contra Bicho, Acero, Planta y Hielo." },
  { q: "¿Cuánto daño hace un ataque de tipo Tierra a un Pokémon de tipo Fuego/Volador?", correct: "x0", wrong: ["x0,5", "x4", "x0,25"], explain: "Tierra contra Fuego es x2 y Tierra contra Volador es x0; en total x0." },
  { q: "¿Qué tipo de ataque resiste el tipo Bicho?", correct: "Planta", wrong: ["Dragón", "Normal", "Fantasma"], explain: "El tipo Bicho recibe la mitad de daño de: Lucha, Tierra y Planta." },
  { q: "¿Cuánto daño hace un ataque de tipo Bicho a un Pokémon de tipo Psíquico/Fantasma?", correct: "x1", wrong: ["x0", "x4", "x2"], explain: "Bicho contra Psíquico es x2 y Bicho contra Fantasma es x0,5; en total x1." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Roca?", correct: "Bicho", wrong: ["Normal", "Fantasma", "Tierra"], explain: "Los ataques de tipo Roca son súper eficaces contra Volador, Bicho, Fuego y Hielo." },
  { q: "¿Qué Pokémon de esta lista es de tipo Siniestro?", correct: "Weavile", wrong: ["Blaziken", "Abomasnow", "Hariyama"], explain: "Weavile es de tipo Siniestro/Hielo." },
  { q: "¿Cuánto daño hace un ataque de tipo Hielo a un Pokémon de tipo Planta/Lucha?", correct: "x2", wrong: ["x4", "x1", "x0,5"], explain: "Hielo contra Planta es x2 y Hielo contra Lucha es x1; en total x2." },
  { q: "¿De qué tipo es Flaaffy?", correct: "Eléctrico", wrong: ["Agua", "Hada", "Eléctrico/Dragón"], explain: "Flaaffy es de tipo Eléctrico puro." },
  { q: "¿Qué tipo de ataque es poco eficaz contra el tipo Veneno?", correct: "Bicho", wrong: ["Psíquico", "Dragón", "Fuego"], explain: "Contra el tipo Veneno son poco eficaces: Lucha, Veneno, Bicho, Planta y Hada." },
  { q: "¿De qué tipo es Heatran?", correct: "Fuego/Acero", wrong: ["Fuego/Dragón", "Veneno/Acero", "Agua"], explain: "Heatran combina los tipos Fuego y Acero." },
  { q: "Cuando Trapinch evoluciona a Vibrava, ¿qué tipo gana?", correct: "Dragón", wrong: ["Agua", "Hada", "Acero"], explain: "Trapinch es Tierra y Vibrava pasa a ser Tierra/Dragón." },
  { q: "¿De qué tipo es Bellsprout?", correct: "Planta/Veneno", wrong: ["Planta/Roca", "Psíquico/Veneno", "Volador"], explain: "Bellsprout combina los tipos Planta y Veneno." },
  { q: "Un ataque de tipo Hielo contra Bulbasaur (Planta/Veneno), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,25", "x0,5", "x0"], explain: "Hielo contra Planta es x2 y Hielo contra Veneno es x1; en total x2." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Tierra?", correct: "Fuego", wrong: ["Volador", "Dragón", "Hada"], explain: "Los ataques de tipo Tierra son súper eficaces contra Veneno, Roca, Acero, Fuego y Eléctrico." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Acero?", correct: "Hada", wrong: ["Planta", "Psíquico", "Fuego"], explain: "Los ataques de tipo Acero son súper eficaces contra Roca, Hielo y Hada." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Eléctrico?", correct: "Volador", wrong: ["Psíquico", "Normal", "Tierra"], explain: "Los ataques de tipo Eléctrico son súper eficaces contra Volador y Agua." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Normal puro?", correct: "1", wrong: ["4", "3", "0"], explain: "El tipo Normal puro es débil a Lucha." },
  { q: "¿Qué tipo de ataque resiste el tipo Eléctrico?", correct: "Volador", wrong: ["Psíquico", "Roca", "Fantasma"], explain: "El tipo Eléctrico recibe la mitad de daño de: Volador, Acero y Eléctrico." },
  { q: "¿De qué tipo es Bayleef?", correct: "Planta", wrong: ["Tierra", "Normal", "Volador/Planta"], explain: "Bayleef es de tipo Planta puro." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Volador?", correct: "Planta", wrong: ["Eléctrico", "Normal", "Roca"], explain: "Los ataques de tipo Volador son súper eficaces contra Lucha, Bicho y Planta." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Bicho?", correct: "Acero", wrong: ["Normal", "Psíquico", "Siniestro"], explain: "El tipo Bicho es poco eficaz (x0,5) contra Lucha, Volador, Veneno, Fantasma, Acero, Fuego y Hada." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Roca?", correct: "Agua", wrong: ["Fuego", "Hada", "Volador"], explain: "El tipo Roca es débil a Lucha, Tierra, Acero, Agua y Planta." },
  { q: "¿Cuánto daño hace un ataque de tipo Acero a un Pokémon de tipo Bicho/Tierra?", correct: "x1", wrong: ["x0,5", "x0,25", "x2"], explain: "Acero contra Bicho es x1 y Acero contra Tierra es x1; en total x1." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Demolición (tipo Lucha)?", correct: "Gastly", wrong: ["Klefki", "Omastar", "Diglett"], explain: "Gastly es de tipo Fantasma, inmune a los ataques de tipo Lucha." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Psíquico?", correct: "Siniestro", wrong: ["Tierra", "Veneno", "Hielo"], explain: "El tipo Psíquico es débil a Bicho, Fantasma y Siniestro." },
  { q: "¿Qué Pokémon de esta lista es de tipo Eléctrico puro?", correct: "Pikachu", wrong: ["Magneton", "Jigglypuff", "Mew"], explain: "Pikachu es de tipo Eléctrico puro; los demás no." },
  { q: "¿De qué tipo es Phione?", correct: "Agua", wrong: ["Fuego", "Roca", "Agua/Hielo"], explain: "Phione es de tipo Agua puro." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Golpe Kárate (tipo Lucha)?", correct: "Bramblin", wrong: ["Rhyperior", "Magby", "Quagsire"], explain: "Bramblin es de tipo Fantasma, inmune a los ataques de tipo Lucha." },
  { q: "¿De qué tipo es Jynx?", correct: "Hielo/Psíquico", wrong: ["Hielo/Normal", "Roca/Psíquico", "Lucha"], explain: "Jynx combina los tipos Hielo y Psíquico." },
  { q: "Cuando Magikarp evoluciona a Gyarados, ¿qué tipo gana?", correct: "Volador", wrong: ["Veneno", "Planta", "Lucha"], explain: "Magikarp es Agua y Gyarados pasa a ser Agua/Volador." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Puya Nociva (tipo Veneno)?", correct: "Jirachi", wrong: ["Sunflora", "Croconaw", "Sharpedo"], explain: "Jirachi es de tipo Acero, inmune a los ataques de tipo Veneno." },
  { q: "¿A qué tipo de ataque es débil x4 Butterfree?", correct: "Roca", wrong: ["Eléctrico", "Fuego", "Psíquico"], explain: "Butterfree es Bicho/Volador y recibe x4 de Roca." },
  { q: "¿De qué tipo es Veluza?", correct: "Agua/Psíquico", wrong: ["Agua/Veneno", "Bicho/Psíquico", "Hielo"], explain: "Veluza combina los tipos Agua y Psíquico." },
  { q: "Un ataque de tipo Eléctrico contra Staravia (Normal/Volador), ¿cuánto daño hace?", correct: "x2", wrong: ["x0", "x0,25", "x4"], explain: "Eléctrico contra Normal es x1 y Eléctrico contra Volador es x2; en total x2." },
  { q: "¿Qué Pokémon de esta lista es de tipo Normal?", correct: "Linoone", wrong: ["Dialga", "Turtwig", "Budew"], explain: "Linoone es de tipo Normal." },
  { q: "¿Cuánto daño hace un ataque de tipo Tierra a un Pokémon de tipo Veneno/Volador?", correct: "x0", wrong: ["x0,5", "x2", "x4"], explain: "Tierra contra Veneno es x2 y Tierra contra Volador es x0; en total x0." },
  { q: "Un ataque de tipo Hielo contra Toxtricity (Eléctrico/Veneno), ¿cuánto daño hace?", correct: "x1", wrong: ["x0", "x0,25", "x2"], explain: "Hielo contra Eléctrico es x1 y Hielo contra Veneno es x1; en total x1." },
  { q: "¿Cuánto daño hace un ataque de tipo Eléctrico a un Pokémon de tipo Tierra/Psíquico?", correct: "x0", wrong: ["x2", "x4", "x0,25"], explain: "Eléctrico contra Tierra es x0 y Eléctrico contra Psíquico es x1; en total x0." },
  { q: "¿Qué Pokémon de esta lista es de tipo Fantasma?", correct: "Duskull", wrong: ["Drapion", "Palkia", "Skitty"], explain: "Duskull es de tipo Fantasma." },
  { q: "¿De qué tipo es Granbull?", correct: "Hada", wrong: ["Acero", "Veneno", "Siniestro/Hada"], explain: "Granbull es de tipo Hada puro." },
  { q: "¿De qué tipo es Nidoran♂?", correct: "Veneno", wrong: ["Tierra", "Normal", "Fantasma/Veneno"], explain: "Nidoran♂ es de tipo Veneno puro." },
  { q: "¿De qué tipo es Vullaby?", correct: "Siniestro/Volador", wrong: ["Siniestro/Planta", "Tierra/Volador", "Fantasma"], explain: "Vullaby combina los tipos Siniestro y Volador." },
  { q: "Un ataque de tipo Dragón contra Squawkabilly (Normal/Volador), ¿cuánto daño hace?", correct: "x1", wrong: ["x0", "x2", "x4"], explain: "Dragón contra Normal es x1 y Dragón contra Volador es x1; en total x1." },
  { q: "Un ataque de tipo Dragón contra Gible (Dragón/Tierra), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,25", "x1", "x0"], explain: "Dragón contra Dragón es x2 y Dragón contra Tierra es x1; en total x2." },
  { q: "Cuando Pineco evoluciona a Forretress, ¿qué tipo gana?", correct: "Acero", wrong: ["Eléctrico", "Psíquico", "Roca"], explain: "Pineco es Bicho y Forretress pasa a ser Bicho/Acero." },
  { q: "¿Qué tipo resiste los ataques de tipo Siniestro?", correct: "Lucha", wrong: ["Roca", "Dragón", "Normal"], explain: "Resisten los ataques de tipo Siniestro: Lucha, Siniestro y Hada." },
  { q: "¿De qué tipo es Nincada?", correct: "Bicho/Tierra", wrong: ["Bicho/Fuego", "Roca/Tierra", "Siniestro"], explain: "Nincada combina los tipos Bicho y Tierra." },
  { q: "¿De qué tipo es Moltres?", correct: "Fuego/Volador", wrong: ["Fuego/Psíquico", "Lucha/Volador", "Hada"], explain: "Moltres combina los tipos Fuego y Volador." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Psíquico/Fuego?", correct: "5", wrong: ["4", "6", "2"], explain: "La combinación Psíquico/Fuego es débil a Tierra, Roca, Fantasma, Agua y Siniestro." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Roca?", correct: "Acero", wrong: ["Psíquico", "Hielo", "Dragón"], explain: "El tipo Roca es poco eficaz (x0,5) contra Lucha, Tierra y Acero." },
  { q: "Un ataque de tipo Fuego contra Spinarak (Bicho/Veneno), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,5", "x4", "x1"], explain: "Fuego contra Bicho es x2 y Fuego contra Veneno es x1; en total x2." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Hada?", correct: "Tinkatuff", wrong: ["Polteageist", "Cetoddle", "Swanna"], explain: "Tinkatuff es de tipo Hada/Acero." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Enfado (tipo Dragón)?", correct: "Azumarill", wrong: ["Kingdra", "Beautifly", "Ariados"], explain: "Azumarill es de tipo Hada, inmune a los ataques de tipo Dragón." },
  { q: "¿A qué tipo de ataque es débil x4 Aron?", correct: "Lucha", wrong: ["Agua", "Volador", "Psíquico"], explain: "Aron es Acero/Roca y recibe x4 de Lucha y Tierra." },
  { q: "¿Cuánto daño hace un ataque de tipo Fuego a un Pokémon de tipo Hielo/Volador?", correct: "x2", wrong: ["x0,5", "x1", "x4"], explain: "Fuego contra Hielo es x2 y Fuego contra Volador es x1; en total x2." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Bicho/Acero?", correct: "1", wrong: ["3", "0", "2"], explain: "La combinación Bicho/Acero es débil a Fuego." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Agua/Volador?", correct: "x2", wrong: ["x0,25", "x1", "x0"], explain: "Roca contra Agua es x1 y Roca contra Volador es x2; en total x2." },
  { q: "¿A qué tipo de ataque es débil x4 Quagsire?", correct: "Planta", wrong: ["Psíquico", "Lucha", "Siniestro"], explain: "Quagsire es Agua/Tierra y recibe x4 de Planta." },
  { q: "¿De qué tipo es Skiploom?", correct: "Planta/Volador", wrong: ["Planta/Hada", "Agua/Volador", "Tierra"], explain: "Skiploom combina los tipos Planta y Volador." },
  { q: "¿Cuál de estos Pokémon es de tipo Lucha puro?", correct: "Riolu", wrong: ["Lucario", "Bronzong", "Dustox"], explain: "Riolu es de tipo Lucha puro; los demás no." },
  { q: "Un ataque de tipo Roca contra Weavile (Siniestro/Hielo), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,5", "x4", "x0,25"], explain: "Roca contra Siniestro es x1 y Roca contra Hielo es x2; en total x2." },
  { q: "¿De qué tipo es Nymble?", correct: "Bicho", wrong: ["Normal", "Lucha", "Agua/Bicho"], explain: "Nymble es de tipo Bicho puro." },
  { q: "¿Qué Pokémon de esta lista es de tipo Normal puro?", correct: "Stantler", wrong: ["Noctowl", "Zapdos", "Chinchou"], explain: "Stantler es de tipo Normal puro; los demás no." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Tierra?", correct: "Bicho", wrong: ["Tierra", "Dragón", "Hielo"], explain: "El tipo Tierra es poco eficaz (x0,5) contra Bicho y Planta." },
  { q: "Un ataque de tipo Lucha contra Gardevoir (Psíquico/Hada), ¿cuánto daño hace?", correct: "x0,25", wrong: ["x4", "x1", "x2"], explain: "Lucha contra Psíquico es x0,5 y Lucha contra Hada es x0,5; en total x0,25." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Acero/Volador?", correct: "2", wrong: ["4", "3", "5"], explain: "La combinación Acero/Volador es débil a Fuego y Eléctrico." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Bicho puro?", correct: "Roca", wrong: ["Siniestro", "Acero", "Hada"], explain: "El tipo Bicho es débil a Volador, Roca y Fuego." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Lucha puro?", correct: "3", wrong: ["0", "2", "4"], explain: "El tipo Lucha puro es débil a Volador, Psíquico y Hada." },
  { q: "¿Qué tipo resiste los ataques de tipo Planta?", correct: "Veneno", wrong: ["Hielo", "Roca", "Hada"], explain: "Resisten los ataques de tipo Planta: Volador, Veneno, Bicho, Acero, Fuego, Planta y Dragón." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Placaje (tipo Normal)?", correct: "Gastly", wrong: ["Furret", "Bellossom", "Jirachi"], explain: "Gastly es de tipo Fantasma, inmune a los ataques de tipo Normal." },
  { q: "¿A qué tipo de ataque es débil x4 Pelipper?", correct: "Eléctrico", wrong: ["Roca", "Agua", "Fuego"], explain: "Pelipper es Agua/Volador y recibe x4 de Eléctrico." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Eléctrico puro?", correct: "1", wrong: ["0", "3", "2"], explain: "El tipo Eléctrico puro es débil a Tierra." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Veneno?", correct: "Roca", wrong: ["Agua", "Eléctrico", "Psíquico"], explain: "El tipo Veneno es poco eficaz (x0,5) contra Veneno, Tierra, Roca y Fantasma." },
  { q: "¿De qué tipo es Shieldon?", correct: "Roca/Acero", wrong: ["Roca/Psíquico", "Fuego/Acero", "Lucha"], explain: "Shieldon combina los tipos Roca y Acero." },
  { q: "Cuando Charmeleon evoluciona a Charizard, ¿qué tipo gana?", correct: "Volador", wrong: ["Acero", "Siniestro", "Roca"], explain: "Charmeleon es Fuego y Charizard pasa a ser Fuego/Volador." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Planta?", correct: "Roca", wrong: ["Eléctrico", "Siniestro", "Veneno"], explain: "Los ataques de tipo Planta son súper eficaces contra Tierra, Roca y Agua." },
  { q: "¿Qué Pokémon de esta lista es de tipo Agua puro?", correct: "Goldeen", wrong: ["Cloyster", "Starmie", "Ninetales"], explain: "Goldeen es de tipo Agua puro; los demás no." },
  { q: "¿De qué tipo es Krabby?", correct: "Agua", wrong: ["Normal", "Volador", "Tierra/Agua"], explain: "Krabby es de tipo Agua puro." },
  { q: "¿A qué tipo de ataque es débil x4 Ninjask?", correct: "Roca", wrong: ["Fuego", "Volador", "Planta"], explain: "Ninjask es Bicho/Volador y recibe x4 de Roca." },
  { q: "¿De qué tipo es Kadabra?", correct: "Psíquico", wrong: ["Acero", "Roca", "Veneno/Psíquico"], explain: "Kadabra es de tipo Psíquico puro." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Agua?", correct: "Dragón", wrong: ["Fuego", "Roca", "Psíquico"], explain: "El tipo Agua es poco eficaz (x0,5) contra Agua, Planta y Dragón." },
  { q: "¿Cuál de estos Pokémon es de tipo Fantasma puro?", correct: "Mismagius", wrong: ["Spiritomb", "Stunky", "Garchomp"], explain: "Mismagius es de tipo Fantasma puro; los demás no." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Veneno/Normal?", correct: "2", wrong: ["0", "3", "5"], explain: "La combinación Veneno/Normal es débil a Tierra y Psíquico." },
  { q: "¿Qué tipo resiste los ataques de tipo Tierra?", correct: "Bicho", wrong: ["Normal", "Hielo", "Roca"], explain: "Resisten los ataques de tipo Tierra: Bicho y Planta." },
  { q: "¿Cuánto daño hace un ataque de tipo Bicho a un Pokémon de tipo Agua/Psíquico?", correct: "x2", wrong: ["x0,5", "x4", "x1"], explain: "Bicho contra Agua es x1 y Bicho contra Psíquico es x2; en total x2." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Bola Sombra (tipo Fantasma)?", correct: "Pidgey", wrong: ["Misdreavus", "Corviknight", "Gulpin"], explain: "Pidgey es de tipo Normal, inmune a los ataques de tipo Fantasma." },
  { q: "¿Qué tipo de ataque es poco eficaz contra el tipo Bicho?", correct: "Tierra", wrong: ["Dragón", "Fantasma", "Hada"], explain: "Contra el tipo Bicho son poco eficaces: Lucha, Tierra y Planta." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Lucha?", correct: "Veneno", wrong: ["Dragón", "Eléctrico", "Siniestro"], explain: "El tipo Lucha es poco eficaz (x0,5) contra Volador, Veneno, Bicho, Psíquico y Hada." },
  { q: "¿Qué tipo resiste los ataques de tipo Roca?", correct: "Lucha", wrong: ["Normal", "Planta", "Siniestro"], explain: "Resisten los ataques de tipo Roca: Lucha, Tierra y Acero." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Volador?", correct: "Planta", wrong: ["Dragón", "Agua", "Acero"], explain: "Los ataques de tipo Volador son súper eficaces contra Lucha, Bicho y Planta." },
  { q: "¿De qué tipo es Houndoom?", correct: "Siniestro/Fuego", wrong: ["Siniestro/Planta", "Fantasma/Fuego", "Tierra"], explain: "Houndoom combina los tipos Siniestro y Fuego." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Veneno?", correct: "Venomoth", wrong: ["Girafarig", "Igglybuff", "Graveler"], explain: "Venomoth es de tipo Bicho/Veneno." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Veneno puro?", correct: "2", wrong: ["1", "4", "3"], explain: "El tipo Veneno puro es débil a Tierra y Psíquico." },
  { q: "¿Qué tipo de ataque resiste el tipo Agua?", correct: "Fuego", wrong: ["Dragón", "Bicho", "Eléctrico"], explain: "El tipo Agua recibe la mitad de daño de: Acero, Fuego, Agua y Hielo." },
  { q: "Un ataque de tipo Agua contra Lairon (Acero/Roca), ¿cuánto daño hace?", correct: "x2", wrong: ["x0", "x0,25", "x0,5"], explain: "Agua contra Acero es x1 y Agua contra Roca es x2; en total x2." },
  { q: "¿Cuánto daño hace un ataque de tipo Bicho a un Pokémon de tipo Normal/Psíquico?", correct: "x2", wrong: ["x4", "x1", "x0"], explain: "Bicho contra Normal es x1 y Bicho contra Psíquico es x2; en total x2." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Planta puro?", correct: "Volador", wrong: ["Normal", "Hada", "Tierra"], explain: "El tipo Planta es débil a Volador, Veneno, Bicho, Fuego y Hielo." },
  { q: "Un ataque de tipo Volador contra Exeggutor (Planta/Psíquico), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,25", "x0", "x0,5"], explain: "Volador contra Planta es x2 y Volador contra Psíquico es x1; en total x2." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Eléctrico puro?", correct: "Tierra", wrong: ["Acero", "Lucha", "Hada"], explain: "El tipo Eléctrico es débil a Tierra." },
  { q: "¿Qué tipo de ataque es poco eficaz contra el tipo Acero?", correct: "Bicho", wrong: ["Siniestro", "Eléctrico", "Fantasma"], explain: "Contra el tipo Acero son poco eficaces: Normal, Volador, Roca, Bicho, Acero, Planta, Psíquico, Hielo, Dragón y Hada." },
  { q: "¿A qué tipo de ataque es débil x4 Wooper?", correct: "Planta", wrong: ["Hada", "Acero", "Siniestro"], explain: "Wooper es Agua/Tierra y recibe x4 de Planta." },
  { q: "¿De qué tipo es Combusken?", correct: "Fuego/Lucha", wrong: ["Fuego/Fantasma", "Siniestro/Lucha", "Psíquico"], explain: "Combusken combina los tipos Fuego y Lucha." },
  { q: "Cuando Slugma evoluciona a Magcargo, ¿qué tipo gana?", correct: "Roca", wrong: ["Planta", "Bicho", "Normal"], explain: "Slugma es Fuego y Magcargo pasa a ser Fuego/Roca." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Lucha?", correct: "Hielo", wrong: ["Tierra", "Eléctrico", "Dragón"], explain: "Los ataques de tipo Lucha son súper eficaces contra Normal, Roca, Acero, Hielo y Siniestro." },
  { q: "Un ataque de tipo Planta contra Qwilfish (Agua/Veneno), ¿cuánto daño hace?", correct: "x1", wrong: ["x2", "x0,5", "x0"], explain: "Planta contra Agua es x2 y Planta contra Veneno es x0,5; en total x1." },
  { q: "¿A qué tipo de ataque es débil x4 Applin?", correct: "Hielo", wrong: ["Volador", "Planta", "Roca"], explain: "Applin es Planta/Dragón y recibe x4 de Hielo." },
  { q: "¿Qué Pokémon de esta lista es de tipo Bicho puro?", correct: "Pinsir", wrong: ["Forretress", "Meganium", "Bulbasaur"], explain: "Pinsir es de tipo Bicho puro; los demás no." },
  { q: "¿Qué Pokémon de esta lista es de tipo Bicho?", correct: "Ledian", wrong: ["Wooper", "Blissey", "Jynx"], explain: "Ledian es de tipo Bicho/Volador." },
  { q: "¿Qué tipo de ataque es poco eficaz contra el tipo Lucha?", correct: "Roca", wrong: ["Veneno", "Hada", "Normal"], explain: "Contra el tipo Lucha son poco eficaces: Roca, Bicho y Siniestro." },
  { q: "¿Qué tipo de ataque es poco eficaz contra el tipo Fuego?", correct: "Bicho", wrong: ["Tierra", "Eléctrico", "Roca"], explain: "Contra el tipo Fuego son poco eficaces: Bicho, Acero, Fuego, Planta, Hielo y Hada." },
  { q: "Un ataque de tipo Lucha contra Kabutops (Roca/Agua), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,25", "x1", "x0"], explain: "Lucha contra Roca es x2 y Lucha contra Agua es x1; en total x2." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Bofetón Lodo (tipo Tierra)?", correct: "Corviknight", wrong: ["Jirachi", "Octillery", "Slaking"], explain: "Corviknight es de tipo Volador, inmune a los ataques de tipo Tierra." },
  { q: "¿Qué tipo es inmune a los ataques de tipo Tierra?", correct: "Volador", wrong: ["Agua", "Hielo", "Siniestro"], explain: "Los ataques de tipo Tierra no afectan a Volador." },
  { q: "¿Qué tipo de ataque resiste el tipo Fantasma?", correct: "Bicho", wrong: ["Fuego", "Agua", "Psíquico"], explain: "El tipo Fantasma recibe la mitad de daño de: Veneno y Bicho." },
  { q: "¿Cuánto daño hace un ataque de tipo Normal a un Pokémon de tipo Fantasma/Planta?", correct: "x0", wrong: ["x4", "x2", "x0,25"], explain: "Normal contra Fantasma es x0 y Normal contra Planta es x1; en total x0." },
  { q: "¿De qué tipo es Delphox?", correct: "Fuego/Psíquico", wrong: ["Fuego/Hielo", "Dragón/Psíquico", "Fantasma"], explain: "Delphox combina los tipos Fuego y Psíquico." },
  { q: "¿De qué tipo es Voltorb?", correct: "Eléctrico", wrong: ["Dragón", "Tierra", "Eléctrico/Siniestro"], explain: "Voltorb es de tipo Eléctrico puro." },
  { q: "Un ataque de tipo Lucha contra Kakuna (Bicho/Veneno), ¿cuánto daño hace?", correct: "x0,25", wrong: ["x4", "x0,5", "x1"], explain: "Lucha contra Bicho es x0,5 y Lucha contra Veneno es x0,5; en total x0,25." },
  { q: "¿Cuánto daño hace un ataque de tipo Acero a un Pokémon de tipo Acero/Psíquico?", correct: "x0,5", wrong: ["x2", "x0", "x1"], explain: "Acero contra Acero es x0,5 y Acero contra Psíquico es x1; en total x0,5." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Hada/Volador?", correct: "5", wrong: ["3", "2", "6"], explain: "La combinación Hada/Volador es débil a Veneno, Roca, Acero, Eléctrico y Hielo." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Agua?", correct: "Tierra", wrong: ["Psíquico", "Acero", "Lucha"], explain: "Los ataques de tipo Agua son súper eficaces contra Tierra, Roca y Fuego." },
  { q: "¿Qué tipo de ataque es poco eficaz contra el tipo Hada?", correct: "Bicho", wrong: ["Hada", "Psíquico", "Volador"], explain: "Contra el tipo Hada son poco eficaces: Lucha, Bicho y Siniestro." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Psíquico puro?", correct: "3", wrong: ["1", "2", "5"], explain: "El tipo Psíquico puro es débil a Bicho, Fantasma y Siniestro." },
  { q: "¿A qué tipo de ataque es débil x4 Moltres?", correct: "Roca", wrong: ["Agua", "Volador", "Dragón"], explain: "Moltres es Fuego/Volador y recibe x4 de Roca." },
  { q: "Un ataque de tipo Hada contra Oddish (Planta/Veneno), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0,25", "x2", "x0"], explain: "Hada contra Planta es x1 y Hada contra Veneno es x0,5; en total x0,5." },
  { q: "¿Qué Pokémon de esta lista es de tipo Eléctrico?", correct: "Mareep", wrong: ["Diglett", "Magmar", "Weepinbell"], explain: "Mareep es de tipo Eléctrico." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Psicorrayo (tipo Psíquico)?", correct: "Ferrocuello", wrong: ["Mareep", "Misdreavus", "Croconaw"], explain: "Ferrocuello es de tipo Siniestro, inmune a los ataques de tipo Psíquico." },
  { q: "¿De qué tipo es Electrode?", correct: "Eléctrico", wrong: ["Tierra", "Volador", "Planta/Eléctrico"], explain: "Electrode es de tipo Eléctrico puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Psíquico/Volador?", correct: "x2", wrong: ["x1", "x4", "x0"], explain: "Roca contra Psíquico es x1 y Roca contra Volador es x2; en total x2." },
  { q: "¿Qué Pokémon de esta lista es de tipo Veneno puro?", correct: "Weezing", wrong: ["Kakuna", "Krabby", "Psyduck"], explain: "Weezing es de tipo Veneno puro; los demás no." },
  { q: "¿De qué tipo es Togepi?", correct: "Hada", wrong: ["Siniestro", "Eléctrico", "Agua/Hada"], explain: "Togepi es de tipo Hada puro." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Normal/Psíquico?", correct: "2", wrong: ["0", "4", "5"], explain: "La combinación Normal/Psíquico es débil a Bicho y Siniestro." },
  { q: "¿De qué tipo es Loudred?", correct: "Normal", wrong: ["Fuego", "Veneno", "Fantasma/Normal"], explain: "Loudred es de tipo Normal puro." },
  { q: "¿De qué tipo es Lugia?", correct: "Psíquico/Volador", wrong: ["Psíquico/Normal", "Tierra/Volador", "Eléctrico"], explain: "Lugia combina los tipos Psíquico y Volador." },
  { q: "¿A qué tipo de ataque es débil x4 Magneton?", correct: "Tierra", wrong: ["Fuego", "Lucha", "Hada"], explain: "Magneton es Eléctrico/Acero y recibe x4 de Tierra." },
  { q: "¿A qué tipo de ataque es débil x4 Magcargo?", correct: "Agua", wrong: ["Lucha", "Roca", "Hielo"], explain: "Magcargo es Fuego/Roca y recibe x4 de Tierra y Agua." },
  { q: "¿Qué Pokémon de esta lista es de tipo Dragón?", correct: "Noivern", wrong: ["Falinks", "Inteleon", "Lilligant"], explain: "Noivern es de tipo Volador/Dragón." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Fantasma puro?", correct: "Siniestro", wrong: ["Hielo", "Acero", "Roca"], explain: "El tipo Fantasma es débil a Fantasma y Siniestro." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Siniestro?", correct: "Chien-Pao", wrong: ["Phantump", "Aegislash", "Ferrosaco"], explain: "Chien-Pao es de tipo Siniestro/Hielo." },
  { q: "¿De qué tipo es Breloom?", correct: "Planta/Lucha", wrong: ["Planta/Psíquico", "Agua/Lucha", "Hada"], explain: "Breloom combina los tipos Planta y Lucha." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Normal?", correct: "Lucha", wrong: ["Hielo", "Hada", "Fantasma"], explain: "El tipo Normal es débil a Lucha." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Dragón puro?", correct: "3", wrong: ["6", "2", "1"], explain: "El tipo Dragón puro es débil a Hielo, Dragón y Hada." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Tierra puro?", correct: "Hielo", wrong: ["Hada", "Fantasma", "Bicho"], explain: "El tipo Tierra es débil a Agua, Planta y Hielo." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Fantasma/Fuego?", correct: "x2", wrong: ["x0,5", "x4", "x0,25"], explain: "Roca contra Fantasma es x1 y Roca contra Fuego es x2; en total x2." },
  { q: "¿Qué tipo de ataque resiste el tipo Lucha?", correct: "Bicho", wrong: ["Tierra", "Volador", "Veneno"], explain: "El tipo Lucha recibe la mitad de daño de: Roca, Bicho y Siniestro." },
  { q: "¿De qué tipo es Slugma?", correct: "Fuego", wrong: ["Hielo", "Dragón", "Fuego/Normal"], explain: "Slugma es de tipo Fuego puro." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Roca puro?", correct: "Agua", wrong: ["Eléctrico", "Hada", "Bicho"], explain: "El tipo Roca es débil a Lucha, Tierra, Acero, Agua y Planta." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Hada puro?", correct: "Acero", wrong: ["Agua", "Eléctrico", "Fantasma"], explain: "El tipo Hada es débil a Veneno y Acero." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Agua puro?", correct: "2", wrong: ["3", "0", "4"], explain: "El tipo Agua puro es débil a Planta y Eléctrico." },
  { q: "¿A qué tipo de ataque es débil x4 Sneasel?", correct: "Lucha", wrong: ["Fuego", "Roca", "Fantasma"], explain: "Sneasel es Siniestro/Hielo y recibe x4 de Lucha." },
  { q: "¿Cuánto daño hace un ataque de tipo Eléctrico a un Pokémon de tipo Siniestro/Psíquico?", correct: "x1", wrong: ["x2", "x0,5", "x4"], explain: "Eléctrico contra Siniestro es x1 y Eléctrico contra Psíquico es x1; en total x1." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Siniestro puro?", correct: "3", wrong: ["1", "5", "4"], explain: "El tipo Siniestro puro es débil a Lucha, Bicho y Hada." },
  { q: "¿De qué tipo es Azurill?", correct: "Normal/Hada", wrong: ["Normal/Siniestro", "Acero/Hada", "Fuego"], explain: "Azurill combina los tipos Normal y Hada." },
  { q: "¿De qué tipo es Ursaring?", correct: "Normal", wrong: ["Volador", "Roca", "Normal/Psíquico"], explain: "Ursaring es de tipo Normal puro." },
  { q: "¿Cuál de estos Pokémon es de tipo Normal puro?", correct: "Bunnelby", wrong: ["Shroodle", "Woobat", "Barbaracle"], explain: "Bunnelby es de tipo Normal puro; los demás no." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Hielo?", correct: "Dragón", wrong: ["Normal", "Roca", "Siniestro"], explain: "Los ataques de tipo Hielo son súper eficaces contra Volador, Tierra, Planta y Dragón." },
  { q: "¿De qué tipo es Girafarig?", correct: "Normal/Psíquico", wrong: ["Normal/Volador", "Tierra/Psíquico", "Fuego"], explain: "Girafarig combina los tipos Normal y Psíquico." },
  { q: "¿Qué Pokémon de esta lista es de tipo Agua?", correct: "Huntail", wrong: ["Swalot", "Pachirisu", "Kecleon"], explain: "Huntail es de tipo Agua." },
  { q: "Un ataque de tipo Hada contra Roselia (Planta/Veneno), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x4", "x0,25", "x2"], explain: "Hada contra Planta es x1 y Hada contra Veneno es x0,5; en total x0,5." },
  { q: "Un ataque de tipo Fuego contra Aerodactyl (Roca/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x1", "x4", "x0"], explain: "Fuego contra Roca es x0,5 y Fuego contra Volador es x1; en total x0,5." },
  { q: "¿De qué tipo es Ralts?", correct: "Psíquico/Hada", wrong: ["Psíquico/Fuego", "Dragón/Hada", "Veneno"], explain: "Ralts combina los tipos Psíquico y Hada." },
  { q: "¿Qué Pokémon de esta lista es de tipo Planta?", correct: "Cherubi", wrong: ["Absol", "Manectric", "Medicham"], explain: "Cherubi es de tipo Planta." },
  { q: "¿A qué tipo de ataques es inmune el tipo Tierra?", correct: "Eléctrico", wrong: ["Normal", "Hielo", "Fantasma"], explain: "El tipo Tierra no recibe daño de ataques de tipo Eléctrico." },
  { q: "¿Qué tipo resiste los ataques de tipo Eléctrico?", correct: "Planta", wrong: ["Acero", "Fuego", "Volador"], explain: "Resisten los ataques de tipo Eléctrico: Planta, Eléctrico y Dragón." },
  { q: "Un ataque de tipo Psíquico contra Venonat (Bicho/Veneno), ¿cuánto daño hace?", correct: "x2", wrong: ["x4", "x0,5", "x0,25"], explain: "Psíquico contra Bicho es x1 y Psíquico contra Veneno es x2; en total x2." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Lucha?", correct: "Hada", wrong: ["Acero", "Fuego", "Normal"], explain: "El tipo Lucha es débil a Volador, Psíquico y Hada." },
  { q: "¿De qué tipo es Diglett?", correct: "Tierra", wrong: ["Fuego", "Acero", "Tierra/Normal"], explain: "Diglett es de tipo Tierra puro." },
  { q: "¿Qué Pokémon de esta lista es de tipo Psíquico?", correct: "Wynaut", wrong: ["Burmy", "Swellow", "Grotle"], explain: "Wynaut es de tipo Psíquico." },
  { q: "¿Qué tipo resiste los ataques de tipo Fuego?", correct: "Agua", wrong: ["Psíquico", "Hada", "Fantasma"], explain: "Resisten los ataques de tipo Fuego: Roca, Fuego, Agua y Dragón." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Acero?", correct: "Hielo", wrong: ["Fantasma", "Volador", "Agua"], explain: "Los ataques de tipo Acero son súper eficaces contra Roca, Hielo y Hada." },
  { q: "¿Cuál de estos Pokémon es de tipo Tierra puro?", correct: "Dugtrio", wrong: ["Nidoqueen", "Shellder", "Porygon"], explain: "Dugtrio es de tipo Tierra puro; los demás no." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Acero?", correct: "Magnemite", wrong: ["Seel", "Octillery", "Growlithe"], explain: "Magnemite es de tipo Eléctrico/Acero." },
  { q: "¿De qué tipo es Togekiss?", correct: "Hada/Volador", wrong: ["Hada/Agua", "Dragón/Volador", "Acero"], explain: "Togekiss combina los tipos Hada y Volador." },
  { q: "Un ataque de tipo Fantasma contra Beautifly (Bicho/Volador), ¿cuánto daño hace?", correct: "x1", wrong: ["x0", "x2", "x0,5"], explain: "Fantasma contra Bicho es x1 y Fantasma contra Volador es x1; en total x1." },
  { q: "Un ataque de tipo Roca contra Houndoom (Siniestro/Fuego), ¿cuánto daño hace?", correct: "x2", wrong: ["x0", "x4", "x1"], explain: "Roca contra Siniestro es x1 y Roca contra Fuego es x2; en total x2." },
  { q: "Cuando Staryu evoluciona a Starmie, ¿qué tipo gana?", correct: "Psíquico", wrong: ["Fantasma", "Acero", "Normal"], explain: "Staryu es Agua y Starmie pasa a ser Agua/Psíquico." },
  { q: "¿Qué tipo resiste los ataques de tipo Lucha?", correct: "Hada", wrong: ["Planta", "Agua", "Normal"], explain: "Resisten los ataques de tipo Lucha: Volador, Veneno, Bicho, Psíquico y Hada." },
  { q: "¿Cuál de estos Pokémon es de tipo Bicho puro?", correct: "Wurmple", wrong: ["Skorupi", "Shroomish", "Porygon-Z"], explain: "Wurmple es de tipo Bicho puro; los demás no." },
  { q: "Cuando Seel evoluciona a Dewgong, ¿qué tipo gana?", correct: "Hielo", wrong: ["Acero", "Fantasma", "Roca"], explain: "Seel es Agua y Dewgong pasa a ser Agua/Hielo." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Planta?", correct: "Tapu Bulu", wrong: ["Pecharunt", "Tapu Fini", "Alomomola"], explain: "Tapu Bulu es de tipo Planta/Hada." },
  { q: "¿Qué tipo resiste los ataques de tipo Dragón?", correct: "Acero", wrong: ["Fantasma", "Lucha", "Roca"], explain: "Resisten los ataques de tipo Dragón: Acero." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Hielo?", correct: "Tierra", wrong: ["Psíquico", "Lucha", "Fuego"], explain: "Los ataques de tipo Hielo son súper eficaces contra Volador, Tierra, Planta y Dragón." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Bomba Lodo (tipo Veneno)?", correct: "Scizor", wrong: ["Machop", "Shuppet", "Kingdra"], explain: "Scizor es de tipo Acero, inmune a los ataques de tipo Veneno." },
  { q: "¿De qué tipo es Forretress?", correct: "Bicho/Acero", wrong: ["Bicho/Hielo", "Eléctrico/Acero", "Dragón"], explain: "Forretress combina los tipos Bicho y Acero." },
  { q: "¿De qué tipo es Porygon?", correct: "Normal", wrong: ["Hielo", "Eléctrico", "Normal/Dragón"], explain: "Porygon es de tipo Normal puro." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Hielo puro?", correct: "4", wrong: ["2", "1", "6"], explain: "El tipo Hielo puro es débil a Lucha, Roca, Acero y Fuego." },
  { q: "Un ataque de tipo Tierra contra Articuno (Hielo/Volador), ¿cuánto daño hace?", correct: "x0", wrong: ["x4", "x1", "x0,5"], explain: "Tierra contra Hielo es x1 y Tierra contra Volador es x0; en total x0." },
  { q: "¿De qué tipo es Shinx?", correct: "Eléctrico", wrong: ["Siniestro", "Planta", "Agua/Eléctrico"], explain: "Shinx es de tipo Eléctrico puro." },
  { q: "Un ataque de tipo Bicho contra Aggron (Acero/Roca), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0", "x2", "x4"], explain: "Bicho contra Acero es x0,5 y Bicho contra Roca es x1; en total x0,5." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Eléctrico?", correct: "Dragón", wrong: ["Volador", "Normal", "Veneno"], explain: "El tipo Eléctrico es poco eficaz (x0,5) contra Planta, Eléctrico y Dragón." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Rayo (tipo Eléctrico)?", correct: "Nidoqueen", wrong: ["Croconaw", "Nidorino", "Ariados"], explain: "Nidoqueen es de tipo Tierra, inmune a los ataques de tipo Eléctrico." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Agua?", correct: "Politoed", wrong: ["Dragonair", "Snorlax", "Ampharos"], explain: "Politoed es de tipo Agua." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Fuego?", correct: "Tierra", wrong: ["Planta", "Hielo", "Lucha"], explain: "El tipo Fuego es débil a Tierra, Roca y Agua." },
  { q: "¿Cuánto daño hace un ataque de tipo Tierra a un Pokémon de tipo Roca/Tierra?", correct: "x2", wrong: ["x0,5", "x0", "x0,25"], explain: "Tierra contra Roca es x2 y Tierra contra Tierra es x1; en total x2." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Fuego?", correct: "Hielo", wrong: ["Veneno", "Roca", "Fuego"], explain: "Los ataques de tipo Fuego son súper eficaces contra Bicho, Acero, Planta y Hielo." },
  { q: "¿De qué tipo es Clamperl?", correct: "Agua", wrong: ["Volador", "Eléctrico", "Siniestro/Agua"], explain: "Clamperl es de tipo Agua puro." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Ataque Rápido (tipo Normal)?", correct: "Gengar", wrong: ["Kingdra", "Jirachi", "Charmeleon"], explain: "Gengar es de tipo Fantasma, inmune a los ataques de tipo Normal." },
  { q: "¿Qué Pokémon de esta lista es de tipo Fuego?", correct: "Arcanine", wrong: ["Squirtle", "Qwilfish", "Geodude"], explain: "Arcanine es de tipo Fuego." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Fuego?", correct: "Chimchar", wrong: ["Whiscash", "Gabite", "Grovyle"], explain: "Chimchar es de tipo Fuego." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Onda Certera (tipo Lucha)?", correct: "Melenaleteo", wrong: ["Kingdra", "Machop", "Aron"], explain: "Melenaleteo es de tipo Fantasma, inmune a los ataques de tipo Lucha." },
  { q: "¿De qué tipo es Skuntank?", correct: "Veneno/Siniestro", wrong: ["Veneno/Fantasma", "Fuego/Siniestro", "Lucha"], explain: "Skuntank combina los tipos Veneno y Siniestro." },
  { q: "Un ataque de tipo Fuego contra Zarude (Siniestro/Planta), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x4", "x0,25"], explain: "Fuego contra Siniestro es x1 y Fuego contra Planta es x2; en total x2." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Normal?", correct: "Eevee", wrong: ["Parasect", "Gyarados", "Seadra"], explain: "Eevee es de tipo Normal." },
  { q: "¿Cuál de estos Pokémon es de tipo Roca puro?", correct: "Cranidos", wrong: ["Shieldon", "Trapinch", "Treecko"], explain: "Cranidos es de tipo Roca puro; los demás no." },
  { q: "Un ataque de tipo Agua contra Weepinbell (Planta/Veneno), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x4", "x0", "x1"], explain: "Agua contra Planta es x0,5 y Agua contra Veneno es x1; en total x0,5." },
  { q: "Un ataque de tipo Veneno contra Skarmory (Acero/Volador), ¿cuánto daño hace?", correct: "x0", wrong: ["x4", "x0,25", "x2"], explain: "Veneno contra Acero es x0 y Veneno contra Volador es x1; en total x0." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Dragón/Eléctrico?", correct: "4", wrong: ["3", "5", "1"], explain: "La combinación Dragón/Eléctrico es débil a Tierra, Hielo, Dragón y Hada." },
  { q: "¿Qué tipo de ataque resiste el tipo Veneno?", correct: "Lucha", wrong: ["Psíquico", "Siniestro", "Acero"], explain: "El tipo Veneno recibe la mitad de daño de: Lucha, Veneno, Bicho, Planta y Hada." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Lengüetazo (tipo Fantasma)?", correct: "Slaking", wrong: ["Shuppet", "Gloom", "Weepinbell"], explain: "Slaking es de tipo Normal, inmune a los ataques de tipo Fantasma." },
  { q: "¿De qué tipo es Gimmighoul?", correct: "Fantasma", wrong: ["Acero", "Psíquico", "Fantasma/Planta"], explain: "Gimmighoul es de tipo Fantasma puro." },
  { q: "¿De qué tipo es Snover?", correct: "Planta/Hielo", wrong: ["Planta/Dragón", "Fuego/Hielo", "Eléctrico"], explain: "Snover combina los tipos Planta y Hielo." },
  { q: "¿De qué tipo es Machamp?", correct: "Lucha", wrong: ["Hielo", "Acero", "Siniestro/Lucha"], explain: "Machamp es de tipo Lucha puro." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Planta?", correct: "Tierra", wrong: ["Volador", "Hielo", "Acero"], explain: "Los ataques de tipo Planta son súper eficaces contra Tierra, Roca y Agua." },
  { q: "¿De qué tipo es Seadra?", correct: "Agua", wrong: ["Hielo", "Veneno", "Fantasma/Agua"], explain: "Seadra es de tipo Agua puro." },
  { q: "¿Qué tipo de ataque es poco eficaz contra el tipo Volador?", correct: "Planta", wrong: ["Psíquico", "Eléctrico", "Dragón"], explain: "Contra el tipo Volador son poco eficaces: Lucha, Bicho y Planta." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Volador puro?", correct: "Hielo", wrong: ["Lucha", "Psíquico", "Acero"], explain: "El tipo Volador es débil a Roca, Eléctrico y Hielo." },
  { q: "¿De qué tipo es Sudowoodo?", correct: "Roca", wrong: ["Fuego", "Agua", "Fantasma/Roca"], explain: "Sudowoodo es de tipo Roca puro." },
  { q: "¿Cuánto daño hace un ataque de tipo Lucha a un Pokémon de tipo Roca/Lucha?", correct: "x2", wrong: ["x0,25", "x0", "x1"], explain: "Lucha contra Roca es x2 y Lucha contra Lucha es x1; en total x2." },
  { q: "Un ataque de tipo Bicho contra Ninjask (Bicho/Volador), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x1", "x0", "x2"], explain: "Bicho contra Bicho es x1 y Bicho contra Volador es x0,5; en total x0,5." },
  { q: "¿A qué tipo de ataque es débil x4 Ledian?", correct: "Roca", wrong: ["Volador", "Hielo", "Veneno"], explain: "Ledian es Bicho/Volador y recibe x4 de Roca." },
  { q: "¿Qué Pokémon de esta lista es de tipo Hada?", correct: "Togekiss", wrong: ["Dusclops", "Vibrava", "Shiftry"], explain: "Togekiss es de tipo Hada/Volador." },
  { q: "¿A qué tipo de ataque es débil x4 Mantine?", correct: "Eléctrico", wrong: ["Roca", "Fuego", "Veneno"], explain: "Mantine es Agua/Volador y recibe x4 de Eléctrico." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Tierra?", correct: "Steelix", wrong: ["Tangela", "Celebi", "Dodrio"], explain: "Steelix es de tipo Acero/Tierra." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Fantasma puro?", correct: "2", wrong: ["3", "4", "5"], explain: "El tipo Fantasma puro es débil a Fantasma y Siniestro." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Siniestro?", correct: "Hada", wrong: ["Fantasma", "Bicho", "Acero"], explain: "El tipo Siniestro es poco eficaz (x0,5) contra Lucha, Siniestro y Hada." },
  { q: "¿A qué tipo de ataques es inmune el tipo Siniestro?", correct: "Psíquico", wrong: ["Planta", "Siniestro", "Lucha"], explain: "El tipo Siniestro no recibe daño de ataques de tipo Psíquico." },
  { q: "¿De qué tipo es Grimer?", correct: "Veneno", wrong: ["Fuego", "Normal", "Roca/Veneno"], explain: "Grimer es de tipo Veneno puro." },
  { q: "¿A qué tipo de ataque es débil x4 Heracross?", correct: "Volador", wrong: ["Psíquico", "Hada", "Planta"], explain: "Heracross es Bicho/Lucha y recibe x4 de Volador." },
  { q: "¿Qué Pokémon de esta lista es de tipo Acero?", correct: "Aggron", wrong: ["Gible", "Bonsly", "Wailmer"], explain: "Aggron es de tipo Acero/Roca." },
  { q: "Un ataque de tipo Planta contra Cyclizar (Dragón/Normal), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x0,25", "x0", "x4"], explain: "Planta contra Dragón es x0,5 y Planta contra Normal es x1; en total x0,5." },
  { q: "Cuando Togepi evoluciona a Togetic, ¿qué tipo gana?", correct: "Volador", wrong: ["Fuego", "Acero", "Dragón"], explain: "Togepi es Hada y Togetic pasa a ser Hada/Volador." },
  { q: "¿Qué Pokémon de esta lista es de tipo Roca puro?", correct: "Boldore", wrong: ["Carkol", "Bramaluna", "Greedent"], explain: "Boldore es de tipo Roca puro; los demás no." },
  { q: "¿De qué tipo es Scizor?", correct: "Bicho/Acero", wrong: ["Bicho/Normal", "Lucha/Acero", "Hielo"], explain: "Scizor combina los tipos Bicho y Acero." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Tierra?", correct: "Planta", wrong: ["Dragón", "Normal", "Acero"], explain: "El tipo Tierra es débil a Agua, Planta y Hielo." },
  { q: "¿Qué tipo de ataque es poco eficaz contra el tipo Fantasma?", correct: "Bicho", wrong: ["Roca", "Hielo", "Hada"], explain: "Contra el tipo Fantasma son poco eficaces: Veneno y Bicho." },
  { q: "¿De qué tipo es Smoliv?", correct: "Planta/Normal", wrong: ["Planta/Dragón", "Eléctrico/Normal", "Bicho"], explain: "Smoliv combina los tipos Planta y Normal." },
  { q: "¿Qué tipo resiste los ataques de tipo Normal?", correct: "Roca", wrong: ["Psíquico", "Volador", "Bicho"], explain: "Resisten los ataques de tipo Normal: Roca y Acero." },
  { q: "Un ataque de tipo Hielo contra Gloom (Planta/Veneno), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,25", "x0,5", "x0"], explain: "Hielo contra Planta es x2 y Hielo contra Veneno es x1; en total x2." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Eléctrico?", correct: "Tierra", wrong: ["Siniestro", "Hada", "Roca"], explain: "El tipo Eléctrico es débil a Tierra." },
  { q: "¿Cuánto daño hace un ataque de tipo Agua a un Pokémon de tipo Normal/Dragón?", correct: "x0,5", wrong: ["x0", "x2", "x4"], explain: "Agua contra Normal es x1 y Agua contra Dragón es x0,5; en total x0,5." },
  { q: "Cuando Metapod evoluciona a Butterfree, ¿qué tipo gana?", correct: "Volador", wrong: ["Eléctrico", "Acero", "Planta"], explain: "Metapod es Bicho y Butterfree pasa a ser Bicho/Volador." },
  { q: "¿A qué tipo de ataque es débil x4 Charizard?", correct: "Roca", wrong: ["Eléctrico", "Agua", "Psíquico"], explain: "Charizard es Fuego/Volador y recibe x4 de Roca." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Normal?", correct: "Acero", wrong: ["Dragón", "Tierra", "Lucha"], explain: "El tipo Normal es poco eficaz (x0,5) contra Roca y Acero." },
  { q: "¿A qué tipo de ataque es débil x4 Ledyba?", correct: "Roca", wrong: ["Volador", "Eléctrico", "Siniestro"], explain: "Ledyba es Bicho/Volador y recibe x4 de Roca." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Bicho/Volador?", correct: "x4", wrong: ["x0,25", "x0,5", "x2"], explain: "Roca contra Bicho es x2 y Roca contra Volador es x2; en total x4." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Dragón?", correct: "Dragonite", wrong: ["Lanturn", "Cleffa", "Poliwag"], explain: "Dragonite es de tipo Dragón/Volador." },
  { q: "Un ataque de tipo Bicho contra Durant (Bicho/Acero), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x1", "x0", "x2"], explain: "Bicho contra Bicho es x1 y Bicho contra Acero es x0,5; en total x0,5." },
  { q: "¿De qué tipo es Torracat?", correct: "Fuego", wrong: ["Planta", "Bicho", "Fuego/Hada"], explain: "Torracat es de tipo Fuego puro." },
  { q: "¿Qué tipo resiste los ataques de tipo Hada?", correct: "Veneno", wrong: ["Eléctrico", "Hada", "Hielo"], explain: "Resisten los ataques de tipo Hada: Veneno, Acero y Fuego." },
  { q: "¿Qué tipo de ataque resiste el tipo Tierra?", correct: "Veneno", wrong: ["Siniestro", "Dragón", "Agua"], explain: "El tipo Tierra recibe la mitad de daño de: Veneno y Roca." },
  { q: "¿A qué tipo de ataque es débil x4 Gabite?", correct: "Hielo", wrong: ["Hada", "Acero", "Psíquico"], explain: "Gabite es Dragón/Tierra y recibe x4 de Hielo." },
  { q: "¿Cuánto daño hace un ataque de tipo Fantasma a un Pokémon de tipo Tierra/Siniestro?", correct: "x0,5", wrong: ["x0,25", "x4", "x0"], explain: "Fantasma contra Tierra es x1 y Fantasma contra Siniestro es x0,5; en total x0,5." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Veneno?", correct: "Hada", wrong: ["Tierra", "Agua", "Fantasma"], explain: "Los ataques de tipo Veneno son súper eficaces contra Planta y Hada." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Hielo?", correct: "Acero", wrong: ["Hielo", "Siniestro", "Normal"], explain: "El tipo Hielo es débil a Lucha, Roca, Acero y Fuego." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Acero puro?", correct: "Tierra", wrong: ["Dragón", "Fantasma", "Roca"], explain: "El tipo Acero es débil a Lucha, Tierra y Fuego." },
  { q: "Un ataque de tipo Fantasma contra Helioptile (Eléctrico/Normal), ¿cuánto daño hace?", correct: "x0", wrong: ["x0,5", "x2", "x1"], explain: "Fantasma contra Eléctrico es x1 y Fantasma contra Normal es x0; en total x0." },
  { q: "¿De qué tipo es Drednaw?", correct: "Agua/Roca", wrong: ["Agua/Psíquico", "Siniestro/Roca", "Veneno"], explain: "Drednaw combina los tipos Agua y Roca." },
  { q: "¿De qué tipo es Uxie?", correct: "Psíquico", wrong: ["Normal", "Siniestro", "Psíquico/Planta"], explain: "Uxie es de tipo Psíquico puro." },
  { q: "Un ataque de tipo Hada contra Kommo-o (Dragón/Lucha), ¿cuánto daño hace?", correct: "x4", wrong: ["x1", "x2", "x0"], explain: "Hada contra Dragón es x2 y Hada contra Lucha es x2; en total x4." },
  { q: "¿Cuánto daño hace un ataque de tipo Acero a un Pokémon de tipo Roca/Siniestro?", correct: "x2", wrong: ["x0,5", "x0", "x1"], explain: "Acero contra Roca es x2 y Acero contra Siniestro es x1; en total x2." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Ácido (tipo Veneno)?", correct: "Klefki", wrong: ["Cubone", "Kingdra", "Diglett"], explain: "Klefki es de tipo Acero, inmune a los ataques de tipo Veneno." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Hada?", correct: "Fuego", wrong: ["Lucha", "Hielo", "Dragón"], explain: "El tipo Hada es poco eficaz (x0,5) contra Veneno, Acero y Fuego." },
  { q: "Un ataque de tipo Fantasma contra Ralts (Psíquico/Hada), ¿cuánto daño hace?", correct: "x2", wrong: ["x0", "x4", "x0,5"], explain: "Fantasma contra Psíquico es x2 y Fantasma contra Hada es x1; en total x2." },
  { q: "¿De qué tipo es Skitty?", correct: "Normal", wrong: ["Hada", "Fantasma", "Normal/Agua"], explain: "Skitty es de tipo Normal puro." },
  { q: "Un ataque de tipo Hielo contra Dodrio (Normal/Volador), ¿cuánto daño hace?", correct: "x2", wrong: ["x0", "x1", "x4"], explain: "Hielo contra Normal es x1 y Hielo contra Volador es x2; en total x2." },
  { q: "¿Qué Pokémon de esta lista es de tipo Lucha?", correct: "Grapploct", wrong: ["Palossand", "Joltik", "Bruxish"], explain: "Grapploct es de tipo Lucha." },
  { q: "¿Qué tipo de ataque es súper eficaz contra el tipo Siniestro?", correct: "Bicho", wrong: ["Agua", "Volador", "Psíquico"], explain: "El tipo Siniestro es débil a Lucha, Bicho y Hada." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Volador puro?", correct: "3", wrong: ["1", "2", "4"], explain: "El tipo Volador puro es débil a Roca, Eléctrico y Hielo." },
  { q: "Un ataque de tipo Psíquico contra Croagunk (Veneno/Lucha), ¿cuánto daño hace?", correct: "x4", wrong: ["x0", "x2", "x0,25"], explain: "Psíquico contra Veneno es x2 y Psíquico contra Lucha es x2; en total x4." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Psíquico?", correct: "Jirachi", wrong: ["Drifblim", "Sharpedo", "Kricketune"], explain: "Jirachi es de tipo Acero/Psíquico." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Siniestro/Lucha?", correct: "3", wrong: ["5", "0", "1"], explain: "La combinación Siniestro/Lucha es débil a Lucha, Volador y Hada." },
  { q: "¿De qué tipo es Mismagius?", correct: "Fantasma", wrong: ["Siniestro", "Tierra", "Hada/Fantasma"], explain: "Mismagius es de tipo Fantasma puro." },
  { q: "Un ataque de tipo Bicho contra Celebi (Psíquico/Planta), ¿cuánto daño hace?", correct: "x4", wrong: ["x2", "x0,5", "x0,25"], explain: "Bicho contra Psíquico es x2 y Bicho contra Planta es x2; en total x4." },
  { q: "Un ataque de tipo Roca contra Ariados (Bicho/Veneno), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,5", "x0", "x0,25"], explain: "Roca contra Bicho es x2 y Roca contra Veneno es x1; en total x2." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Fuego puro?", correct: "3", wrong: ["2", "0", "6"], explain: "El tipo Fuego puro es débil a Tierra, Roca y Agua." },
  { q: "¿Qué Pokémon de esta lista es de tipo Veneno?", correct: "Nidorina", wrong: ["Ledyba", "Kabuto", "Hoppip"], explain: "Nidorina es de tipo Veneno." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Pulso Dragón (tipo Dragón)?", correct: "Marill", wrong: ["Croconaw", "Magby", "Drowzee"], explain: "Marill es de tipo Hada, inmune a los ataques de tipo Dragón." },
  { q: "¿Qué tipo de ataque resiste el tipo Acero?", correct: "Bicho", wrong: ["Tierra", "Lucha", "Fantasma"], explain: "El tipo Acero recibe la mitad de daño de: Normal, Volador, Roca, Bicho, Acero, Planta, Psíquico, Hielo, Dragón y Hada." },
  { q: "¿De qué tipo es Dunsparce?", correct: "Normal", wrong: ["Hielo", "Eléctrico", "Bicho/Normal"], explain: "Dunsparce es de tipo Normal puro." },
  { q: "¿De qué tipo es Golduck?", correct: "Agua", wrong: ["Normal", "Veneno", "Agua/Psíquico"], explain: "Golduck es de tipo Agua puro." },
  { q: "Un ataque de tipo Psíquico contra Crawdaunt (Agua/Siniestro), ¿cuánto daño hace?", correct: "x0", wrong: ["x0,25", "x2", "x1"], explain: "Psíquico contra Agua es x1 y Psíquico contra Siniestro es x0; en total x0." },
  { q: "Un ataque de tipo Tierra contra Cutiefly (Bicho/Hada), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x1", "x4", "x0"], explain: "Tierra contra Bicho es x0,5 y Tierra contra Hada es x1; en total x0,5." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Hielo?", correct: "Fuego", wrong: ["Planta", "Volador", "Tierra"], explain: "El tipo Hielo es poco eficaz (x0,5) contra Acero, Fuego, Agua y Hielo." },
  { q: "¿Cuál de estos Pokémon es de tipo Agua puro?", correct: "Clawitzer", wrong: ["Veluza", "Durant", "Hatenna"], explain: "Clawitzer es de tipo Agua puro; los demás no." },
  { q: "¿De qué tipo es Bastiodon?", correct: "Roca/Acero", wrong: ["Roca/Dragón", "Hada/Acero", "Normal"], explain: "Bastiodon combina los tipos Roca y Acero." },
  { q: "Un ataque de tipo Planta contra Larvitar (Roca/Tierra), ¿cuánto daño hace?", correct: "x4", wrong: ["x0,5", "x1", "x0"], explain: "Planta contra Roca es x2 y Planta contra Tierra es x2; en total x4." },
  { q: "¿Qué Pokémon de esta lista es de tipo Planta puro?", correct: "Tangrowth", wrong: ["Snover", "Milotic", "Gallade"], explain: "Tangrowth es de tipo Planta puro; los demás no." },
  { q: "¿A qué tipo de ataque es débil x4 Parasect?", correct: "Fuego", wrong: ["Roca", "Hielo", "Planta"], explain: "Parasect es Bicho/Planta y recibe x4 de Volador y Fuego." },
  { q: "¿De qué tipo es Yanma?", correct: "Bicho/Volador", wrong: ["Bicho/Hada", "Eléctrico/Volador", "Psíquico"], explain: "Yanma combina los tipos Bicho y Volador." },
  { q: "¿Cuánto daño hace un ataque de tipo Lucha a un Pokémon de tipo Siniestro/Normal?", correct: "x4", wrong: ["x0,5", "x0,25", "x2"], explain: "Lucha contra Siniestro es x2 y Lucha contra Normal es x2; en total x4." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Fantasma?", correct: "Psíquico", wrong: ["Veneno", "Agua", "Siniestro"], explain: "Los ataques de tipo Fantasma son súper eficaces contra Fantasma y Psíquico." },
  { q: "Un ataque de tipo Fuego contra Venomoth (Bicho/Veneno), ¿cuánto daño hace?", correct: "x2", wrong: ["x0,5", "x0", "x1"], explain: "Fuego contra Bicho es x2 y Fuego contra Veneno es x1; en total x2." },
  { q: "Un ataque de tipo Bicho contra Starmie (Agua/Psíquico), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x0", "x0,5"], explain: "Bicho contra Agua es x1 y Bicho contra Psíquico es x2; en total x2." },
  { q: "¿De qué tipo es Venonat?", correct: "Bicho/Veneno", wrong: ["Bicho/Planta", "Agua/Veneno", "Hada"], explain: "Venonat combina los tipos Bicho y Veneno." },
  { q: "Un ataque de tipo Normal contra Pupitar (Roca/Tierra), ¿cuánto daño hace?", correct: "x0,5", wrong: ["x4", "x2", "x0"], explain: "Normal contra Roca es x0,5 y Normal contra Tierra es x1; en total x0,5." },
  { q: "¿Qué tipo de ataque resiste el tipo Roca?", correct: "Normal", wrong: ["Psíquico", "Acero", "Eléctrico"], explain: "El tipo Roca recibe la mitad de daño de: Normal, Volador, Veneno y Fuego." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Fantasma?", correct: "Siniestro", wrong: ["Planta", "Fantasma", "Tierra"], explain: "El tipo Fantasma es poco eficaz (x0,5) contra Siniestro." },
  { q: "¿De qué tipo es Jumpluff?", correct: "Planta/Volador", wrong: ["Planta/Lucha", "Hada/Volador", "Fuego"], explain: "Jumpluff combina los tipos Planta y Volador." },
  { q: "¿A qué tipo de ataque es débil x4 Dragonite?", correct: "Hielo", wrong: ["Hada", "Psíquico", "Bicho"], explain: "Dragonite es Dragón/Volador y recibe x4 de Hielo." },
  { q: "¿De qué tipo es Zekrom?", correct: "Dragón/Eléctrico", wrong: ["Dragón/Roca", "Fantasma/Eléctrico", "Bicho"], explain: "Zekrom combina los tipos Dragón y Eléctrico." },
  { q: "¿A qué tipo de ataque es débil x4 Jumpluff?", correct: "Hielo", wrong: ["Fuego", "Volador", "Lucha"], explain: "Jumpluff es Planta/Volador y recibe x4 de Hielo." },
  { q: "Un ataque de tipo Acero contra Victreebel (Planta/Veneno), ¿cuánto daño hace?", correct: "x1", wrong: ["x0,5", "x0", "x2"], explain: "Acero contra Planta es x1 y Acero contra Veneno es x1; en total x1." },
  { q: "¿Cuánto daño hace un ataque de tipo Roca a un Pokémon de tipo Hielo/Bicho?", correct: "x4", wrong: ["x0", "x0,5", "x2"], explain: "Roca contra Hielo es x2 y Roca contra Bicho es x2; en total x4." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Psíquico?", correct: "Lucha", wrong: ["Normal", "Psíquico", "Planta"], explain: "Los ataques de tipo Psíquico son súper eficaces contra Lucha y Veneno." },
  { q: "¿De qué tipo es Espeon?", correct: "Psíquico", wrong: ["Normal", "Acero", "Psíquico/Veneno"], explain: "Espeon es de tipo Psíquico puro." },
  { q: "¿Contra cuál de estos tipos es poco eficaz el tipo Volador?", correct: "Acero", wrong: ["Siniestro", "Bicho", "Planta"], explain: "El tipo Volador es poco eficaz (x0,5) contra Roca, Acero y Eléctrico." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Bicho?", correct: "Planta", wrong: ["Eléctrico", "Fuego", "Hielo"], explain: "Los ataques de tipo Bicho son súper eficaces contra Planta, Psíquico y Siniestro." },
  { q: "Un ataque de tipo Tierra contra Drapion (Veneno/Siniestro), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x0", "x4"], explain: "Tierra contra Veneno es x2 y Tierra contra Siniestro es x1; en total x2." },
  { q: "¿De qué tipo es Yanmega?", correct: "Bicho/Volador", wrong: ["Bicho/Planta", "Normal/Volador", "Roca"], explain: "Yanmega combina los tipos Bicho y Volador." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Bicho?", correct: "Paras", wrong: ["Dewgong", "Electabuzz", "Tauros"], explain: "Paras es de tipo Bicho/Planta." },
  { q: "¿De qué tipo es Beedrill?", correct: "Bicho/Veneno", wrong: ["Bicho/Hada", "Volador/Veneno", "Roca"], explain: "Beedrill combina los tipos Bicho y Veneno." },
  { q: "¿Cuánto daño hace un ataque de tipo Veneno a un Pokémon de tipo Bicho/Hada?", correct: "x2", wrong: ["x0", "x4", "x0,25"], explain: "Veneno contra Bicho es x1 y Veneno contra Hada es x2; en total x2." },
  { q: "¿De qué tipo es Venomoth?", correct: "Bicho/Veneno", wrong: ["Bicho/Siniestro", "Hielo/Veneno", "Volador"], explain: "Venomoth combina los tipos Bicho y Veneno." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Roca?", correct: "Bastiodon", wrong: ["Carnivine", "Darkrai", "Latias"], explain: "Bastiodon es de tipo Roca/Acero." },
  { q: "Un ataque de tipo Volador contra Blaziken (Fuego/Lucha), ¿cuánto daño hace?", correct: "x2", wrong: ["x1", "x0,5", "x0,25"], explain: "Volador contra Fuego es x1 y Volador contra Lucha es x2; en total x2." },
  { q: "¿A qué tipo de ataque es débil x4 Geodude?", correct: "Agua", wrong: ["Lucha", "Hielo", "Eléctrico"], explain: "Geodude es Roca/Tierra y recibe x4 de Agua y Planta." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Fantasma?", correct: "Psíquico", wrong: ["Planta", "Dragón", "Lucha"], explain: "Los ataques de tipo Fantasma son súper eficaces contra Fantasma y Psíquico." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Planta puro?", correct: "5", wrong: ["4", "2", "3"], explain: "El tipo Planta puro es débil a Volador, Veneno, Bicho, Fuego y Hielo." },
  { q: "¿Qué tipo de ataque resiste el tipo Hada?", correct: "Bicho", wrong: ["Acero", "Hielo", "Psíquico"], explain: "El tipo Hada recibe la mitad de daño de: Lucha, Bicho y Siniestro." },
  { q: "¿De qué tipo es Duskull?", correct: "Fantasma", wrong: ["Roca", "Tierra", "Fantasma/Eléctrico"], explain: "Duskull es de tipo Fantasma puro." },
  { q: "¿Qué tipo de ataque resiste el tipo Fuego?", correct: "Acero", wrong: ["Fantasma", "Siniestro", "Veneno"], explain: "El tipo Fuego recibe la mitad de daño de: Bicho, Acero, Fuego, Planta, Hielo y Hada." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Siniestro/Hielo?", correct: "6", wrong: ["3", "8", "9"], explain: "La combinación Siniestro/Hielo es débil a Lucha, Roca, Bicho, Acero, Fuego y Hada." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Planta/Dragón?", correct: "6", wrong: ["7", "3", "8"], explain: "La combinación Planta/Dragón es débil a Volador, Veneno, Bicho, Hielo, Dragón y Hada." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Cometa Draco (tipo Dragón)?", correct: "Jigglypuff", wrong: ["Sneasel", "Gothita", "Machop"], explain: "Jigglypuff es de tipo Hada, inmune a los ataques de tipo Dragón." },
  { q: "¿A qué tipo de ataque es débil x4 Aggron?", correct: "Tierra", wrong: ["Agua", "Volador", "Hada"], explain: "Aggron es Acero/Roca y recibe x4 de Lucha y Tierra." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Garra Dragón (tipo Dragón)?", correct: "Jigglypuff", wrong: ["Misdreavus", "Beautifly", "Gothita"], explain: "Jigglypuff es de tipo Hada, inmune a los ataques de tipo Dragón." },
  { q: "¿Cuánto daño hace un ataque de tipo Hielo a un Pokémon de tipo Tierra/Dragón?", correct: "x4", wrong: ["x0,25", "x1", "x0"], explain: "Hielo contra Tierra es x2 y Hielo contra Dragón es x2; en total x4." },
  { q: "¿A cuántos tipos de ataque es débil (x2 o más) un Pokémon de tipo Eléctrico/Volador?", correct: "2", wrong: ["4", "3", "1"], explain: "La combinación Eléctrico/Volador es débil a Roca y Hielo." },
  { q: "¿A qué tipo le hacen el doble de daño los ataques de tipo Veneno?", correct: "Planta", wrong: ["Veneno", "Dragón", "Eléctrico"], explain: "Los ataques de tipo Veneno son súper eficaces contra Planta y Hada." },
  { q: "¿Cuántas debilidades tiene un Pokémon de tipo Roca puro?", correct: "5", wrong: ["2", "4", "7"], explain: "El tipo Roca puro es débil a Lucha, Tierra, Acero, Agua y Planta." },
  { q: "¿Contra cuál de estos tipos es súper eficaz el tipo Psíquico?", correct: "Veneno", wrong: ["Bicho", "Eléctrico", "Normal"], explain: "Los ataques de tipo Psíquico son súper eficaces contra Lucha y Veneno." },
  { q: "¿Cuál de estos Pokémon tiene el tipo Eléctrico?", correct: "Raichu", wrong: ["Wigglytuff", "Beedrill", "Cyndaquil"], explain: "Raichu es de tipo Eléctrico." },
  { q: "¿De qué tipo es Porygon-Z?", correct: "Normal", wrong: ["Planta", "Psíquico", "Normal/Fantasma"], explain: "Porygon-Z es de tipo Normal puro." },
  { q: "¿A qué tipo de ataque es débil un Pokémon de tipo Agua puro?", correct: "Eléctrico", wrong: ["Agua", "Normal", "Bicho"], explain: "El tipo Agua es débil a Planta y Eléctrico." },
  { q: "¿Qué tipo de ataque es poco eficaz contra el tipo Roca?", correct: "Normal", wrong: ["Psíquico", "Hada", "Eléctrico"], explain: "Contra el tipo Roca son poco eficaces: Normal, Volador, Veneno y Fuego." },
  { q: "¿Qué tipo de ataque resiste el tipo Planta?", correct: "Tierra", wrong: ["Roca", "Psíquico", "Veneno"], explain: "El tipo Planta recibe la mitad de daño de: Tierra, Agua, Planta y Eléctrico." },
  { q: "Sin contar habilidades, ¿qué Pokémon no recibe daño de Puño Trueno (tipo Eléctrico)?", correct: "Phanpy", wrong: ["Croconaw", "Quilava", "Jirachi"], explain: "Phanpy es de tipo Tierra, inmune a los ataques de tipo Eléctrico." },
  { q: "Un ataque de tipo Hielo contra Cradily (Roca/Planta), ¿cuánto daño hace?", correct: "x2", wrong: ["x0", "x0,5", "x0,25"], explain: "Hielo contra Roca es x1 y Hielo contra Planta es x2; en total x2." },
  { q: "¿De qué tipo es Sceptile?", correct: "Planta", wrong: ["Bicho", "Roca", "Hielo/Planta"], explain: "Sceptile es de tipo Planta puro." },
]);
